"""Generate tests that hold the emitted code to what the map claims.

`situc map` is the product: it says a field sits at offset 4, occupies two
bytes, can be written without moving anything, and goes stale when a tag
covers it. Nothing checked that the generated C agreed. A capability map that
the accessors quietly contradict is worse than no map, because it is believed.

So this is the same discipline `gen-codec-tests` applies to a codec signature,
turned on the compiler's own output. The compiler cannot verify an
implementation it never sees; it *can* generate the tests that would falsify
one, and its own backend is no more trustworthy than anybody else's algorithm.

Everything here derives from the schema alone. A user runs `situc gen-checks`
and gets a suite, with no vectors to write and nothing to keep in step by hand
-- which is what makes it get run.

The conformance checks work from the outside. Rather than asserting that an
accessor was emitted a particular way, they poke bytes in the buffer and watch
which ones the accessor notices: a field claiming offset 4 and size 2 must see
every one of those bytes change and no other. That catches an offset the
backend got wrong, a mask that is too wide, and a stride that drifted, without
knowing anything about how the accessor is written.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c.names import c_name, ident, macro
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import own_members

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Suite:
	"""The checks emitted, and the ones deliberately not."""

	lines: list[str]      = field(default_factory=list)
	names: list[str]      = field(default_factory=list)
	skipped: list[str]    = field(default_factory=list)

	def add(self, name: str, body: list[str], doc: list[str]) -> None:
		self.lines.extend(["", *doc,
		                   f"static void {name}(void **state)", "{",
		                   "\t(void)state;", *body, "}"])
		self.names.append(name)

	def skip(self, subject: str, why: str) -> None:
		self.skipped.append(f"{subject}: {why}")


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> str:
	suite = Suite()

	for name in sorted(resolved.structs):
		struct = resolved.structs[name]
		if struct.layout.register is not None:
			_register_checks(suite, struct, prefix)
		else:
			_struct_checks(suite, resolved, struct, prefix)

	return _render(suite, basename)


def _render(suite: Suite, basename: str) -> str:
	lines = [
		f"/* Generated by situc from {basename}.situ -- do not edit.",
		" *",
		" * Every check here is derived from the schema, and every one of them",
		" * holds the generated accessors to what the capability map claims. A",
		" * map the accessors contradict is worse than no map, because it is",
		" * believed.",
		" */",
		"",
		"#include <setjmp.h>",
		"#include <stdarg.h>",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <string.h>",
		"",
		"#include <cmocka.h>",
		"",
		f'#include "{basename}.h"',
	]

	if suite.skipped:
		lines.extend(["", "/* Not checked here, and why:"])
		lines.extend(f" *   {note}" for note in suite.skipped)
		lines.append(" */")

	lines.extend(suite.lines)

	if not suite.names:
		lines.extend([
			"",
			"/* Nothing in this schema has a checkable accessor yet. cmocka",
			" * refuses an empty group, so this one asserts that it is empty on",
			" * purpose rather than by accident. */",
			"static void test_nothing_to_check(void **state)",
			"{",
			"\t(void)state;",
			"}",
		])
		suite.names.append("test_nothing_to_check")

	lines.extend(["", "int main(void)", "{", "\tconst struct CMUnitTest checks[] = {"])
	lines.extend(f"\t\tcmocka_unit_test({name})," for name in suite.names)
	lines.extend(["\t};", "",
	              "\treturn cmocka_run_group_tests(checks, NULL, NULL);", "}"])

	return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Buffer-target structs
# ---------------------------------------------------------------------------


def _struct_checks(suite: Suite, resolved: ResolvedSchema, struct: ResolvedStruct,
		prefix: str) -> None:
	layout = struct.layout

	if not layout.is_byte_sized:
		suite.skip(struct.name, "not a whole number of bytes, so it has no accessors")
		return

	extent = _buffer_size(layout)
	if extent is None:
		_instance_checks(suite, resolved, struct, prefix)
		return

	_view_checks(suite, struct, prefix, extent)

	for entry in struct.entries:
		_field_checks(suite, resolved, struct, entry, prefix, extent)

	_validate_checks(suite, resolved, struct, prefix, extent)
	_coverage_checks(suite, struct, prefix, extent)
	_gate_checks(suite, struct, prefix, extent)


#: What each dynamic member is given when an instance is synthesised. Two, so
#: that a stride exists to be wrong about, and small enough that the whole
#: instance stays a comfortable buffer.
INSTANCE_COUNT = 2

#: Bytes left over for a trailing `remaining` member, so it has somewhere to be.
INSTANCE_TAIL = 8


def _element_bytes(resolved: ResolvedSchema, placement: Placement) -> int | None:
	"""How many bytes one element of an array member takes."""
	if placement.scalar is not None:
		if placement.scalar.bits % BITS_PER_BYTE:
			return None
		return placement.scalar.bits // BITS_PER_BYTE
	nested = resolved.structs.get(placement.type_name or "")
	if nested is None or not nested.layout.is_fixed_size:
		return None
	return int(nested.layout.size_bytes)


def _member_bytes(resolved: ResolvedSchema, placement: Placement,
		chosen: dict[str, int]) -> int | None:
	"""The size this member takes in the synthesised instance.

	`None` means the walk cannot continue: something here has no size this code
	knows how to pin down, and guessing would put every later member on an
	offset the check would then assert with confidence.
	"""
	if placement.sized_by == "remaining":
		return INSTANCE_TAIL
	if placement.sized_by is not None:
		each = _element_bytes(resolved, placement)
		return None if each is None else each * chosen[placement.sized_by]
	if placement.array_count is not None:
		each = _element_bytes(resolved, placement)
		return None if each is None else each * placement.array_count
	if placement.size_bits is None or placement.size_bits % BITS_PER_BYTE:
		return None
	return placement.size_bits // BITS_PER_BYTE


def _instance_checks(suite: Suite, resolved: ResolvedSchema,
		struct: ResolvedStruct, prefix: str) -> None:
	"""One concrete instance of a struct that has no worst case.

	An unbounded struct got no checks at all, because no buffer can be sized for
	the general case. But nothing forces the general case: pick a length for
	every member that has one, and the layout that follows is arithmetic. That
	is what a user does by hand, and it is the only thing that holds the offset
	functions to account -- they are the whole reason the struct is unbounded,
	and mutation testing found them checked by nothing.

	The offsets asserted here are computed by walking the members and adding up
	their chosen sizes. The accessors compute theirs by summing length fields at
	run time. Two different routes to the same number, which is what makes
	disagreement mean something.
	"""
	members = own_members(struct)
	drivers = sorted({placement.sized_by for placement in members
	                  if placement.sized_by and placement.sized_by != "remaining"})

	chosen  = {path: INSTANCE_COUNT for path in drivers}
	setters = []
	for path in drivers:
		target = resolved.find(f"{struct.name}.{path}")
		if target is None or target.placement.scalar is None:
			suite.skip(struct.name, f"`{path}` sizes a member but has no setter")
			return
		setters.append(f"\t{ident(prefix, struct.name, c_name(path), 'set')}"
		               f"(&msg, view, {INSTANCE_COUNT});")

	# Walk the members, giving each the size the chosen values imply.
	offsets: list[tuple[Placement, int]] = []
	at = 0
	for placement in members:
		size = _member_bytes(resolved, placement, chosen)
		if size is None:
			suite.skip(struct.name,
			           f"`{placement.path}` has no size this can pin down, so the"
			           " members after it cannot be placed")
			return
		offsets.append((placement, at))
		at += size

	total = at
	body  = [
		f"\tuint8_t buf[{total}u];",
		"\tsitu_msg_t msg;",
		"\tsitu_view_t view;",
		"",
		"\tmemset(buf, 0, sizeof buf);",
		"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
		f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
		f"(&msg, 0, {total}u, &view), SITU_OK);",
	]

	if setters:
		body.extend([
			"",
			f"\t/* Give every variable member {INSTANCE_COUNT} elements. Each of",
			"\t * these bumps the generation, so the view is taken again after. */",
			*setters,
			"",
			f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
			f"(&msg, 0, {total}u, &view), SITU_OK);",
		])

	asserted = 0
	for placement, offset in offsets:
		lines = _instance_assertions(struct, placement, prefix, offset, chosen)
		if lines:
			body.extend(["", *lines])
			asserted += 1

	if not asserted:
		suite.skip(struct.name, "unbounded, and no member exposes where it starts")
		return

	suite.add(
		f"check_{c_name(struct.name)}_places_its_members_in_one_instance",
		body,
		[f"/* {struct.name} has no worst case, so no buffer fits every instance.",
		 " * This is one instance: every variable member given"
		 f" {INSTANCE_COUNT} elements,",
		 " * and each member asked where it starts.",
		 " *",
		 " * The expected offsets are added up from the chosen sizes; the",
		 " * accessors sum length fields at run time. Two routes to the same",
		 " * number, so a disagreement is a real one. */"])


def _instance_assertions(struct: ResolvedStruct, placement: Placement,
		prefix: str, offset: int, chosen: dict[str, int]) -> list[str]:
	"""Ask one member where it starts, however it is willing to say."""
	if placement.kind != "field":
		return []

	local = c_name(placement.path[len(struct.name) + 1:])
	name  = placement.path
	lines = [f"\t/* {name} starts at {offset}. */"]

	if placement.sized_by is not None or placement.array_count is not None:
		if placement.scalar is not None:
			ptr = ident(prefix, struct.name, local, "ptr")
			lines.append(f"\tassert_int_equal((uint32_t)({ptr}(view) - view.base),"
			             f" {offset}u);")
			if placement.sized_by and placement.sized_by != "remaining":
				length = ident(prefix, struct.name, local, "len")
				lines.append(f"\tassert_int_equal({length}(view),"
				             f" {chosen[placement.sized_by]}u);")
			return lines

		at    = ident(prefix, struct.name, local, "at")
		first = f"first_{local}"
		lines.extend([
			f"\tsitu_view_t {first};",
			f"\tassert_int_equal({at}(view, 0u, &{first}), SITU_OK);",
			f"\tassert_int_equal((uint32_t)({first}.base - view.base), {offset}u);",
		])
		if placement.sized_by and placement.sized_by != "remaining":
			count = ident(prefix, struct.name, local, "count")
			lines.append(f"\tassert_int_equal({count}(view),"
			             f" {chosen[placement.sized_by]}u);")
		return lines

	if placement.scalar is None and placement.type_name:
		inner = f"inner_{local}"
		view  = ident(prefix, struct.name, local, "view")
		lines.extend([
			f"\tsitu_view_t {inner};",
			f"\tassert_int_equal({view}(view, &{inner}), SITU_OK);",
			f"\tassert_int_equal((uint32_t)({inner}.base - view.base), {offset}u);",
		])
		return lines

	return []


def _buffer_size(layout: object) -> int | None:
	"""A buffer big enough for the worst case, or None if there is no worst case."""
	maximum = getattr(layout, "size_max_bytes", None)
	if maximum is not None:
		return max(int(maximum), 1)
	minimum = getattr(layout, "size_bytes", 0)
	if getattr(layout, "is_fixed_size", False):
		return max(int(minimum), 1)
	return None


def _acquire(struct: ResolvedStruct, prefix: str, extent: int,
		length: str | None = None) -> list[str]:
	"""The preamble every check shares: a buffer, a message, a view."""
	name = struct.name
	call = (f"{ident(prefix, name, 'view')}(&msg, 0, &view)"
	        if struct.layout.is_fixed_size
	        else f"{ident(prefix, name, 'view')}(&msg, 0, {length or extent}u, &view)")

	return [
		f"\tuint8_t buf[{extent}u];",
		"\tsitu_msg_t msg;",
		"\tsitu_view_t view;",
		"",
		"\tmemset(buf, 0, sizeof buf);",
		"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
		f"\tassert_int_equal({call}, SITU_OK);",
	]


def _view_checks(suite: Suite, struct: ResolvedStruct, prefix: str,
		extent: int) -> None:
	"""A view that does not fit must be refused, not truncated."""
	name   = struct.name
	layout = struct.layout
	least  = layout.size_bytes

	if least <= 1:
		suite.skip(name, "is one byte or less, so there is no shorter buffer "
		           "C can declare")
		return

	call = (f"{ident(prefix, name, 'view')}(&msg, 0, &view)"
	        if layout.is_fixed_size
	        else f"{ident(prefix, name, 'view')}(&msg, 0, {least - 1}u, &view)")

	suite.add(
		f"check_{c_name(name)}_refuses_a_short_buffer",
		[
			f"\tuint8_t buf[{max(least - 1, 1)}u];",
			"\tsitu_msg_t msg;",
			"\tsitu_view_t view;",
			"",
			"\tmemset(buf, 0, sizeof buf);",
			"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
			f"\tassert_int_equal({call}, SITU_ERR_BOUNDS);",
		],
		[f"/* A buffer one byte short of {name} must be refused rather than",
		 " * truncated: a view is the one bounds check, and everything after it",
		 " * trusts it. */"])


def _field_checks(suite: Suite, resolved: ResolvedSchema, struct: ResolvedStruct,
		entry: Resolved, prefix: str, extent: int) -> None:
	placement = entry.placement
	local     = placement.path[len(struct.name) + 1:]

	if placement.kind in ("element", "reserved"):
		return
	if "." in local and placement.sealed_by is None:
		return		# emitted under the nested struct's own section

	if placement.varint is not None:
		suite.skip(placement.path, "a varint has no fixed extent to check")
		return

	if placement.array_count is not None or placement.sized_by is not None:
		_array_checks(suite, struct, entry, prefix, extent)
		return		# no scalar accessor; the elements are what there is to check
	if placement.scalar is None:
		_nested_placement_check(suite, struct, entry, prefix, extent)
		return		# its interior is checked under its own struct's section
	if placement.offset_bits is None:
		return		# a dynamic offset has no fixed extent to name here, and
				# the structs that have one are unbounded, so no buffer can
				# be sized for them either -- recorded as a skip, not checked
	if placement.kind != "field":
		return		# a marker has no plain getter; its own accessors are shaped
				# by the byte order it carries
	if placement.sealed_by is not None and not placement.unverified_ok:
		return		# reached through the gate; checked by _gate_checks

	_extent_check(suite, struct, entry, prefix, extent)
	_round_trip_check(suite, struct, entry, prefix, extent)
	_encoding_check(suite, struct, entry, prefix, extent)


def _outside(first: int, last: int) -> str:
	"""`i` is inside the claimed range, written so no comparison is vacuous.

	`i >= 0u` is always true and `-Wtype-limits` says so, which would make
	generated code that a user compiles with the project's own flags fail to
	build.
	"""
	if first == 0:
		return f"i <= {last}u"
	if first == last:
		return f"i == {first}u"
	return f"i >= {first}u && i <= {last}u"


def _getter(struct: ResolvedStruct, placement: Placement, prefix: str,
		view: str = "view") -> str:
	local = c_name(placement.path[len(struct.name) + 1:])
	return f"{ident(prefix, struct.name, local, 'get')}({view})"


def _extent_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""The map's offset and size claim, checked from outside the accessor.

	Every byte the field claims must be one the getter notices, and no other
	byte may be. That falsifies a wrong offset, a mask that reaches too far and
	a stride that drifted, without assuming anything about how the accessor was
	written.
	"""
	placement = entry.placement
	assert placement.offset_bits is not None, "checked by the caller"
	first = placement.offset_bits // BITS_PER_BYTE
	last  = (placement.offset_bits + placement.size_bits - 1) // BITS_PER_BYTE

	if last >= extent:
		return

	suite.add(
		f"check_{c_name(placement.path)}_occupies_its_claimed_bytes",
		[
			*_acquire(struct, prefix, extent),
			"",
			f"\tconst uint64_t before = (uint64_t){_getter(struct, placement, prefix)};",
			"\tuint32_t i;",
			"\tint noticed = 0;",
			"",
			f"\t/* The map claims bytes {first}..{last}. Each of them must reach",
			"\t * the value, and nothing else may. */",
			f"\tfor (i = {first}u; i <= {last}u; i++) {{",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			f"\t\tif ((uint64_t){_getter(struct, placement, prefix)} != before) {{",
			"\t\t\tnoticed = 1;",
			"\t\t}",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			"\t}",
			"\tassert_true(noticed);",
			"",
			"\tfor (i = 0; i < (uint32_t)sizeof buf; i++) {",
			f"\t\tif ({_outside(first, last)}) {{",
			"\t\t\tcontinue;",
			"\t\t}",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			f"\t\tassert_int_equal((uint64_t){_getter(struct, placement, prefix)},"
			" before);",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			"\t}",
		],
		[f"/* {placement.path}: the map claims"
		 f" {entry.vector.get(Axis.OFFSET).render()}"
		 f" {entry.vector.get(Axis.SIZE).render()}.",
		 " *",
		 " * Checked from outside: poke every byte in the buffer and the getter",
		 " * must notice exactly the ones the map named. */"])


def _round_trip_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""Boundary values, and the claim that writing one moves nothing else.

	`mutate = InPlaceFixed` is a promise that a write touches this field's bytes
	and no others. Nothing checked it, and it is the promise the whole language
	is built to make.
	"""
	placement = entry.placement
	scalar    = placement.scalar
	assert scalar is not None

	if entry.vector.get(Axis.MUTATE).base != "InPlaceFixed":
		return
	if placement.covered_by or placement.marker is not None:
		return		# a covered write takes the message; checked separately
	if placement.kind != "field" or placement.type_name != scalar.name:
		return		# enum-typed setters take the enum, not an integer

	assert placement.offset_bits is not None, "checked by the caller"
	local  = c_name(placement.path[len(struct.name) + 1:])
	setter = ident(prefix, struct.name, local, "set")
	first  = placement.offset_bits // BITS_PER_BYTE
	last   = (placement.offset_bits + placement.size_bits - 1) // BITS_PER_BYTE

	if last >= extent or _constrained(placement):
		return

	values = _boundary_values(scalar)
	body: list[str] = [*_acquire(struct, prefix, extent), ""]
	body.extend([
		"\tuint8_t witness[sizeof buf];",
		"\tuint32_t i;",
		"",
		"\tmemset(buf, 0xA5, sizeof buf);",
	])

	for value in values:
		body.extend([
			"\tmemcpy(witness, buf, sizeof buf);",
			f"\t{setter}(view, {value});",
			f"\tassert_int_equal((uint64_t){_getter(struct, placement, prefix)}, "
			f"(uint64_t)({value}));",
			"",
			"\t/* InPlaceFixed: this field's bytes, and nothing else. */",
			"\tfor (i = 0; i < (uint32_t)sizeof buf; i++) {",
			f"\t\tif ({_outside(first, last)}) {{",
			"\t\t\tcontinue;",
			"\t\t}",
			"\t\tassert_int_equal(buf[i], witness[i]);",
			"\t}",
			"",
		])

	suite.add(
		f"check_{c_name(placement.path)}_round_trips_in_place",
		body[:-1],
		[f"/* {placement.path}: the map claims mutate="
		 f"{entry.vector.get(Axis.MUTATE).render()}.",
		 " *",
		 " * Every boundary value the type admits must survive a write and a",
		 " * read, and the write must leave every other byte alone. */"])


def _nested_placement_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""Where a nested struct sits inside its parent.

	Its interior is checked thoroughly, but under its own struct's section --
	against a buffer where it starts at zero. That says nothing about where the
	parent puts it, and mutation testing found the hole: moving every nested
	member one byte late passed the whole generated suite, because each nested
	field still agreed with every other nested field.
	"""
	placement = entry.placement

	if placement.kind != "field":
		return		# a region names bytes its members already own, and has no
				# view of its own to locate
	if placement.offset_bits is None or placement.array_count is not None:
		return
	if placement.sized_by is not None or placement.type_name is None:
		return
	if placement.offset_bits % BITS_PER_BYTE != 0:
		return
	if placement.sealed_by is not None:
		return		# reached through the gate, which has its own checks

	local  = c_name(placement.path[len(struct.name) + 1:])
	getter = ident(prefix, struct.name, local, "view")
	offset = placement.offset_bits // BITS_PER_BYTE

	suite.add(
		f"check_{c_name(placement.path)}_starts_where_the_map_says",
		[
			*_acquire(struct, prefix, extent),
			"",
			"\tsitu_view_t inner;",
			"",
			f"\tassert_int_equal({getter}(view, &inner), SITU_OK);",
			"",
			"\t/* The map's offset, measured from the parent rather than",
			"\t * recomputed from it. */",
			f"\tassert_int_equal((uint32_t)(inner.base - view.base), {offset}u);",
		],
		[f"/* {placement.path}: the map claims"
		 f" {entry.vector.get(Axis.OFFSET).render()}.",
		 " *",
		 " * Its fields are checked under its own struct, where it begins at",
		 " * zero. Only this says where the parent actually puts it. */"])


def _array_checks(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""Element addressing: the stride, and the bound.

	Arrays had no generated check at all. That is the gap mutation testing found
	last: a stride one byte too wide made every element after the first read the
	wrong bytes, and the whole suite -- generated and hand-written alike -- still
	passed. Nothing else here indexes anything, so nothing else could notice.

	Both checks work from outside the accessor. The stride is read as the
	distance between two element bases, not recomputed from the map, so an
	accessor and a check cannot agree by construction.
	"""
	placement = entry.placement
	local     = c_name(placement.path[len(struct.name) + 1:])
	count     = placement.array_count

	if count is None or count < 2:
		return		# `remaining`, or too short for a stride to exist

	scalar = placement.scalar
	if scalar is not None:
		if scalar.bits == BITS_PER_BYTE:
			return	# a byte array is handed out as a pointer, not indexed
		_element_encoding_check(suite, struct, entry, prefix, extent, count)
		return

	nested = resolve_element_struct(placement)
	if nested is None:
		return

	at = ident(prefix, struct.name, local, "at")
	suite.add(
		f"check_{c_name(placement.path)}_elements_are_one_stride_apart",
		[
			*_acquire(struct, prefix, extent),
			"",
			"\tsitu_view_t first;",
			"\tsitu_view_t second;",
			"",
			f"\tassert_int_equal({at}(view, 0u, &first), SITU_OK);",
			f"\tassert_int_equal({at}(view, 1u, &second), SITU_OK);",
			"",
			"\t/* The distance between consecutive elements is the element size,",
			"\t * measured rather than recomputed. */",
			"\tassert_int_equal((uint32_t)(second.base - first.base),",
			f"\t                 {macro(prefix, nested, 'SIZE_FIXED')});",
			"",
			f"\t/* And the array ends where it says it does. */",
			f"\tassert_int_not_equal({at}(view, {count}u, &second), SITU_OK);",
		],
		[f"/* {placement.path}: {count} elements, and the spacing between them.",
		 " *",
		 " * A stride that drifted puts every element after the first on the",
		 " * wrong bytes while each one still reads and writes consistently, so",
		 " * only the spacing itself falsifies it. */"])


def _element_encoding_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int, count: int) -> None:
	"""An element past the first, at the bytes its index puts it on.

	Elements wider than a byte are reached by index rather than by pointer, and
	the stride in that accessor was checked by nothing: widening it made every
	element after the zeroth read the wrong bytes while still round-tripping
	against itself. Writing the pattern at the offset the map implies and
	demanding the value back falsifies it.
	"""
	placement = entry.placement
	scalar    = placement.scalar
	assert scalar is not None
	assert placement.offset_bits is not None, "checked by the caller"

	if placement.offset_bits % BITS_PER_BYTE or scalar.bits % BITS_PER_BYTE:
		return
	if placement.endian is ast.Endian.NATIVE:
		return

	index  = count - 1		# the last one: the furthest a drifting stride moves
	stride = scalar.bits // BITS_PER_BYTE
	at     = placement.offset_bits // BITS_PER_BYTE + index * stride
	raw    = _probe_pattern(scalar.bits)
	placed = _placed_bytes(at * BITS_PER_BYTE, scalar.bits, raw,
	                       placement.endian, placement.bit_order, False)
	if placed is None or at + stride > extent:
		return

	local  = c_name(placement.path[len(struct.name) + 1:])
	getter = f"{ident(prefix, struct.name, local, 'get')}(view, {index}u)"
	if scalar.signed:
		want, got = f"(int64_t){_signed_value(raw, scalar.bits)}", f"(int64_t){getter}"
	else:
		want, got = f"(uint64_t){raw:#x}u", f"(uint64_t){getter}"

	body = [*_acquire(struct, prefix, extent), ""]
	body.append(f"\t/* element {index} of {count} sits {index} strides"
	            f" ({index * stride} bytes) past the first. */")
	body.extend(f"\tbuf[{byte}u] = {placed[byte]:#04x}u;" for byte in sorted(placed))
	body.extend(["", f"\tassert_int_equal({got}, {want});"])

	suite.add(
		f"check_{c_name(placement.path)}_element_lands_on_its_stride",
		body,
		[f"/* {placement.path}[{index}]: the bytes its index puts it on.",
		 " *",
		 " * A stride that drifted leaves element zero right and every other",
		 " * element quietly wrong, so only a later one can tell. */"])


def resolve_element_struct(placement: Placement) -> str | None:
	"""The struct name an array's elements have, or None if they are not one."""
	name = placement.type_name
	return name if name and placement.scalar is None else None


#: Distinct bytes, top bit set in the first. Distinct so any permutation of the
#: field's bytes is a different value; top bit set so a getter that forgot to
#: sign-extend returns something else.
PROBE_BYTES = (0x81, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF)


def _bcd_probe(digits: int) -> tuple[int, int]:
	"""A BCD probe: (the bytes to write, the number they spell).

	The generic pattern will not do here. Half its nibbles are above nine, and
	a nibble above nine is not a digit -- what a decoder does with one is not
	something a conformance check should be asserting.
	"""
	sequence = [(i % 9) + 1 for i in range(digits)]

	raw   = 0
	value = 0
	for digit in sequence:
		raw   = (raw << 4) | digit
		value = value * 10 + digit
	return raw, value


def _probe_pattern(bits: int) -> int:
	"""A raw bit pattern that differs from its own byte- and bit-reversal."""
	if bits >= BITS_PER_BYTE and bits % BITS_PER_BYTE == 0:
		value = 0
		for byte in PROBE_BYTES[: bits // BITS_PER_BYTE]:
			value = (value << BITS_PER_BYTE) | byte
		return value
	if bits == 1:
		return 1
	return (1 << bits) - 2		# 0b1...10: top bit set, and not a palindrome


def _placed_bytes(offset_bits: int, bits: int, raw: int, endian: ast.Endian | None,
		bit_order: ast.BitOrder | None, packed: bool) -> dict[int, int] | None:
	"""Where `raw` lands in a zeroed buffer, from the map rather than the accessor.

	This is the whole point of the check: the expected bytes are derived here,
	from the offset and the declared order, by code that shares nothing with the
	emitter. An accessor and a check that agree because they were generated from
	the same expression would agree just as readily about a wrong answer.

	`None` when the encoding is not a fixed pattern -- `native` order depends on
	the machine that eventually runs the code, which is not knowable here.
	"""
	if endian is ast.Endian.NATIVE:
		return None

	if not packed:
		if offset_bits % BITS_PER_BYTE != 0 or bits % BITS_PER_BYTE != 0:
			return None
		first  = offset_bits // BITS_PER_BYTE
		count  = bits // BITS_PER_BYTE
		chunks = [(raw >> (BITS_PER_BYTE * i)) & 0xFF for i in range(count)]
		if endian is not ast.Endian.LITTLE:
			chunks.reverse()	# big endian: most significant byte lowest
		return {first + i: chunk for i, chunk in enumerate(chunks)}

	# Bit-packed: assemble the whole bytes the field touches, then place the
	# value within them the way the declared bit order numbers bits.
	first = offset_bits // BITS_PER_BYTE
	last  = (offset_bits + bits - 1) // BITS_PER_BYTE
	span  = (last - first + 1) * BITS_PER_BYTE
	skip  = offset_bits - first * BITS_PER_BYTE

	if bit_order is ast.BitOrder.LSB_FIRST:
		acc   = raw << skip
		order = range(first, last + 1)			# earlier byte, lower bits
	else:
		acc   = raw << (span - skip - bits)
		order = range(last, first - 1, -1)		# earlier byte, higher bits

	placed = {}
	for at in order:
		placed[at] = acc & 0xFF
		acc >>= BITS_PER_BYTE
	return placed


def _signed_value(raw: int, bits: int) -> int:
	"""`raw` read as two's complement, which is what the getter must return."""
	return raw - (1 << bits) if raw >= 1 << (bits - 1) else raw


def _encoding_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""A concrete byte pattern, against the value the map says it encodes.

	Without this every generated check is symmetric: `_extent_check` asks which
	bytes a field reaches and `_round_trip_check` asks whether the setter and
	the getter agree with each other. Swap the byte order in both and both still
	pass, and byte order is the single thing situ exists to pin down. Mutation
	testing found exactly that -- a generator emitting little-endian loads for
	big-endian fields passed the entire generated suite.

	So: write the bytes, and demand the number.
	"""
	placement = entry.placement
	scalar    = placement.scalar
	assert scalar is not None
	assert placement.offset_bits is not None, "checked by the caller"

	if placement.marker is not None:
		return		# byte order chosen at runtime; no one fixed pattern
	if placement.covered_by:
		return		# reached through the coverage machinery, not a plain read
	if placement.offset_bits + placement.size_bits > extent * BITS_PER_BYTE:
		return

	bits = scalar.bits
	if scalar.is_bcd:
		raw, decoded = _bcd_probe(scalar.digits)
	else:
		raw, decoded = _probe_pattern(bits), None
	placed = _placed_bytes(placement.offset_bits, bits, raw,
	                       placement.endian, placement.bit_order,
	                       scalar.is_bit_packed)
	if placed is None:
		suite.skip(placement.path,
		           "native byte order has no fixed encoding to check")
		return

	if scalar.signed:
		want = f"(int64_t){_signed_value(raw, bits)}"
		got  = f"(int64_t){_getter(struct, placement, prefix)}"
	elif decoded is not None:
		want = f"(uint64_t){decoded}u"		# BCD: the digits, not the nibbles
		got  = f"(uint64_t){_getter(struct, placement, prefix)}"
	else:
		want = f"(uint64_t){raw:#x}u"
		got  = f"(uint64_t){_getter(struct, placement, prefix)}"

	order = "bit-packed" if scalar.is_bit_packed else "byte-aligned"
	body  = [*_acquire(struct, prefix, extent), ""]
	body.append(f"\t/* {order}, {bits}-bit, "
	            f"{(placement.endian.value if placement.endian else 'declared')}"
	            f" order at bit {placement.offset_bits}. */")
	for at in sorted(placed):
		body.append(f"\tbuf[{at}u] = {placed[at]:#04x}u;")
	body.append("")
	body.append(f"\tassert_int_equal({got}, {want});")

	suite.add(
		f"check_{c_name(placement.path)}_decodes_a_known_encoding",
		body,
		[f"/* {placement.path}: these bytes, and therefore this value.",
		 " *",
		 " * The expected bytes are computed from the map's offset and declared",
		 " * order, not from the accessor, so a getter that reads the right",
		 " * bytes in the wrong order fails here and nowhere else. */"])


def _constrained(placement: Placement) -> bool:
	"""A field a constraint pins cannot take arbitrary boundary values."""
	return any(attr.name in ("must_eq", "max", "min") for attr in placement.attrs)


def _boundary_values(scalar: object) -> list[str]:
	bits   = getattr(scalar, "bits", 8)
	signed = getattr(scalar, "signed", False)
	ctype  = _ctype(scalar)

	# A BCD field's range is decimal, not binary: `bcd2` holds 0 to 99, and
	# writing 255 to it stores digits that are not 255. The setter would
	# encode it, the getter would decode something else, and the round trip
	# would fail for a reason that is the check's fault rather than the code's.
	if getattr(scalar, "is_bcd", False):
		return [f"({ctype})0", f"({ctype}){scalar.decimal_max}u"]	# type: ignore[attr-defined]

	if signed:
		high = (1 << (bits - 1)) - 1
		low  = -(1 << (bits - 1))
		return [f"({ctype})0", f"({ctype}){high}", f"({ctype})({low})"]

	return [f"({ctype})0", f"({ctype})0x{(1 << bits) - 1:X}u"]


def _ctype(scalar: object) -> str:
	bits   = getattr(scalar, "bits", 8)
	signed = getattr(scalar, "signed", False)
	width  = next((w for w in WORD_WIDTHS if bits <= w), 64)
	return f"{'int' if signed else 'uint'}{width}_t"


def _validate_checks(suite: Suite, resolved: ResolvedSchema, struct: ResolvedStruct,
		prefix: str, extent: int) -> None:
	"""Each declared constraint must actually refuse a buffer that breaks it.

	The wrong value is computed here rather than read back through a getter: a
	nested field has no accessor in the enclosing struct, and a check that
	needed one would silently skip exactly the fields most worth checking.
	"""
	from situc.expr import evaluate

	env = resolved.layout.env

	for entry in struct.entries:
		placement = entry.placement
		must_eq   = next((attr for attr in placement.attrs
		                  if attr.name == "must_eq"), None)
		if must_eq is None or must_eq.value is None or placement.offset_bits is None:
			continue
		if placement.offset_bits % BITS_PER_BYTE or placement.size_bits != BITS_PER_BYTE:
			continue

		offset = placement.offset_bits // BITS_PER_BYTE
		if offset >= extent:
			continue

		try:
			demanded = evaluate(must_eq.value, env)
		except Exception:	# noqa: BLE001 - a constraint we cannot fold is one we cannot break
			suite.skip(placement.path, "its `must_eq` is not a compile-time value")
			continue

		wrong = (demanded + 1) & 0xFF

		suite.add(
			f"check_{c_name(placement.path)}_must_eq_is_enforced",
			[
				*_acquire(struct, prefix, extent),
				"",
				f"\t/* The schema demands {demanded}; anything else must be refused. */",
				f"\tbuf[{offset}u] = 0x{wrong:02X}u;",
				f"\tassert_int_equal({ident(prefix, struct.name, 'validate')}(view),",
				"\t                 SITU_ERR_CONSTRAINT);",
			],
			[f"/* {placement.path} declares `must_eq`, which is malleability",
			 " * control rather than pedantry (section 8.8): a value the schema",
			 " * does not admit has to be refused on parse. */"])


def _coverage_checks(suite: Suite, struct: ResolvedStruct, prefix: str,
		extent: int) -> None:
	"""`auth = Covered(t)` is a claim that writing marks `t` stale."""
	tags = [entry.placement for entry in struct.entries
	        if entry.placement.kind in ("tag", "checksum")]
	if not tags:
		return

	covered = [entry for entry in struct.entries
	           if entry.placement.covered_by
	           and entry.placement.scalar is not None
	           and entry.placement.kind == "field"
	           and entry.placement.array_count is None
	           and entry.placement.sized_by is None
	           and entry.placement.sealed_by is None
	           and entry.vector.get(Axis.MUTATE).base == "InPlaceFixed"]
	if not covered:
		return

	entry  = covered[0]
	local  = c_name(entry.placement.path[len(struct.name) + 1:])
	setter = ident(prefix, struct.name, local, "set")
	tag    = tags[0].name
	ctype  = _ctype(entry.placement.scalar)

	_span_check(suite, struct, prefix, extent, tag)

	suite.add(
		f"check_{c_name(struct.name)}_covered_write_marks_{c_name(tag)}",
		[
			*_acquire(struct, prefix, extent),
			"",
			"\tassert_int_equal(situ_msg_transmittable(&msg), SITU_OK);",
			"",
			f"\t{setter}(&msg, view, ({ctype})1);",
			"",
			f"\tassert_true({ident(prefix, struct.name, c_name(tag), 'is_dirty')}"
			"(&msg));",
			"\tassert_int_equal(situ_msg_transmittable(&msg), SITU_ERR_TAG);",
			"",
			f"\t{ident(prefix, struct.name, c_name(tag), 'finalize')}(&msg);",
			"\tassert_int_equal(situ_msg_transmittable(&msg), SITU_OK);",
		],
		[f"/* {entry.placement.path} is Covered({tag}). Section 14.2 says a write",
		 " * to it leaves the tag stale and the message refuses to be",
		 " * transmittable until finalize puts it right. */"])


def _span_check(suite: Suite, struct: ResolvedStruct, prefix: str,
		extent: int, tag: str) -> None:
	"""What the tag's algorithm actually runs over.

	The span is not recomputed here. A region's extent is its interior put
	through a codec's expansion, and reconstructing that would duplicate the
	solver -- which is exactly why the emitter takes the region's end from where
	the next member starts instead.

	But it can be bounded from the outside without the solver, and that is
	enough: every member the map says is covered has to be inside the span. A
	span that collapsed, or that started past the first covered byte, fails
	that whatever the expansion turns out to be. Mutation testing found a region
	ending at its own start with nothing generated to notice.
	"""
	known = [entry.placement for entry in struct.entries
	         if entry.placement.covered_by
	         and entry.placement.offset_bits is not None
	         and entry.placement.size_bits
	         and entry.placement.kind != "authenticated"]
	if not known:
		return

	first = min(placement.offset_bits or 0 for placement in known)
	last  = max((placement.offset_bits or 0) + placement.size_bits
	            for placement in known)
	if first % BITS_PER_BYTE or last % BITS_PER_BYTE:
		return

	begins = first // BITS_PER_BYTE
	ends   = last // BITS_PER_BYTE

	suite.add(
		f"check_{c_name(struct.name)}_{c_name(tag)}_covers_what_it_claims",
		[
			*_acquire(struct, prefix, extent),
			"",
			"\tuint32_t offset = 0;",
			"\tuint32_t len    = 0;",
			"",
			f"\tassert_int_equal({ident(prefix, struct.name, c_name(tag), 'covered')}"
			"(view, &offset, &len), SITU_OK);",
			"",
			f"\t/* The map says bytes {begins}..{ends} are covered. The span may",
			"\t * reach further -- a codec's expansion is its own business -- but",
			"\t * it may not leave any of them out. */",
			f"\tassert_true(offset <= {begins}u);",
			f"\tassert_true(offset + len >= {ends}u);",
			"",
			"\t/* And it has to stay inside the message it is computed over. */",
			"\tassert_true(offset + len <= view.limit);",
		],
		[f"/* {struct.name}.{tag} covers {ends - begins} bytes of named members.",
		 " *",
		 " * Bounded rather than recomputed: the extent of a coded region is its",
		 " * interior through the codec's expansion, and duplicating that here",
		 " * would just be a second solver to get wrong. */"])


def _gate_checks(suite: Suite, struct: ResolvedStruct, prefix: str,
		extent: int) -> None:
	"""The stage gate of 14.3, on the half that can be tested at run time."""
	for entry in struct.entries:
		placement = entry.placement
		if placement.kind != "sealed" or placement.unverified_ok:
			continue

		local = c_name(placement.path[len(struct.name) + 1:])
		gate  = ident(prefix, struct.name, local, "t")

		suite.add(
			f"check_{c_name(placement.path)}_refuses_before_verification",
			[
				*_acquire(struct, prefix, extent),
				f"\t{gate} gate;",
				"",
				"\tmemset(&gate, 0, sizeof gate);",
				f"\tassert_int_equal({ident(prefix, struct.name, local, 'open')}"
				"(view, 0, &gate), SITU_ERR_TAG);",
				"\tassert_null(gate.view.base);",
				"",
				f"\tassert_int_equal({ident(prefix, struct.name, local, 'open')}"
				"(view, 1, &gate), SITU_OK);",
				"\tassert_non_null(gate.view.base);",
			],
			[f"/* {placement.path} is VerifyGated. The half of 14.3 that a running",
			 " * test can reach: no view into the interior before the tag",
			 " * verifies. That reaching it does not *compile* is the other half,",
			 " * and no test that runs can show it. */"])


# ---------------------------------------------------------------------------
# The MMIO target
# ---------------------------------------------------------------------------


def _register_checks(suite: Suite, struct: ResolvedStruct, prefix: str) -> None:
	"""Exercise a register against memory standing in for the bus.

	A user cannot issue a bus transaction in CI, and the arithmetic is what
	goes wrong anyway: which bits a field occupies, what a builder composes,
	what a `w1c` clear writes. Pointing the accessors at an array checks all of
	that. What it cannot check is the bus itself, which is the part no test
	could reach.
	"""
	info = struct.layout.register
	assert info is not None

	if info.access_width not in WORD_WIDTHS:
		suite.skip(struct.name, "access width is not a width C can name")
		return

	block = ((info.address or 0) + info.access_width // BITS_PER_BYTE)
	word  = f"uint{info.access_width}_t"
	name  = struct.name

	fields = [entry for entry in struct.entries
	          if entry.placement.kind == "field"
	          and entry.placement.access_mode is not None]

	for entry in fields:
		placement = entry.placement
		mode      = placement.access_mode
		assert mode is not None
		if not mode.readable or not mode.writable or not mode.is_assignment:
			continue

		local = c_name(placement.path[len(name) + 1:])
		mask  = (1 << placement.size_bits) - 1
		shift = placement.offset_bits or 0

		suite.add(
			f"check_{c_name(placement.path)}_composes_and_decodes",
			[
				f"\t{word} word = 0;",
				"",
				f"\tword = {ident(prefix, name, local, 'with')}(word, "
				f"({word})0x{mask:X}u);",
				f"\tassert_int_equal(word, ({word})(0x{mask:X}u << {shift}u));",
				f"\tassert_int_equal({ident(prefix, name, local, 'get')}(word), "
				f"({word})0x{mask:X}u);",
				"",
				"\t/* And it must leave every other bit of the word alone. */",
				f"\tword = ({word})~({word})0;",
				f"\tword = {ident(prefix, name, local, 'with')}(word, ({word})0);",
				f"\tassert_int_equal(word, "
				f"({word})~(({word})0x{mask:X}u << {shift}u));",
			],
			[f"/* {placement.path}: the builder places the field and the getter",
			 " * takes it back out, and neither touches a neighbouring bit. */"])

	_register_bit_operations(suite, struct, prefix, block, word)


def _register_bit_operations(suite: Suite, struct: ResolvedStruct, prefix: str,
		block: int, word: str) -> None:
	"""`w1c` writes a one to clear; a trigger writes only its own bit."""
	info = struct.layout.register
	assert info is not None
	name = struct.name

	for entry in struct.entries:
		placement = entry.placement
		mode      = placement.access_mode
		if mode is None or placement.kind != "field":
			continue

		local = c_name(placement.path[len(name) + 1:])
		mask  = (1 << placement.size_bits) - 1
		shift = placement.offset_bits or 0
		at    = ident(prefix, name, "at")

		if mode.writable and not mode.is_assignment:
			verb = "clear" if mode in (ast.AccessMode.W1C,
			                           ast.AccessMode.W0C) else "set"
			ones = mode in (ast.AccessMode.W1C, ast.AccessMode.W1S)
			expect = (f"({word})(0x{mask:X}u << {shift}u)" if ones
			          else f"({word})~(({word})0x{mask:X}u << {shift}u)")

			suite.add(
				f"check_{c_name(placement.path)}_{verb}_writes_the_bit",
				[
					f"\tuint8_t block[{block}u];",
					"",
					"\tmemset(block, 0, sizeof block);",
					f"\t{ident(prefix, name, local, verb)}(block);",
					f"\tassert_int_equal(*{at}(block), {expect});",
				],
				[f"/* {placement.path} is `{mode.value}`: the write is not an",
				 f" * assignment, so the operation is a {verb} and what reaches the",
				 " * bus is the bit pattern the hardware acts on. */"])

		if placement.on_write is ast.SideEffect.TRIGGER and mode.writable:
			suite.add(
				f"check_{c_name(placement.path)}_trigger_writes_only_itself",
				[
					f"\tuint8_t block[{block}u];",
					"",
					"\tmemset(block, 0xFF, sizeof block);",
					f"\t{ident(prefix, name, local, 'trigger')}(block);",
					f"\tassert_int_equal(*{at}(block), "
					f"({word})(0x{mask:X}u << {shift}u));",
				],
				[f"/* {placement.path} has `on_write = trigger`. It writes a word",
				 " * with this field set and every other field zero, which is the",
				 " * only word that can be composed without reading first. */"])
