"""Generate tests that hold the emitted code to what the map claims.

`situc map` is the product: it says a field sits at offset 4, occupies two
bytes, can be written without moving anything, and goes stale when a tag
covers it. Nothing checked that the generated C agreed. A capability map that
the accessors quietly contradict is worse than no map, because it is believed.

So this is the same discipline `gen-codec-tests` applies to a codec signature,
turned on the compiler's own output. The compiler cannot verify an
implementation it never sees; it *can* generate the tests that would falsify
one, and its own backend is no more trustworthy than anybody else's algorithm.

Everything here derives from the schema alone. A user runs `situc gen-checks`
and gets a suite, with no vectors to write and nothing to keep in step by hand
-- which is what makes it get run.

The conformance checks work from the outside. Rather than asserting that an
accessor was emitted a particular way, they poke bytes in the buffer and watch
which ones the accessor notices: a field claiming offset 4 and size 2 must see
every one of those bytes change and no other. That catches an offset the
backend got wrong, a mask that is too wide, and a stride that drifted, without
knowing anything about how the accessor is written.
"""

from __future__ import annotations

import re

from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c import frame
from situc.codegen.c.names import c_name, ident, macro
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.relation import conversation_key
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import (
	Obligation, data_sized, enclosing_arm, has_computable_extent,
	indexed_elements, obligations, own_members, local_name,
)

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Suite:
	"""The checks emitted, and the ones deliberately not."""

	lines: list[str]      = field(default_factory=list)
	names: list[str]      = field(default_factory=list)
	skipped: list[str]    = field(default_factory=list)
	#: Headers beyond the schema's own, added by a check family that needs
	#: one. A relation's predicate lives in `<basename>_relate.h`, which the
	#: view-level suite has no reason to include and must not include when
	#: the schema declares no relation -- the file is not emitted then.
	includes: list[str]   = field(default_factory=list)

	def add(self, name: str, body: list[str], doc: list[str]) -> None:
		self.lines.extend(["", *doc,
		                   f"static void {name}(void **state)", "{",
		                   "\t(void)state;", *body, "}"])
		self.names.append(name)

	def skip(self, subject: str, why: str) -> None:
		self.skipped.append(f"{subject}: {why}")


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> str:
	suite = Suite()

	for name in sorted(resolved.structs):
		struct = resolved.structs[name]
		if struct.layout.register is not None:
			_register_checks(suite, struct, prefix)
		else:
			_struct_checks(suite, schema, resolved, struct, prefix)

	_relation_checks(suite, schema, resolved, basename, prefix)
	_frame_checks(suite, resolved, basename, prefix)

	return _render(suite, basename)


def _render(suite: Suite, basename: str) -> str:
	lines = [
		f"/* Generated by situc from {basename}.situ -- do not edit.",
		" *",
		" * Every check here is derived from the schema, and every one of them",
		" * holds the generated accessors to what the capability map claims. A",
		" * map the accessors contradict is worse than no map, because it is",
		" * believed.",
		" */",
		"",
		"#include <setjmp.h>",
		"#include <stdarg.h>",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <string.h>",
		"",
		"#include <cmocka.h>",
		"",
		f'#include "{basename}.h"',
	]

	lines.extend(f'#include "{header}"' for header in suite.includes)

	if suite.skipped:
		lines.extend(["", "/* Not checked here, and why:"])
		lines.extend(f" *   {note}" for note in suite.skipped)
		lines.append(" */")

	lines.extend(suite.lines)

	if not suite.names:
		lines.extend([
			"",
			"/* Nothing in this schema has a checkable accessor yet. cmocka",
			" * refuses an empty group, so this one asserts that it is empty on",
			" * purpose rather than by accident. */",
			"static void test_nothing_to_check(void **state)",
			"{",
			"\t(void)state;",
			"}",
		])
		suite.names.append("test_nothing_to_check")

	lines.extend(["", "int main(void)", "{", "\tconst struct CMUnitTest checks[] = {"])
	lines.extend(f"\t\tcmocka_unit_test({name})," for name in suite.names)
	lines.extend(["\t};", "",
	              "\treturn cmocka_run_group_tests(checks, NULL, NULL);", "}"])

	return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Relations
# ---------------------------------------------------------------------------


def _relation_checks(suite: Suite, schema: ast.Schema, resolved: ResolvedSchema,
		basename: str, prefix: str) -> None:
	"""A relation's predicate, executed rather than merely compiled.

	Two zeroed messages satisfy every equality a relation can state, and a
	message of `0xff` beside a zeroed one satisfies none of them. That gives a
	positive and a negative case without reading an offset or naming a
	member's type, which is what lets this cover a nested path and a bit-packed
	enum on the same terms as a plain integer.

	**Both cases or neither.** A predicate that answers `SITU_OK` to everything
	passes the positive alone, and one that answers `SITU_ERR_CONSTRAINT` to
	everything passes the negative alone; only the pair says the predicate
	discriminates. That is the same reasoning as invariant 35, applied to the
	one construct that had generated code nothing ever ran.
	"""
	emitted = False

	for relation in schema.relations():
		name = relation.name
		key  = conversation_key(relation)

		if not key:
			suite.skip(f"relation {name}", "states no equality, so a pair of "
			           "zeroed messages is not known to satisfy it")
			continue
		if len(key) != len(relation.body):
			suite.skip(f"relation {name}", "carries a constraint that is not "
			           "an equality, which zeroed messages need not satisfy")
			continue

		params = []
		for param in relation.params:
			struct = resolved.structs.get(param.type_name)
			extent = None
			if (struct is not None and struct.layout.is_byte_sized
					and struct.layout.is_fixed_size):
				extent = _buffer_size(struct.layout)
			params.append((param.name, struct, extent))

		if any(extent is None for _, _, extent in params):
			suite.skip(f"relation {name}", "names a message whose extent is "
			           "decided by the data, so a fixed buffer cannot stand in")
			continue

		def case(fill: int, expect: str) -> list[str]:
			decls: list[str] = []
			stmts: list[str] = []
			fills = (fill, 0x00)

			for (label, struct, extent), byte in zip(params, fills):
				assert struct is not None
				decls.extend([
					f"\tuint8_t {label}_buf[{extent}u];",
					f"\tsitu_msg_t {label}_msg;",
					f"\tsitu_view_t {label}_view;",
				])
				view = ident(prefix, struct.name, "view")
				stmts.extend([
					f"\tmemset({label}_buf, 0x{byte:02x}, sizeof {label}_buf);",
					f"\tsitu_msg_init(&{label}_msg, {label}_buf, "
					f"(uint32_t)sizeof {label}_buf);",
					f"\tassert_int_equal({view}(&{label}_msg, 0, &{label}_view), "
					"SITU_OK);",
				])

			args = ", ".join(f"{label}_view" for label, _, _ in params)
			stmts.append(f"\tassert_int_equal({ident(prefix, 'rel', name)}"
			             f"({args}), {expect});")
			return [*decls, "", *stmts]

		spelled = ", ".join(f"{left} == {right}" for left, right in key)

		suite.add(
			f"check_relation_{c_name(name)}_holds_when_the_key_matches",
			case(0x00, "SITU_OK"),
			[f"/* {name} says {spelled}. Two zeroed messages agree on every",
			 " * one of those, so the predicate must accept the pair. */"])

		suite.add(
			f"check_relation_{c_name(name)}_refuses_a_mismatched_key",
			case(0xff, "SITU_ERR_CONSTRAINT"),
			[f"/* The same relation, with the first message filled with 0xff:",
			 " * every equality above now compares a nonzero value against a",
			 " * zero one, so the predicate must refuse the pair. Without this",
			 " * case a predicate that accepts everything would still pass. */"])

		emitted = True

	if emitted:
		suite.includes.append(f"{basename}_relate.h")


# ---------------------------------------------------------------------------
# Framing
# ---------------------------------------------------------------------------


def _frame_checks(suite: Suite, resolved: ResolvedSchema, basename: str,
		prefix: str) -> None:
	"""Rung 4's reader, fed the way a stream actually arrives.

	The permission this rung buys is holding bytes between calls, so the
	property worth checking is that where the bytes are cut does not change
	what comes out. Pushing one byte at a time cuts the stream at every
	boundary there is, which is the strongest version of that for the cost of
	a loop.

	The pair discriminates for the same reason as the relation one. A reader
	that announced a message on every push would satisfy "two messages arrive"
	and fail on a stream a byte short; one that never announced anything would
	pass the short case and fail the whole one.
	"""
	emitted = False

	for struct in frame.framed_structs(resolved):
		name   = struct.name
		layout = struct.layout

		if not (layout.is_byte_sized and layout.is_fixed_size):
			suite.skip(f"framing {name}", "has no fixed extent, so a stream of "
			           "whole messages cannot be built out of zeroes")
			continue

		extent = _buffer_size(layout)
		if extent is None or extent < 2:
			suite.skip(f"framing {name}", "is under two bytes, so there is no "
			           "partial message C can declare a buffer for")
			continue

		reader = ident(prefix, name, "reader")
		whole  = extent * 2

		suite.add(
			f"check_{c_name(name)}_reader_reassembles_across_every_boundary",
			[
				f"\tuint8_t stream[{whole}u];",
				f"\tuint8_t back[{whole}u];",
				f"\t{reader}_t reader;",
				"\tsitu_msg_t msg;",
				"\tsitu_view_t view;",
				"\tuint32_t seen = 0u;",
				"\tuint32_t i;",
				"",
				"\tmemset(stream, 0, sizeof stream);",
				f"\t{reader}_init(&reader, back, (uint32_t)sizeof back);",
				"",
				"\tfor (i = 0u; i < (uint32_t)sizeof stream; i++) {",
				f"\t\tassert_int_equal({reader}_push(&reader, &stream[i], 1u),",
				"\t\t                 SITU_OK);",
				"\t\t/* Bounded by the answer, not by the reader. A reader that",
				"\t\t * announced a message on every call would spin here for",
				"\t\t * ever, and a test that hangs is worse than one that",
				"\t\t * fails: the third message is impossible, so seeing it is",
				"\t\t * the failure. */",
				f"\t\twhile (seen <= 2u",
				f"\t\t       && {reader}_next(&reader, &msg, &view) == SITU_OK) {{",
				"\t\t\tseen++;",
				f"\t\t\t{reader}_advance(&reader);",
				"\t\t}",
				"\t}",
				"",
				"\tassert_int_equal(seen, 2u);",
			],
			[f"/* Two whole {name} messages pushed one byte at a time, which",
			 " * cuts the stream at every boundary it has. Exactly two must",
			 " * come out: where the bytes were split is not allowed to change",
			 " * what the reader reassembles. */"])

		suite.add(
			f"check_{c_name(name)}_reader_yields_nothing_from_a_partial_message",
			[
				f"\tuint8_t stream[{extent - 1}u];",
				f"\tuint8_t back[{extent}u];",
				f"\t{reader}_t reader;",
				"\tsitu_msg_t msg;",
				"\tsitu_view_t view;",
				"",
				"\tmemset(stream, 0, sizeof stream);",
				f"\t{reader}_init(&reader, back, (uint32_t)sizeof back);",
				f"\tassert_int_equal({reader}_push(&reader, stream,",
				"\t                 (uint32_t)sizeof stream), SITU_OK);",
				f"\tassert_int_equal({reader}_next(&reader, &msg, &view),",
				"\t                 SITU_ERR_TRUNCATED);",
			],
			[f"/* One byte short of a whole {name}. A reader that handed this",
			 " * out would be handing out a message that has not arrived, and",
			 " * without this case a reader announcing one on every push would",
			 " * still satisfy the check above. */"])

		emitted = True

	if emitted:
		suite.includes.append(f"{basename}_frame.h")


# ---------------------------------------------------------------------------
# Buffer-target structs
# ---------------------------------------------------------------------------


def _struct_checks(suite: Suite, schema: ast.Schema, resolved: ResolvedSchema,
		struct: ResolvedStruct, prefix: str) -> None:
	layout = struct.layout

	if not layout.is_byte_sized:
		suite.skip(struct.name, "not a whole number of bytes, so it has no accessors")
		return

	extent = _buffer_size(layout)
	if extent is None:
		_instance_checks(suite, resolved, struct, prefix)
		return

	_view_checks(suite, struct, prefix, extent)

	for entry in struct.entries:
		_field_checks(suite, resolved, struct, entry, prefix, extent)

	_validate_checks(suite, schema, resolved, struct, prefix, extent)
	_coverage_checks(suite, schema, resolved, struct, prefix, extent)
	_gate_checks(suite, struct, prefix, extent)


#: What each dynamic member is given when an instance is synthesised. Two, so
#: that a stride exists to be wrong about, and small enough that the whole
#: instance stays a comfortable buffer.
INSTANCE_COUNT = 2

#: Bytes left over for a trailing `remaining` member, so it has somewhere to be.
INSTANCE_TAIL = 8

#: Floor for an instance whose tail cannot be sized, so a run walking it has
#: room for more than the one element nobody is claiming it has.
MIN_INSTANCE = 32


def _element_bytes(resolved: ResolvedSchema, placement: Placement) -> int | None:
	"""How many bytes one element of an array member takes."""
	if placement.scalar is not None:
		if placement.scalar.bits % BITS_PER_BYTE:
			return None
		return placement.scalar.bits // BITS_PER_BYTE
	nested = resolved.structs.get(placement.type_name or "")
	if nested is None or not nested.layout.is_fixed_size:
		return None
	return int(nested.layout.size_bytes)


#: Content bytes given to each delimited member of a synthesised instance.
#: Non-zero so that a member's content is distinguishable from the zero fill,
#: and small enough that several fit a comfortable buffer.
INSTANCE_CONTENT = 3


def _member_bytes(resolved: ResolvedSchema, placement: Placement,
		chosen: dict[str, int]) -> int | None:
	"""The size this member takes in the synthesised instance.

	`None` means the walk cannot continue: something here has no size this code
	knows how to pin down, and guessing would put every later member on an
	offset the check would then assert with confidence.
	"""
	if placement.delimiter is not None:
		if placement.type_name in resolved.structs:
			# A run of records, synthesised empty: the terminator stands where
			# the first element would. Building a populated one would mean
			# synthesising the element's own delimiters recursively, and the
			# empty run is worth pinning in its own right -- "the terminator
			# is at position zero, so there are no elements" is the first
			# thing a walk gets wrong.
			return len(placement.delimiter)

		# Chosen rather than derived: a delimited member is as long as the
		# instance decides to make it, and the instance writes the delimiter
		# where it says. Deriving it from `size_bits` gives the empty-content
		# case, and the check then asserts an offset the accessor -- scanning
		# a buffer with no delimiter anywhere in it -- has no reason to agree
		# with.
		return INSTANCE_CONTENT + len(placement.delimiter)

	if placement.sized_by == "remaining":
		return INSTANCE_TAIL
	if placement.sized_by is not None:
		each = _element_bytes(resolved, placement)
		return None if each is None else each * chosen[placement.sized_by]
	if placement.repeat_while is not None:
		# How many elements a `while` run has is decided by the bytes, and
		# this instance is zeroed -- so whether the run ends at the first
		# element is a question about the predicate, which this does not
		# evaluate. Falling through below answered "one element", which is the
		# `array_count` lie by another route: the members after it were then
		# placed at an offset the run walks straight past.
		return None
	if placement.array_count is not None:
		each = _element_bytes(resolved, placement)
		return None if each is None else each * placement.array_count
	if placement.size_bits is None or placement.size_bits % BITS_PER_BYTE:
		return None
	return placement.size_bits // BITS_PER_BYTE


def _instance_checks(suite: Suite, resolved: ResolvedSchema,
		struct: ResolvedStruct, prefix: str) -> None:
	"""One concrete instance of a struct that has no worst case.

	An unbounded struct got no checks at all, because no buffer can be sized for
	the general case. But nothing forces the general case: pick a length for
	every member that has one, and the layout that follows is arithmetic. That
	is what a user does by hand, and it is the only thing that holds the offset
	functions to account -- they are the whole reason the struct is unbounded,
	and mutation testing found them checked by nothing.

	The offsets asserted here are computed by walking the members and adding up
	their chosen sizes. The accessors compute theirs by summing length fields at
	run time. Two different routes to the same number, which is what makes
	disagreement mean something.
	"""
	members = own_members(struct)
	# A member sized by *arithmetic* is driven too, and this counted only the
	# bare references: `u8 value[length - 1]` has a `size_expr` and no
	# `sized_by`, so `length` was left at zero and the span check came out as
	# "bytes 2..1" -- an empty range whose loop never ran and whose assertion
	# therefore failed. `examples/ble`'s AD structure is the shape (26.36).
	named = {placement.sized_by for placement in members
	         if placement.sized_by and placement.sized_by != "remaining"}
	for placement in members:
		if placement.size_expr is not None:
			# `size_expr` is the rendered source, not a tree: the identifiers
			# in it are the fields it reads.
			named |= {word for word in re.findall(r"[A-Za-z_][A-Za-z0-9_.]*",
			                                      placement.size_expr)
			          if resolved.find(f"{struct.name}.{word}") is not None}
	drivers = sorted(named)

	chosen  = {path: INSTANCE_COUNT for path in drivers}
	setters = []
	for path in drivers:
		target = resolved.find(f"{struct.name}.{path}")
		if target is None or target.placement.scalar is None:
			suite.skip(struct.name, f"`{path}` sizes a member but has no setter")
			return
		setters.append(f"\t{ident(prefix, struct.name, c_name(path), 'set')}"
		               f"(&msg, view, {INSTANCE_COUNT});")

	# Walk the members, giving each the size the chosen values imply.
	offsets: list[tuple[Placement, int]] = []
	at = 0
	unpinned: str | None = None
	for placement in members:
		size = _member_bytes(resolved, placement, chosen)
		if size is None:
			# Stop asserting here rather than abandoning the struct. Where
			# *this* member starts is still known and still worth pinning; it
			# is everything after it that is not, so the walk records the
			# member and stops.
			offsets.append((placement, at))
			unpinned = placement.path
			break
		offsets.append((placement, at))
		at += size

	if unpinned is not None:
		# The buffer still has to hold something the accessors can walk. The
		# minimum is what the layout guarantees, doubled so a run has room for
		# more than the one element it is not being asserted to have.
		at = max(at * 2, struct.layout.size_bytes * 2, MIN_INSTANCE)

	total = at
	body  = [
		f"\tuint8_t buf[{total}u];",
		"\tsitu_msg_t msg;",
		# Zeroed rather than left to the acquisition: a view is written only
		# when `situ_view_at` succeeds, and a compiler that cannot prove the
		# assertion below holds is right to say so.
		"\tsitu_view_t view = {0};",
		"",
		"\tmemset(buf, 0, sizeof buf);",
	]

	delimited = [(placement, offset) for placement, offset in offsets
	             if placement.delimiter is not None]
	if delimited:
		body.extend([
			"",
			f"\t/* Put each delimiter {INSTANCE_CONTENT} bytes into its member, so",
			"\t * the scan has something to find. Without this every delimited",
			"\t * member runs to the end of the buffer and the offsets below",
			"\t * are arithmetic about a frame that does not exist. */",
		])
		for placement, offset in delimited:
			assert placement.delimiter is not None
			# A byte array's delimiter ends its content; a run's terminator
			# stands where an element would start. Putting a run's terminator
			# after three bytes of zeros made the walk try to parse those
			# zeros as an element.
			at = offset if placement.type_name in resolved.structs \
				else offset + INSTANCE_CONTENT
			for index, byte in enumerate(placement.delimiter):
				body.append(f"\tbuf[{at + index}u] = 0x{byte:02X}u;")

	body.extend([
		"",
		"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
		f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
		f"(&msg, 0, {total}u, &view), SITU_OK);",
	])

	if setters:
		body.extend([
			"",
			f"\t/* Give every variable member {INSTANCE_COUNT} elements. Each of",
			"\t * these bumps the generation, so the view is taken again after. */",
			*setters,
			"",
			f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
			f"(&msg, 0, {total}u, &view), SITU_OK);",
		])

	asserted = 0
	for placement, offset in offsets:
		lines = _instance_assertions(struct, placement, prefix, offset, chosen)
		if lines:
			body.extend(["", *lines])
			asserted += 1

	if not asserted:
		suite.skip(struct.name, "unbounded, and no member exposes where it starts")
		return

	suite.add(
		f"check_{c_name(struct.name)}_places_its_members_in_one_instance",
		body,
		[f"/* {struct.name} has no worst case, so no buffer fits every instance.",
		 " * This is one instance: every variable member given"
		 f" {INSTANCE_COUNT} elements,",
		 " * and each member asked where it starts.",
		 " *",
		 " * The expected offsets are added up from the chosen sizes; the",
		 " * accessors sum length fields at run time. Two routes to the same",
		 " * number, so a disagreement is a real one."
		 + ("" if unpinned is not None else " */"),
		 *([] if unpinned is None else [
			 " *",
			 f" * Assertions stop at `{unpinned}`: how far it reaches is",
			 " * decided by the bytes rather than by a length this can",
			 " * choose, so where the members after it start is not a",
			 " * number to assert. */"]),
		 ])


def _instance_assertions(struct: ResolvedStruct, placement: Placement,
		prefix: str, offset: int, chosen: dict[str, int]) -> list[str]:
	"""Ask one member where it starts, however it is willing to say."""
	if placement.kind != "field":
		return []

	local = c_name(placement.path[len(struct.name) + 1:])
	name  = placement.path
	lines = [f"\t/* {name} starts at {offset}. */"]

	# Before the counted case. This reached the delimiter branch below only
	# because the solver claimed `array_count = 1` for a delimited member --
	# so the condition passed for the wrong reason and the right thing
	# happened by accident. Removing that lie exposed it, and only the
	# compile step noticed: pytest was green and the generated C was not.
	#
	# Then exactly the same thing for a `while` run, which carried the same
	# false count for the same reason, and fell through to the nested-struct
	# branch the moment it stopped. A run has `_count` and `_at`; it has no
	# `_view`, because there is no one instance to take a view of.
	if placement.delimiter is not None or placement.sized_by is not None \
			or placement.repeat_while is not None \
			or placement.array_count is not None:
		# A delimited byte run has a pointer and a length like any other; only
		# a run of *records* has a count and an indexed accessor. The element
		# type is what separates them, not the delimiter.
		if placement.scalar is not None:
			ptr = ident(prefix, struct.name, local, "ptr")
			lines.append(f"\tassert_int_equal((uint32_t)({ptr}(view) - view.base),"
			             f" {offset}u);")
			if placement.sized_by and placement.sized_by != "remaining":
				length = ident(prefix, struct.name, local, "len")
				lines.append(f"\tassert_int_equal({length}(view),"
				             f" {chosen[placement.sized_by]}u);")
			return lines

		at    = ident(prefix, struct.name, local, "at")
		first = f"first_{local}"

		if placement.delimiter is not None:
			# The instance is the empty run. Asking for element 0 must fail,
			# and the count must be zero -- which is the answer a walk that
			# looked for its terminator anywhere rather than only where an
			# element would start does not give.
			count = ident(prefix, struct.name, local, "count")
			lines.extend([
				f"\tsitu_view_t {first};",
				f"\tassert_int_equal({count}(view), 0u);",
				f"\tassert_int_equal({at}(view, 0u, &{first}), SITU_ERR_BOUNDS);",
			])
			return lines

		if placement.repeat_while is not None:
			# How many there are depends on the bytes, and this instance is
			# zeroed -- so whether there is even *one* depends on what the
			# condition makes of a zeroed element. Every `while` run in the
			# tree yielded one until `examples/netlink`, whose condition is
			# `nla_len >= 4`: a zeroed attribute declares a length of zero,
			# which is not an attribute, and the run is empty.
			#
			# So the assertion is that the count and the element accessor
			# agree, and that where there is an element it is where the map
			# says. Asking only the second question asserted that a zeroed
			# buffer produces an element, which is a property of the schema
			# rather than of the accessors.
			count = ident(prefix, struct.name, local, "count")
			lines.extend([
				f"\tsitu_view_t {first};",
				f"\tif ({count}(view) > 0u) {{",
				f"\t\tassert_int_equal({at}(view, 0u, &{first}), SITU_OK);",
				f"\t\tassert_int_equal((uint32_t)({first}.base - view.base),"
				f" {offset}u);",
				"\t} else {",
				f"\t\tassert_int_equal({at}(view, 0u, &{first}),"
				" SITU_ERR_BOUNDS);",
				"\t}",
			])
			return lines

		lines.extend([
			f"\tsitu_view_t {first};",
			f"\tassert_int_equal({at}(view, 0u, &{first}), SITU_OK);",
			f"\tassert_int_equal((uint32_t)({first}.base - view.base), {offset}u);",
		])
		if placement.sized_by and placement.sized_by != "remaining":
			count = ident(prefix, struct.name, local, "count")
			lines.append(f"\tassert_int_equal({count}(view),"
			             f" {chosen[placement.sized_by]}u);")
		return lines

	if placement.scalar is None and placement.type_name:
		inner = f"inner_{local}"
		view  = ident(prefix, struct.name, local, "view")
		lines.extend([
			f"\tsitu_view_t {inner};",
			f"\tassert_int_equal({view}(view, &{inner}), SITU_OK);",
			f"\tassert_int_equal((uint32_t)({inner}.base - view.base), {offset}u);",
		])
		return lines

	return []


#: The largest instance these checks will build on the stack.
#:
#: The worst case is the right size in principle and not in practice: a cpio
#: entry declares its file size in eight hex digits, so its worst case is four
#: gigabytes, and `uint8_t buf[4294971507u]` is neither a stack frame nor a
#: `uint32_t`. The checks assert *offsets* over a zeroed instance, where every
#: data-decided length reads zero -- so the worst case was never what they
#: needed, only what they asked for.
INSTANCE_CEILING = 64 * 1024


def _buffer_size(layout: object) -> int | None:
	"""A buffer big enough for the worst case, or as much of it as fits."""
	maximum = getattr(layout, "size_max_bytes", None)
	if maximum is not None:
		return min(max(int(maximum), 1), INSTANCE_CEILING)
	minimum = getattr(layout, "size_bytes", 0)
	if getattr(layout, "is_fixed_size", False):
		return max(int(minimum), 1)
	return None


def _acquire(struct: ResolvedStruct, prefix: str, extent: int,
		length: str | None = None) -> list[str]:
	"""The preamble every check shares: a buffer, a message, a view."""
	name = struct.name
	call = (f"{ident(prefix, name, 'view')}(&msg, 0, &view)"
	        if struct.layout.is_fixed_size
	        else f"{ident(prefix, name, 'view')}(&msg, 0, {length or extent}u, &view)")

	return [
		f"\tuint8_t buf[{extent}u];",
		"\tsitu_msg_t msg;",
		"\tsitu_view_t view;",
		"",
		"\tmemset(buf, 0, sizeof buf);",
		"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
		f"\tassert_int_equal({call}, SITU_OK);",
	]


def _view_checks(suite: Suite, struct: ResolvedStruct, prefix: str,
		extent: int) -> None:
	"""A view that does not fit must be refused, not truncated."""
	name   = struct.name
	layout = struct.layout
	least  = layout.size_bytes

	if least <= 1:
		suite.skip(name, "is one byte or less, so there is no shorter buffer "
		           "C can declare")
		return

	call = (f"{ident(prefix, name, 'view')}(&msg, 0, &view)"
	        if layout.is_fixed_size
	        else f"{ident(prefix, name, 'view')}(&msg, 0, {least - 1}u, &view)")

	suite.add(
		f"check_{c_name(name)}_refuses_a_short_buffer",
		[
			f"\tuint8_t buf[{max(least - 1, 1)}u];",
			"\tsitu_msg_t msg;",
			"\tsitu_view_t view;",
			"",
			"\tmemset(buf, 0, sizeof buf);",
			"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
			f"\tassert_int_equal({call}, SITU_ERR_BOUNDS);",
		],
		[f"/* A buffer one byte short of {name} must be refused rather than",
		 " * truncated: a view is the one bounds check, and everything after it",
		 " * trusts it. */"])


def _delimited_checks(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""The scan finds a planted delimiter, and reports its absence.

	Both, because a `_len` that returned the whole buffer would pass the
	second on its own -- and that is what an unterminated member does, so the
	two answers have to be told apart by something.
	"""
	placement = entry.placement
	delim     = placement.delimiter
	if delim is None or placement.offset_bits != 0:
		return
	if placement.scalar is None:
		return		# a run of records; its walk is checked by the instance

	local   = c_name(placement.path[len(struct.name) + 1:])
	length  = ident(prefix, struct.name, local, "len")
	done    = ident(prefix, struct.name, local, "terminated")
	content = 3
	room    = min(extent, content + len(delim) + 4)

	planted = [f"\tbuf[{i}u] = 0x{0x41 + i:02X}u;" for i in range(content)]
	planted += [f"\tbuf[{content + i}u] = 0x{byte:02X}u;"
	            for i, byte in enumerate(delim)]

	suite.add(
		f"check_{c_name(struct.name)}_{local}_stops_at_its_delimiter",
		[
			f"\tuint8_t buf[{room}u];",
			"\tsitu_msg_t msg;",
			"\tsitu_view_t view = {0};",
			"",
			"\tmemset(buf, 0x2E, sizeof buf);",
			*planted,
			"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
			f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
			f"(&msg, 0, {room}u, &view), SITU_OK);",
			"",
			f"\tassert_int_equal({length}(view), {content}u);",
			f"\tassert_true({done}(view));",
		],
		[f"/* {placement.path} runs to its delimiter and stops there. Its",
		 "\t * `size_bits` is the delimiter's own width, so a check written",
		 "\t * against that would assert the one number that is not the",
		 "\t * member's length. */"])

	suite.add(
		f"check_{c_name(struct.name)}_{local}_reports_a_missing_delimiter",
		[
			f"\tuint8_t buf[{room}u];",
			"\tsitu_msg_t msg;",
			"\tsitu_view_t view = {0};",
			"",
			"\tmemset(buf, 0x2E, sizeof buf);",
			"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
			f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
			f"(&msg, 0, {room}u, &view), SITU_OK);",
			"",
			f"\tassert_false({done}(view));",
		],
		["/* And says so when it is not there, rather than reporting an empty",
		 "\t * member: a frame that stops early is not a frame with a short",
		 "\t * field in it. */"])


def _versioned_checks(suite: Suite, resolved: ResolvedSchema,
		struct: ResolvedStruct, entry: Resolved, prefix: str,
		extent: int) -> None:
	"""A member arrives at its version, and is refused before it.

	Both halves. A getter that always returned the bytes would pass the first
	and silently hand back whatever follows for an older message, which is the
	failure `[since]` exists to prevent -- so testing only that it works at
	the right version would test the half that was never in doubt.
	"""
	placement = entry.placement
	version   = placement.version_field
	since     = placement.since
	if version is None or since is None or placement.scalar is None:
		return

	local  = c_name(placement.path[len(struct.name) + 1:])
	getter = ident(prefix, struct.name, local, "get")
	setter = ident(prefix, struct.name, c_name(version), "set")

	# The accessor's own type, not the backing scalar's width. An enum
	# member's out-parameter is `situ_dialect_t *`, and `uint8_t *` is a
	# different pointer type -- the third generator to make this mistake, all
	# three of them reading `scalar.bits` where the header reads the type
	# name. Nothing had ever put an enum behind a `[since]`.
	ctype = (ident(prefix, placement.type_name or "") + "_t"
	         if placement.type_name in resolved.layout.env.enums
	         else _ctype(placement.scalar))

	def body(at_version: int, expected: str) -> list[str]:
		return [
			*_acquire(struct, prefix, extent),
			f"\t{ctype} value = 0;",
			"",
			f"\t{setter}(view, {at_version});",
			f"\tassert_int_equal({getter}(view, &value), {expected});",
		]

	suite.add(
		f"check_{c_name(struct.name)}_{local}_is_readable_from_version_{since}",
		body(since, "SITU_OK"),
		[f"/* {placement.path} arrives in version {since}. */"])

	suite.add(
		f"check_{c_name(struct.name)}_{local}_is_refused_before_version_{since}",
		body(since - 1, "SITU_ERR_VERSION"),
		[f"/* And is not there before it. A getter that returned the bytes",
		 "\t * anyway would hand back whatever follows -- another member's,",
		 "\t * or another message's. */"])

	writer = ident(prefix, struct.name, local, "set")
	suite.add(
		f"check_{c_name(struct.name)}_{local}_is_unwritable_before_version_{since}",
		[
			*_acquire(struct, prefix, extent),
			"",
			f"\t{setter}(view, {since - 1});",
			f"\tassert_int_equal({writer}(view, ({ctype})1), SITU_ERR_VERSION);",
		],
		["/* And cannot be written there either. The getter refused this from",
		 "\t * the start and the setter did not, which is the asymmetry worth",
		 "\t * naming: reading the wrong bytes is a wrong answer, and writing",
		 "\t * them is somebody else's data. */"])


def _passes_unknown(schema: ast.Schema, name: str | None) -> bool:
	"""Whether this enum admits values no member names (section 8.7)."""
	for decl in schema.enums():
		if decl.name == name:
			return decl.effective_default is ast.EnumDefault.PASS
	return False


def _text_number_checks(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str) -> None:
	"""A number written as digits parses, and one written badly does not.

	The claim `repr = TextConverted` makes is that the conversion is real and
	that it can fail. Both halves need holding to: a getter that returned the
	right number for good digits and zero for `12x` would satisfy the first
	and quietly break the second, which is the failure the axis exists to warn
	about.
	"""
	placement = entry.placement
	if placement.offset_bits != 0 or placement.delimiter is None:
		suite.skip(placement.path,
		           "a text number behind another member has no fixed offset to "
		           "write digits at")
		return

	local  = c_name(placement.path[len(struct.name) + 1:])
	getter = ident(prefix, struct.name, local, "get")
	ctype  = _ctype(placement.scalar)
	delim  = placement.delimiter
	digits = "42"
	extent = len(digits) + len(delim) + 4

	def frame(content: str) -> list[str]:
		body = [f"\tmemset(buf, 0, sizeof buf);"]
		for index, char in enumerate(content):
			body.append(f"\tbuf[{index}u] = 0x{ord(char):02X}u;")
		for index, byte in enumerate(delim):
			body.append(f"\tbuf[{len(content) + index}u] = 0x{byte:02X}u;")
		return body

	suite.add(
		f"check_{c_name(struct.name)}_{local}_reads_its_digits",
		[
			f"\tuint8_t buf[{extent}u];",
			"\tsitu_msg_t msg;",
			"\tsitu_view_t view = {0};",
			f"\t{ctype} value = 0;",
			"",
			*frame(digits),
			"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
			f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
			f"(&msg, 0, {extent}u, &view), SITU_OK);",
			"",
			f"\tassert_int_equal({getter}(view, &value), SITU_OK);",
			f"\tassert_int_equal(value, {digits});",
		],
		[f"/* {placement.path} is written as digits. The map calls it",
		 "\t * TextConverted, which is a claim that the conversion happens --",
		 "\t * a getter handing back the first byte would pass no test that",
		 "\t * did not look at the number. */"])

	suite.add(
		f"check_{c_name(struct.name)}_{local}_refuses_what_is_not_a_number",
		[
			f"\tuint8_t buf[{extent}u];",
			"\tsitu_msg_t msg;",
			"\tsitu_view_t view = {0};",
			f"\t{ctype} value = 0;",
			"",
			*frame("4x"),
			"\tsitu_msg_init(&msg, buf, (uint32_t)sizeof buf);",
			f"\tassert_int_equal({ident(prefix, struct.name, 'view')}"
			f"(&msg, 0, {extent}u, &view), SITU_OK);",
			"",
			f"\tassert_int_equal({getter}(view, &value), SITU_ERR_CONSTRAINT);",
			f"\tassert_int_equal({ident(prefix, struct.name, 'validate')}(view),"
			" SITU_ERR_CONSTRAINT);",
		],
		["/* The other half of TextConverted: the conversion can fail, and a",
		 "\t * getter that returned zero for `4x` would be handing back a",
		 "\t * number nobody wrote. */"])


def _field_checks(suite: Suite, resolved: ResolvedSchema, struct: ResolvedStruct,
		entry: Resolved, prefix: str, extent: int) -> None:
	placement = entry.placement
	local     = placement.path[len(struct.name) + 1:]

	if placement.kind in ("element", "reserved"):
		return
	if "." in local and placement.sealed_by is None:
		return		# emitted under the nested struct's own section

	if placement.varint is not None:
		suite.skip(placement.path, "a varint has no fixed extent to check")
		return

	if placement.radix is not None:
		_text_number_checks(suite, struct, entry, prefix)
		return		# no fixed extent, and its getter returns an error rather
				# than a value -- the checks below assume both

	if placement.since is not None:
		_versioned_checks(suite, resolved, struct, entry, prefix, extent)
		return		# same: its getter takes an out-parameter, because there
				# is no value to return when the field is not there

	if placement.delimiter is not None:
		_delimited_checks(suite, struct, entry, prefix, extent)
		return		# it has no `_get` and no fixed extent: the checks below
				# read `size_bits`, which for one of these is the
				# delimiter's own width and not the member's

	# `data_sized` as well, which is the same question with a spelling
	# missing: `u8 d[(n + 1) * 4]` has no scalar accessor either, and this
	# checked it as one -- against a getter the C backend emitted only because
	# it had the same gap in the same place.
	if placement.array_count is not None or placement.sized_by is not None \
			or data_sized(placement):
		_array_checks(suite, struct, entry, prefix, extent)
		return		# no scalar accessor; the elements are what there is to check
	if placement.scalar is None:
		# Only where a sub-view was emitted. A nested struct whose own extent
		# is unknowable has none, and a check calling one is a check that does
		# not compile -- the generated suite failing to build is the same
		# class of wrong as the header failing to.
		if placement.offset_bits is not None:
			_nested_placement_check(suite, resolved, struct, entry, prefix, extent)
		return		# its interior is checked under its own struct's section
	if placement.offset_bits is None:
		return		# a dynamic offset has no fixed extent to name here, and
				# the structs that have one are unbounded, so no buffer can
				# be sized for them either -- recorded as a skip, not checked
	if placement.kind != "field":
		return		# a marker has no plain getter; its own accessors are shaped
				# by the byte order it carries
	if placement.sealed_by is not None and not placement.unverified_ok:
		return		# reached through the gate; checked by _gate_checks

	_extent_check(suite, struct, entry, prefix, extent)
	_round_trip_check(suite, struct, entry, prefix, extent)
	_encoding_check(suite, struct, entry, prefix, extent)


def _outside(first: int, last: int) -> str:
	"""`i` is inside the claimed range, written so no comparison is vacuous.

	`i >= 0u` is always true and `-Wtype-limits` says so, which would make
	generated code that a user compiles with the project's own flags fail to
	build.
	"""
	if first == 0:
		return f"i <= {last}u"
	if first == last:
		return f"i == {first}u"
	return f"i >= {first}u && i <= {last}u"


def _getter(struct: ResolvedStruct, placement: Placement, prefix: str,
		view: str = "view") -> str:
	local = c_name(placement.path[len(struct.name) + 1:])
	return f"{ident(prefix, struct.name, local, 'get')}({view})"


def _extent_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""The map's offset and size claim, checked from outside the accessor.

	Every byte the field claims must be one the getter notices, and no other
	byte may be. That falsifies a wrong offset, a mask that reaches too far and
	a stride that drifted, without assuming anything about how the accessor was
	written.
	"""
	placement = entry.placement
	assert placement.offset_bits is not None, "checked by the caller"

	# A member whose extent the data decides has no byte span to claim:
	# `size_bits` is its *minimum*, which for `u8 value[length - 1]` is zero
	# and makes the range `2..1`. The loop over it never ran, so the check
	# asserted that a getter noticed a change in none of the bytes, and
	# failed for a schema that was right (26.36).
	#
	# What the map says about such a member is a rule rather than a range,
	# which is `_round_trip_check`'s business and the differential drivers'.
	if not placement.is_fixed_size or placement.size_bits == 0:
		return

	first = placement.offset_bits // BITS_PER_BYTE
	last  = (placement.offset_bits + placement.size_bits - 1) // BITS_PER_BYTE

	if last >= extent:
		return

	suite.add(
		f"check_{c_name(placement.path)}_occupies_its_claimed_bytes",
		[
			*_acquire(struct, prefix, extent),
			"",
			f"\tconst uint64_t before = (uint64_t){_getter(struct, placement, prefix)};",
			"\tuint32_t i;",
			"\tint noticed = 0;",
			"",
			f"\t/* The map claims bytes {first}..{last}. Each of them must reach",
			"\t * the value, and nothing else may. */",
			f"\tfor (i = {first}u; i <= {last}u; i++) {{",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			f"\t\tif ((uint64_t){_getter(struct, placement, prefix)} != before) {{",
			"\t\t\tnoticed = 1;",
			"\t\t}",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			"\t}",
			"\tassert_true(noticed);",
			"",
			"\tfor (i = 0; i < (uint32_t)sizeof buf; i++) {",
			f"\t\tif ({_outside(first, last)}) {{",
			"\t\t\tcontinue;",
			"\t\t}",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			f"\t\tassert_int_equal((uint64_t){_getter(struct, placement, prefix)},"
			" before);",
			"\t\tbuf[i] = (uint8_t)~buf[i];",
			"\t}",
		],
		[f"/* {placement.path}: the map claims"
		 f" {entry.vector.get(Axis.OFFSET).render()}"
		 f" {entry.vector.get(Axis.SIZE).render()}.",
		 " *",
		 " * Checked from outside: poke every byte in the buffer and the getter",
		 " * must notice exactly the ones the map named. */"])


def _round_trip_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""Boundary values, and the claim that writing one moves nothing else.

	`mutate = InPlaceFixed` is a promise that a write touches this field's bytes
	and no others. Nothing checked it, and it is the promise the whole language
	is built to make.
	"""
	placement = entry.placement
	scalar    = placement.scalar
	assert scalar is not None

	if entry.vector.get(Axis.MUTATE).base != "InPlaceFixed":
		return
	if placement.covered_by or placement.marker is not None:
		return		# a covered write takes the message; checked separately

	# So does a field that decides where a later member starts: writing it
	# moves them, so the setter bumps the message generation (12.3) and takes
	# two more arguments than this writes. No schema in the tree had a driver
	# whose own struct was checked here until `examples/ble` arrived with
	# `num`, and the suite did not compile (26.36).
	if any(other.placement.sized_by == local_name(struct, placement)
	       for other in struct.entries):
		return
	if placement.kind != "field" or placement.type_name != scalar.name:
		return		# enum-typed setters take the enum, not an integer

	assert placement.offset_bits is not None, "checked by the caller"
	local  = c_name(placement.path[len(struct.name) + 1:])
	setter = ident(prefix, struct.name, local, "set")
	first  = placement.offset_bits // BITS_PER_BYTE
	last   = (placement.offset_bits + placement.size_bits - 1) // BITS_PER_BYTE

	if last >= extent or _constrained(placement):
		return

	values = _boundary_values(scalar)
	body: list[str] = [*_acquire(struct, prefix, extent), ""]
	body.extend([
		"\tuint8_t witness[sizeof buf];",
		"\tuint32_t i;",
		"",
		"\tmemset(buf, 0xA5, sizeof buf);",
	])

	for value in values:
		body.extend([
			"\tmemcpy(witness, buf, sizeof buf);",
			f"\t{setter}(view, {value});",
			f"\tassert_int_equal((uint64_t){_getter(struct, placement, prefix)}, "
			f"(uint64_t)({value}));",
			"",
			"\t/* InPlaceFixed: this field's bytes, and nothing else. */",
			"\tfor (i = 0; i < (uint32_t)sizeof buf; i++) {",
			f"\t\tif ({_outside(first, last)}) {{",
			"\t\t\tcontinue;",
			"\t\t}",
			"\t\tassert_int_equal(buf[i], witness[i]);",
			"\t}",
			"",
		])

	suite.add(
		f"check_{c_name(placement.path)}_round_trips_in_place",
		body[:-1],
		[f"/* {placement.path}: the map claims mutate="
		 f"{entry.vector.get(Axis.MUTATE).render()}.",
		 " *",
		 " * Every boundary value the type admits must survive a write and a",
		 " * read, and the write must leave every other byte alone. */"])


def _nested_placement_check(suite: Suite, resolved: ResolvedSchema,
		struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""Where a nested struct sits inside its parent.

	Its interior is checked thoroughly, but under its own struct's section --
	against a buffer where it starts at zero. That says nothing about where the
	parent puts it, and mutation testing found the hole: moving every nested
	member one byte late passed the whole generated suite, because each nested
	field still agreed with every other nested field.
	"""
	placement = entry.placement

	if placement.kind != "field":
		return		# a region names bytes its members already own, and has no
				# view of its own to locate
	if placement.offset_bits is None or placement.array_count is not None:
		return
	if placement.sized_by is not None or placement.type_name is None:
		return
	# A run is not a nested struct, however few elements it has. It carried a
	# false `array_count = 1` and was excluded above for the wrong reason; the
	# right one is that a run has `_at`, and `_instance_assertions` is where
	# runs are checked.
	if placement.repeat_while is not None or placement.delimiter is not None:
		return
	if placement.offset_bits % BITS_PER_BYTE != 0:
		return
	if placement.sealed_by is not None:
		return		# reached through the gate, which has its own checks

	# Only where a sub-view exists to call. A nested struct whose extent
	# cannot be measured from its own bytes gets none, and this check had its
	# own idea of when that was -- which is to say it had none.
	nested = resolved.structs.get(placement.type_name or "")
	if nested is not None and not nested.layout.is_fixed_size \
			and not has_computable_extent(resolved.structs, nested):
		suite.skip(placement.path,
		           "its type cannot be measured from its own bytes, so there "
		           "is no sub-view accessor to check")
		return

	local  = c_name(placement.path[len(struct.name) + 1:])
	getter = ident(prefix, struct.name, local, "view")
	offset = placement.offset_bits // BITS_PER_BYTE

	suite.add(
		f"check_{c_name(placement.path)}_starts_where_the_map_says",
		[
			*_acquire(struct, prefix, extent),
			"",
			"\tsitu_view_t inner;",
			"",
			f"\tassert_int_equal({getter}(view, &inner), SITU_OK);",
			"",
			"\t/* The map's offset, measured from the parent rather than",
			"\t * recomputed from it. */",
			f"\tassert_int_equal((uint32_t)(inner.base - view.base), {offset}u);",
		],
		[f"/* {placement.path}: the map claims"
		 f" {entry.vector.get(Axis.OFFSET).render()}.",
		 " *",
		 " * Its fields are checked under its own struct, where it begins at",
		 " * zero. Only this says where the parent actually puts it. */"])


def _array_checks(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""Element addressing: the stride, and the bound.

	Arrays had no generated check at all. That is the gap mutation testing found
	last: a stride one byte too wide made every element after the first read the
	wrong bytes, and the whole suite -- generated and hand-written alike -- still
	passed. Nothing else here indexes anything, so nothing else could notice.

	Both checks work from outside the accessor. The stride is read as the
	distance between two element bases, not recomputed from the map, so an
	accessor and a check cannot agree by construction.
	"""
	placement = entry.placement
	local     = c_name(placement.path[len(struct.name) + 1:])
	count     = placement.array_count

	# Behind the gate of 14.3, which the scalar branch has always skipped here
	# and this did not: every accessor for a sealed member takes the gate, so a
	# check calling one with a plain view does not compile. It only arose once
	# an array inside a sealed region *had* accessors -- before that the gap
	# was in the emitter and this could not reach it.
	if placement.sealed_by is not None and not placement.unverified_ok:
		return

	if count is None:
		# The same array with its count in the message. It has a stride to
		# drift just as the constant-count one does, and reaching it means
		# writing the driver first -- which is why this returned instead, and
		# why the shape that broke in four backends at once had no check here
		# either.
		_run_element_check(suite, struct, entry, prefix, extent)
		return
	if count < 2:
		return		# too short for a stride to exist

	scalar = placement.scalar
	if scalar is not None:
		if scalar.bits == BITS_PER_BYTE:
			return	# a byte array is handed out as a pointer, not indexed
		_element_encoding_check(suite, struct, entry, prefix, extent, count)
		return

	nested = resolve_element_struct(placement)
	if nested is None:
		return

	at = ident(prefix, struct.name, local, "at")
	suite.add(
		f"check_{c_name(placement.path)}_elements_are_one_stride_apart",
		[
			*_acquire(struct, prefix, extent),
			"",
			"\tsitu_view_t first;",
			"\tsitu_view_t second;",
			"",
			f"\tassert_int_equal({at}(view, 0u, &first), SITU_OK);",
			f"\tassert_int_equal({at}(view, 1u, &second), SITU_OK);",
			"",
			"\t/* The distance between consecutive elements is the element size,",
			"\t * measured rather than recomputed. */",
			"\tassert_int_equal((uint32_t)(second.base - first.base),",
			f"\t                 {macro(prefix, nested, 'SIZE_FIXED')});",
			"",
			f"\t/* And the array ends where it says it does. */",
			f"\tassert_int_not_equal({at}(view, {count}u, &second), SITU_OK);",
		],
		[f"/* {placement.path}: {count} elements, and the spacing between them.",
		 " *",
		 " * A stride that drifted puts every element after the first on the",
		 " * wrong bytes while each one still reads and writes consistently, so",
		 " * only the spacing itself falsifies it. */"])


def _element_encoding_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int, count: int) -> None:
	"""An element past the first, at the bytes its index puts it on.

	Elements wider than a byte are reached by index rather than by pointer, and
	the stride in that accessor was checked by nothing: widening it made every
	element after the zeroth read the wrong bytes while still round-tripping
	against itself. Writing the pattern at the offset the map implies and
	demanding the value back falsifies it.
	"""
	placement = entry.placement
	scalar    = placement.scalar
	assert scalar is not None
	assert placement.offset_bits is not None, "checked by the caller"

	if placement.offset_bits % BITS_PER_BYTE or scalar.bits % BITS_PER_BYTE:
		return
	if placement.endian is ast.Endian.NATIVE:
		return

	index  = count - 1		# the last one: the furthest a drifting stride moves
	stride = scalar.bits // BITS_PER_BYTE
	at     = placement.offset_bits // BITS_PER_BYTE + index * stride
	raw    = _probe_pattern(scalar.bits)
	placed = _placed_bytes(at * BITS_PER_BYTE, scalar.bits, raw,
	                       placement.endian, placement.bit_order, False)
	if placed is None or at + stride > extent:
		return

	local  = c_name(placement.path[len(struct.name) + 1:])
	getter = f"{ident(prefix, struct.name, local, 'get')}(view, {index}u)"
	if scalar.signed:
		want, got = (f"(int64_t){_c_signed(_signed_value(raw, scalar.bits))}",
		             f"(int64_t){getter}")
	else:
		want, got = f"(uint64_t){raw:#x}u", f"(uint64_t){getter}"

	body = [*_acquire(struct, prefix, extent), ""]
	body.append(f"\t/* element {index} of {count} sits {index} strides"
	            f" ({index * stride} bytes) past the first. */")
	body.extend(f"\tbuf[{byte}u] = {placed[byte]:#04x}u;" for byte in sorted(placed))
	body.extend(["", f"\tassert_int_equal({got}, {want});"])

	suite.add(
		f"check_{c_name(placement.path)}_element_lands_on_its_stride",
		body,
		[f"/* {placement.path}[{index}]: the bytes its index puts it on.",
		 " *",
		 " * A stride that drifted leaves element zero right and every other",
		 " * element quietly wrong, so only a later one can tell. */"])


def _run_element_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""An element of a run the *message* counts, at the bytes its index puts it.

	The constant-count check above writes a pattern and demands the value; this
	one writes the count as well, because there is no element to reach until
	the driver says there is. That extra step is the whole reason this shape
	had no check: `_array_checks` returned on a count it could not read from
	the schema, and the accessor it would have exercised was a scalar getter in
	C and a span of raw bytes in the other three.

	Only where the count can be written from here: a plain scalar driver at a
	byte-aligned constant offset. A varint or a text number decides its own
	width, and a check that guessed it would be asserting the guess.
	"""
	placement = entry.placement
	scalar    = placement.scalar

	if scalar is None or not indexed_elements(placement):
		return		# a byte run is a pointer and a length, not an index
	if placement.offset_bits is None or placement.offset_bits % BITS_PER_BYTE:
		return
	if placement.endian is ast.Endian.NATIVE:
		return

	driver = _writable_driver(struct, placement)
	if driver is None:
		return

	index  = 1		# the first element a drifting stride can move
	stride = scalar.bits // BITS_PER_BYTE
	at     = placement.offset_bits // BITS_PER_BYTE + index * stride
	raw    = _probe_pattern(scalar.bits)
	placed = _placed_bytes(at * BITS_PER_BYTE, scalar.bits, raw,
	                       placement.endian, placement.bit_order, False)
	if placed is None or at + stride > extent:
		return

	# Two elements is all this needs, and asking for more of them than the
	# frame holds would have the accessor answer zero -- correctly, and about
	# a different question.
	counted = _placed_bytes(driver.offset_bits or 0, driver.scalar.bits
	                        if driver.scalar else 8, index + 1,
	                        driver.endian, driver.bit_order, False)
	if counted is None:
		return

	local  = c_name(placement.path[len(struct.name) + 1:])
	getter = f"{ident(prefix, struct.name, local, 'get')}(view, {index}u)"
	if scalar.signed:
		want, got = (f"(int64_t){_c_signed(_signed_value(raw, scalar.bits))}",
		             f"(int64_t){getter}")
	else:
		want, got = f"(uint64_t){raw:#x}u", f"(uint64_t){getter}"

	body = [*_acquire(struct, prefix, extent), ""]
	body.append(f"\t/* {driver.path} says how many, and this asks for the"
	            f" last of them. */")
	body.extend(f"\tbuf[{byte}u] = {counted[byte]:#04x}u;"
	            for byte in sorted(counted))
	body.append("")
	body.append(f"\t/* element {index} sits one stride ({stride} bytes) past"
	            " the first. */")
	body.extend(f"\tbuf[{byte}u] = {placed[byte]:#04x}u;" for byte in sorted(placed))
	body.extend([
		"",
		f"\tassert_int_equal((uint64_t){ident(prefix, struct.name, local, 'count')}"
		f"(view), (uint64_t){index + 1}u);",
		f"\tassert_int_equal({got}, {want});",
	])

	suite.add(
		f"check_{c_name(placement.path)}_element_lands_on_its_stride",
		body,
		[f"/* {placement.path}[{index}]: the bytes its index puts it on, for a",
		 " * count the message carries rather than the schema.",
		 " *",
		 " * The count is written first, because there is no element to reach",
		 " * until the driver says there is -- and asking for the count back is",
		 " * half the check: a stride that drifted moves the elements, and a",
		 " * count that forgot the element width invents them. */"])


def _writable_driver(struct: ResolvedStruct, placement: Placement) -> Placement | None:
	"""The field that says how many elements, where a check can write it.

	A plain scalar at a byte-aligned constant offset and nothing else: a varint
	is as wide as its own bytes say, and a text number is digits, so writing
	either from here means reimplementing an encoder inside a check.
	"""
	if placement.sized_by is None:
		return None		# arithmetic over fields, or `remaining`

	for candidate in own_members(struct):
		if candidate.path != f"{struct.name}.{placement.sized_by}":
			continue
		if candidate.scalar is None or candidate.varint is not None:
			return None
		if candidate.radix is not None or candidate.scalar.is_bcd:
			return None
		if candidate.scalar.is_bit_packed or candidate.offset_bits is None:
			return None
		if candidate.offset_bits % BITS_PER_BYTE:
			return None
		return candidate
	return None


def resolve_element_struct(placement: Placement) -> str | None:
	"""The struct name an array's elements have, or None if they are not one."""
	name = placement.type_name
	return name if name and placement.scalar is None else None


#: Distinct bytes, top bit set in the first. Distinct so any permutation of the
#: field's bytes is a different value; top bit set so a getter that forgot to
#: sign-extend returns something else.
PROBE_BYTES = (0x81, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF)


def _bcd_probe(digits: int) -> tuple[int, int]:
	"""A BCD probe: (the bytes to write, the number they spell).

	The generic pattern will not do here. Half its nibbles are above nine, and
	a nibble above nine is not a digit -- what a decoder does with one is not
	something a conformance check should be asserting.
	"""
	sequence = [(i % 9) + 1 for i in range(digits)]

	raw   = 0
	value = 0
	for digit in sequence:
		raw   = (raw << 4) | digit
		value = value * 10 + digit
	return raw, value


def _probe_pattern(bits: int) -> int:
	"""A raw bit pattern that differs from its own byte- and bit-reversal."""
	if bits >= BITS_PER_BYTE and bits % BITS_PER_BYTE == 0:
		value = 0
		for byte in PROBE_BYTES[: bits // BITS_PER_BYTE]:
			value = (value << BITS_PER_BYTE) | byte
		return value
	if bits == 1:
		return 1
	return (1 << bits) - 2		# 0b1...10: top bit set, and not a palindrome


def _placed_bytes(offset_bits: int, bits: int, raw: int, endian: ast.Endian | None,
		bit_order: ast.BitOrder | None, packed: bool) -> dict[int, int] | None:
	"""Where `raw` lands in a zeroed buffer, from the map rather than the accessor.

	This is the whole point of the check: the expected bytes are derived here,
	from the offset and the declared order, by code that shares nothing with the
	emitter. An accessor and a check that agree because they were generated from
	the same expression would agree just as readily about a wrong answer.

	`None` when the encoding is not a fixed pattern -- `native` order depends on
	the machine that eventually runs the code, which is not knowable here.
	"""
	if endian is ast.Endian.NATIVE:
		return None

	if not packed:
		if offset_bits % BITS_PER_BYTE != 0 or bits % BITS_PER_BYTE != 0:
			return None
		first  = offset_bits // BITS_PER_BYTE
		count  = bits // BITS_PER_BYTE
		chunks = [(raw >> (BITS_PER_BYTE * i)) & 0xFF for i in range(count)]
		if endian is not ast.Endian.LITTLE:
			chunks.reverse()	# big endian: most significant byte lowest
		return {first + i: chunk for i, chunk in enumerate(chunks)}

	# Bit-packed: assemble the whole bytes the field touches, then place the
	# value within them the way the declared bit order numbers bits.
	first = offset_bits // BITS_PER_BYTE
	last  = (offset_bits + bits - 1) // BITS_PER_BYTE
	span  = (last - first + 1) * BITS_PER_BYTE
	skip  = offset_bits - first * BITS_PER_BYTE

	if bit_order is ast.BitOrder.LSB_FIRST:
		acc   = raw << skip
		order = range(first, last + 1)			# earlier byte, lower bits
	else:
		acc   = raw << (span - skip - bits)
		order = range(last, first - 1, -1)		# earlier byte, higher bits

	placed = {}
	for at in order:
		placed[at] = acc & 0xFF
		acc >>= BITS_PER_BYTE
	return placed


def _signed_value(raw: int, bits: int) -> int:
	"""`raw` read as two's complement, which is what the getter must return."""
	return raw - (1 << bits) if raw >= 1 << (bits - 1) else raw


def _c_signed(value: int) -> str:
	"""A C literal for a signed value, including the one C cannot spell.

	There is no negative integer literal for the 64-bit two's-complement
	minimum: `-9223372036854775808` is unary minus applied to a magnitude
	that does not fit a signed type, so a conforming compiler calls the
	constant "so large that it is unsigned" and `-Werror` stops the build.
	`-N - 1` is exact and portable. Found by `std/image.situ`, whose variant
	arm carries the tree's first `i64` (26.79).
	"""
	if value == -(1 << 63):
		return "(-9223372036854775807 - 1)"
	return str(value)


def _encoding_check(suite: Suite, struct: ResolvedStruct, entry: Resolved,
		prefix: str, extent: int) -> None:
	"""A concrete byte pattern, against the value the map says it encodes.

	Without this every generated check is symmetric: `_extent_check` asks which
	bytes a field reaches and `_round_trip_check` asks whether the setter and
	the getter agree with each other. Swap the byte order in both and both still
	pass, and byte order is the single thing situ exists to pin down. Mutation
	testing found exactly that -- a generator emitting little-endian loads for
	big-endian fields passed the entire generated suite.

	So: write the bytes, and demand the number.
	"""
	placement = entry.placement
	scalar    = placement.scalar
	assert scalar is not None
	assert placement.offset_bits is not None, "checked by the caller"

	if placement.marker is not None:
		return		# byte order chosen at runtime; no one fixed pattern
	if placement.covered_by:
		return		# reached through the coverage machinery, not a plain read
	if placement.offset_bits + placement.size_bits > extent * BITS_PER_BYTE:
		return

	bits = scalar.bits
	if scalar.is_bcd:
		raw, decoded = _bcd_probe(scalar.digits)
	else:
		raw, decoded = _probe_pattern(bits), None
	placed = _placed_bytes(placement.offset_bits, bits, raw,
	                       placement.endian, placement.bit_order,
	                       scalar.is_bit_packed)
	if placed is None:
		suite.skip(placement.path,
		           "native byte order has no fixed encoding to check")
		return

	if scalar.signed:
		want = f"(int64_t){_signed_value(raw, bits)}"
		got  = f"(int64_t){_getter(struct, placement, prefix)}"
	elif decoded is not None:
		want = f"(uint64_t){decoded}u"		# BCD: the digits, not the nibbles
		got  = f"(uint64_t){_getter(struct, placement, prefix)}"
	else:
		want = f"(uint64_t){raw:#x}u"
		got  = f"(uint64_t){_getter(struct, placement, prefix)}"

	order = "bit-packed" if scalar.is_bit_packed else "byte-aligned"
	body  = [*_acquire(struct, prefix, extent), ""]
	body.append(f"\t/* {order}, {bits}-bit, "
	            f"{(placement.endian.value if placement.endian else 'declared')}"
	            f" order at bit {placement.offset_bits}. */")
	for at in sorted(placed):
		body.append(f"\tbuf[{at}u] = {placed[at]:#04x}u;")
	body.append("")
	body.append(f"\tassert_int_equal({got}, {want});")

	suite.add(
		f"check_{c_name(placement.path)}_decodes_a_known_encoding",
		body,
		[f"/* {placement.path}: these bytes, and therefore this value.",
		 " *",
		 " * The expected bytes are computed from the map's offset and declared",
		 " * order, not from the accessor, so a getter that reads the right",
		 " * bytes in the wrong order fails here and nowhere else. */"])


def _constrained(placement: Placement) -> bool:
	"""A field a constraint pins cannot take arbitrary boundary values."""
	return any(attr.name in ("must_eq", "max", "min") for attr in placement.attrs)


def _boundary_values(scalar: object) -> list[str]:
	bits   = getattr(scalar, "bits", 8)
	signed = getattr(scalar, "signed", False)
	ctype  = _ctype(scalar)

	# A BCD field's range is decimal, not binary: `bcd2` holds 0 to 99, and
	# writing 255 to it stores digits that are not 255. The setter would
	# encode it, the getter would decode something else, and the round trip
	# would fail for a reason that is the check's fault rather than the code's.
	if getattr(scalar, "is_bcd", False):
		return [f"({ctype})0", f"({ctype}){scalar.decimal_max}u"]	# type: ignore[attr-defined]

	if signed:
		high = (1 << (bits - 1)) - 1
		low  = -(1 << (bits - 1))
		return [f"({ctype})0", f"({ctype}){high}",
		        f"({ctype})({_c_signed(low)})"]

	return [f"({ctype})0", f"({ctype})0x{(1 << bits) - 1:X}u"]


def _ctype(scalar: object) -> str:
	bits   = getattr(scalar, "bits", 8)
	signed = getattr(scalar, "signed", False)
	width  = next((w for w in WORD_WIDTHS if bits <= w), 64)
	return f"{'int' if signed else 'uint'}{width}_t"


def _reserved_policy(placement: Placement) -> str | None:
	"""`must_be_zero` (the default) or `must_be_one`, for a reserved field."""
	if placement.kind != "reserved":
		return None
	for attr in placement.attrs:
		if attr.name in ("must_be_zero", "must_be_one"):
			return attr.name
		if attr.name in ("preserve", "unknown"):
			return None		# not a constraint: the bits are carried, not checked
	return "must_be_zero"


def _required_pattern(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> int | None:
	"""The value this member must hold for the struct to validate, if any."""
	policy = _reserved_policy(placement)
	if policy == "must_be_one":
		return (1 << placement.size_bits) - 1
	if policy == "must_be_zero":
		return 0

	# `must_eq` pins the value; `min` is the smallest that satisfies it, and
	# satisfies any `max` alongside it too. A field with only `max` is happy at
	# zero, which is where the buffer starts.
	from situc.expr import evaluate

	for name in ("must_eq", "min"):
		for attr in placement.attrs:
			if attr.name != name or attr.value is None:
				continue
			try:
				return int(evaluate(attr.value, resolved.layout.env))
			except Exception:	# noqa: BLE001 - not foldable, so not satisfiable
				return None

	# An enum with `default = error` admits its members and nothing else, so a
	# baseline that leaves one at zero is not valid unless zero is a member.
	values = resolved.layout.env.enums.get(placement.type_name or "")
	if values:
		return None if 0 in values.values() else min(values.values())
	return None


def _selected_arms(resolved: ResolvedSchema, struct: ResolvedStruct,
		chosen: str | None) -> set[str]:
	"""Which arms the message a baseline builds actually carries.

	One per variant, and never more: `chosen` where the check being built
	selects an arm of that variant itself, and otherwise whichever arm the
	discriminant's own baseline value happens to name. The second half is
	the part that is easy to forget -- a check about a member *outside*
	every variant still leaves the discriminant somewhere, and the arm it
	lands on has constraints of its own that the baseline has to satisfy or
	`validate` refuses the buffer the check calls valid.
	"""
	held: set[str] = set()

	for variant in own_members(struct):
		if variant.kind != "variant" or variant.discriminant is None:
			continue

		arms = {arm.value: arm.member for arm in variant.arm_cases
		        if arm.value is not None and arm.member is not None}
		if chosen is not None and chosen in arms.values():
			held.add(chosen)
			continue

		disc = next((entry.placement for entry in struct.entries
		             if entry.placement.name == variant.discriminant), None)
		if disc is None:
			continue

		landed = arms.get(_required_pattern(resolved, struct, disc) or 0)
		if landed is not None:
			held.add(landed)

	return held


def _baseline(resolved: ResolvedSchema, struct: ResolvedStruct,
		extent: int, inside: str | None = None) -> list[str] | None:
	"""Statements making the buffer satisfy every constraint the struct has.

	Without this a constraint check can only show that a wrong value is
	refused, which for `must_be_one` is vacuous -- a zeroed buffer already
	breaks it, so the check would pass against a validator that did nothing.
	Establishing that the *right* value is accepted first is what gives the
	refusal meaning.

	`inside` is the arm the check about to be built lives in, and the arms
	are the reason this takes an argument at all. A member of an arm is in
	the message only when the discriminant selects that arm, so satisfying
	every arm's constraints at once writes several mutually exclusive
	layouts over each other: Modbus has ten exception arms sharing one byte,
	and the baseline set that byte ten times. Only the selected arm's
	members belong here; the rest are not in this message.

	`None` when some constraint cannot be satisfied from here, because a
	baseline that is not actually valid would make every check built on it
	assert the wrong thing.
	"""
	writes: list[str] = []
	carried = _selected_arms(resolved, struct, inside)

	for entry in struct.entries:
		placement = entry.placement
		if placement.offset_bits is None or not placement.size_bits:
			continue
		if placement.array_count is not None or placement.sized_by is not None:
			continue
		if "[]" in placement.path:
			continue		# an array element; see _reserved_checks

		# Not this message's arm, so not this message's constraint.
		held = enclosing_arm(struct, placement)
		if held is not None and held[1].member not in carried:
			continue

		value = _required_pattern(resolved, struct, placement)
		if value in (None, 0):
			continue		# nothing to write: the buffer starts zeroed
		assert value is not None

		placed = _placed_bytes(placement.offset_bits, placement.size_bits, value,
		                       placement.endian, placement.bit_order,
		                       bool(placement.scalar and placement.scalar.is_bit_packed))
		if placed is None:
			return None
		if max(placed) >= extent:
			return None

		writes.extend(f"\tbuf[{at}u] |= {placed[at]:#04x}u;"
		              for at in sorted(placed) if placed[at])

	return writes


def _validate_checks(suite: Suite, schema: ast.Schema,
		resolved: ResolvedSchema, struct: ResolvedStruct,
		prefix: str, extent: int) -> None:
	"""Each declared constraint must actually refuse a buffer that breaks it.

	The wrong value is computed here rather than read back through a getter: a
	nested field has no accessor in the enclosing struct, and a check that
	needed one would silently skip exactly the fields most worth checking.
	"""
	from situc.expr import evaluate

	env = resolved.layout.env

	if _baseline(resolved, struct, extent) is not None:
		_reserved_checks(suite, resolved, struct, prefix, extent)
		_enum_checks(suite, schema, resolved, struct, prefix, extent)

	for entry in struct.entries:
		placement = entry.placement
		must_eq   = next((attr for attr in placement.attrs
		                  if attr.name == "must_eq"), None)
		if must_eq is None or must_eq.value is None or placement.offset_bits is None:
			continue
		if placement.offset_bits % BITS_PER_BYTE or placement.size_bits != BITS_PER_BYTE:
			continue

		offset = placement.offset_bits // BITS_PER_BYTE
		if offset >= extent:
			continue

		try:
			demanded = evaluate(must_eq.value, env)
		except Exception:	# noqa: BLE001 - a constraint we cannot fold is one we cannot break
			suite.skip(placement.path, "its `must_eq` is not a compile-time value")
			continue

		wrong = (demanded + 1) & 0xFF

		# A `must_eq` inside a variant arm is a constraint on bytes that are
		# only in the message when the discriminant selects that arm -- the
		# same thing the reserved and enum checks below had to learn.
		prelude = _prelude(resolved, struct, placement, extent)
		if prelude is None:
			continue

		suite.add(
			f"check_{c_name(placement.path)}_must_eq_is_enforced",
			[
				*_acquire(struct, prefix, extent),
				"",
				*(prelude + [""] if prelude else []),
				f"\t/* The schema demands {demanded}; anything else must be refused. */",
				f"\tbuf[{offset}u] = 0x{wrong:02X}u;",
				f"\tassert_int_equal({ident(prefix, struct.name, 'validate')}(view),",
				"\t                 SITU_ERR_CONSTRAINT);",
			],
			[f"/* {placement.path} declares `must_eq`, which is malleability",
			 " * control rather than pedantry (section 8.8): a value the schema",
			 " * does not admit has to be refused on parse. */"])


def _enum_checks(suite: Suite, schema: ast.Schema,
		resolved: ResolvedSchema, struct: ResolvedStruct,
		prefix: str, extent: int) -> None:
	"""An enum field admits its members and, with `default = error`, nothing else.

	Section 8.7 says so and every backend emitted it as a comment until three of
	them were compared. This is what keeps it true.
	"""
	validate = ident(prefix, struct.name, "validate")

	for entry in struct.entries:
		placement = entry.placement
		values    = resolved.layout.env.enums.get(placement.type_name or "")

		if not values or placement.offset_bits is None or "[]" in placement.path:
			continue
		if placement.offset_bits % BITS_PER_BYTE or placement.size_bits != BITS_PER_BYTE:
			continue
		if placement.offset_bits // BITS_PER_BYTE >= extent:
			continue

		decl = next((held for held in resolved.layout.env.enums
		             if held == placement.type_name), None)
		if decl is None:
			continue

		# `default = pass` says an unknown value is accepted, which is exactly
		# what section 8.7 offers it for -- IANA keeps assigning numbers, and
		# a receiver refusing tomorrow's would refuse tomorrow's traffic. This
		# emitted the rejection check regardless of the policy, so a schema
		# that used the escape hatch failed a test asserting it had not.
		if _passes_unknown(schema, placement.type_name):
			continue

		# A value no member names. Walking up from zero finds one unless the
		# enum covers the whole byte, in which case there is nothing to reject.
		taken   = set(values.values())
		unknown = next((v for v in range(256) if v not in taken), None)
		if unknown is None:
			continue

		# An enum inside a variant arm is read only when the discriminant
		# selects that arm. Ten Modbus exception arms share one byte and each
		# had a check that wrote an unknown value there while the discriminant
		# still named a different arm -- so the byte was somebody else's, and
		# `validate` was right to accept it.
		prelude = _prelude(resolved, struct, placement, extent)
		if prelude is None:
			continue

		offset = placement.offset_bits // BITS_PER_BYTE
		suite.add(
			f"check_{c_name(placement.path)}_rejects_a_value_no_member_names",
			[
				*_acquire(struct, prefix, extent),
				"",
				*prelude,
				f"\tassert_int_equal({validate}(view), SITU_OK);",
				"",
				f"\t/* {unknown} names no member of `{placement.type_name}`. */",
				f"\tbuf[{offset}u] = {unknown}u;",
				f"\tassert_int_equal({validate}(view), SITU_ERR_CONSTRAINT);",
			],
			[f"/* {placement.path} is a `{placement.type_name}`, which rejects",
			 " * unknown values (section 8.7). A field declared to admit a"
			 f" handful",
			 " * of values that takes all 256 is not the field the schema"
			 " described. */"])


def _select_arm(struct: ResolvedStruct, placement: Placement,
		extent: int) -> list[str] | None:
	"""Statements putting the discriminant where this member exists.

	Empty where the member is not inside a variant arm at all -- which is
	every member of every struct in this repository until an ICMP message
	grew one. None where the arm cannot be selected from here, so the caller
	drops the check rather than asserting about bytes nobody selected.
	"""
	found = enclosing_arm(struct, placement)
	if found is None:
		return []

	variant, arm = found
	if arm.value is None:
		return None			# the default arm: no value selects it

	held = next((entry.placement for entry in struct.entries
	             if entry.placement.name == variant.discriminant), None)
	if held is None or held.offset_bits is None or held.scalar is None:
		return None

	placed = _placed_bytes(held.offset_bits, held.size_bits, arm.value,
	                       held.endian, held.bit_order,
	                       held.scalar.is_bit_packed)
	if placed is None or max(placed) >= extent:
		return None

	mask = _placed_bytes(held.offset_bits, held.size_bits,
	                     (1 << held.size_bits) - 1, held.endian, held.bit_order,
	                     held.scalar.is_bit_packed)
	if mask is None:
		return None

	# Clear the discriminant's bits and write the value, rather than OR the
	# value in. The baseline has already been here -- an enum discriminant
	# with `default = error` gets its lowest member written, to make the
	# buffer valid -- and OR-ing `0x02` over that `0x01` selects arm three.
	return [f"\t/* Select the arm this member is in: "
	        f"{variant.discriminant} = {arm.value}. */",
	        *(f"\tbuf[{at}u] = {placed[at]:#04x}u;" if mask[at] == 0xFF
	          else f"\tbuf[{at}u] = (uint8_t)((buf[{at}u] & "
	               f"(uint8_t)~{mask[at]:#04x}u) | {placed[at]:#04x}u);"
	          for at in sorted(mask))]


def _prelude(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement, extent: int) -> list[str] | None:
	"""The buffer as a check on this member needs it before breaking it.

	Two things, and they used to be asked in three places and answered in
	one: every constraint that applies to *this* message satisfied, and the
	arm this member lives in selected. A member inside an arm needs both --
	the baseline that satisfies its siblings, and the discriminant that puts
	them in the message at all -- and the enum checks had neither, so ten
	Modbus checks asserted that `validate` would refuse a byte belonging to
	an arm nobody had selected.

	`None` where the arm cannot be selected from here, so the caller drops
	the check rather than asserting about bytes nobody selected.
	"""
	select = _select_arm(struct, placement, extent)
	if select is None:
		return None

	found  = enclosing_arm(struct, placement)
	inside = found[1].member if found is not None else None
	base   = _baseline(resolved, struct, extent, inside) or []

	reach = _reach_version(struct, extent)
	if reach is None:
		return None

	lines: list[str] = []
	if base:
		lines += ["\t/* Every constraint satisfied, so a refusal below is",
		          "\t * about the field this check breaks and nothing else. */",
		          *base, ""]
	lines += reach
	lines += select
	return lines


def _reach_version(struct: ResolvedStruct, extent: int) -> list[str] | None:
	"""Put the version field where every versioned member is present.

	The same job `_select_arm` does for an arm, and it was missing for the
	same reason: a member behind `[since = 3]` is not in a message whose
	version byte is zero, so a check that poked its bytes and asserted
	`validate` would refuse them was asserting about a field the message does
	not carry. `validate` accepted it, correctly.

	The highest version in the struct rather than this member's own, so the
	baseline above -- which satisfies every versioned member's constraints --
	describes a message that actually exists.
	"""
	versioned = [held.placement.since for held in struct.entries
	             if held.placement.since is not None]
	if not versioned:
		return []

	name = next((held.placement.version_field for held in struct.entries
	             if held.placement.version_field is not None), None)
	held = next((held.placement for held in struct.entries
	             if held.placement.name == name), None)
	if held is None or held.offset_bits is None or held.scalar is None:
		return None

	placed = _placed_bytes(held.offset_bits, held.size_bits, max(versioned),
	                       held.endian, held.bit_order, held.scalar.is_bit_packed)
	if placed is None or max(placed) >= extent:
		return None

	return [f"\t/* Version {max(versioned)}, so every versioned member is here. */",
	        *(f"\tbuf[{at}u] = {placed[at]:#04x}u;" for at in sorted(placed)),
	        ""]


def _reserved_checks(suite: Suite, resolved: ResolvedSchema, struct: ResolvedStruct,
		prefix: str, extent: int) -> None:
	"""Reserved bits are a constraint, and section 8.8 says why.

	They are malleability control: a receiver that ignores them lets a sender
	vary bytes the format says are fixed, which is a signature-bypass primitive
	in anything authenticated. Nothing generated checked them, and `must_be_one`
	in particular had a validator that had never run against a valid buffer.
	"""
	validate = ident(prefix, struct.name, "validate")

	for entry in struct.entries:
		placement = entry.placement
		policy    = _reserved_policy(placement)

		if policy is None or placement.offset_bits is None or not placement.size_bits:
			continue

		# A field inside an array element is not validated by the enclosing
		# struct, deliberately: walking every element on every parse is a cost
		# the caller should choose, so `validate` on the element type is where
		# that check lives. Demanding it here would fail a design decision
		# rather than a bug.
		if "[]" in placement.path:
			continue
		if placement.offset_bits + placement.size_bits > extent * BITS_PER_BYTE:
			continue

		# A member inside a variant arm is only in the message when the
		# discriminant selects that arm, so the poke below has to select it
		# first. Without this the check flipped bytes belonging to whichever
		# arm a zeroed discriminant picks and asserted that `validate` would
		# refuse them -- an assertion about the wrong bytes, which passed only
		# as long as no schema had a reserved field inside an arm.
		prelude = _prelude(resolved, struct, placement, extent)
		if prelude is None:
			continue

		# Break exactly this field: the bits it owns, flipped away from what the
		# policy demands. Everything else stays at the baseline, so a refusal
		# can only be about this one.
		wrong  = 0 if policy == "must_be_one" else (1 << placement.size_bits) - 1
		placed = _placed_bytes(placement.offset_bits, placement.size_bits, wrong,
		                       placement.endian, placement.bit_order,
		                       bool(placement.scalar and placement.scalar.is_bit_packed))
		if placed is None:
			continue

		mask = _placed_bytes(placement.offset_bits, placement.size_bits,
		                     (1 << placement.size_bits) - 1,
		                     placement.endian, placement.bit_order,
		                     bool(placement.scalar and placement.scalar.is_bit_packed))
		assert mask is not None

		body = [*_acquire(struct, prefix, extent), "", *prelude]
		body.append(f"\tassert_int_equal({validate}(view), SITU_OK);")
		body.append("")
		body.append(f"\t/* {placement.path} declares {policy}. */")
		for at in sorted(mask):
			body.append(f"\tbuf[{at}u] = (uint8_t)((buf[{at}u] & "
			            f"(uint8_t)~{mask[at]:#04x}u) | {placed[at]:#04x}u);")
		body.append(f"\tassert_int_equal({validate}(view), SITU_ERR_CONSTRAINT);")

		suite.add(
			f"check_{c_name(placement.path)}_{policy}_is_enforced",
			body,
			[f"/* {placement.path} is reserved [{policy}].",
			 " *",
			 " * Section 8.8: reserved bits are malleability control, not",
			 " * pedantry. A receiver that ignores them lets a sender vary bytes",
			 " * the format calls fixed, which is a bypass primitive in anything",
			 " * authenticated. */"])


def _coverage_checks(suite: Suite, schema: ast.Schema,
		resolved: ResolvedSchema, struct: ResolvedStruct,
		prefix: str, extent: int) -> None:
	"""`auth = Covered(o)` is a claim that writing marks `o` stale.

	One check per obligation, not one per struct. The old version took the
	first covered field and the first tag and paired them, which is right only
	while a struct carries exactly one obligation -- with a tag and an
	invariant side by side it wrote through a field the invariant covers and
	then asserted the *tag* had gone dirty.
	"""
	held = obligations(schema, struct)
	if not held:
		return

	for one in held:
		if one.kind == "tag":
			_span_check(suite, resolved, struct, prefix, extent, one.name)

	_dirty_mask_check(suite, struct, held, prefix, extent)

	for one in held:
		# A field this obligation covers, with a setter to write it through.
		# An array or a nested struct is reached by pointer and marks nothing
		# by itself, so there is no call here to make.
		entry = next((entry for entry in struct.entries
		              if one.label in entry.placement.covered_by
		              and entry.placement.scalar is not None
		              and entry.placement.kind == "field"
		              and entry.placement.array_count is None
		              and entry.placement.sized_by is None
		              and entry.placement.sealed_by is None
		              and entry.vector.get(Axis.MUTATE).base == "InPlaceFixed"),
		             None)
		if entry is None:
			continue

		local  = c_name(entry.placement.path[len(struct.name) + 1:])
		setter = ident(prefix, struct.name, local, "set")
		ctype  = _ctype(entry.placement.scalar)
		name   = c_name(one.name)

		if one.kind == "tag":
			stale     = f"{ident(prefix, struct.name, name, 'is_dirty')}(&msg)"
			discharge = f"{ident(prefix, struct.name, name, 'finalize')}(&msg);"
			why       = ("Section 14.2 says a write to it leaves the tag stale "
			             "and the\n\t * message refuses to be transmittable "
			             "until finalize puts it right.")
			# The recompute takes the view as well: it writes bytes, where
			# finalize only reads them and stores a tag it was handed.
		else:
			stale     = f"{ident(prefix, struct.name, name, 'is_stale')}(&msg)"
			discharge = f"{ident(prefix, struct.name, name, 'recompute')}(&msg, view);"
			why       = ("Section 16.1 says a write to it leaves the derived "
			             "field stale\n\t * and the message refuses to be "
			             "transmittable until recompute puts it right.")

		suite.add(
			f"check_{c_name(struct.name)}_covered_write_marks_{name}",
			[
				*_acquire(struct, prefix, extent),
				"",
				"\tassert_int_equal(situ_msg_transmittable(&msg), SITU_OK);",
				"",
				f"\t{setter}(&msg, view, ({ctype})1);",
				"",
				f"\tassert_true({stale});",
				"\tassert_int_equal(situ_msg_transmittable(&msg), SITU_ERR_TAG);",
				"",
				f"\t{discharge}",
				f"\tassert_false({stale});",
				"\tassert_int_equal(situ_msg_transmittable(&msg), SITU_OK);",
			],
			[f"/* {entry.placement.path} is Covered({one.label}).",
			 f"\t * {why} */"])


def _dirty_mask_check(suite: Suite, struct: ResolvedStruct,
		held: list[Obligation], prefix: str, extent: int) -> None:
	"""`DIRTY_MASK` names every obligation this struct carries, and only those.

	It is a constant for callers rather than something generated code consumes,
	the way `SIZE_FIXED` is -- a message may hold several structs, and
	`situ_msg_transmittable` answers for all of them at once, so asking about
	one struct's obligations means masking. Nothing tested that the mask
	covered the right bits, and a deliberate off-by-one in it went unnoticed.

	Tags *and* invariants, because they share the dirty word. A mask over the
	tags alone would leave a struct able to be stale in a way its own mask
	cannot express.
	"""
	if not held:
		return

	mask = macro(prefix, struct.name, "DIRTY_MASK")
	bits = [macro(prefix, struct.name, c_name(one.name), one.suffix)
	        for one in held]

	body = [*_acquire(struct, prefix, extent), ""]
	body.append(f"\t/* Every one of this struct's {len(held)} obligation(s)"
	            " is in the mask. */")
	for bit in bits:
		body.append(f"\tassert_int_equal({mask} & {bit}, {bit});")
	body.extend([
		"",
		"\t/* And nothing else is: marking them all makes the message exactly",
		"\t * as dirty as the mask says it can be. */",
	])
	for bit in bits:
		body.append(f"\tsitu_msg_mark_dirty(&msg, {bit});")
	body.append(f"\tassert_int_equal(msg.dirty, {mask});")

	kinds = ", ".join(sorted({one.kind for one in held}))
	suite.add(
		f"check_{c_name(struct.name)}_dirty_mask_names_every_obligation",
		body,
		[f"/* {struct.name} carries {len(held)} obligation(s) ({kinds}), and",
		 "\t * DIRTY_MASK is how a caller asks about them together. A message may",
		 "\t * hold several structs, so `situ_msg_transmittable` is too broad a",
		 "\t * question. */"])


def _span_check(suite: Suite, resolved: ResolvedSchema, struct: ResolvedStruct,
		prefix: str, extent: int, tag: str) -> None:
	"""What the tag's algorithm actually runs over.

	The span is not recomputed here. A region's extent is its interior put
	through a codec's expansion, and reconstructing that would duplicate the
	solver -- which is exactly why the emitter takes the region's end from where
	the next member starts instead.

	But it can be bounded from the outside without the solver, and that is
	enough: every member the map says is covered has to be inside the span. A
	span that collapsed, or that started past the first covered byte, fails
	that whatever the expansion turns out to be. Mutation testing found a region
	ending at its own start with nothing generated to notice.
	"""
	# Only what *this* tag covers. A struct may carry several, each over its
	# own region, and asking one of them to span another's bytes is a demand
	# the schema never made.
	# `offset_bits is not None` is not the whole question: a member of a nested
	# struct behind a variable-length one carries a *frame-relative* offset,
	# measured from that struct rather than from the message. Reading it as an
	# absolute one had this check demanding that a tag cover bytes 0..3 of a
	# frame whose covered region starts at 1.
	known = [entry.placement for entry in struct.entries
	         if tag in entry.placement.covered_by
	         and entry.placement.offset_bits is not None
	         and not (entry.placement.frame_relative
	                  and entry.placement.frame_base_dynamic)
	         and entry.placement.size_bits
	         and entry.placement.kind != "authenticated"]
	if not known:
		return

	first = min(placement.offset_bits or 0 for placement in known)
	last  = max((placement.offset_bits or 0) + placement.size_bits
	            for placement in known)
	if first % BITS_PER_BYTE or last % BITS_PER_BYTE:
		return

	begins = first // BITS_PER_BYTE
	ends   = last // BITS_PER_BYTE

	# On an instance that satisfies the schema, not on a zeroed buffer. The
	# span reaches to the end of what the region holds, and where that is a
	# length the data decides, a zeroed instance decides a nonsense one: an
	# IPv4 header with `ihl = 0` breaks `[min = 5]` and puts the end of the
	# options twenty bytes before their start. A check has to ask about a
	# message the schema admits.
	baseline = _baseline(resolved, struct, extent) or []

	suite.add(
		f"check_{c_name(struct.name)}_{c_name(tag)}_covers_what_it_claims",
		[
			*_acquire(struct, prefix, extent),
			"",
			*baseline,
			"",
			"\tuint32_t offset = 0;",
			"\tuint32_t len    = 0;",
			"",
			f"\tassert_int_equal({ident(prefix, struct.name, c_name(tag), 'covered')}"
			"(view, &offset, &len), SITU_OK);",
			"",
			f"\t/* The map says bytes {begins}..{ends} are covered. The span may",
			"\t * reach further -- a codec's expansion is its own business -- but",
			"\t * it may not leave any of them out. */",
			f"\tassert_true(offset <= {begins}u);",
			f"\tassert_true(offset + len >= {ends}u);",
			"",
			"\t/* And it has to stay inside the message it is computed over. */",
			"\tassert_true(offset + len <= view.limit);",
		],
		[f"/* {struct.name}.{tag} covers {ends - begins} bytes of named members.",
		 " *",
		 " * Bounded rather than recomputed: the extent of a coded region is its",
		 " * interior through the codec's expansion, and duplicating that here",
		 " * would just be a second solver to get wrong. */"])


def _gate_checks(suite: Suite, struct: ResolvedStruct, prefix: str,
		extent: int) -> None:
	"""The stage gate of 14.3, on the half that can be tested at run time."""
	for entry in struct.entries:
		placement = entry.placement
		if placement.kind != "sealed" or placement.unverified_ok:
			continue

		local = c_name(placement.path[len(struct.name) + 1:])
		gate  = ident(prefix, struct.name, local, "t")

		suite.add(
			f"check_{c_name(placement.path)}_refuses_before_verification",
			[
				*_acquire(struct, prefix, extent),
				f"\t{gate} gate;",
				"",
				"\tmemset(&gate, 0, sizeof gate);",
				f"\tassert_int_equal({ident(prefix, struct.name, local, 'open')}"
				"(view, 0, &gate), SITU_ERR_TAG);",
				"\tassert_null(gate.view.base);",
				"",
				f"\tassert_int_equal({ident(prefix, struct.name, local, 'open')}"
				"(view, 1, &gate), SITU_OK);",
				"\tassert_non_null(gate.view.base);",
			],
			[f"/* {placement.path} is VerifyGated. The half of 14.3 that a running",
			 " * test can reach: no view into the interior before the tag",
			 " * verifies. That reaching it does not *compile* is the other half,",
			 " * and no test that runs can show it. */"])


# ---------------------------------------------------------------------------
# The MMIO target
# ---------------------------------------------------------------------------


def _register_checks(suite: Suite, struct: ResolvedStruct, prefix: str) -> None:
	"""Exercise a register against memory standing in for the bus.

	A user cannot issue a bus transaction in CI, and the arithmetic is what
	goes wrong anyway: which bits a field occupies, what a builder composes,
	what a `w1c` clear writes. Pointing the accessors at an array checks all of
	that. What it cannot check is the bus itself, which is the part no test
	could reach.
	"""
	info = struct.layout.register
	assert info is not None

	if info.access_width not in WORD_WIDTHS:
		suite.skip(struct.name, "access width is not a width C can name")
		return

	block = ((info.address or 0) + info.access_width // BITS_PER_BYTE)
	word  = f"uint{info.access_width}_t"
	name  = struct.name

	fields = [entry for entry in struct.entries
	          if entry.placement.kind == "field"
	          and entry.placement.access_mode is not None]

	for entry in fields:
		placement = entry.placement
		mode      = placement.access_mode
		assert mode is not None
		if not mode.readable or not mode.writable or not mode.is_assignment:
			continue

		local = c_name(placement.path[len(name) + 1:])
		mask  = (1 << placement.size_bits) - 1
		shift = placement.offset_bits or 0

		suite.add(
			f"check_{c_name(placement.path)}_composes_and_decodes",
			[
				f"\t{word} word = 0;",
				"",
				f"\tword = {ident(prefix, name, local, 'with')}(word, "
				f"({word})0x{mask:X}u);",
				f"\tassert_int_equal(word, ({word})(0x{mask:X}u << {shift}u));",
				f"\tassert_int_equal({ident(prefix, name, local, 'get')}(word), "
				f"({word})0x{mask:X}u);",
				"",
				"\t/* And it must leave every other bit of the word alone. */",
				f"\tword = ({word})~({word})0;",
				f"\tword = {ident(prefix, name, local, 'with')}(word, ({word})0);",
				f"\tassert_int_equal(word, "
				f"({word})~(({word})0x{mask:X}u << {shift}u));",
			],
			[f"/* {placement.path}: the builder places the field and the getter",
			 " * takes it back out, and neither touches a neighbouring bit. */"])

	_register_bit_operations(suite, struct, prefix, block, word)


def _register_bit_operations(suite: Suite, struct: ResolvedStruct, prefix: str,
		block: int, word: str) -> None:
	"""`w1c` writes a one to clear; a trigger writes only its own bit."""
	info = struct.layout.register
	assert info is not None
	name = struct.name

	for entry in struct.entries:
		placement = entry.placement
		mode      = placement.access_mode
		if mode is None or placement.kind != "field":
			continue

		local = c_name(placement.path[len(name) + 1:])
		mask  = (1 << placement.size_bits) - 1
		shift = placement.offset_bits or 0
		at    = ident(prefix, name, "at")

		if mode.writable and not mode.is_assignment:
			verb = "clear" if mode in (ast.AccessMode.W1C,
			                           ast.AccessMode.W0C) else "set"
			ones = mode in (ast.AccessMode.W1C, ast.AccessMode.W1S)
			expect = (f"({word})(0x{mask:X}u << {shift}u)" if ones
			          else f"({word})~(({word})0x{mask:X}u << {shift}u)")

			suite.add(
				f"check_{c_name(placement.path)}_{verb}_writes_the_bit",
				[
					f"\tuint8_t block[{block}u];",
					"",
					"\tmemset(block, 0, sizeof block);",
					f"\t{ident(prefix, name, local, verb)}(block);",
					f"\tassert_int_equal(*{at}(block), {expect});",
				],
				[f"/* {placement.path} is `{mode.value}`: the write is not an",
				 f" * assignment, so the operation is a {verb} and what reaches the",
				 " * bus is the bit pattern the hardware acts on. */"])

		if placement.on_write is ast.SideEffect.TRIGGER and mode.writable:
			suite.add(
				f"check_{c_name(placement.path)}_trigger_writes_only_itself",
				[
					f"\tuint8_t block[{block}u];",
					"",
					"\tmemset(block, 0xFF, sizeof block);",
					f"\t{ident(prefix, name, local, 'trigger')}(block);",
					f"\tassert_int_equal(*{at}(block), "
					f"({word})(0x{mask:X}u << {shift}u));",
				],
				[f"/* {placement.path} has `on_write = trigger`. It writes a word",
				 " * with this field set and every other field zero, which is the",
				 " * only word that can be composed without reading first. */"])
