"""Generate property tests that would falsify a lying codec signature.

Section 13.1: a tier-1 codec is trusted and unverified, so it can lie, and every
capability conclusion downstream inherits the lie. The compiler cannot verify an
implementation it never sees -- but it can generate the tests that would catch a
lying one, and generating them from the signature costs the user nothing.

Each declared property gets the cheap falsifying test from the section 13.1
table. The properties cannot be proven; they can be attacked, and an
implementation that survives the attack is one a reviewer can reason about.

The generated suite calls the two functions the codec's `impl` binds:

    <symbol>_encode(in, in_len, out, out_cap, &out_len)
    <symbol>_decode(in, in_len, out, out_cap, &out_len)

which is the tier-1 ABI of section 13.2a -- the same shape whatever the
algorithm, because the harness knows only the signature.

It was `situ_codec_<codec>_encode`, which is a name nothing else in this
project used: not the accessors, not the spec, and not the `impl x extern
"my_x"` that names the implementation. So a user who wrote a codec to satisfy
these tests had written a function nothing called, and the harness could not be
linked against any implementation this repository produces. It had never been
run (26.35).

A codec with no `impl`, or with a derived one, gets no suite here and the file
says which and why. A signature may exist with no implementation at all (13.1),
and a derived implementation cannot lie about properties derived from its own
kernel -- what it can get wrong is the transform, which is a different harness.
"""

from __future__ import annotations

from math import lcm

from situc import ast
from situc.codegen.c.derived import pair_of
from situc.traverse import decode_counts_bits, extern_symbol,\
	table_is_padded

# Input sizes the length tests sweep. Chosen to straddle block boundaries and
# to include the degenerate cases, which is where a length claim usually breaks.
SWEEP = (0, 1, 2, 3, 7, 8, 15, 16, 17, 31, 32, 63, 64, 127, 128, 255, 256)

MAX_INPUT  = 256
MAX_OUTPUT = 2048


def generate(schema: ast.Schema, basename: str, prefix: str = "situ") -> str:
	codecs = schema.codecs()

	lines = [
		f"/* Generated by situc from {basename}.situ -- do not edit.",
		" *",
		" * Property tests over the codec signatures this schema declares. A",
		" * tier-1 signature is trusted and unverified, so it can lie; these are",
		" * the tests that would catch a lying one.",
		" *",
		" * Supply an implementation of each codec's encode and decode, then:",
		" *",
		f" *   cc -I. {basename}_codec_tests.c my_codecs.c situ.c -lcmocka \\",
		f" *       -o {basename}_codec_tests",
		" */",
		"",
		"#include <setjmp.h>",
		"#include <stdarg.h>",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <string.h>",
		"",
		"#include <cmocka.h>",
		"",
		'#include "situ.h"',
		"",
	]

	cases: list[str] = []
	suites: list[str] = []
	for codec in codecs:
		symbol = extern_symbol(schema, codec.name)
		if symbol is not None:
			body, names = _codec_suite(codec, symbol)
			suites.extend(body)
			cases.extend(names)
			continue

		# A derived codec is attacked through the pair its kernel emits
		# rather than through the tier-1 ABI: it has no `impl extern` to
		# bind one, and its implementation is situ's own. Its *properties*
		# cannot lie -- they follow from the kernel -- and its
		# implementation still can (13.1).
		pair = pair_of(codec, prefix) if _is_derived(schema, codec) else None
		if pair is not None:
			body, names = _derived_suite(codec, *pair)
			suites.extend(body)
			cases.extend(names)
			continue

		suites.extend(_declined(schema, codec))

	# The shared generator only where something calls it. A file of refusals
	# is a legitimate output -- `std/codecs.situ` is contracts and no `impl`
	# -- and an unused static function in it is an error under this project's
	# own flags.
	if cases:
		lines.extend(_shared())
	lines.extend(suites)

	lines.extend(_main(cases))
	return "\n".join(lines) + "\n"


def _shared() -> list[str]:
	return [
		f"#define SITU_CODEC_MAX_INPUT  {MAX_INPUT}u",
		f"#define SITU_CODEC_MAX_OUTPUT {MAX_OUTPUT}u",
		"",
		"/* A cheap deterministic generator, so a failure is reproducible from",
		" * the seed alone rather than from whatever the last test left behind. */",
		"static void situ_codec_fill(uint8_t *buf, uint32_t len, uint32_t seed)",
		"{",
		"\tuint32_t state = seed * 1664525u + 1013904223u;",
		"\tuint32_t i;",
		"",
		"\tfor (i = 0; i < len; i++) {",
		"\t\tstate = state * 1664525u + 1013904223u;",
		"\t\tbuf[i] = (uint8_t)(state >> 24);",
		"\t}",
		"}",
		"",
	]


def _declined(schema: ast.Schema, codec: ast.CodecDecl) -> list[str]:
	"""Why a codec has no suite, where it would have had one.

	A refusal that names itself, like every other artifact here: a file that
	quietly omits a codec is indistinguishable from one that never had it.
	"""
	bound = next((decl for decl in schema.impls()
	              if decl.codec == codec.name), None)
	why = ("no `impl` binds an implementation, and a signature may exist with"
	       " none (13.1)" if bound is None else
	       "its implementation is derived, so its properties follow from its"
	       " own kernel and cannot lie (13.1)")

	return [f"/* ---- {codec.name}: no suite ---- */",
	        f"/* {why}. */", ""]


def _codec_suite(codec: ast.CodecDecl,
		symbol: str) -> tuple[list[str], list[str]]:
	encode = f"{symbol}_encode"
	decode = f"{symbol}_decode"

	lines = [
		f"/* ---- {codec.name} ---- */",
		"",
		f"extern situ_err_t {encode}(const uint8_t *in, uint32_t in_len,",
		"\t\tuint8_t *out, uint32_t out_cap, uint32_t *out_len);",
		f"extern situ_err_t {decode}(const uint8_t *in, uint32_t in_len,",
		"\t\tuint8_t *out, uint32_t out_cap, uint32_t *out_len);",
		"",
	]

	names: list[str] = []

	for builder in (_length_test, _deterministic_test, _invertible_test,
	                _seekable_test, _systematic_test, _granularity_test):
		body, name = builder(codec, encode, decode)

		# A builder with no test may still have something to say -- that the
		# signature claims nothing here, or that the claim cannot be checked
		# mechanically. Both are worth emitting: silence would read as coverage.
		if not body:
			continue

		lines.extend(body)
		lines.append("")
		if name is not None:
			names.append(name)

	return lines, names


def _expected_length(codec: ast.CodecDecl) -> str | None:
	"""The declared output extent as a C expression over `in_len`.

	None where the signature does not pin it: an unbounded or data-dependent
	expansion has no exact length to check, only a bound.
	"""
	if codec.expansion is ast.Expansion.PRESERVING:
		return "in_len"
	if codec.expansion is ast.Expansion.FIXED_ADD:
		return f"in_len + {codec.expansion_add}u"
	if codec.expansion is ast.Expansion.RATIO_EXACT:
		assert codec.ratio is not None
		a, b = codec.ratio
		return f"(in_len * {a}u + {b - 1}u) / {b}u"
	if codec.expansion is ast.Expansion.RATIO_PADDED:
		assert codec.ratio is not None
		a, b     = codec.ratio
		bytes_in = lcm(8, b) // 8
		return (f"((in_len + {bytes_in - 1}u) / {bytes_in}u)"
		        f" * {lcm(8, b) // b * a // 8}u")
	return None


def _length_test(codec: ast.CodecDecl, encode: str,
		decode: str) -> tuple[list[str], str | None]:
	"""`length_preserving` / `expansion`: output extent matches the declaration
	across a range of input sizes."""
	name  = f"test_{codec.name}_length"
	exact = _expected_length(codec)

	if exact is not None:
		check = [
			f"\t\tassert_int_equal(out_len, {exact});",
		]
		claim = "the declared expansion"
	elif codec.expansion is ast.Expansion.RATIO_BOUNDED:
		assert codec.ratio is not None
		a, b = codec.ratio
		check = [
			f"\t\tassert_true(out_len <= (in_len * {a}u + {b - 1}u) / {b}u);",
		]
		claim = "the declared worst case"
	else:
		# `unbounded` claims nothing about extent, so there is nothing to
		# falsify. Saying so is better than emitting a test that always passes.
		return ([f"/* {codec.name}: expansion is unbounded, so the signature",
		         " * makes no length claim there is anything to falsify. */"],
		        None)

	return ([
		f"/* Declared: {claim}. */",
		f"static void {name}(void **state)",
		"{",
		"\tstatic const uint32_t sizes[] = {",
		"\t\t" + ", ".join(f"{n}u" for n in SWEEP) + ",",
		"\t};",
		"\tuint8_t input[SITU_CODEC_MAX_INPUT];",
		"\tuint8_t output[SITU_CODEC_MAX_OUTPUT];",
		"\tsize_t i;",
		"",
		"\t(void)state;",
		"\tfor (i = 0; i < sizeof(sizes) / sizeof(sizes[0]); i++) {",
		"\t\tuint32_t in_len  = sizes[i];",
		"\t\tuint32_t out_len = 0;",
		"",
		"\t\tsitu_codec_fill(input, in_len, (uint32_t)i);",
		f"\t\tassert_int_equal({encode}(input, in_len, output,",
		"\t\t\tsizeof(output), &out_len), SITU_OK);",
		*check,
		"\t}",
		"}",
	], name)


def _deterministic_test(codec: ast.CodecDecl, encode: str,
		decode: str) -> tuple[list[str], str | None]:
	if not codec.deterministic:
		return ([], None)

	name = f"test_{codec.name}_deterministic"
	return ([
		"/* Declared: `deterministic`. Repeated encoding of identical input must",
		" * be byte-identical. */",
		f"static void {name}(void **state)",
		"{",
		"\tuint8_t input[64];",
		"\tuint8_t first[SITU_CODEC_MAX_OUTPUT];",
		"\tuint8_t second[SITU_CODEC_MAX_OUTPUT];",
		"\tuint32_t first_len = 0;",
		"\tuint32_t second_len = 0;",
		"",
		"\t(void)state;",
		"\tsitu_codec_fill(input, sizeof(input), 7u);",
		"",
		f"\tassert_int_equal({encode}(input, sizeof(input), first,",
		"\t\tsizeof(first), &first_len), SITU_OK);",
		f"\tassert_int_equal({encode}(input, sizeof(input), second,",
		"\t\tsizeof(second), &second_len), SITU_OK);",
		"",
		"\tassert_int_equal(first_len, second_len);",
		"\tassert_memory_equal(first, second, first_len);",
		"}",
	], name)


def _invertible_test(codec: ast.CodecDecl, encode: str,
		decode: str) -> tuple[list[str], str | None]:
	if not codec.invertible:
		return ([], None)

	name = f"test_{codec.name}_invertible"
	return ([
		"/* Declared: `invertible`. decode(encode(x)) == x over random and",
		" * edge-case inputs. */",
		f"static void {name}(void **state)",
		"{",
		"\tstatic const uint32_t sizes[] = {",
		"\t\t" + ", ".join(f"{n}u" for n in SWEEP) + ",",
		"\t};",
		"\tuint8_t input[SITU_CODEC_MAX_INPUT];",
		"\tuint8_t coded[SITU_CODEC_MAX_OUTPUT];",
		"\tuint8_t back[SITU_CODEC_MAX_OUTPUT];",
		"\tsize_t i;",
		"",
		"\t(void)state;",
		"\tfor (i = 0; i < sizeof(sizes) / sizeof(sizes[0]); i++) {",
		"\t\tuint32_t in_len    = sizes[i];",
		"\t\tuint32_t coded_len = 0;",
		"\t\tuint32_t back_len  = 0;",
		"",
		"\t\tsitu_codec_fill(input, in_len, (uint32_t)i + 100u);",
		f"\t\tassert_int_equal({encode}(input, in_len, coded,",
		"\t\t\tsizeof(coded), &coded_len), SITU_OK);",
		f"\t\tassert_int_equal({decode}(coded, coded_len, back,",
		"\t\t\tsizeof(back), &back_len), SITU_OK);",
		"",
		"\t\tassert_int_equal(back_len, in_len);",
		"\t\tif (in_len > 0u) {",
		"\t\t\tassert_memory_equal(back, input, in_len);",
		"\t\t}",
		"\t}",
		"}",
	], name)


def _seekable_test(codec: ast.CodecDecl, encode: str,
		decode: str) -> tuple[list[str], str | None]:
	"""`seekable = linear`: byte N of the output produced from a partial input
	equals byte N of the full output."""
	if codec.seekable is not ast.Seekable.LINEAR:
		return ([], None)

	name = f"test_{codec.name}_seekable_linear"
	return ([
		"/* Declared: `seekable = linear`. A prefix of the input must produce a",
		" * prefix of the output: that is what lets a generated accessor",
		" * re-transform one byte range instead of the whole region. */",
		f"static void {name}(void **state)",
		"{",
		"\tuint8_t input[128];",
		"\tuint8_t whole[SITU_CODEC_MAX_OUTPUT];",
		"\tuint8_t partial[SITU_CODEC_MAX_OUTPUT];",
		"\tuint32_t whole_len   = 0;",
		"\tuint32_t partial_len = 0;",
		"",
		"\t(void)state;",
		"\tsitu_codec_fill(input, sizeof(input), 21u);",
		"",
		f"\tassert_int_equal({encode}(input, sizeof(input), whole,",
		"\t\tsizeof(whole), &whole_len), SITU_OK);",
		f"\tassert_int_equal({encode}(input, sizeof(input) / 2u, partial,",
		"\t\tsizeof(partial), &partial_len), SITU_OK);",
		"",
		"\tassert_true(partial_len <= whole_len);",
		"\tassert_memory_equal(partial, whole, partial_len);",
		"}",
	], name)


def _systematic_test(codec: ast.CodecDecl, encode: str,
		decode: str) -> tuple[list[str], str | None]:
	"""`systematic`: the input bytes appear verbatim in the output.

	Only checkable where the compiler knows where they should land, which for
	an appended-parity form is at offset zero.
	"""
	if not codec.systematic:
		return ([], None)

	if codec.expansion is not ast.Expansion.FIXED_ADD:
		return ([f"/* {codec.name}: `systematic` is declared, but the compiler",
		         " * cannot say where the data lands unless the expansion is an",
		         " * appended constant. Check the offsets by hand. */"], None)

	name = f"test_{codec.name}_systematic"
	return ([
		"/* Declared: `systematic`. The input appears verbatim at the offsets the",
		" * compiler computed, which is what allows a field to be read with no",
		" * decode at all. */",
		f"static void {name}(void **state)",
		"{",
		"\tuint8_t input[64];",
		"\tuint8_t output[SITU_CODEC_MAX_OUTPUT];",
		"\tuint32_t out_len = 0;",
		"",
		"\t(void)state;",
		"\tsitu_codec_fill(input, sizeof(input), 33u);",
		"",
		f"\tassert_int_equal({encode}(input, sizeof(input), output,",
		"\t\tsizeof(output), &out_len), SITU_OK);",
		"",
		"\tassert_memory_equal(output, input, sizeof(input));",
		"}",
	], name)


def _granularity_test(codec: ast.CodecDecl, encode: str,
		decode: str) -> tuple[list[str], str | None]:
	"""`granularity = block(N)`: modifying one input block changes only the
	corresponding output block."""
	if codec.granularity is not ast.Granularity.BLOCK:
		return ([], None)
	if codec.granularity_size is None or codec.expansion is not ast.Expansion.PRESERVING:
		return ([f"/* {codec.name}: block granularity is declared, but without a",
		         " * fixed block size and a length-preserving expansion the",
		         " * independence of blocks cannot be checked mechanically. */"], None)

	size = codec.granularity_size
	name = f"test_{codec.name}_block_independence"
	return ([
		f"/* Declared: `granularity = block({size})`. Changing one input block",
		" * must leave every other output block alone -- which is what makes a",
		" * write re-transform one block instead of the region. */",
		f"static void {name}(void **state)",
		"{",
		f"\tconst uint32_t block = {size}u;",
		f"\tuint8_t input[{size * 4}];",
		"\tuint8_t before[SITU_CODEC_MAX_OUTPUT];",
		"\tuint8_t after[SITU_CODEC_MAX_OUTPUT];",
		"\tuint32_t before_len = 0;",
		"\tuint32_t after_len  = 0;",
		"",
		"\t(void)state;",
		"\tsitu_codec_fill(input, sizeof(input), 55u);",
		f"\tassert_int_equal({encode}(input, sizeof(input), before,",
		"\t\tsizeof(before), &before_len), SITU_OK);",
		"",
		"\t/* Disturb one byte of the second block. */",
		"\tinput[block] ^= 0xFFu;",
		f"\tassert_int_equal({encode}(input, sizeof(input), after,",
		"\t\tsizeof(after), &after_len), SITU_OK);",
		"",
		"\tassert_int_equal(before_len, after_len);",
		"\tassert_memory_equal(before, after, block);",
		"\tassert_memory_equal(before + 2u * block, after + 2u * block,",
		"\t\tbefore_len - 2u * block);",
		"}",
	], name)


def _main(cases: list[str]) -> list[str]:
	if not cases:
		return [
			"int main(void)",
			"{",
			"\t/* No codec in this schema declares a property with a falsifying",
			"\t * test. That is not a pass: it means the signatures claim nothing. */",
			"\treturn 0;",
			"}",
		]

	lines = ["int main(void)", "{", "\tconst struct CMUnitTest tests[] = {"]
	for case in cases:
		lines.append(f"\t\tcmocka_unit_test({case}),")
	lines.extend([
		"\t};",
		"",
		"\treturn cmocka_run_group_tests(tests, NULL, NULL);",
		"}",
	])
	return lines


# ---------------------------------------------------------------------------
# Tier 2: the pair a kernel generates
# ---------------------------------------------------------------------------


def _is_derived(schema: ast.Schema, codec: ast.CodecDecl) -> bool:
	return any(decl.codec == codec.name
	           and decl.kind is ast.ImplKind.DERIVED
	           for decl in schema.impls())


def _step(codec: ast.CodecDecl) -> int:
	"""The input granularity, in bytes, a length has to be a multiple of.

	A block interleaver rearranges whole blocks and a padded code emits whole
	groups; handing either a partial one is asking for what it does not do.
	One byte for everything else, which is every symbol map whose symbols
	divide a byte.
	"""
	kernel = codec.kernel
	assert kernel is not None

	if kernel.family is ast.KernelFamily.PERMUTATION:
		rows    = kernel.argument("rows")
		columns = kernel.argument("columns")
		return max(1, getattr(rows, "value", 1) * getattr(columns, "value", 1))
	if codec.expansion is ast.Expansion.RATIO_PADDED and codec.ratio is not None:
		return lcm(8, codec.ratio[1]) // 8
	return 1


def _derived_suite(codec: ast.CodecDecl, encode: str,
		decode: str) -> tuple[list[str], list[str]]:
	"""Property tests over an implementation situ generated.

	Section 13.1: a tier-2 codec's *properties* cannot lie, because they are
	derived from the same kernel description the implementation is. What can
	be wrong is the implementation, and nothing had ever run one of these
	against the properties it is supposed to have (26.35).

	The call shape is the kernel's -- `(in, count, out) -> count`, counting
	bits where the kernel is bit-oriented -- rather than the tier-1 ABI, and
	that is the whole difference. A derived codec has no `impl extern` to bind
	an ABI to.
	"""
	bits  = decode_counts_bits(codec)
	step  = _step(codec)
	unit  = " * 8u" if bits else ""
	sizes = [n * step for n in (0, 1, 2, 3, 7, 8) if n * step <= MAX_INPUT // 2]

	counted = "bits" if bits else "len"
	head = [
		f"/* ---- {codec.name} (derived) ---- */",
		"",
		# Declared here rather than by including the schema's header: this
		# file is generated from a codec library that may declare no struct
		# at all, and `std/kernels.situ` is exactly that.
		f"extern uint32_t {encode}(const uint8_t *in, uint32_t {counted},"
		" uint8_t *out);",
		f"extern uint32_t {decode}(const uint8_t *in, uint32_t {counted},"
		" uint8_t *out);",
		"",
	]
	body: list[str] = []
	names: list[str] = []

	# Round trip, which is `invertible` and is the property worth having
	# whatever else the signature says: an implementation whose inverse is
	# not one has nothing else worth checking.
	if codec.invertible:
		name = f"test_{codec.name}_derived_invertible"
		names.append(name)
		body.extend([
			"/* Derived: `invertible`. What comes back is what went in, at",
			" * every length the kernel admits. */",
			f"static void {name}(void **state)",
			"{",
			f"	static const uint32_t sizes[] = {{ {', '.join(f'{n}u' for n in sizes)} }};",
			"	uint8_t input[SITU_CODEC_MAX_INPUT];",
			"	uint8_t coded[SITU_CODEC_MAX_OUTPUT];",
			"	uint8_t back[SITU_CODEC_MAX_OUTPUT];",
			"	size_t i;",
			"",
			"	(void)state;",
			"	for (i = 0; i < sizeof(sizes) / sizeof(sizes[0]); i++) {",
			"		const uint32_t in_len = sizes[i];",
			"		uint32_t coded_len;",
			"",
			"		situ_codec_fill(input, in_len, (uint32_t)i + 7u);",
			f"		coded_len = {encode}(input, in_len{unit}, coded);",
			f"		assert_int_equal({decode}(coded, coded_len, back),",
			f"			in_len{unit});",
			"		if (in_len > 0u) {",
			"			assert_memory_equal(back, input, in_len);",
			"		}",
			"	}",
			"}",
			"",
		])

	if codec.deterministic:
		name = f"test_{codec.name}_derived_deterministic"
		names.append(name)
		body.extend([
			"/* Derived: `deterministic`. Twice over one input, byte for byte. */",
			f"static void {name}(void **state)",
			"{",
			f"	const uint32_t in_len = {sizes[-1]}u;",
			"	uint8_t input[SITU_CODEC_MAX_INPUT];",
			"	uint8_t first[SITU_CODEC_MAX_OUTPUT];",
			"	uint8_t second[SITU_CODEC_MAX_OUTPUT];",
			"	uint32_t first_len;",
			"	uint32_t second_len;",
			"",
			"	(void)state;",
			"	situ_codec_fill(input, in_len, 11u);",
			f"	first_len  = {encode}(input, in_len{unit}, first);",
			f"	second_len = {encode}(input, in_len{unit}, second);",
			"",
			"	assert_int_equal(first_len, second_len);",
			# Whole bytes of the written bits, where the count is bits: a
			# bit-oriented codec writes `n` bits, and the rest of the last
			# byte belongs to whoever owns the buffer. Comparing it
			# compares what the caller left there, which is how this test
			# first failed a correct HDLC stuffer (26.35).
			f"\tassert_memory_equal(first, second,"
			f" {'first_len / 8u' if bits else 'first_len'});",
			"}",
			"",
		])

	length = _derived_length(codec, encode, unit, sizes)
	if length is not None:
		body.extend(length[0])
		names.append(length[1])

	seek = _derived_seekable(codec, encode, unit, step)
	if seek is not None:
		body.extend(seek[0])
		names.append(seek[1])

	return (head + body if names else
	        [*head, "/* Nothing declared that this shape can attack. */", ""],
	        names)


def _derived_length(codec: ast.CodecDecl, encode: str, unit: str,
		sizes: list[int]) -> tuple[list[str], str] | None:
	"""The declared expansion, as arithmetic on the count the pair returns.

	Only where the expansion is exact: `ratio_bounded` and `unbounded` say
	the output depends on the content, which is a claim about what *cannot*
	be asserted.
	"""
	if codec.expansion is ast.Expansion.PRESERVING:
		expect = "in_len{unit}"
	elif codec.expansion is ast.Expansion.FIXED_ADD:
		expect = f"in_len{{unit}} + {codec.expansion_add}u"
	elif codec.expansion is ast.Expansion.RATIO_EXACT and codec.ratio:
		expect = f"in_len{{unit}} * {codec.ratio[0]}u / {codec.ratio[1]}u"
	elif codec.expansion is ast.Expansion.RATIO_PADDED and codec.ratio:
		group_in  = lcm(8, codec.ratio[1]) // 8
		group_out = lcm(8, codec.ratio[1]) // codec.ratio[1] * codec.ratio[0] // 8
		expect = (f"((in_len + {group_in - 1}u) / {group_in}u) * {group_out}u")
	else:
		return None

	name = f"test_{codec.name}_derived_length"
	return ([
		f"/* Derived: {codec.expansion.value}. The count the encode returns is",
		" * what the signature says it is, at every length. */",
		f"static void {name}(void **state)",
		"{",
		f"	static const uint32_t sizes[] = {{ {', '.join(f'{n}u' for n in sizes)} }};",
		"	uint8_t input[SITU_CODEC_MAX_INPUT];",
		"	uint8_t coded[SITU_CODEC_MAX_OUTPUT];",
		"	size_t i;",
		"",
		"	(void)state;",
		"	for (i = 0; i < sizeof(sizes) / sizeof(sizes[0]); i++) {",
		"		const uint32_t in_len = sizes[i];",
		"",
		"		situ_codec_fill(input, in_len, (uint32_t)i + 23u);",
		f"		assert_int_equal({encode}(input, in_len{unit}, coded),",
		f"			{expect.format(unit=unit)});",
		"	}",
		"}",
		"",
	], name)


def _derived_seekable(codec: ast.CodecDecl, encode: str, unit: str,
		step: int) -> tuple[list[str], str] | None:
	"""`seekable = linear`: a prefix in, a prefix out.

	Cut on a granularity boundary, which is what makes the claim a claim: a
	padded code emits whole groups, so cutting base64 at 64 of 128 bytes
	pads the 64 and the outputs diverge at the last group. The tier-1 harness
	cuts at half and does not ask, which would have failed a correct base64
	the first time one was bound (26.35).
	"""
	if codec.seekable is not ast.Seekable.LINEAR:
		return None

	whole = (MAX_INPUT // 2 // step) * step
	half  = (whole // 2 // step) * step
	if half == 0 or whole == 0:
		return None

	name = f"test_{codec.name}_derived_seekable_linear"
	return ([
		"/* Derived: `seekable = linear`. A prefix of the input produces a",
		f" * prefix of the output, cut at {step}-byte granularity because that",
		" * is the unit the claim is about. */",
		f"static void {name}(void **state)",
		"{",
		"	uint8_t input[SITU_CODEC_MAX_INPUT];",
		"	uint8_t whole[SITU_CODEC_MAX_OUTPUT];",
		"	uint8_t partial[SITU_CODEC_MAX_OUTPUT];",
		"	uint32_t whole_len;",
		"	uint32_t partial_len;",
		"",
		"	(void)state;",
		f"	situ_codec_fill(input, {whole}u, 21u);",
		"",
		f"	whole_len   = {encode}(input, {whole}u{unit}, whole);",
		f"	partial_len = {encode}(input, {half}u{unit}, partial);",
		"",
		"	assert_true(partial_len <= whole_len);",
		f"	assert_memory_equal(partial, whole,"
		f" ({'partial_len / 8u' if unit else 'partial_len'}));",
		"}",
		"",
	], name)
