"""Generate implementations from kernel descriptions (section 26.12).

Tier 2's other half. `situc/kernels.py` works out what a kernel implies; this
emits the code that does it, and the two come from the same description -- which
is the point. A tier-1 codec's properties are a promise nobody checked; a
tier-2 codec's properties and its implementation are computed from one source,
so they cannot disagree.

Two families here, in the order 26.12 recommends: polynomial, which is every
CRC variant and lands as a `checksum` rather than a codec, and table, which is
Manchester, 4b5b and the base-N alphabets. (Not NRZI or 8b10b: see
`kernels.py`.)

The generated CRC is table-driven and the table is computed here rather than
copied, so a variant nobody has written down works the same as a famous one.
What is not computed here is the check value it must produce: those come from
the CRC catalogue, and testing against them is what makes this an
implementation of CRC-32 rather than an implementation of whatever this file
happens to do.
"""

from __future__ import annotations

import textwrap

from math import lcm

from situc import ast
from situc.codegen.c.names import ident, macro
from situc.traverse import DERIVED_STUFFING as DERIVED_STUFFING
from situc.traverse import table_is_padded
from situc.layout import BITS_PER_BYTE
from situc import __version__

WORD_WIDTHS = (8, 16, 32, 64)


def generate(schema: ast.Schema, basename: str, prefix: str = "situ") -> str:
	"""Emit every derived implementation the schema binds."""
	derived = {impl.codec for impl in schema.impls()
	           if impl.kind is ast.ImplKind.DERIVED}

	lines = [
		f"/* Generated by situc {__version__} from {basename}.situ -- do not edit.",
		" *",
		" * Implementations derived from kernel descriptions (section 13.4).",
		" * The properties in the capability map and the code below come from",
		" * one description, so they cannot disagree.",
		" */",
		"",
		"#include <stdint.h>",
		"#include <stddef.h>",
		"",
		f'#include "{basename}.h"',
	]

	emitted = 0
	for decl in schema.codecs():
		if decl.name not in derived or decl.kernel is None:
			continue

		body = _for_kernel(decl, prefix)
		if body is None:
			lines.extend([
				"",
				f"/* No implementation for `{decl.name}`: a "
				f"{decl.kernel.family.value} kernel is described but not yet",
				" * generated. Its properties are derived and correct; bind an",
				f" * `impl {decl.name} extern \"...\"` to supply the code.",
				*_what_is_generated(decl),
				" */",
			])
			continue

		lines.extend(body)
		emitted += 1

	if not emitted:
		lines.extend([
			"",
			"/* Nothing derived in this schema. A translation unit with no",
			" * external definitions is not valid C, so here is one. */",
			f"extern const int {ident(prefix, basename, 'derived_none')};",
			f"const int {ident(prefix, basename, 'derived_none')} = 0;",
		])

	return "\n".join(lines) + "\n"


#: Linear block codes this build derives an implementation for.
#:
#: One entry, and named anyway. It was the literal `"hamming_7_4"` written
#: twice -- the prototype gate in `_byte_declarations` and the dispatch in
#: `_linear_block` -- which is the shape that had just cost this file a
#: silent gap in `stuffing`, in the same two places. A second code added to
#: one of them would declare a function nothing defined, or define one
#: nothing declared, and neither is visible in the diff that causes it.
DERIVED_LINEAR = ("hamming_7_4",)

#: Stuffing codes this build derives an implementation for.
#:
#: One list because there were three. The dispatch in `_stuffing` and the
#: prototype gate in `_byte_declarations` were consolidated first; `traverse`
#: held a third copy that pass did not find, and it is the one every backend
#: asks the shape question of. It lives there now and is imported here.

#: The escape-stuffed byte codes, which differ from COBS in kind: rather than
#: eliminating a byte value, they keep it and prefix it with an escape, so the
#: delimiter stays available to frame with. Each entry is the delimiter, the
#: escape, and how a byte that cannot appear literally is spelled after it.
#:
#: The two here spell that last part differently, and the difference is not
#: cosmetic. SLIP substitutes from a table -- 0xC0 becomes 0xDC and 0xDB
#: becomes 0xDD, which is not a uniform transformation of either. PPP defines
#: the escape as "the next byte, exclusive-ored with 0x20", which is a rule
#: rather than a table and is why its decoder below is the more general of the
#: two: it reverses any escaped byte, including the control characters an
#: ACCM asks a sender to escape and which no fixed table could enumerate.
ESCAPE_STUFFING: dict[str, tuple[str, int, int, int | None,
                                 tuple[tuple[int, int], ...]]] = {
	"slip": ("SLIP, RFC 1055", 0xC0, 0xDB, None,
	         ((0xC0, 0xDC), (0xDB, 0xDD))),
	"ppp_async": ("PPP asynchronous framing, RFC 1662 section 4.2",
	              0x7E, 0x7D, 0x20, ((0x7E, 0x5E), (0x7D, 0x5D))),
}


def declarations(schema: ast.Schema, prefix: str) -> list[str]:
	"""The prototypes the header needs for what `generate` emits."""
	derived = {impl.codec for impl in schema.impls()
	           if impl.kind is ast.ImplKind.DERIVED}
	lines: list[str] = []

	for decl in schema.codecs():
		if decl.name not in derived or decl.kernel is None:
			continue

		if decl.kernel.family is ast.KernelFamily.POLYNOMIAL:
			if decl.kernel.argument("field") is not None:
				lines.extend(_rs_declarations(decl, prefix))
				continue

			width = _width(decl)
			if width is None:
				continue
			lines.extend([
				"",
				f"/* `{decl.name}`: derived from a polynomial kernel. */",
				f"#define {macro(prefix, decl.name, 'WIDTH')} {width}u",
				f"uint{_accumulator(width)}_t {ident(prefix, decl.name)}"
				"(const uint8_t *data, uint32_t len);",
			])
		elif decl.kernel.family is ast.KernelFamily.TABLE:
			# Bits, unless the code pads: a padded table walks whole input
			# bytes into whole output groups and counts both in bytes. The
			# prototype said `bits` for every table, which C does not check
			# against the definition -- the types are the same and only the
			# name differs -- so base64's header lied about its own unit
			# (26.35).
			counted = "len" if table_is_padded(decl) else "bits"
			lines.extend([
				"",
				f"/* `{decl.name}`: derived from a table kernel. */",
				f"uint32_t {ident(prefix, decl.name, 'encode')}"
				f"(const uint8_t *in, uint32_t {counted}, uint8_t *out);",
				f"uint32_t {ident(prefix, decl.name, 'decode')}"
				f"(const uint8_t *in, uint32_t {counted}, uint8_t *out);",
			])
		else:
			lines.extend(_byte_declarations(decl, prefix))

	return lines


def pair_of(decl: ast.CodecDecl, prefix: str = "situ") -> tuple[str, str] | None:
	"""The `(in, count, out) -> count` encode/decode pair this kernel emits.

	Four of the six families produce that one shape, which is what
	`_byte_declarations` says: bytes in, bytes out, and a count. `None` for
	the two that do not -- a polynomial kernel is a checksum over its input
	and a linear block code is a nibble in and a codeword out, and neither is
	a transform with an inverse of the same shape.

	Asked here rather than inferred from the emitted text, because
	`gen-codec-tests` needs to know which codecs it can attack and reading a
	prototype back out of a string is how a second description starts.
	"""
	kernel = decl.kernel
	if kernel is None:
		return None

	family = kernel.family
	if family is ast.KernelFamily.POLYNOMIAL or family is ast.KernelFamily.LINEAR:
		return None
	if family is ast.KernelFamily.PERMUTATION and kernel.argument("rows") is None:
		return None
	if family is ast.KernelFamily.STUFFING and _named_code(decl) not in DERIVED_STUFFING:
		return None
	if family is ast.KernelFamily.TABLE and _symbol_map(
			decl, _number(decl, "input_bits"), _number(decl, "output_bits")) is None:
		return None

	return (ident(prefix, decl.name, "encode"), ident(prefix, decl.name, "decode"))


def _what_is_generated(decl: ast.CodecDecl) -> list[str]:
	"""Which descriptions of this family DO generate, where that is a list.

	The message above says a kernel is "not yet generated", and on its own
	that reads as though the whole family were unimplemented. It was read
	that way: decision 0017 recorded that `stuffing` "returns no
	implementation for any input at all", when three codes generated then and
	five do now. Naming them is the difference between a gap somebody can
	close and a family somebody writes off.

	**That fix reached one family of four.** `stuffing` named its codes and
	`table`, `linear_block` and `permutation` went on saying only the old
	sentence -- so a schema naming an unknown table code was told nothing
	about the eight that work, which is the reading 0017 made about stuffing
	and would have made again. The lesson was learned exactly and applied
	once, which is the shape this session found twice more the same night:
	in the workflow, where `pipefail` was added where `tee` swallowed a
	status and not where `head` did.

	`permutation` is the odd one and says something different, because what
	it declines on is not an unknown name: a bare `span` describes the extent
	of some permutation without saying which, which is enough for the
	properties and not enough for the code.
	"""
	kernel = decl.kernel
	assert kernel is not None

	if kernel.family is ast.KernelFamily.PERMUTATION:
		return [
			" *",
			*_wrap("A permutation generates from `rows` and `columns`, which "
			       "say which permutation it is. A bare `span` gives the "
			       "extent and not the mapping, so the properties follow and "
			       "the code cannot."),
		]

	catalogue = {
		ast.KernelFamily.STUFFING: ("stuffing codes", DERIVED_STUFFING),
		ast.KernelFamily.TABLE:    ("table codes", tuple(sorted(NAMED_CODES))),
		ast.KernelFamily.LINEAR:   ("linear block codes", DERIVED_LINEAR),
	}.get(kernel.family)
	if catalogue is None:
		return []

	what, codes = catalogue
	named = _named_code(decl)
	known = ", ".join(f"`{code}`" for code in codes)
	lines = [" *", *_wrap(f"The {what} this build generates are {known}.")]

	if named is not None:
		lines.extend(_wrap(f"`{named}` is not one of them."))
	elif kernel.family is ast.KernelFamily.TABLE:
		lines.extend(_wrap("This kernel names no code. A table is selected by "
		                   "`code`, or given outright as one `symbol` per "
		                   "input symbol."))
	else:
		lines.extend(_wrap(f"This kernel names no code, and a "
		                   f"{what[:-6]} code is what selects one."))
	return lines


def _wrap(prose: str) -> list[str]:
	"""One sentence as C comment continuation lines, inside 78 columns."""
	return [f" * {line}" for line in textwrap.wrap(prose, width=74)]


def _for_kernel(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	kernel = decl.kernel
	assert kernel is not None

	if kernel.family is ast.KernelFamily.POLYNOMIAL:
		if kernel.argument("field") is not None:
			return _reed_solomon(decl, prefix)
		return _polynomial(decl, prefix)
	if kernel.family is ast.KernelFamily.TABLE:
		return _table(decl, prefix)
	if kernel.family is ast.KernelFamily.PERMUTATION:
		return _permutation(decl, prefix)
	if kernel.family is ast.KernelFamily.LINEAR:
		return _linear_block(decl, prefix)
	if kernel.family is ast.KernelFamily.SHIFT:
		return _shift_register(decl, prefix)
	if kernel.family is ast.KernelFamily.ONES_COMPLEMENT:
		return _ones_complement(decl, prefix)
	return _stuffing(decl, prefix)


# ---------------------------------------------------------------------------
# One's complement: RFC 1071, the checksum on almost every packet
# ---------------------------------------------------------------------------


def _ones_complement(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""RFC 1071's sum, which four of this repository's examples carry.

	Sixteen lines and no table. The data is read as big-endian 16-bit words
	and added into a wider accumulator, the carries are folded back until
	none is left, and the result is complemented where the kernel says so.

	Two details are the whole of the algorithm's reputation for being
	fiddled. An odd trailing byte is the *high* half of a final word, not
	the low one -- padding it the other way gives a number that is wrong for
	every odd-length input and right for every test somebody wrote with an
	even one. And the fold is a loop rather than a single add, because
	folding once can carry again.

	The sum is order-independent over 16-bit words, which is why a protocol
	may compute it over a pseudo-header and a payload separately and add the
	halves. That property is the reason RFC 1071 exists as a document rather
	than a line of code, and nothing here needs to do anything to preserve
	it.
	"""
	kernel = decl.kernel
	assert kernel is not None

	name       = ident(prefix, decl.name)
	complement = kernel.flag("complement")
	final      = "(uint16_t)(~sum & 0xFFFFu)" if complement \
		else "(uint16_t)(sum & 0xFFFFu)"

	return [
		"",
		f"/* {decl.name}: RFC 1071, one's-complement sum with end-around",
		" * carry" + (", complemented" if complement else "") + ". */",
		f"uint16_t {name}(const uint8_t *data, uint32_t len)",
		"{",
		"\t/* 64 bits, so the accumulator cannot overflow for any length a",
		"\t * uint32_t can express: at most 2^31 words of 0xFFFF is about",
		"\t * 1.4e14, and 2^64 is 1.8e19. A uint32_t held 65537 words and",
		"\t * wrapped on the next one -- 128 KiB, which no IP datagram",
		"\t * reaches and any file does. */",
		"\tuint64_t sum = 0;",
		"\tuint32_t i;",
		"",
		"\tfor (i = 0; i + 1u < len; i += 2u) {",
		"\t\tsum += (uint64_t)(((uint32_t)data[i] << 8) | data[i + 1u]);",
		"\t}",
		"\tif (i < len) {",
		"\t\t/* The odd byte is the high half of a final word. Padding it",
		"\t\t * low is wrong for every odd length and right for every",
		"\t\t * even-length test anybody writes. */",
		"\t\tsum += (uint64_t)((uint32_t)data[i] << 8);",
		"\t}",
		"",
		"\t/* A loop rather than one add, because a fold can carry again --",
		"\t * which a 64-bit accumulator makes reachable rather than",
		"\t * theoretical. */",
		"\twhile (sum >> 16) {",
		"\t\tsum = (sum & 0xFFFFu) + (sum >> 16);",
		"\t}",
		f"\treturn {final};",
		"}",
	]


# ---------------------------------------------------------------------------
# Polynomial: every CRC variant
# ---------------------------------------------------------------------------


def _width(decl: ast.CodecDecl) -> int | None:
	"""A CRC width this can generate: any whole number of bytes up to eight.

	It was the four C word widths, so a 24-bit CRC derived a correct signature
	-- `+3 bytes`, systematic, seekable -- and generated nothing, with a note
	telling the author to supply it themselves. Bluetooth LE's link-layer CRC
	is 24 bits, which is how the gap was noticed; CRC-24/OpenPGP, CRC-40/GSM
	and the 12-bit telemetry CRCs are the same shape.

	Nothing about the algorithm needed the width to be a word. The table is
	computed either way, and what a non-word width needs is an accumulator
	wider than itself and a mask after every shift -- which `_accumulator`
	and the emitter below now do.
	"""
	kernel = decl.kernel
	assert kernel is not None
	value = kernel.argument("width")
	width = value.value if isinstance(value, ast.IntLiteral) else None
	if width is None or width % 8 or not 8 <= width <= 64:
		return None
	return width


def _accumulator(width: int) -> int:
	"""The C word that holds a `width`-bit CRC: the next one up, or its own.

	A 24-bit CRC accumulates in a `uint32_t`, and every shift is masked back
	to 24 bits. There is no `uint24_t`, and inventing a struct for one would
	buy nothing a mask does not.
	"""
	return next(word for word in WORD_WIDTHS if word >= width)


def _number(decl: ast.CodecDecl, name: str, default: int = 0) -> int:
	kernel = decl.kernel
	assert kernel is not None
	value = kernel.argument(name)
	return value.value if isinstance(value, ast.IntLiteral) else default


def _polynomial(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""A table-driven CRC, with the table computed rather than copied.

	The parameters are the CRC catalogue's: width, polynomial, initial value,
	whether input and output are reflected, and a final xor. Every named
	variant is a point in that space, so generating from it means a variant
	nobody has written down works exactly as well as a famous one.
	"""
	width = _width(decl)
	if width is None:
		return None

	poly    = _number(decl, "poly")
	init    = _number(decl, "init")
	xorout  = _number(decl, "xorout")
	kernel  = decl.kernel
	assert kernel is not None
	reflect = kernel.flag("reflect")

	if not poly:
		return None

	table  = _crc_table(width, poly, reflect)
	held   = _accumulator(width)
	word   = f"uint{held}_t"
	name   = ident(prefix, decl.name)
	mask   = (1 << width) - 1
	digits = width // 4

	# A width narrower than the word it is held in has to be masked back after
	# every shift, or the bits above it survive into the next lookup and the
	# digest is not the one the polynomial defines.
	narrow = f" & 0x{mask:X}u" if held != width else ""

	lines = [
		"",
		f"/* {decl.name}: width={width} poly=0x{poly:0{digits}X} "
		f"init=0x{init:0{digits}X}",
		f" * xorout=0x{xorout:0{digits}X} reflect={'yes' if reflect else 'no'}",
		" *",
		" * The table is computed from the polynomial, not copied from one: a",
		" * variant nobody has written down works the same as a famous one.",
		" */",
		f"static const {word} {name}_table[256] = {{",
	]

	for row in range(0, 256, 4):
		entries = ", ".join(f"0x{table[row + column]:0{digits}X}u"
		                    for column in range(4))
		lines.append(f"\t{entries},")

	lines.append("};")
	lines.append("")
	# A reflected CRC runs the register the other way round, so it *starts*
	# the other way round: the initial value is the catalogue's, bit-reversed.
	# Emitting it as written was right for every reflected CRC in the library
	# -- CRC-32 and CRC-16/MODBUS both start all-ones, which is its own
	# reverse -- and wrong for the first one that does not. CRC-24/BLE starts
	# at 0x555555 and came out as 0xD39857 where the catalogue says 0xC25A56.
	started = _reverse(init, width) if reflect else init

	lines.append(f"{word} {name}(const uint8_t *data, uint32_t len)")
	lines.append("{")
	lines.append(f"\t{word} crc = ({word})0x{started:0{digits}X}u;")
	lines.append("\tuint32_t i;")
	lines.append("")
	lines.append("\tfor (i = 0; i < len; i++) {")

	if reflect:
		lines.append(f"\t\tcrc = ({word})(({name}_table[(crc ^ data[i]) & 0xFFu]"
		             f" ^ (crc >> 8)){narrow});")
	elif width == 8:
		lines.append(f"\t\tcrc = {name}_table[crc ^ data[i]];")
	else:
		lines.append(f"\t\tcrc = ({word})(({name}_table"
		             f"[((crc >> {width - 8}) ^ data[i]) & 0xFFu]"
		             f" ^ ({word})(crc << 8)){narrow});")

	lines.append("\t}")
	lines.append("")
	lines.append(f"\treturn ({word})(crc ^ ({word})0x{xorout:0{digits}X}u)"
	             f"{f' & 0x{mask:X}u' if width < 64 else ''};")
	lines.append("}")
	return lines


def _crc_table(width: int, poly: int, reflect: bool) -> list[int]:
	"""One byte's worth of the polynomial division, for each possible byte.

	Reflected variants run the division the other way round, which is the same
	arithmetic over the bit-reversed polynomial. Doing it here rather than
	reversing bits at run time is what keeps the generated loop one table
	lookup wide.
	"""
	mask  = (1 << width) - 1
	table = []

	if reflect:
		reversed_poly = _reverse(poly, width)
		for byte in range(256):
			crc = byte
			for _ in range(8):
				crc = (crc >> 1) ^ (reversed_poly if crc & 1 else 0)
			table.append(crc & mask)
		return table

	top = 1 << (width - 1)
	for byte in range(256):
		crc = (byte << (width - 8)) & mask
		for _ in range(8):
			crc = ((crc << 1) ^ poly) & mask if crc & top else (crc << 1) & mask
		table.append(crc)
	return table


def _reverse(value: int, width: int) -> int:
	result = 0
	for _ in range(width):
		result = (result << 1) | (value & 1)
		value >>= 1
	return result


# ---------------------------------------------------------------------------
# Table: line codes
# ---------------------------------------------------------------------------


def _table(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""A symbol map, encoded and decoded a symbol at a time.

	The map may be given outright, as one `symbol` per input symbol, or
	named -- and a code with a 32-entry table is better named than
	transcribed, because a table copied into a schema is a table nobody will
	check. `NAMED_CODES` holds the eight this build knows.

	This said "`manchester` and `nrzi` are small enough to describe in the
	schema", and both halves aged badly. Bare `manchester` is *refused*,
	because it names two codes that differ by an inversion (`AMBIGUOUS_CODES`);
	and `nrzi` is not a table code at all -- it is differential, which no
	stateless symbol map expresses, and 26.140 moved it to the shift register
	family where it belongs.
	"""
	kernel = decl.kernel
	assert kernel is not None

	inputs  = _number(decl, "input_bits")
	outputs = _number(decl, "output_bits")
	mapping = _symbol_map(decl, inputs, outputs)

	if mapping is None or inputs > 8 or outputs > 16:
		return None

	# A padded code emits whole groups and fills a partial one, which is a
	# different shape of loop: symbol at a time cannot express it, because the
	# last group's symbol count depends on how much input was left.
	pad = kernel.argument("pad")
	if isinstance(pad, ast.IntLiteral):
		return _padded_table(decl, prefix, inputs, outputs, mapping, pad.value)

	name = ident(prefix, decl.name)
	size = 1 << inputs

	lines = [
		"",
		f"/* {decl.name}: {inputs} bits in, {outputs} bits out, ratio "
		f"{outputs}:{inputs}.",
		" *",
		" * The ratio is exact, so an output position is a linear function of",
		" * an input one -- which is why interior offsets survive this and not",
		" * a stuffing code.",
		" */",
		f"static const uint16_t {name}_encode_table[{size}] = {{",
		"\t" + ", ".join(f"0x{mapping[symbol]:X}u" for symbol in range(size)),
		"};",
		"",
		"/* Encode `bits` input bits from `in` into `out`. Returns the number of",
		*([" * output bits written, which is exactly bits * "
		   f"{outputs} / {inputs} -- or 0 if `bits`",
		   " * is not a whole number of symbols, which has no encoding, the way",
		   " * a partial block has no permutation. */"] if inputs > 1 else
		  [" * output bits written, which is exactly bits * "
		   f"{outputs} / {inputs}. */"]),
		f"uint32_t {name}_encode(const uint8_t *in, uint32_t bits, uint8_t *out)",
		"{",
		"\tuint32_t at;",
		"\tuint32_t written = 0;",
		"",
		*([f"\tif (bits % {inputs}u != 0u) {{",
		   "\t\treturn 0;",
		   "\t}",
		   ""] if inputs > 1 else []),
		f"\tfor (at = 0; at + {inputs}u <= bits; at += {inputs}u) {{",
		f"\t\tuint32_t symbol = (uint32_t)situ_bits_get_msb(in, at, {inputs}u);",
		f"\t\tsitu_bits_set_msb(out, written, {outputs}u,",
		f"\t\t                  (uint64_t){name}_encode_table[symbol]);",
		f"\t\twritten += {outputs}u;",
		"\t}",
		"",
		"\treturn written;",
		"}",
		"",
		"/* Decode. Returns the number of input bits recovered, or 0 on a symbol",
		" * the code does not define, or on a length that is not a whole number",
		" * of symbols -- both are a corrupted stream rather than a decodable",
		" * one, and neither is something to decode part of. */",
		f"uint32_t {name}_decode(const uint8_t *in, uint32_t bits, uint8_t *out)",
		"{",
		"\tuint32_t at;",
		"\tuint32_t written = 0;",
		"",
		f"\tif (bits % {outputs}u != 0u) {{",
		"\t\treturn 0;",
		"\t}",
		"",
		f"\tfor (at = 0; at + {outputs}u <= bits; at += {outputs}u) {{",
		f"\t\tuint32_t code = (uint32_t)situ_bits_get_msb(in, at, {outputs}u);",
		f"\t\tuint32_t symbol;",
		"\t\tint found = 0;",
		"",
		f"\t\tfor (symbol = 0; symbol < {size}u; symbol++) {{",
		f"\t\t\tif ({name}_encode_table[symbol] == code) {{",
		f"\t\t\t\tsitu_bits_set_msb(out, written, {inputs}u, symbol);",
		f"\t\t\t\twritten += {inputs}u;",
		"\t\t\t\tfound = 1;",
		"\t\t\t\tbreak;",
		"\t\t\t}",
		"\t\t}",
		"",
		"\t\tif (!found) {",
		"\t\t\treturn 0;",
		"\t\t}",
		"\t}",
		"",
		"\treturn written;",
		"}",
	]
	return lines


def _padded_table(decl: ast.CodecDecl, prefix: str, inputs: int, outputs: int,
		mapping: list[int], pad: int) -> list[str] | None:
	"""A base-N code: whole groups, with a partial one filled out.

	base32 and base64. A group is the smallest run of input that is both a
	whole number of bytes and a whole number of symbols -- five bytes and three
	respectively -- so an input that does not end on one has its last group
	padded rather than truncated. That is the whole difference from base16,
	where four bits divide a byte and the question never arises.

	The arithmetic here was written against Python's `base64` module and agrees
	with it at every input length, which matters more than usual: an encoder
	that is wrong only for inputs of length 3n+1 looks right in casual testing.
	"""
	if outputs != BITS_PER_BYTE or inputs >= BITS_PER_BYTE:
		return None

	name       = ident(prefix, decl.name)
	group_bits = lcm(BITS_PER_BYTE, inputs)
	group_in   = group_bits // BITS_PER_BYTE		# input bytes per group
	symbols    = group_bits // inputs			# output bytes per group
	mask       = (1 << inputs) - 1

	table   = ", ".join(f"0x{value:02X}u" for value in mapping)
	reverse = [0xFF] * 256
	for symbol, value in enumerate(mapping):
		reverse[value] = symbol
	inverse = ", ".join(f"0x{value:02X}u" for value in reverse)

	return [
		"",
		f"/* {decl.name}: RFC 4648 base{1 << inputs}.",
		" *",
		f" * {group_in} input bytes make {symbols} output bytes. A shorter final"
		f" group is",
		f" * filled with 0x{pad:02X}, so the output is always a whole number of",
		" * groups -- which is what `ratio_padded` in the capability map means.",
		" */",
		f"static const uint8_t {name}_alphabet[{len(mapping)}] = {{ {table} }};",
		"",
		f"/* Symbol for each byte, 0xFF where the byte is not in the alphabet. */",
		f"static const uint8_t {name}_symbol[256] = {{ {inverse} }};",
		"",
		f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"	uint32_t written = 0;",
		"	uint32_t start;",
		"",
		f"	for (start = 0; start < len; start += {group_in}u) {{",
		f"		uint32_t have = len - start < {group_in}u ? len - start : {group_in}u;",
		"		uint64_t acc  = 0;",
		"		uint32_t full;",
		"		uint32_t i;",
		"",
		f"		for (i = 0; i < {group_in}u; i++) {{",
		"			acc = (acc << 8) | (i < have ? (uint64_t)in[start + i] : 0u);",
		"		}",
		"",
		"		/* Symbols that carry data; the rest are padding. */",
		f"		full = (have * 8u + {inputs - 1}u) / {inputs}u;",
		"",
		f"		for (i = 0; i < {symbols}u; i++) {{",
		f"			uint32_t shift = {group_bits}u - {inputs}u * (i + 1u);",
		"",
		"			out[written + i] = i < full",
		f"				? {name}_alphabet[(uint32_t)(acc >> shift) & 0x{mask:02X}u]",
		f"				: (uint8_t)0x{pad:02X}u;",
		"		}",
		f"		written += {symbols}u;",
		"	}",
		"",
		"	return written;",
		"}",
		"",
		f"/* Returns the number of bytes decoded, or 0 for input that is not a",
		f" * whole number of groups or carries a byte outside the alphabet. */",
		f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"	uint32_t written = 0;",
		"	uint32_t start;",
		"",
		f"	if ((len % {symbols}u) != 0u) {{",
		"		return 0;",
		"	}",
		"",
		f"	for (start = 0; start < len; start += {symbols}u) {{",
		"		uint64_t acc  = 0;",
		"		uint32_t kept = 0;",
		"		uint32_t i;",
		"",
		f"		while (kept < {symbols}u && in[start + kept] != 0x{pad:02X}u) {{",
		"			kept++;",
		"		}",
		"",
		f"		for (i = 0; i < {symbols}u; i++) {{",
		"			uint32_t symbol = 0;",
		"",
		"			if (i < kept) {",
		f"				symbol = {name}_symbol[in[start + i]];",
		"				if (symbol == 0xFFu) {",
		"					return 0;",
		"				}",
		"			}",
		f"			acc = (acc << {inputs}u) | symbol;",
		"		}",
		"",
		"		{",
		f"			uint32_t bytes = kept * {inputs}u / 8u;",
		"",
		f"			for (i = 0; i < bytes; i++) {{",
		f"				uint32_t shift = {group_bits}u - 8u * (i + 1u);",
		"",
		"				out[written + i] = (uint8_t)((acc >> shift) & 0xFFu);",
		"			}",
		"			written += bytes;",
		"		}",
		"	}",
		"",
		"	return written;",
		"}",
	]


def _symbol_map(decl: ast.CodecDecl, inputs: int, outputs: int
		) -> list[int] | None:
	"""The output symbol for every input symbol.

	`map = (a, b, ...)` gives it outright. A named code is looked up: the point
	of a table kernel is that the table is data, and a 4b5b table transcribed
	into a schema is a table nobody will check.
	"""
	kernel = decl.kernel
	assert kernel is not None

	if not inputs or not outputs or inputs > 8:
		return None

	named = kernel.argument("code")
	if isinstance(named, ast.NameRef) and named.name in NAMED_CODES:
		table = NAMED_CODES[named.name]
		return table if len(table) == (1 << inputs) else None

	entries = [arg.value for arg in kernel.args if arg.name == "symbol"]
	if len(entries) == (1 << inputs) and all(
			isinstance(value, ast.IntLiteral) for value in entries):
		return [value.value for value in entries
		        if isinstance(value, ast.IntLiteral)]

	return None


# Line-code tables, from the standards rather than from situ.
NAMED_CODES: dict[str, list[int]] = {
	# The two Manchesters, named apart because they are two codes. IEEE
	# 802.3's is a one as a falling edge, encoded 10; G.E. Thomas's is the
	# bit-inverse of it, and both are called "Manchester" in the wild. A
	# schema that says only `manchester` is refused (`kernels.py`), because a
	# decoder built on the wrong one returns the complement of what was sent
	# and nothing at run time can see that.
	"manchester_802_3": [0b01, 0b10],
	"manchester_thomas": [0b10, 0b01],
	# ANSI X3.263 / FDDI 4b5b, the data symbols. The five-bit codes are chosen
	# to bound the run length, which is why they are not an arithmetic function
	# of the input.
	"fddi_4b5b": [
		0b11110, 0b01001, 0b10100, 0b10101,
		0b01010, 0b01011, 0b01110, 0b01111,
		0b10010, 0b10011, 0b10110, 0b10111,
		0b11010, 0b11011, 0b11100, 0b11101,
	],
	# RFC 4648 base16: a nibble to an ASCII hex digit, uppercase, which is what
	# the RFC specifies. It needs no padding at any length -- every byte is
	# exactly two nibbles -- which is what separates it from base32 and base64
	# and why it is the one of the three that fits a table kernel unchanged.
	"base16": [ord(c) for c in "0123456789ABCDEF"],
	# The same code in lowercase. Not an alias: a protocol that specifies one
	# and receives the other has received something it did not specify, and
	# situ has no business deciding that does not matter.
	"base16_lower": [ord(c) for c in "0123456789abcdef"],
	# RFC 4648 base32 and base64. Unlike base16 these need padding, because a
	# group is five bytes and three bytes respectively and an input rarely ends
	# on one. The alphabets are the RFC's; base64url swaps the last two
	# characters so the result survives a URL, which is a different code and
	# not a rendering choice.
	"base32": [ord(c) for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"],
	"base64": [ord(c) for c in
	           "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"],
	"base64url": [ord(c) for c in
	              "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"],
}


def _rs_declarations(decl: ast.CodecDecl, prefix: str) -> list[str]:
	n = _number(decl, "n")
	k = _number(decl, "k")
	if _number(decl, "field") != 256 or not n or not k:
		return []

	return [
		"",
		f"/* `{decl.name}`: Reed-Solomon({n}, {k}). Systematic, so the message",
		f" * sits verbatim ahead of the {n - k} parity symbols. */",
		f"uint32_t {ident(prefix, decl.name, 'encode')}"
		"(const uint8_t *data, uint32_t len, uint8_t *parity);",
		f"int {ident(prefix, decl.name, 'decode')}(uint8_t *block, uint32_t len);",
	]


def _byte_declarations(decl: ast.CodecDecl, prefix: str) -> list[str]:
	"""Prototypes for the families that work over whole bytes.

	One shape for four families, because the interface a caller wants is the
	same one every time: bytes in, bytes out, and a count. What differs is
	whether the count can change, which the expansion property already says.
	"""
	kernel = decl.kernel
	assert kernel is not None

	if kernel.family is ast.KernelFamily.PERMUTATION:
		if kernel.argument("rows") is None:
			return []
		return [
			"",
			f"/* `{decl.name}`: a block interleaver. Length-preserving, and the",
			" * input length must be a whole number of blocks. */",
			f"#define {macro(prefix, decl.name, 'BLOCK')} "
			f"{_number(decl, 'rows') * _number(decl, 'columns')}u",
			f"uint32_t {ident(prefix, decl.name, 'encode')}"
			"(const uint8_t *in, uint32_t len, uint8_t *out);",
			f"uint32_t {ident(prefix, decl.name, 'decode')}"
			"(const uint8_t *in, uint32_t len, uint8_t *out);",
		]

	if kernel.family is ast.KernelFamily.LINEAR:
		if _named_code(decl) not in DERIVED_LINEAR:
			return []
		return [
			"",
			f"/* `{decl.name}`: Hamming(7, 4) in standard form. One nibble in,",
			" * one seven-bit codeword out, and single-error correction on the",
			" * way back -- which is what a linear block code is for. */",
			f"uint8_t {ident(prefix, decl.name, 'encode')}(uint8_t nibble);",
			f"uint8_t {ident(prefix, decl.name, 'decode')}"
			"(uint8_t codeword, int *corrected);",
		]

	if kernel.family is ast.KernelFamily.SHIFT:
		return [
			"",
			f"/* `{decl.name}`: a scrambler. Length-preserving, and its own",
			" * inverse where the feedback comes from the input. */",
			f"uint32_t {ident(prefix, decl.name, 'encode')}"
			"(const uint8_t *in, uint32_t len, uint8_t *out);",
			f"uint32_t {ident(prefix, decl.name, 'decode')}"
			"(const uint8_t *in, uint32_t len, uint8_t *out);",
		]

	if kernel.family is ast.KernelFamily.STUFFING:
		if _named_code(decl) not in DERIVED_STUFFING:
			return []
		return [
			"",
			f"/* `{decl.name}`: stuffing. The output length depends on the",
			" * content, which is why interior addressing does not survive it",
			" * and why real protocols apply it only at the outermost layer. */",
			f"uint32_t {ident(prefix, decl.name, 'encode')}"
			"(const uint8_t *in, uint32_t len, uint8_t *out);",
			f"uint32_t {ident(prefix, decl.name, 'decode')}"
			"(const uint8_t *in, uint32_t len, uint8_t *out);",
		]

	return []


def _named_code(decl: ast.CodecDecl) -> str | None:
	kernel = decl.kernel
	assert kernel is not None
	value = kernel.argument("code")
	return value.name if isinstance(value, ast.NameRef) else None


# ---------------------------------------------------------------------------
# Permutation: block interleavers
# ---------------------------------------------------------------------------


def _permutation(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""Write the block in rows, read it back in columns.

	The classic block interleaver, and the reason `seekable = permuted` exists
	as a value distinct from `linear` and `none`: every byte is still
	reachable, so random access survives, but not in order, so a sequential
	prefetch does not.
	"""
	kernel = decl.kernel
	assert kernel is not None

	if kernel.argument("rows") is None:
		return None

	rows    = _number(decl, "rows")
	columns = _number(decl, "columns")
	block   = rows * columns
	name    = ident(prefix, decl.name)

	return [
		"",
		f"/* {decl.name}: a {rows} x {columns} block interleaver.",
		" *",
		" * Written in rows and read in columns, so a burst of adjacent bytes in",
		f" * the output lands {columns} apart in the input -- which is what puts a",
		" * burst error across codewords rather than inside one.",
		" */",
		f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		f"\tconst uint32_t block = {block}u;",
		"\tuint32_t at;",
		"",
		"\t/* Whole blocks only: a partial one has no defined permutation. */",
		"\tif (len % block != 0u) {",
		"\t\treturn 0;",
		"\t}",
		"",
		"\tfor (at = 0; at < len; at += block) {",
		"\t\tuint32_t row;",
		"\t\tuint32_t column;",
		"",
		f"\t\tfor (row = 0; row < {rows}u; row++) {{",
		f"\t\t\tfor (column = 0; column < {columns}u; column++) {{",
		f"\t\t\t\tout[at + column * {rows}u + row] =",
		f"\t\t\t\t\tin[at + row * {columns}u + column];",
		"\t\t\t}",
		"\t\t}",
		"\t}",
		"",
		"\treturn len;",
		"}",
		"",
		f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		f"\tconst uint32_t block = {block}u;",
		"\tuint32_t at;",
		"",
		"\tif (len % block != 0u) {",
		"\t\treturn 0;",
		"\t}",
		"",
		"\tfor (at = 0; at < len; at += block) {",
		"\t\tuint32_t row;",
		"\t\tuint32_t column;",
		"",
		f"\t\tfor (row = 0; row < {rows}u; row++) {{",
		f"\t\t\tfor (column = 0; column < {columns}u; column++) {{",
		f"\t\t\t\tout[at + row * {columns}u + column] =",
		f"\t\t\t\t\tin[at + column * {rows}u + row];",
		"\t\t\t}",
		"\t\t}",
		"\t}",
		"",
		"\treturn len;",
		"}",
	]


# ---------------------------------------------------------------------------
# Linear block: Hamming(7, 4)
# ---------------------------------------------------------------------------

# The standard systematic generator. Data bits d0..d3 occupy positions 0..3 of
# the codeword and the three parity bits follow, each covering the subset of
# the data bits its row names. Taken from the code's definition rather than
# from a table somebody transcribed.
_HAMMING_PARITY = (0b1101, 0b1011, 0b0111)


def _linear_block(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""Hamming(7, 4), with the syndrome table computed from the parity rows.

	Systematic, so the four data bits sit verbatim in the low positions and a
	reader that trusts the codeword can take them without decoding at all --
	which is exactly what the `systematic` property promises, and what makes it
	worth deriving rather than declaring.
	"""
	if _named_code(decl) not in DERIVED_LINEAR:
		return None

	name = ident(prefix, decl.name)

	# Syndrome -> the bit position it accuses, or 7 for "no error".
	syndrome = [7] * 8
	for position in range(7):
		codeword = 1 << position
		value = 0
		for row, mask in enumerate(_HAMMING_PARITY):
			bits = (codeword & 0xF) & mask
			parity = bin(bits).count("1") & 1
			parity ^= (codeword >> (4 + row)) & 1
			value |= parity << row
		syndrome[value] = position

	encode = []
	for nibble in range(16):
		word = nibble
		for row, mask in enumerate(_HAMMING_PARITY):
			word |= (bin(nibble & mask).count("1") & 1) << (4 + row)
		encode.append(word)

	return [
		"",
		f"/* {decl.name}: Hamming(7, 4), systematic.",
		" *",
		" * The four data bits sit verbatim in the low positions, which is what",
		" * `systematic` promises: a reader that trusts the codeword can take",
		" * them without decoding. The three parity bits correct any single-bit",
		" * error, which is what the syndrome table below is for.",
		" */",
		f"static const uint8_t {name}_encode_table[16] = {{",
		"\t" + ", ".join(f"0x{word:02X}u" for word in encode),
		"};",
		"",
		f"/* Syndrome to the bit it accuses; 7 means no error. */",
		f"static const uint8_t {name}_syndrome[8] = {{",
		"\t" + ", ".join(f"{position}u" for position in syndrome),
		"};",
		"",
		f"uint8_t {name}_encode(uint8_t nibble)",
		"{",
		f"\treturn {name}_encode_table[nibble & 0x0Fu];",
		"}",
		"",
		f"uint8_t {name}_decode(uint8_t codeword, int *corrected)",
		"{",
		"\tuint8_t value = (uint8_t)(codeword & 0x7Fu);",
		"\tuint8_t check = 0u;",
		"\tuint8_t row;",
		"",
		"\tfor (row = 0u; row < 3u; row++) {",
		"\t\tstatic const uint8_t masks[3] = { 0x0Du, 0x0Bu, 0x07u };",
		"\t\tuint8_t bits = (uint8_t)(value & masks[row]);",
		"\t\tuint8_t parity = 0u;",
		"",
		"\t\twhile (bits) {",
		"\t\t\tparity ^= (uint8_t)(bits & 1u);",
		"\t\t\tbits = (uint8_t)(bits >> 1);",
		"\t\t}",
		"\t\tparity ^= (uint8_t)((value >> (4u + row)) & 1u);",
		"\t\tcheck = (uint8_t)(check | (uint8_t)(parity << row));",
		"\t}",
		"",
		"\tif (check != 0u) {",
		f"\t\tuint8_t at = {name}_syndrome[check];",
		"",
		"\t\tif (at < 7u) {",
		"\t\t\tvalue = (uint8_t)(value ^ (uint8_t)(1u << at));",
		"\t\t\tif (corrected != NULL) {",
		"\t\t\t\t*corrected = 1;",
		"\t\t\t}",
		"\t\t}",
		"\t} else if (corrected != NULL) {",
		"\t\t*corrected = 0;",
		"\t}",
		"",
		"\treturn (uint8_t)(value & 0x0Fu);",
		"}",
	]


# ---------------------------------------------------------------------------
# Shift register: scramblers
# ---------------------------------------------------------------------------


def _shift_register(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""An LFSR, and where its feedback comes from decides everything.

	Additive: the register runs on its own state and the data is XORed with the
	keystream. Startable anywhere, its own inverse, and a corrupt bit spoils
	only itself.

	Multiplicative: the register is fed from the scrambled output, so a
	receiver synchronises itself without being told the state -- and pays for it
	with error propagation, because a corrupt bit stays in the register and
	spoils the next few too.

	Both are here because the pair is the point: the same family, the same taps
	and opposite properties, worked out from one word of the description.

	ANY WIDTH UP TO 64, not the three that happen to be C words. This read
	`width not in (8, 16, 32)` and returned None for everything else, which is
	the same gap `_width` above describes for CRCs and was left here when that
	one was closed: `kernels.py` validates only the feedback source, so a
	24-bit or 48-bit register is a schema situ accepts, derives a correct
	signature for, and then declines to implement -- with a note telling the
	author to write it themselves. Nothing about an LFSR needs the register to
	be a word. It needs an accumulator at least as wide, which `_accumulator`
	already picks, and a mask wherever a shift can carry a bit past the
	register's own end.

	The mask is emitted only where the word is wider than the register. At 8,
	16 and 32 the C type truncates at exactly the right bit, so the generated
	code for those three is unchanged to the byte -- which is what a reader of
	`git log` should be able to check rather than take on trust.
	"""
	kernel = decl.kernel
	assert kernel is not None

	taps  = _number(decl, "taps")
	width = _number(decl, "width", 16)
	seed  = _number(decl, "seed", (1 << width) - 1)

	if not taps or not 1 <= width <= WORD_WIDTHS[-1]:
		return None

	source = kernel.argument("feedback")
	additive = isinstance(source, ast.NameRef) and source.name == "input"
	complemented = kernel.flag("complement_feedback")
	name  = ident(prefix, decl.name)
	held  = _accumulator(width)
	word  = f"uint{held}_t"

	# Only the multiplicative path shifts *left*, so only it can push a bit
	# past the register's end; the additive path shifts right from a seed that
	# already fits, and never grows. Where the word is the register's own
	# width the type does the masking, and the expression is left exactly as
	# it was rather than gaining a mask that says what C already says -- the
	# three widths that worked emit the same bytes they always did.
	#
	# The mask does not change the ciphertext, and claiming it did would be
	# the easy overstatement: the feedback reads `state & taps`, and taps
	# name only bits below the width, so an accumulator carrying junk above
	# the register's end scrambles identically. Checked by stripping it from
	# a 24-bit encoder and diffing the output, which matched. What it buys is
	# a register that holds what it says it holds -- for anyone who reads the
	# state in a debugger, compares it against a reference implementation, or
	# widens this code later into somewhere the high bits are read.
	def shifted_in(bit: str) -> str:
		inner = f"({word})(state << 1) | {bit}"
		if held == width:
			return f"state = ({word})({inner});"
		return f"state = ({word})(({inner}) & ({word})0x{(1 << width) - 1:X}u);"

	# The one XOR that separates the two differential conventions. It is built
	# here rather than spelled twice because the encoder and the decoder must
	# complement or not complement together: a decoder that disagreed with its
	# encoder about this returns the complement of what was sent, which is
	# plausible bytes with nothing at run time to notice.
	feedback = (f"(uint8_t)({name}_parity(({word})(state & "
	            f"({word})0x{taps:X}u)))")
	if complemented:
		feedback = f"(uint8_t)({feedback} ^ 1u)"

	shared = [
		"",
		f"/* {decl.name}: a {width}-bit LFSR, taps 0x{taps:X}, seed 0x{seed:X}.",
		" *",
		(" * Additive: the register runs on its own state, so this is startable"
		 if additive else
		 " * Multiplicative: the register is fed from the scrambled output, so a"),
		(" * anywhere and is its own inverse, and a corrupt bit spoils only itself."
		 if additive else
		 " * receiver synchronises without being told the state -- and pays for it"),
		(" */" if additive else
		 " * with error propagation, which the signature reports."),
	]
	if complemented:
		shared += [
			" *",
			" * The feedback is complemented, so the bit that causes a"
			" transition is",
			" * the opposite one from the same register without it. That is"
			" the whole",
			" * of the difference between the two NRZI conventions, and a"
			" receiver",
			" * built on the wrong one returns the complement of what was"
			" sent.",
		]
	if not additive:
		shared.append(" */")

	if additive:
		body = [
			f"static {word} {name}_step({word} state)",
			"{",
			f"\t{word} bit = ({word})(state & 1u);",
			"",
			f"\tstate = ({word})(state >> 1);",
			"\tif (bit) {",
			f"\t\tstate = ({word})(state ^ ({word})0x{taps:X}u);",
			"\t}",
			"\treturn state;",
			"}",
			"",
			f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
			"{",
			f"\t{word} state = ({word})0x{seed:X}u;",
			"\tuint32_t at;",
			"\tuint32_t bit;",
			"",
			"\tfor (at = 0; at < len; at++) {",
			"\t\tuint8_t key = 0u;",
			"",
			"\t\tfor (bit = 0; bit < 8u; bit++) {",
			"\t\t\tkey = (uint8_t)(key | (uint8_t)((state & 1u) << bit));",
			f"\t\t\tstate = {name}_step(state);",
			"\t\t}",
			"\t\tout[at] = (uint8_t)(in[at] ^ key);",
			"\t}",
			"",
			"\treturn len;",
			"}",
			"",
			"/* Its own inverse: the keystream does not depend on the data. */",
			f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
			"{",
			f"\treturn {name}_encode(in, len, out);",
			"}",
		]
	else:
		body = [
			f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
			"{",
			f"\t{word} state = ({word})0x{seed:X}u;",
			"\tuint32_t at;",
			"\tuint32_t bit;",
			"",
			"\tfor (at = 0; at < len; at++) {",
			"\t\tuint8_t coded = 0u;",
			"",
			"\t\tfor (bit = 0; bit < 8u; bit++) {",
			"\t\t\tuint8_t plain = (uint8_t)((in[at] >> bit) & 1u);",
			f"\t\t\tuint8_t feedback = {feedback};",
			"\t\t\tuint8_t output = (uint8_t)(plain ^ feedback);",
			"",
			"\t\t\tcoded = (uint8_t)(coded | (uint8_t)(output << bit));",
			f"\t\t\t/* The scrambled bit goes into the register: that is what",
			"\t\t\t * makes a receiver self-synchronising. */",
			f"\t\t\t{shifted_in('output')}",
			"\t\t}",
			"\t\tout[at] = coded;",
			"\t}",
			"",
			"\treturn len;",
			"}",
			"",
			"/* Not its own inverse: the register is fed from the scrambled side,",
			" * so decoding shifts in what it received rather than what it made. */",
			f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
			"{",
			f"\t{word} state = ({word})0x{seed:X}u;",
			"\tuint32_t at;",
			"\tuint32_t bit;",
			"",
			"\tfor (at = 0; at < len; at++) {",
			"\t\tuint8_t plain = 0u;",
			"",
			"\t\tfor (bit = 0; bit < 8u; bit++) {",
			"\t\t\tuint8_t coded = (uint8_t)((in[at] >> bit) & 1u);",
			f"\t\t\tuint8_t feedback = {feedback};",
			"",
			"\t\t\tplain = (uint8_t)(plain | (uint8_t)"
			"((uint8_t)(coded ^ feedback) << bit));",
			f"\t\t\t{shifted_in('coded')}",
			"\t\t}",
			"\t\tout[at] = plain;",
			"\t}",
			"",
			"\treturn len;",
			"}",
		]
		body = [
			f"static uint8_t {name}_parity({word} value)",
			"{",
			"\tuint8_t bits = 0u;",
			"",
			"\twhile (value) {",
			"\t\tbits ^= (uint8_t)(value & 1u);",
			f"\t\tvalue = ({word})(value >> 1);",
			"\t}",
			"\treturn bits;",
			"}",
			"",
		] + body

	return shared + body


# ---------------------------------------------------------------------------
# Stuffing: COBS and HDLC
# ---------------------------------------------------------------------------


def _stuffing(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	code = _named_code(decl)
	if code not in DERIVED_STUFFING:
		return None
	if code == "cobs":
		return _cobs(decl, prefix)
	if code in BIT_STUFFING:
		return _bit_stuffing(decl, prefix, code)
	if code == "smtp_dot":
		return _smtp_dot(decl, prefix)
	if code in ESCAPE_STUFFING:
		return _escape_stuffing(decl, prefix, code)
	return None


def _escape_stuffing(decl: ast.CodecDecl, prefix: str, code: str) -> list[str]:
	"""An escape-stuffed byte code: SLIP and PPP's asynchronous framing.

	Both keep every payload byte and make the ones that would be mistaken for
	framing unmistakable by putting an escape in front. That is the opposite
	trade from COBS, which removes the delimiter value from the body entirely
	and pays a pointer per group for it; here the payload is untouched and the
	worst case is two bytes out for one in, when every byte needs escaping.

	The decoder differs between the two and the comments say why: PPP's
	escape is defined as a transformation, so reversing it needs no table and
	covers escapes this generator never enumerated.
	"""
	title, delim, esc, xor, pairs = ESCAPE_STUFFING[code]
	name = ident(prefix, decl.name)

	lines = [
		"",
		f"/* {decl.name}: {title}.",
		" *",
		f" * A payload byte equal to the delimiter (0x{delim:02X}) or to the"
		f" escape",
		f" * (0x{esc:02X}) is sent as the escape followed by a substitute, so"
		" neither",
		" * can be mistaken for the end of a frame. Every other byte is sent as",
		" * it stands.",
		" *",
		" * `out` needs 2 * len + 1 bytes: twice the payload if every byte has",
		" * to be escaped, plus the trailing delimiter. Returns the length",
		" * written.",
		" */",
		f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"\tuint32_t read;",
		"\tuint32_t written = 0;",
		"",
		"\tfor (read = 0; read < len; read++) {",
		"\t\tswitch (in[read]) {",
	]

	for literal, escaped in pairs:
		lines += [
			f"\t\tcase 0x{literal:02X}u:",
			f"\t\t\tout[written++] = (uint8_t)0x{esc:02X}u;",
			f"\t\t\tout[written++] = (uint8_t)0x{escaped:02X}u;",
			"\t\t\tbreak;",
		]

	lines += [
		"\t\tdefault:",
		"\t\t\tout[written++] = in[read];",
		"\t\t\tbreak;",
		"\t\t}",
		"\t}",
		"",
		f"\tout[written++] = (uint8_t)0x{delim:02X}u;\t/* the frame"
		" delimiter */",
		"\treturn written;",
		"}",
		"",
	]

	if xor is None:
		undo = [
			"\t\tswitch (in[read++]) {",
			*[line for literal, escaped in pairs for line in (
				f"\t\tcase 0x{escaped:02X}u:",
				f"\t\t\tout[written++] = (uint8_t)0x{literal:02X}u;",
				"\t\t\tbreak;")],
			"\t\tdefault:",
			"\t\t\t/* An escape this code does not define. Refusing beats",
			"\t\t\t * inventing a byte: the frame is not what it claims. */",
			"\t\t\treturn 0;",
			"\t\t}",
		]
		note = [
			" * The substitutions are a table rather than a transformation --"
			f" 0x{pairs[0][0]:02X}",
			f" * becomes 0x{pairs[0][1]:02X} and 0x{pairs[1][0]:02X} becomes"
			f" 0x{pairs[1][1]:02X}, which is no single operation on either --",
			" * so an escape sequence outside it is refused rather than"
			" guessed.",
		]
	else:
		undo = [
			f"\t\t/* RFC 1662: an escaped byte is the original exclusive-ored",
			f"\t\t * with 0x{xor:02X}, so undoing it is the same operation"
			" again. */",
			f"\t\tout[written++] = (uint8_t)(in[read++] ^ 0x{xor:02X}u);",
		]
		note = [
			f" * The escape is defined as a transformation -- exclusive-or"
			f" with 0x{xor:02X} --",
			" * rather than as a table, so this reverses any escaped byte and"
			" not",
			" * only the two that must always be escaped. That matters: a peer",
			" * whose ACCM asks it to escape control characters sends escapes",
			" * this generator never enumerated, and they decode correctly"
			" here.",
			" *",
			" * Encoding escapes only the two that are mandatory, which is what"
			" an",
			" * ACCM of zero asks for. A link that negotiated a different one"
			" is",
			" * asking the sender for escapes this does not add.",
		]

	lines += [
		"/* The inverse, stopping at the delimiter.",
		" *",
		*note,
		" */",
		f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"\tuint32_t read = 0;",
		"\tuint32_t written = 0;",
		"",
		"\twhile (read < len) {",
		"\t\tconst uint8_t byte = in[read++];",
		"",
		f"\t\tif (byte == (uint8_t)0x{delim:02X}u) {{",
		"\t\t\tbreak;\t\t/* the delimiter ends the frame */",
		"\t\t}",
		f"\t\tif (byte != (uint8_t)0x{esc:02X}u) {{",
		"\t\t\tout[written++] = byte;",
		"\t\t\tcontinue;",
		"\t\t}",
		"\t\tif (read >= len) {",
		"\t\t\treturn 0;\t/* truncated: an escape ended the input */",
		"\t\t}",
		*undo,
		"\t}",
		"",
		"\treturn written;",
		"}",
	]
	return lines


def _smtp_dot(decl: ast.CodecDecl, prefix: str) -> list[str]:
	"""SMTP dot-stuffing, RFC 5321 section 4.5.2.

	A line beginning with a period is sent with two, and the receiver removes
	one. That is what makes `CRLF . CRLF` an unambiguous terminator: a body
	line of a single dot arrives as two dots, so the only bare dot on its own
	line is the one that ends the body.

	`unit = stream` rather than `byte`, and the schema says why: the trigger is
	"the start of a line", which cannot be evaluated from one byte without
	knowing what preceded it. Both directions here carry that state in a flag
	rather than looking backwards, so neither needs the buffer to be a whole
	message.

	The terminator is not written or consumed here. The region is delimited
	*and* coded, and the scan runs on the encoded bytes -- which is the order
	the stuffing exists to make safe (13.6).
	"""
	name = ident(prefix, decl.name)

	return [
		"",
		f"/* {decl.name}: SMTP dot-stuffing (RFC 5321 section 4.5.2).",
		" *",
		" * A line beginning with `.` is sent with two. The receiver removes"
		" one,",
		" * which is what leaves `CRLF . CRLF` unambiguous as a terminator.",
		" *",
		" * `out` needs len + the number of dot-led lines, which the declared",
		" * `ratio_bounded(4, 3)` bounds at one added byte per three: a body of",
		" * nothing but `.CRLF` is the worst case. Returns the length written.",
		" */",
		f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"	uint32_t read;",
		"	uint32_t written = 0;",
		"	int at_line_start = 1;	/* the body starts at the start of a line */",
		"",
		"	for (read = 0; read < len; read++) {",
		"		if (at_line_start && in[read] == (uint8_t)'.') {",
		"			out[written++] = (uint8_t)'.';",
		"		}",
		"		out[written++] = in[read];",
		"",
		"		/* A line ends at LF. Testing for it rather than for CRLF is what",
		"		 * keeps this a stream: a CR at the end of one call and an LF at",
		"		 * the start of the next would otherwise be missed. */",
		"		at_line_start = in[read] == (uint8_t)'\\n';",
		"	}",
		"",
		"	return written;",
		"}",
		"",
		f"/* The inverse. A line of `..` becomes `.`; a line of one `.` is the",
		" * terminator and never reaches here, because the scan that framed the",
		" * region stopped at it. */",
		f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"	uint32_t read;",
		"	uint32_t written = 0;",
		"	int at_line_start = 1;",
		"",
		"	for (read = 0; read < len; read++) {",
		"		if (at_line_start && in[read] == (uint8_t)'.') {",
		"			/* Drop the added one and keep whatever follows, which for a",
		"			 * line that was `.` alone is the CRLF. */",
		"			at_line_start = 0;",
		"			continue;",
		"		}",
		"		out[written++] = in[read];",
		"		at_line_start = in[read] == (uint8_t)'\\n';",
		"	}",
		"",
		"	return written;",
		"}",
	]


def _cobs(decl: ast.CodecDecl, prefix: str) -> list[str]:
	"""Consistent Overhead Byte Stuffing, as Cheshire and Baker defined it.

	Every zero byte is removed from the payload and replaced by a pointer to
	the next one, so a zero can be used as an unambiguous frame delimiter. The
	overhead is one byte per 254, which is where `ratio_bounded(255, 254)`
	comes from -- and the reason it is *bounded* rather than exact is that how
	many bytes it adds depends entirely on the content.
	"""
	name = ident(prefix, decl.name)

	return [
		"",
		f"/* {decl.name}: COBS (Cheshire and Baker).",
		" *",
		" * A zero byte becomes a pointer to the next one, so no zero survives in",
		" * the body and a zero can delimit the frame. The output length depends",
		" * on the content, which is exactly why interior addressing does not",
		" * survive this and why it belongs at the outermost layer.",
		" *",
		" * `out` needs len + len/254 + 2 bytes. Returns the length written.",
		" */",
		f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"\tuint32_t read = 0;",
		"\tuint32_t code_at = 0;",
		"\tuint32_t written = 1;",
		"\tuint8_t  code = 1;",
		"",
		"\tfor (read = 0; read < len; read++) {",
		"\t\tif (in[read] != 0u) {",
		"\t\t\tout[written++] = in[read];",
		"\t\t\tcode++;",
		"\t\t\t/* A full group is flushed only when more input follows. At",
		"\t\t\t * the very end there is nothing for a new group to hold, and",
		"\t\t\t * opening one would spend a second overhead byte -- which is",
		"\t\t\t * the one thing COBS promises not to do. */",
		"\t\t\tif (code != 0xFFu || read + 1u >= len) {",
		"\t\t\t\tcontinue;",
		"\t\t\t}",
		"\t\t}",
		"",
		"\t\tout[code_at] = code;",
		"\t\tcode_at = written++;",
		"\t\tcode = 1;",
		"\t}",
		"",
		"\tout[code_at] = code;",
		"\tout[written++] = 0u;\t\t/* the delimiter */",
		"\treturn written;",
		"}",
		"",
		f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"\tuint32_t read = 0;",
		"\tuint32_t written = 0;",
		"",
		"\twhile (read < len) {",
		"\t\tuint8_t code = in[read];",
		"\t\tuint8_t at;",
		"",
		"\t\tif (code == 0u) {",
		"\t\t\tbreak;\t\t/* the delimiter ends the frame */",
		"\t\t}",
		"\t\tread++;",
		"",
		"\t\tfor (at = 1u; at < code; at++) {",
		"\t\t\tif (read >= len) {",
		"\t\t\t\treturn 0;\t/* truncated: a code ran past the end */",
		"\t\t\t}",
		"\t\t\tout[written++] = in[read++];",
		"\t\t}",
		"",
		"\t\tif (code != 0xFFu && read < len && in[read] != 0u) {",
		"\t\t\tout[written++] = 0u;",
		"\t\t}",
		"\t}",
		"",
		"\treturn written;",
		"}",
	]


#: Bit-stuffing codes: the run of ones that triggers an inserted zero, what
#: the insertion is for, and what a run one longer means to a decoder.
#:
#: Two codes rather than one with a parameter, and they are named apart for
#: the reason 26.140 names the two NRZIs apart: a decoder built on the wrong
#: run length returns bytes that are wrong from the first stuffed bit onward,
#: with nothing at run time to notice. What they share is the algorithm, so
#: the generator is one function and the run is its argument -- the opposite
#: trade from SLIP and PPP, which share a name for their shape and differ in
#: what they actually do (decision 0017's third amendment).
BIT_STUFFING: dict[str, tuple[int, tuple[str, ...], str]] = {
	"hdlc": (5,
	         ("After five consecutive ones a zero is inserted, so the flag "
	          "sequence",
	          "cannot appear inside a frame. Six bits out for five in, worst "
	          "case,",
	          "and where a frame lands in that range depends on its content."),
	         "six ones is a flag, not data"),
	"usb":  (6,
	         ("After six consecutive ones a zero is inserted, so the line "
	          "cannot",
	          "hold still: this goes out through NRZI, which transitions on a "
	          "zero,",
	          "so an unbroken run of ones would leave a receiver nothing to",
	          "recover its clock from. USB 2.0 section 7.1.9. Seven bits out "
	          "for",
	          "six in, worst case."),
	         "seven ones cannot be sent"),
}


def _bit_stuffing(decl: ast.CodecDecl, prefix: str, code: str) -> list[str]:
	"""Insert a zero after a run of ones: HDLC's five, USB's six.

	One algorithm and one constant. The worst case is `run + 1` bits out for
	`run` in, and how close to it any particular frame gets depends on the
	data -- which is `ratio_bounded` and why `kernels.STUFFING_BOUNDS` holds
	the pair rather than the schema being trusted for it.
	"""
	name = ident(prefix, decl.name)
	run, purpose, overrun = BIT_STUFFING[code]

	return [
		"",
		f"/* {decl.name}: {code.upper()} bit stuffing.",
		" *",
		*(f" * {line}" for line in purpose),
		" *",
		f" * Lengths are in bits. `out` needs len + len / {run} + 1 bits.",
		" */",
		f"uint32_t {name}_encode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"\tuint32_t at;",
		"\tuint32_t written = 0;",
		"\tuint32_t ones = 0;",
		"",
		"\tfor (at = 0; at < len; at++) {",
		"\t\tuint32_t bit = (uint32_t)situ_bits_get_msb(in, at, 1u);",
		"",
		"\t\tsitu_bits_set_msb(out, written++, 1u, bit);",
		"",
		"\t\tif (bit) {",
		"\t\t\tones++;",
		f"\t\t\tif (ones == {run}u) {{",
		"\t\t\t\tsitu_bits_set_msb(out, written++, 1u, 0u);",
		"\t\t\t\tones = 0;",
		"\t\t\t}",
		"\t\t} else {",
		"\t\t\tones = 0;",
		"\t\t}",
		"\t}",
		"",
		"\treturn written;",
		"}",
		"",
		f"uint32_t {name}_decode(const uint8_t *in, uint32_t len, uint8_t *out)",
		"{",
		"\tuint32_t at;",
		"\tuint32_t written = 0;",
		"\tuint32_t ones = 0;",
		"",
		"\tfor (at = 0; at < len; at++) {",
		"\t\tuint32_t bit = (uint32_t)situ_bits_get_msb(in, at, 1u);",
		"",
		f"\t\tif (ones == {run}u) {{",
		"\t\t\t/* A stuffed zero, which the encoder put there. */",
		"\t\t\tones = 0;",
		"\t\t\tif (bit) {",
		f"\t\t\t\treturn 0;\t/* {overrun} */",
		"\t\t\t}",
		"\t\t\tcontinue;",
		"\t\t}",
		"",
		"\t\tsitu_bits_set_msb(out, written++, 1u, bit);",
		"\t\tones = bit ? ones + 1u : 0u;",
		"\t}",
		"",
		"\treturn written;",
		"}",
	]


# ---------------------------------------------------------------------------
# Reed-Solomon over GF(2^m)
#
# Section 26.12 calls this the largest single item in the phase and it is: the
# encoder is a polynomial division like a CRC's, and the decoder is four
# separate algorithms in a row. What is written below is the standard
# construction -- syndromes, Berlekamp-Massey, Chien search, Forney -- rather
# than anything novel, because a novel error-correcting code is the last thing
# anybody wants.
#
# The tables are computed here rather than copied. A transcribed log table is
# exactly the kind of artefact that is wrong in one entry and produces a codec
# that works on most inputs.
# ---------------------------------------------------------------------------


def _gf_tables(field: int, primitive: int) -> tuple[list[int], list[int]]:
	"""Antilog and log for GF(2^m), generated from the primitive polynomial.

	The antilog table is doubled so a product of two logs can be looked up
	without a modulo, which is the usual trick and the reason the generated
	multiply is two loads and an add.
	"""
	size   = field - 1
	exp    = [0] * (2 * field)
	log    = [0] * field
	value  = 1

	for power in range(size):
		exp[power] = value
		log[value] = power
		value <<= 1
		if value & field:
			value ^= primitive

	for power in range(size, 2 * size):
		exp[power] = exp[power - size]

	return exp, log


def _reed_solomon(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	field = _number(decl, "field")
	n     = _number(decl, "n")
	k     = _number(decl, "k")

	if field != 256 or not n or not k:
		return None

	primitive  = _number(decl, "primitive", 0x11D)
	first_root = _number(decl, "first_root", 0)
	nroots     = n - k
	size       = field - 1

	exp, log = _gf_tables(field, primitive)

	# Constant term first. The division loop below indexes from the low end,
	# which is the standard formulation and the one every reference uses;
	# multiplying the roots out produces it leading-first.
	generator = list(reversed(
		_rs_generator_coefficients(nroots, first_root, exp, log, size)))
	name = ident(prefix, decl.name)

	return [
		"",
		f"/* {decl.name}: Reed-Solomon({n}, {k}) over GF({field}).",
		" *",
		f" * {nroots} parity symbols, correcting up to {nroots // 2} symbol errors",
		" * anywhere in the block. Systematic: the message sits verbatim ahead of",
		" * the parity, so a reader that trusts the block takes it with no decode",
		" * at all.",
		" *",
		f" * Primitive polynomial 0x{primitive:X}, first root alpha^{first_root}.",
		" * Every table below is computed from those two numbers rather than",
		" * copied, so a code nobody has standardised works as well as one that",
		" * has -- and no transcription can be wrong in one entry.",
		" */",
		f"#define {macro(prefix, decl.name, 'BLOCK')}  {n}u",
		f"#define {macro(prefix, decl.name, 'DATA')}   {k}u",
		f"#define {macro(prefix, decl.name, 'PARITY')} {nroots}u",
		"",
		*_gf_arithmetic(name, exp, log, size),
		*_rs_encoder(name, generator, nroots, k),
		*_rs_decoder(name, n, nroots, first_root, size),
	]


def _rs_generator_coefficients(nroots: int, first_root: int, exp: list[int],
		log: list[int], size: int) -> list[int]:
	"""Multiply out (x - alpha^(first_root + i)) for each root."""
	poly = [1]

	for root in range(nroots):
		alpha = exp[(first_root + root) % size]
		shifted = poly + [0]

		for at in range(len(poly)):
			if poly[at] and alpha:
				shifted[at + 1] ^= exp[(log[poly[at]] + log[alpha]) % size]

		poly = shifted

	return poly


def _gf_arithmetic(name: str, exp: list[int], log: list[int],
		size: int) -> list[str]:
	rows = []
	for start in range(0, len(exp), 16):
		rows.append("\t" + ", ".join(f"0x{value:02X}u"
		                             for value in exp[start:start + 16]) + ",")

	log_rows = []
	for start in range(0, len(log), 16):
		log_rows.append("\t" + ", ".join(f"0x{value:02X}u"
		                                 for value in log[start:start + 16]) + ",")

	return [
		f"/* Antilog, doubled so a product of logs needs no modulo. */",
		f"static const uint8_t {name}_exp[{len(exp)}] = {{",
		*rows,
		"};",
		"",
		f"static const uint8_t {name}_log[{len(log)}] = {{",
		*log_rows,
		"};",
		"",
		f"static uint8_t {name}_mul(uint8_t a, uint8_t b)",
		"{",
		"\tif (a == 0u || b == 0u) {",
		"\t\treturn 0u;",
		"\t}",
		f"\treturn {name}_exp[(uint32_t){name}_log[a] + (uint32_t){name}_log[b]];",
		"}",
		"",
		f"static uint8_t {name}_inv(uint8_t a)",
		"{",
		f"\treturn {name}_exp[{size}u - (uint32_t){name}_log[a]];",
		"}",
		"",
		f"/* alpha raised to a power, with the exponent reduced first. */",
		f"static uint8_t {name}_pow(uint32_t power)",
		"{",
		f"\treturn {name}_exp[power % {size}u];",
		"}",
		"",
	]


def _rs_encoder(name: str, generator: list[int], nroots: int,
		k: int) -> list[str]:
	rows = "\t" + ", ".join(f"0x{value:02X}u" for value in generator) + ","

	return [
		"/* The generator polynomial, multiplied out from its roots. */",
		f"static const uint8_t {name}_generator[{len(generator)}] = {{",
		rows,
		"};",
		"",
		"/* Systematic encode: the message is left alone and the parity is the",
		" * remainder of dividing it, shifted, by the generator. */",
		f"uint32_t {name}_encode(const uint8_t *data, uint32_t len, uint8_t *parity)",
		"{",
		f"\tuint32_t at;",
		f"\tuint32_t j;",
		"",
		f"\tif (len != {k}u) {{",
		"\t\treturn 0;",
		"\t}",
		"",
		f"\tfor (at = 0; at < {nroots}u; at++) {{",
		"\t\tparity[at] = 0u;",
		"\t}",
		"",
		"\tfor (at = 0; at < len; at++) {",
		"\t\tuint8_t feedback = (uint8_t)(data[at] ^ parity[0]);",
		"",
		f"\t\tfor (j = 0; j + 1u < {nroots}u; j++) {{",
		"\t\t\tparity[j] = (uint8_t)(parity[j + 1] ^",
		f"\t\t\t\t{name}_mul(feedback, {name}_generator[{nroots}u - 1u - j]));",
		"\t\t}",
		f"\t\tparity[{nroots}u - 1u] = {name}_mul(feedback, "
		f"{name}_generator[0]);",
		"\t}",
		"",
		f"\treturn {nroots}u;",
		"}",
		"",
	]


def _rs_decoder(name: str, n: int, nroots: int, first_root: int,
		size: int) -> list[str]:
	"""The standard four steps, in the standard order.

	Syndromes say whether anything is wrong; Berlekamp-Massey finds the error
	locator polynomial from them; a Chien search finds its roots, which are the
	error positions; Forney gives the magnitude at each. Nothing here is novel,
	deliberately: a novel error-correcting code is the last thing anybody
	wants, and the value situ adds is that the properties in the capability map
	were derived from the same description as this code.
	"""
	half = nroots // 2

	return [
		"/* Decode in place. Returns the number of symbols corrected, or -1 if",
		" * the block holds more errors than the code can correct -- which it",
		" * detects rather than guessing at, because a miscorrection is worse",
		" * than a refusal. */",
		f"int {name}_decode(uint8_t *block, uint32_t len)",
		"{",
		f"\tuint8_t syndrome[{nroots}u];",
		f"\tuint8_t lambda[{half + 1}u];",
		f"\tuint8_t previous[{half + 1}u];",
		f"\tuint8_t scratch[{half + 1}u];",
		f"\tuint8_t omega[{nroots}u];",
		f"\tuint8_t position[{half}u];",
		"\tuint32_t at;",
		"\tuint32_t j;",
		"\tuint32_t found = 0;",
		"\tuint32_t degree = 0;",
		"\tuint32_t shift = 1;",
		"\tuint8_t  discrepancy_last = 1;",
		"\tint      wrong = 0;",
		"",
		f"\tif (len != {n}u) {{",
		"\t\treturn -1;",
		"\t}",
		"",
		"\t/* 1. Syndromes: the block evaluated at each root. All zero means",
		"\t *    nothing is wrong, which is the common case and the cheap one. */",
		f"\tfor (at = 0; at < {nroots}u; at++) {{",
		"\t\tuint8_t value = 0u;",
		f"\t\tuint8_t root = {name}_pow({first_root}u + at);",
		"",
		"\t\tfor (j = 0; j < len; j++) {",
		f"\t\t\tvalue = (uint8_t)(block[j] ^ {name}_mul(value, root));",
		"\t\t}",
		"\t\tsyndrome[at] = value;",
		"\t\tif (value) {",
		"\t\t\twrong = 1;",
		"\t\t}",
		"\t}",
		"",
		"\tif (!wrong) {",
		"\t\treturn 0;",
		"\t}",
		"",
		"\t/* 2. Berlekamp-Massey: the shortest register that makes the",
		"\t *    syndromes, whose connection polynomial locates the errors. */",
		f"\tfor (at = 0; at <= {half}u; at++) {{",
		"\t\tlambda[at] = 0u;",
		"\t\tprevious[at] = 0u;",
		"\t}",
		"\tlambda[0] = 1u;",
		"\tprevious[0] = 1u;",
		"",
		f"\tfor (at = 0; at < {nroots}u; at++) {{",
		"\t\tuint8_t discrepancy = syndrome[at];",
		"",
		"\t\tfor (j = 1; j <= degree; j++) {",
		"\t\t\tdiscrepancy = (uint8_t)(discrepancy ^",
		f"\t\t\t\t{name}_mul(lambda[j], syndrome[at - j]));",
		"\t\t}",
		"",
		"\t\tif (discrepancy == 0u) {",
		"\t\t\tshift++;",
		"\t\t\tcontinue;",
		"\t\t}",
		"",
		f"\t\tfor (j = 0; j <= {half}u; j++) {{",
		"\t\t\tscratch[j] = lambda[j];",
		"\t\t}",
		f"\t\tfor (j = shift; j <= {half}u; j++) {{",
		"\t\t\tlambda[j] = (uint8_t)(lambda[j] ^",
		f"\t\t\t\t{name}_mul({name}_mul(discrepancy, "
		f"{name}_inv(discrepancy_last)),",
		"\t\t\t\t             previous[j - shift]));",
		"\t\t}",
		"",
		"\t\tif (2u * degree <= at) {",
		"\t\t\tdegree = at + 1u - degree;",
		f"\t\t\tfor (j = 0; j <= {half}u; j++) {{",
		"\t\t\t\tprevious[j] = scratch[j];",
		"\t\t\t}",
		"\t\t\tdiscrepancy_last = discrepancy;",
		"\t\t\tshift = 1;",
		"\t\t} else {",
		"\t\t\tshift++;",
		"\t\t}",
		"\t}",
		"",
		f"\tif (degree > {half}u || degree == 0u) {{",
		"\t\treturn -1;\t\t/* more errors than the code can locate */",
		"\t}",
		"",
		"\t/* 3. Chien search: every position whose evaluation vanishes is an",
		"\t *    error. Exhaustive over the block, which is what makes the cost",
		"\t *    of decoding proportional to the block and not to the errors. */",
		"\tfor (at = 0; at < len; at++) {",
		"\t\tuint8_t value = 1u;\t/* lambda[0] is always 1 */",
		f"\t\tuint8_t x = {name}_pow({size}u - ((len - 1u - at) % {size}u));",
		"\t\tuint8_t term = 1u;",
		"",
		"\t\tfor (j = 1; j <= degree; j++) {",
		f"\t\t\tterm = {name}_mul(term, x);",
		f"\t\t\tvalue = (uint8_t)(value ^ {name}_mul(lambda[j], term));",
		"\t\t}",
		"",
		"\t\tif (value == 0u) {",
		"\t\t\tif (found >= degree) {",
		"\t\t\t\treturn -1;",
		"\t\t\t}",
		"\t\t\tposition[found++] = (uint8_t)at;",
		"\t\t}",
		"\t}",
		"",
		"\tif (found != degree) {",
		"\t\treturn -1;\t\t/* the locator has roots outside the block */",
		"\t}",
		"",
		"\t/* 4. Forney: the magnitude at each located position, from the error",
		"\t *    evaluator over the formal derivative of the locator. */",
		f"\tfor (at = 0; at < {nroots}u; at++) {{",
		"\t\tuint8_t value = 0u;",
		"",
		"\t\tfor (j = 0; j <= at && j <= degree; j++) {",
		"\t\t\tvalue = (uint8_t)(value ^",
		f"\t\t\t\t{name}_mul(lambda[j], syndrome[at - j]));",
		"\t\t}",
		"\t\tomega[at] = value;",
		"\t}",
		"",
		"\tfor (at = 0; at < found; at++) {",
		f"\t\tuint8_t x = {name}_pow((len - 1u - position[at]) % {size}u);",
		f"\t\tuint8_t inverse = {name}_inv(x);",
		"\t\tuint8_t top = 0u;",
		"\t\tuint8_t bottom = 0u;",
		"\t\tuint8_t term = 1u;",
		"",
		f"\t\tfor (j = 0; j < {nroots}u; j++) {{",
		f"\t\t\ttop = (uint8_t)(top ^ {name}_mul(omega[j], term));",
		f"\t\t\tterm = {name}_mul(term, inverse);",
		"\t\t}",
		"",
		"\t\t/* The formal derivative over GF(2) keeps only the odd terms. */",
		"\t\tterm = 1u;",
		"\t\tfor (j = 1; j <= degree; j += 2u) {",
		f"\t\t\tbottom = (uint8_t)(bottom ^ {name}_mul(lambda[j], term));",
		f"\t\t\tterm = {name}_mul({name}_mul(term, inverse), inverse);",
		"\t\t}",
		"",
		"\t\tif (bottom == 0u) {",
		"\t\t\treturn -1;",
		"\t\t}",
		"",
		"\t\t{",
		f"\t\t\tuint8_t magnitude = {name}_mul(top, {name}_inv(bottom));",
		"",
		f"\t\t\tif ({first_root} == 0) {{",
		f"\t\t\t\tmagnitude = {name}_mul(magnitude, x);",
		"\t\t\t}",
		"\t\t\tblock[position[at]] = (uint8_t)(block[position[at]] ^ magnitude);",
		"\t\t}",
		"\t}",
		"",
		"\treturn (int)found;",
		"}",
	]
