"""Shared scaffolding for the rung-6 driver artifacts (decision 0033).

A driver adds `<name>_<facility>.c` and its header over `--layer drive` and
pumps the state machine through the `situ_io_t` submit vtable, owning the
socket, the clock and the timer arithmetic. The readiness and no-multiplexer
drivers -- `epoll`, `poll`, `blocking` -- differ only in how the loop waits
for the deadline `step` returns; everything around that loop is identical, so
it lives here and each driver module supplies just its `_run` plus the few
strings that name it.

`io_uring` is completion rather than readiness -- its context carries a ring,
not a bare fd, and it has a setup/teardown pair -- so it uses only
`reply_view` from here and carries its own header, submit and source. That
split is deliberate: this module holds what the fd-based drivers genuinely
share, not a lowest common denominator forced over the one that is different.
"""

from __future__ import annotations

from typing import Callable

from situc import ast
from situc.codegen.c.drive import driven
from situc.codegen.c.names import ident, macro
from situc.resolve import ResolvedSchema
from situc import __version__

__all__ = ["reply_view", "submit_and_clock", "header", "source", "generate"]

#: A driver's `_run`: the event loop for one relation, the one thing that
#: differs between facilities.
RunFn = Callable[[ast.Relation, ResolvedSchema, str], "list[str]"]


def reply_view(relation: ast.Relation, resolved: ResolvedSchema,
		prefix: str) -> tuple[str, bool]:
	"""The reply message's view accessor, and whether it is the fixed form.

	`on_message` reads the conversation key off a view of the reply, so the
	loop acquires one over the received datagram first. A fixed struct knows
	its own extent and takes `(msg, offset, out)`; a frame takes the received
	length too (`emit.py:_view_acquisition`).
	"""
	reply = relation.params[1]
	struct = resolved.structs[reply.type_name]
	return ident(prefix, reply.type_name, "view"), struct.layout.is_fixed_size


def submit_and_clock(prefix: str, facility: str) -> list[str]:
	"""The send-only submit vtable and the clock -- one copy, since neither
	depends on which relation is driven. The submit ctx is a bare `int fd`;
	the completion drivers carry more and write their own."""
	submit = ident(prefix, facility, "submit")
	return [
		"/* Where the bytes go: the submit ctx holds the connected datagram",
		" * fd. A datagram send is all-or-nothing, so a full send buffer",
		" * (EAGAIN) is a dropped datagram the retry budget recovers, and an",
		" * interrupt (EINTR) is retried; only a hard error propagates. */",
		f"static situ_err_t {submit}(void *ctx, const uint8_t *data,"
		" uint32_t len)",
		"{",
		f"\t{ident(prefix, facility, 'ctx')}_t *sock = ctx;",
		"\tfor (;;) {",
		"\t\tconst ssize_t sent = send(sock->fd, data, len, 0);",
		"\t\tif (sent >= 0) {",
		"\t\t\treturn SITU_OK;\t/* a datagram is all-or-nothing */",
		"\t\t}",
		"\t\tif (errno == EINTR) {",
		"\t\t\tcontinue;",
		"\t\t}",
		"\t\tif (errno == EAGAIN || errno == EWOULDBLOCK) {",
		"\t\t\treturn SITU_OK;\t/* buffer full: let retransmission recover it */",
		"\t\t}",
		"\t\treturn SITU_ERR_BOUNDS;\t/* a hard error */",
		"\t}",
		"}",
		"",
		f"situ_io_t {ident(prefix, facility, 'io')}"
		f"({ident(prefix, facility, 'ctx')}_t *ctx)",
		"{",
		"\tsitu_io_t io;",
		f"\tio.submit = {submit};",
		"\tio.ctx    = ctx;",
		"\treturn io;",
		"}",
		"",
		"/* The clock, read only here and never by the state machine. The value",
		" * wraps at 2^32 ms and that is fine: every deadline comparison is a",
		" * wrap-safe signed difference, here and inside `step`. */",
		f"static uint32_t {ident(prefix, facility, 'now_ms')}(void)",
		"{",
		"\tstruct timespec ts;",
		"\t(void)clock_gettime(CLOCK_MONOTONIC, &ts);",
		"\tconst uint64_t ms = (uint64_t)ts.tv_sec * 1000u",
		"\t                  + (uint64_t)ts.tv_nsec / 1000000u;",
		"\treturn (uint32_t)ms;",
		"}",
		"",
	]


def header(basename: str, prefix: str,
		ready: list[tuple[ast.Relation, tuple[int, int]]],
		facility: str, doc: list[str]) -> str:
	"""The `<name>_<facility>.h`: the `int fd` submit context, the vtable
	accessor, the callback types and a run prototype per relation. `doc` is
	the driver's own comment body, the one part that is not boilerplate."""
	guard = macro(prefix, basename, f"{facility.upper()}_H")
	lines = [
		f"/* Generated by situc {__version__} from {basename}.situ -- do not"
		" edit.",
		" *",
		*doc,
		" */",
		"",
		f"#ifndef {guard}",
		f"#define {guard}",
		"",
		f"#include \"{basename}_drive.h\"",
		"",
		"#ifdef __cplusplus",
		"extern \"C\" {",
		"#endif",
		"",
		"/* The submit context: a connected datagram fd. Build the vtable with",
		" * the accessor below and hand it to the drive machine's `_init`. */",
		"typedef struct {",
		"\tint fd;",
		f"}} {ident(prefix, facility, 'ctx')}_t;",
		"",
		f"situ_io_t {ident(prefix, facility, 'io')}"
		f"({ident(prefix, facility, 'ctx')}_t *ctx);",
		"",
		"/* A correlated reply, and a batch of exchanges that ran out of",
		" * retries. Either callback may be NULL; `user` is threaded through. */",
		f"typedef void (*{ident(prefix, facility, 'reply')}_fn)"
		"(uint32_t id, void *user);",
		f"typedef void (*{ident(prefix, facility, 'expired')}_fn)"
		"(uint32_t count, void *user);",
		"",
	]
	for relation, _policy in ready:
		drive = ident(prefix, "drive", relation.name)
		run   = ident(prefix, facility, relation.name, "run")
		lines += [
			f"situ_err_t {run}(int fd, {drive}_t *drive,",
			f"                 {ident(prefix, facility, 'reply')}_fn on_reply,",
			f"                 {ident(prefix, facility, 'expired')}_fn"
			" on_expired,",
			"                 void *user);",
			"",
		]
	lines += [
		"#ifdef __cplusplus",
		"}",
		"#endif",
		"",
		f"#endif /* {guard} */",
	]
	return "\n".join(lines) + "\n"


def source(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str, ready: list[tuple[ast.Relation, tuple[int, int]]],
		facility: str, doc: list[str], includes: list[str],
		run: RunFn) -> str:
	"""The `<name>_<facility>.c`: the driver's comment, its system includes,
	the shared submit-and-clock, then its own `_run` per relation."""
	lines = [
		f"/* Generated by situc {__version__} from {basename}.situ -- do not"
		" edit.",
		" *",
		*doc,
		" */",
		"#define _POSIX_C_SOURCE 200809L",
		"",
		f"#include \"{basename}_{facility}.h\"",
		"",
		*includes,
		"",
		*submit_and_clock(prefix, facility),
	]
	for relation, _policy in ready:
		lines.extend(run(relation, resolved, prefix))
	return "\n".join(lines).rstrip("\n") + "\n"


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str, *, facility: str, header_doc: list[str],
		source_doc: list[str], includes: list[str], run: RunFn
		) -> dict[str, str]:
	"""An fd-based driver's header and source, or nothing where no exchange
	states a policy -- the same `driven()` gate the drive layer uses."""
	ready = driven(schema, resolved)
	if not ready:
		return {}
	return {
		f"{basename}_{facility}.h": header(basename, prefix, ready, facility,
		                                   header_doc),
		f"{basename}_{facility}.c": source(schema, resolved, basename, prefix,
		                                   ready, facility, source_doc,
		                                   includes, run),
	}
