"""Generate C11 accessors from a resolved schema.

The generated API exposes exactly the operations the capability vector supports
(project.md section 4). Where an operation is refused, the header says why and
what would have to change -- a user grepping for a missing setter has to find
the explanation in the header itself, not only in compiler output (section
20.2).

Principles that shape every line emitted here:

- **Views are values.** A view is a small struct passed by value. No allocation,
  no lifetime management.
- **Field access is a constant offset from the view base.** Accessors are
  `static inline` so they compile to `base + K`.
- **Errors are return codes.** Never errno, never longjmp.
- **Getters for ValueConverted fields return by value only.** A pointer into a
  byte-swapped field is a bug waiting to happen, so none is offered.
- **Nothing allocates, recurses, or uses a VLA.** Ever.
"""

from __future__ import annotations

from dataclasses import dataclass

from situc import ast
from situc.capability import Axis
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.types import ScalarKind, ScalarType

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Generated:
	"""The two files a schema compiles to."""

	header: str
	source: str
	basename: str

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.h": self.header, f"{self.basename}.c": self.source}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> Generated:
	emitter = Emitter(schema, resolved, basename, prefix)
	return Generated(
		header   = emitter.header(),
		source   = emitter.source(),
		basename = basename,
	)


def ident(*parts: str) -> str:
	return "_".join(part for part in parts if part)


def macro(*parts: str) -> str:
	return "_".join(part for part in parts if part).upper()


def c_name(path: str) -> str:
	"""A path rendered as a C identifier fragment.

	Nested paths flatten with underscores, and the synthesised names of
	reserved regions are dropped: they have no accessor.
	"""
	return path.replace(".", "_").replace("[]", "")


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str, prefix: str) -> None:
		self.schema   = schema
		self.resolved = resolved
		self.basename = basename
		self.prefix   = prefix
		self.structs  = {decl.name: decl for decl in schema.structs()}
		self.enums    = {decl.name: decl for decl in schema.enums()}
		self.markers  = {decl.name: decl for decl in schema.markers()}

	# -- header ---------------------------------------------------------

	def header(self) -> str:
		guard = macro(self.prefix, self.basename, "h")
		lines = [
			*self._banner(),
			f"#ifndef {guard}",
			f"#define {guard}",
			"",
			'#include "situ.h"',
			"",
			"#ifdef __cplusplus",
			'extern "C" {',
			"#endif",
		]

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		# Declaration order, not alphabetical: a struct's sub-view accessor
		# refers to the nested struct's SIZE_FIXED macro, so the nested one has
		# to be emitted first. The solver resolves dependencies before their
		# dependents, so its insertion order is already what C needs.
		for struct in self.resolved.structs.values():
			lines.extend(self._struct_header(struct))

		lines.extend([
			"",
			"#ifdef __cplusplus",
			"}",
			"#endif",
			"",
			f"#endif /* {guard} */",
		])
		return "\n".join(lines) + "\n"

	def _banner(self) -> list[str]:
		return [
			f"/* Generated by situc from {self.basename}.situ -- do not edit.",
			" *",
			" * The operations below are exactly the ones this schema's capability",
			" * vectors support. Where one is missing, a comment says why and what",
			" * would have to change; see the committed capability map for the full",
			" * picture.",
			" */",
			"",
		]

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		backing = decl.backing.scalar
		assert backing is not None
		values = self.resolved.layout.env.enums[decl.name]

		lines = [
			"",
			f"/* enum {decl.name} : {decl.backing.name}"
			f" -- unknown values are {decl.effective_default.value} */",
			f"typedef enum {ident(self.prefix, decl.name)} {{",
		]
		for member in decl.members:
			lines.append(f"\t{macro(self.prefix, decl.name, member.name)}"
			             f" = {values[member.name]},")
		lines.append(f"}} {ident(self.prefix, decl.name)}_t;")
		return lines

	def _struct_header(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		lines  = ["", f"/* ---- struct {struct.name} ---- */", ""]

		if not layout.is_byte_sized:
			lines.append(f"/* {struct.name} is {layout.size_bits} bits, not a whole")
			lines.append(" * number of bytes, so no accessors are generated for it. */")
			return lines

		lines.extend(self._size_constants(struct))
		lines.extend(self._view_acquisition(struct))

		for entry in struct.entries:
			lines.extend(self._field(struct, entry))

		lines.extend(self._shifting_setters(struct))
		lines.extend(self._validate_decl(struct))
		return lines

	def _size_constants(self, struct: ResolvedStruct) -> list[str]:
		"""So callers can size static buffers without running the compiler.

		SIZE_FIXED is emitted only when there is one. A frame has a range, and
		pretending otherwise would hand a caller a number that is wrong for
		every message but the shortest.
		"""
		layout = struct.layout
		name   = struct.name
		lines  = []

		if layout.is_fixed_size:
			lines.append(f"#define {macro(self.prefix, name, 'SIZE_FIXED')} "
			             f"{layout.size_bytes}u")

		lines.append(f"#define {macro(self.prefix, name, 'SIZE_MIN')}   "
		             f"{layout.size_bytes}u")

		if layout.size_max_bytes is not None:
			lines.append(f"#define {macro(self.prefix, name, 'SIZE_MAX')}   "
			             f"{layout.size_max_bytes}u")
		else:
			lines.extend([
				f"/* No {macro(self.prefix, name, 'SIZE_MAX')}: nothing in the "
				"schema bounds this",
				" * struct's length. Give the driving length field a `[max = N]`",
				" * to make it statically allocatable. */",
			])

		lines.append("")
		return lines

	def _view_acquisition(self, struct: ResolvedStruct) -> list[str]:
		"""One bounds check at the frame boundary (section 12.2).

		A fixed struct knows its own extent. A frame does not: how many bytes it
		occupies depends on the data, so the caller supplies what they have and
		the check is against that.
		"""
		layout = struct.layout
		name   = struct.name

		if layout.is_fixed_size:
			return [
				*self._invalidation_note(struct),
				"/* Acquire a view. This is the one bounds check; the field",
				" * accessors below are constant offsets from the view base. */",
				f"static inline situ_err_t {ident(self.prefix, name, 'view')}"
				"(const situ_msg_t *msg, uint32_t offset, situ_view_t *out)",
				"{",
				f"\treturn situ_view_at(msg, offset, "
				f"{macro(self.prefix, name, 'SIZE_FIXED')}, out);",
				"}",
			]

		return [
			*self._invalidation_note(struct),
			"/* Acquire a view. This struct is a frame: its extent depends on the",
			" * data, so the caller supplies the length they have and the bounds",
			" * check is made against that. The fields at a static offset are then",
			" * constant offsets from the base; the rest resolve through their own",
			" * offset functions below. */",
			f"static inline situ_err_t {ident(self.prefix, name, 'view')}"
			"(const situ_msg_t *msg, uint32_t offset, uint32_t length,",
			"\t\tsitu_view_t *out)",
			"{",
			f"\tif (length < {macro(self.prefix, name, 'SIZE_MIN')}) {{",
			"\t\treturn SITU_ERR_BOUNDS;",
			"\t}",
			"",
			"\treturn situ_view_at(msg, offset, length, out);",
			"}",
		]

	def _drivers(self, struct: ResolvedStruct) -> list[str]:
		"""Fields whose value decides where later members start."""
		return sorted({
			placement.sized_by
			for placement in self._top_level(struct)
			if placement.sized_by and placement.sized_by != "remaining"
		})

	def _invalidation_note(self, struct: ResolvedStruct) -> list[str]:
		"""Document, per view type, exactly what invalidates it.

		Section 12.3 asks for this by name. The C type system cannot enforce
		view invalidation, so the generated header has to say what does it --
		otherwise the only record of the rule is in the compiler's head.
		"""
		drivers = self._drivers(struct)

		if not drivers:
			return [
				f"/* INVALIDATION: nothing invalidates a {struct.name} view.",
				" * Every member has a fixed size, so no write can move another.",
				" */",
			]

		listed = ", ".join(f"`{name}`" for name in drivers)
		return [
			f"/* INVALIDATION: a {struct.name} view, and every view derived from",
			f" * it, is invalidated by writing {listed} -- those decide where the",
			" * members after them start. Use the setters at the end of this",
			" * struct's section, which bump the message generation; a stale view",
			" * is then caught on use in a SITU_CHECKED build.",
			" *",
			" * Re-acquire the view after any such write.",
			" */",
		]

	def _shifting_setters(self, struct: ResolvedStruct) -> list[str]:
		"""Setters for fields that drive a length in this struct.

		Writing one of these moves every member after the region it sizes, so
		the message's generation has to be bumped: that is the only thing
		standing between a caller and a stale view (section 12.3). The setter
		therefore takes the message, which also makes the cost visible in the
		signature rather than only in a comment.
		"""
		drivers = self._drivers(struct)
		if not drivers:
			return []

		lines = ["", "/* Writing any of these changes where later members start, so each",
		         " * one bumps the message generation and invalidates outstanding",
		         " * views. In a SITU_CHECKED build a stale view is then caught on",
		         " * use; in a release build the check compiles out. */"]

		for path in drivers:
			target = self.resolved.find(f"{struct.name}.{path}")
			if target is None or target.placement.scalar is None:
				continue

			local = c_name(path)
			ctype = self._field_ctype(target.placement)
			store = self._store_statement(
				target.placement.scalar, target.placement,
				self._value_base(struct, target.placement), "value",
				offset=self._value_offset(target.placement))

			lines.extend([
				f"static inline void "
				f"{ident(self.prefix, struct.name, local, 'set')}"
				f"(situ_msg_t *msg, situ_view_t view, {ctype} value)",
				"{",
				f"\t{store}",
				"\tsitu_msg_touch(msg);",
				"}",
			])

		return lines

	# -- one field ------------------------------------------------------

	def _field(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement

		# An element entry describes every element of an array at once, so it
		# has no accessor of its own: the array field emits an indexed one.
		if placement.kind == "element":
			return []

		# A nested struct's members are emitted under their own struct, so only
		# the aggregate itself gets an accessor here. Checked before the
		# reserved case, or a nested reserved region would be noted twice.
		if "." in placement.path[len(struct.name) + 1 :]:
			return []

		if placement.kind == "reserved":
			return self._reserved_note(placement)

		lines = ["", *self._field_comment(entry)]

		if placement.kind == "marker":
			lines.extend(self._marker(struct, placement))
			return lines

		if placement.varint is not None:
			lines.extend(self._varint_note(placement))
			return lines

		# A dynamically placed member needs its offset worked out at runtime
		# before anything can read it.
		if placement.offset_bits is None:
			lines.extend(self._offset_function(struct, placement))

		if placement.type_name in self.structs:
			if self._is_array(placement):
				lines.extend(self._element_view(struct, placement))
			else:
				lines.extend(self._sub_view(struct, placement))
			return lines

		if placement.array_count is not None or placement.sized_by is not None:
			lines.extend(self._array(struct, entry))
			return lines

		lines.extend(self._scalar_get(struct, entry))
		lines.extend(self._scalar_set(struct, entry))
		return lines

	def _field_comment(self, entry: Resolved) -> list[str]:
		placement = entry.placement
		vector    = entry.vector
		offset    = vector.get(Axis.OFFSET).render()
		axes      = " ".join(
			f"{axis.value}={vector.get(axis).render()}"
			for axis in (Axis.SIZE, Axis.ALIGN, Axis.REPR, Axis.ATOMIC, Axis.MUTATE))

		return [
			f"/* {placement.path} : {placement.type_name}  at {offset}",
			f" * {axes}",
			" */",
		]

	def _varint_note(self, placement: Placement) -> list[str]:
		"""A varint has no constant-offset accessor to generate.

		Its width is not known until it is read, so there is no `base + K` for
		this field and none for anything after it in the same frame. Decoding
		them is phase 6 codegen work; refusing to emit an accessor is better
		than emitting one that pretends the width is fixed.
		"""
		return [
			f"/* No accessor: `{placement.name}` is a `{placement.varint}`, whose",
			" * width is not known until it is read. Varint decoding is not",
			" * generated yet; the capability map already records what the field",
			" * costs. */",
		]

	def _reserved_note(self, placement: Placement) -> list[str]:
		return [
			"",
			f"/* {placement.path} : {placement.type_name} -- reserved, no accessor.",
			" * Reserved regions are validated on parse, not exposed; see the",
			" * validate function below. */",
		]

	def _marker(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		"""The byte-order marker's constants and accessors (section 8.3).

		The marker is compared as a byte sequence, not decoded as a number: it
		has to be readable before its own byte order is known. Reading it big
		endian and comparing against the literal as written is the only
		interpretation that does not presuppose the answer.

		The host constant is what a writer uses instead of hardcoding an order,
		which is what makes the writer deterministic even though the format is
		not canonical.
		"""
		from situc.expr import evaluate

		marker = self.markers[placement.name]
		scalar = placement.scalar
		assert scalar is not None

		env    = self.resolved.layout.env
		little = evaluate(marker.little, env)
		big    = evaluate(marker.big, env)
		width  = scalar.bits
		base   = macro(self.prefix, struct.name, placement.name)
		local  = c_name(self._local(struct, placement))

		return [
			f"#define {base}_LITTLE 0x{little:0{width // 4}X}u",
			f"#define {base}_BIG    0x{big:0{width // 4}X}u",
			"",
			"/* The host's own order, resolved at compile time. A writer stores",
			" * this rather than picking an order, so the writer is deterministic",
			" * even though the format admits both. */",
			"#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__",
			f"#define {base}_HOST {base}_BIG",
			"#else",
			f"#define {base}_HOST {base}_LITTLE",
			"#endif",
			"",
			f"static inline int "
			f"{ident(self.prefix, struct.name, local, 'is_little')}(situ_view_t view)",
			"{",
			f"\treturn situ_get_be{width}(view.base + {placement.offset_bytes}u)"
			f" == {base}_LITTLE;",
			"}",
			f"static inline uint{width}_t "
			f"{ident(self.prefix, struct.name, local, 'host')}(void)",
			"{",
			f"\treturn {base}_HOST;",
			"}",
			f"static inline void "
			f"{ident(self.prefix, struct.name, local, 'set_host')}(situ_view_t view)",
			"{",
			f"\tsitu_put_be{width}(view.base + {placement.offset_bytes}u, {base}_HOST);",
			"}",
		]

	def _value_base(self, struct: ResolvedStruct, placement: Placement) -> str:
		"""The pointer a scalar accessor loads from.

		A statically placed field reads from the view base at a constant
		displacement. A dynamically placed one has its offset resolved first,
		so the displacement folds into the pointer and the load itself stays a
		single access.
		"""
		if placement.offset_bits is not None:
			return "view.base"
		return f"(view.base + {self._base_expression(struct, placement)})"

	def _value_offset(self, placement: Placement) -> int | None:
		return None if placement.offset_bits is not None else 0

	def _is_array(self, placement: Placement) -> bool:
		return self.resolved.find(placement.path + "[]") is not None

	def _base_expression(self, struct: ResolvedStruct, placement: Placement) -> str:
		"""Where this member starts, in bytes, as a C expression."""
		if placement.offset_bits is not None:
			return f"{placement.offset_bytes}u"
		local = c_name(self._local(struct, placement))
		return f"{ident(self.prefix, struct.name, local, 'offset')}(view)"

	def _top_level(self, struct: ResolvedStruct) -> list[Placement]:
		"""The struct's own members, without absorbed nested ones."""
		return [
			entry.placement for entry in struct.entries
			if entry.placement.kind != "element"
			and "." not in entry.placement.path[len(struct.name) + 1 :]
		]

	def _offset_function(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""Resolve a dynamic offset by summing what precedes it.

		Everything before the first variable-length member contributes a
		constant; each variable-length member contributes its own length, read
		from the field that drives it. That field always has a static offset,
		because a size expression may only name a field declared before it and
		everything before the first dynamic member is statically placed.
		"""
		local = c_name(self._local(struct, placement))
		lines = [
			f"static inline uint32_t "
			f"{ident(self.prefix, struct.name, local, 'offset')}(situ_view_t view)",
			"{",
		]

		constant = 0
		terms    = []
		for other in self._top_level(struct):
			if other.path == placement.path:
				break
			if other.is_fixed_size:
				constant += other.size_bits // BITS_PER_BYTE
			else:
				terms.append(self._length_expression(struct, other))

		lines.append(f"\tuint32_t offset = {constant}u;")
		for term in terms:
			lines.append(f"\toffset = offset + ({term});")
		lines.extend(["", "\treturn offset;", "}"])
		return lines

	def _length_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str:
		"""How many bytes a variable-length member occupies, at runtime."""
		element = (placement.element_bits or BITS_PER_BYTE) // BITS_PER_BYTE

		if placement.sized_by == "remaining":
			return f"view.limit - {self._base_expression(struct, placement)}"

		count = self._count_expression(struct, placement)
		return f"(uint32_t){count}" if element == 1 else f"(uint32_t){count} * {element}u"

	def _count_expression(self, struct: ResolvedStruct, placement: Placement) -> str:
		"""Read the field that drives a member's length.

		Usually a constant-offset load, but not always: the driving field has to
		precede the member it sizes, which does not mean it precedes every
		dynamic member. A second variable-length region can be counted by a
		field that is itself dynamically placed, so this goes through the same
		base resolution as any other read.
		"""
		if placement.sized_by is None:
			return f"{placement.array_count or 0}u"

		target = self.resolved.find(f"{struct.name}.{placement.sized_by}")
		if target is None or target.placement.scalar is None:
			return f"{placement.array_count or 0}u"

		loaded = self._load_expression(
			target.placement.scalar, target.placement,
			self._value_base(struct, target.placement),
			offset=self._value_offset(target.placement))
		return f"({loaded})"

	def _element_view(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""Indexed access to one element of an array of structs.

		Acquiring the element view is the bounds check; the fields inside it are
		then constant offsets from its base (section 12.2). That is what gives a
		dynamically positioned static struct its static capabilities back, and
		why the accessors inside `Record` are the same ones a standalone
		`Record` would have.
		"""
		local  = c_name(self._local(struct, placement))
		nested = placement.type_name
		base   = self._base_expression(struct, placement)
		lines  = []

		if placement.array_count is not None:
			lines.append(f"#define {macro(self.prefix, struct.name, local, 'COUNT')} "
			             f"{placement.array_count}u")
		else:
			lines.extend([
				f"static inline uint32_t "
				f"{ident(self.prefix, struct.name, local, 'count')}(situ_view_t view)",
				"{",
				f"\treturn (uint32_t){self._count_expression(struct, placement)};",
				"}",
			])

		lines.extend([
			f"static inline situ_err_t "
			f"{ident(self.prefix, struct.name, local, 'at')}"
			"(situ_view_t view, uint32_t index, situ_view_t *out)",
			"{",
			f"\tconst uint32_t stride = {macro(self.prefix, nested, 'SIZE_FIXED')};",
			f"\tconst uint32_t base   = {base};",
			"",
			"\treturn situ_view_sub(view, base + index * stride, stride, out);",
			"}",
		])
		return lines

	def _sub_view(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		nested = placement.type_name
		base   = self._base_expression(struct, placement)
		return [
			f"static inline situ_err_t "
			f"{ident(self.prefix, struct.name, c_name(self._local(struct, placement)), 'view')}"
			"(situ_view_t view, situ_view_t *out)",
			"{",
			f"\treturn situ_view_sub(view, {base}, "
			f"{macro(self.prefix, nested, 'SIZE_FIXED')}, out);",
			"}",
		]

	def _array(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		local     = c_name(self._local(struct, placement))
		scalar    = placement.scalar
		count     = placement.array_count
		assert scalar is not None

		lines = []
		if count is not None:
			lines.append(
				f"#define {macro(self.prefix, struct.name, local, 'COUNT')} {count}u")
		else:
			# A run-time length: the count comes from the field that drives it,
			# and `remaining` measures to the end of the view.
			lines.extend([
				f"static inline uint32_t "
				f"{ident(self.prefix, struct.name, local, 'len')}(situ_view_t view)",
				"{",
				f"\treturn {self._length_expression(struct, placement)};",
				"}",
			])

		if scalar.bits == BITS_PER_BYTE:
			# A byte array is the bytes: MemoryIdentical, so a pointer is safe
			# and is what callers actually want.
			lines.extend(self._address_note(entry))
			lines.extend([
				f"static inline uint8_t *"
				f"{ident(self.prefix, struct.name, local, 'ptr')}(situ_view_t view)",
				"{",
				f"\treturn view.base + {self._base_expression(struct, placement)};",
				"}",
			])
			return lines

		lines.extend([
			f"/* No pointer accessor: the element type is {placement.type_name},",
			" * which is ValueConverted, so a pointer into it would alias bytes",
			" * that are not the value. Index the elements individually. */",
		])
		lines.extend(self._indexed_element(struct, entry, local, scalar))
		return lines

	def _indexed_element(self, struct: ResolvedStruct, entry: Resolved,
			local: str, scalar: ScalarType) -> list[str]:
		placement = entry.placement
		ctype     = self._field_ctype(placement)
		stride    = scalar.bits // BITS_PER_BYTE
		getter    = ident(self.prefix, struct.name, local, "get")

		base = self._base_expression(struct, placement)
		load = self._load_expression(
			scalar, placement, f"view.base + {base} + index * {stride}u", offset=0)
		return [
			f"static inline {ctype} {getter}(situ_view_t view, uint32_t index)",
			"{",
			f"\treturn ({ctype})({load});",
			"}",
		]

	# -- scalars --------------------------------------------------------

	def _scalar_get(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None:
			return []

		local  = c_name(self._local(struct, placement))
		ctype  = self._field_ctype(placement)
		getter = ident(self.prefix, struct.name, local, "get")
		base   = self._value_base(struct, placement)
		load   = self._load_expression(scalar, placement, base,
		                               offset=self._value_offset(placement))

		lines = [
			f"static inline {ctype} {getter}(situ_view_t view)",
			"{",
			f"\treturn ({ctype})({load});",
			"}",
		]

		# A pointer accessor is offered only where the value is literally the
		# bytes. Section 20.2: never hand out a pointer into a converted field.
		if (entry.vector.get(Axis.REPR).base == "MemoryIdentical"
				and not scalar.is_bit_packed
				and placement.kind != "marker"
				and placement.type_name not in self.enums):
			lines.extend(self._address_note(entry))
			lines.extend([
				f"static inline {self._ctype(scalar)} *"
				f"{ident(self.prefix, struct.name, local, 'ptr')}(situ_view_t view)",
				"{",
				f"\treturn ({self._ctype(scalar)} *)(view.base + "
				f"{self._base_expression(struct, placement)});",
				"}",
			])

		return lines

	def _scalar_set(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None:
			return []

		refusal = self._setter_refusal(entry)
		if refusal is not None:
			return refusal

		# A field that drives a length gets one setter, not two: writing it
		# moves later members, so it has to bump the generation. The shifting
		# setter at the end of this struct's section is that one.
		local_path = self._local(struct, placement)
		if local_path in self._drivers(struct):
			return [
				f"/* No plain setter: `{local_path}` decides where later members",
				" * start, so writing it must invalidate outstanding views. Use",
				f" * {ident(self.prefix, struct.name, c_name(local_path), 'set')}(),",
				" * which takes the message and bumps its generation. */",
			]

		local = c_name(self._local(struct, placement))
		ctype = self._field_ctype(placement)
		setter = ident(self.prefix, struct.name, local, "set")

		base = self._value_base(struct, placement)
		return [
			f"static inline void {setter}(situ_view_t view, {ctype} value)",
			"{",
			f"\t{self._store_statement(scalar, placement, base, 'value', offset=self._value_offset(placement))}",
			"}",
		]

	def _address_note(self, entry: Resolved) -> list[str]:
		"""Say how long a pointer stays good.

		The pointer is valid now; what varies is what invalidates it. Section
		11.1's address axis exists to answer exactly that, so the answer belongs
		beside the accessor rather than only in the map.
		"""
		address = entry.vector.get(Axis.ADDRESS).base

		if address == "Stable":
			return []

		if address == "FrameStable":
			return ["/* The returned pointer is valid while the enclosing frame's",
			        " * base does not move. */"]

		return ["/* The returned pointer is invalidated by any write that changes",
		        " * the length of what precedes this field; see the INVALIDATION",
		        " * note on this struct's view accessor. */"]

	def _setter_refusal(self, entry: Resolved) -> list[str] | None:
		"""Explain a missing setter, in the header, where it will be looked for.

		A missing setter with no explanation is hostile (project.md section 4).
		The text is the same blame chain `situc explain` prints.
		"""
		mutate = entry.vector.get(Axis.MUTATE)
		if mutate.base in ("InPlaceFixed", "InPlaceSlack"):
			return None

		lines = [f"/* No setter: mutate is {mutate.render()}."]
		for weakening in entry.blame(Axis.MUTATE):
			lines.append(f" *   caused by: {weakening.rule.construct}")
			lines.append(f" *              {weakening.effect.because}")
			if weakening.rule.remedy:
				lines.append(f" *   remedy:    {weakening.rule.remedy}")
		lines.append(" */")
		return lines

	def _load_expression(self, scalar: ScalarType, placement: Placement,
			base: str, offset: int | None = None) -> str:
		offset = placement.offset_bytes if offset is None else offset

		if placement.marker is not None and not scalar.is_bit_packed \
				and scalar.bits > BITS_PER_BYTE:
			return self._conditional_load(scalar, placement, base)

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			raw   = (f"situ_bits_get_{order}({base}, {placement.offset_bits}u, "
			         f"{scalar.bits}u)")
			if scalar.signed:
				return f"({self._ctype(scalar)})situ_sign_extend({raw}, {scalar.bits}u)"
			return f"({self._ctype(scalar)}){raw}"

		if scalar.bits == BITS_PER_BYTE:
			cast = self._ctype(scalar)
			return f"({cast})({base})[{offset}u]"

		suffix = "le" if placement.endian is ast.Endian.LITTLE else "be"
		if placement.endian is ast.Endian.NATIVE:
			suffix = "le" if _host_is_little() else "be"

		width = scalar.bits
		if width in WORD_WIDTHS:
			raw = f"situ_get_{suffix}{width}({base} + {offset}u)"
			return f"({self._ctype(scalar)}){raw}" if scalar.signed else raw

		# Non-word whole-byte widths (u24, u48) go through the bit path, which
		# handles any width without a special case.
		raw = f"situ_bits_get_msb({base}, {placement.offset_bits}u, {width}u)"
		if placement.endian is ast.Endian.LITTLE:
			raw = f"situ_bits_get_lsb({base}, {placement.offset_bits}u, {width}u)"
		if scalar.signed:
			return f"({self._ctype(scalar)})situ_sign_extend({raw}, {width}u)"
		return f"({self._ctype(scalar)}){raw}"

	def _conditional_load(self, scalar: ScalarType, placement: Placement,
			base: str) -> str:
		"""A parse-time branch on the marker.

		The branch is on a public, layout-irrelevant value, so it is not a side
		channel (section 11.1).
		"""
		predicate = self._marker_predicate(placement)
		width     = scalar.bits
		offset    = placement.offset_bytes
		if width in WORD_WIDTHS:
			return (f"{predicate} ? situ_get_le{width}({base} + {offset}u)"
			        f" : situ_get_be{width}({base} + {offset}u)")

		bits = placement.offset_bits
		return (f"{predicate} ? situ_bits_get_lsb({base}, {bits}u, {width}u)"
		        f" : situ_bits_get_msb({base}, {bits}u, {width}u)")

	def _marker_predicate(self, placement: Placement) -> str:
		owner = placement.path.partition(".")[0]
		return ident(self.prefix, owner, placement.marker or "", "is_little") + "(view)"

	def _store_statement(self, scalar: ScalarType, placement: Placement,
			base: str, value: str, offset: int | None = None) -> str:
		offset = placement.offset_bytes if offset is None else offset

		if placement.marker is not None and not scalar.is_bit_packed \
				and scalar.bits > BITS_PER_BYTE:
			width     = scalar.bits
			predicate = self._marker_predicate(placement)
			if width in WORD_WIDTHS:
				return (f"if ({predicate}) {{\n"
				        f"\t\tsitu_put_le{width}({base} + {offset}u, "
				        f"(uint{width}_t){value});\n"
				        f"\t}} else {{\n"
				        f"\t\tsitu_put_be{width}({base} + {offset}u, "
				        f"(uint{width}_t){value});\n"
				        f"\t}}")
			bits = placement.offset_bits
			return (f"if ({predicate}) {{\n"
			        f"\t\tsitu_bits_set_lsb({base}, {bits}u, {width}u, "
			        f"(uint64_t){value});\n"
			        f"\t}} else {{\n"
			        f"\t\tsitu_bits_set_msb({base}, {bits}u, {width}u, "
			        f"(uint64_t){value});\n"
			        f"\t}}")

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			return (f"situ_bits_set_{order}({base}, {placement.offset_bits}u, "
			        f"{scalar.bits}u, (uint64_t){value});")

		if scalar.bits == BITS_PER_BYTE:
			return f"({base})[{offset}u] = (uint8_t){value};"

		suffix = "le" if placement.endian is ast.Endian.LITTLE else "be"
		if placement.endian is ast.Endian.NATIVE:
			suffix = "le" if _host_is_little() else "be"

		width = scalar.bits
		if width in WORD_WIDTHS:
			return (f"situ_put_{suffix}{width}({base} + {offset}u, "
			        f"(uint{width}_t){value});")

		order = "lsb" if placement.endian is ast.Endian.LITTLE else "msb"
		return (f"situ_bits_set_{order}({base}, {placement.offset_bits}u, "
		        f"{width}u, (uint64_t){value});")

	# -- validation -----------------------------------------------------

	def _validate_decl(self, struct: ResolvedStruct) -> list[str]:
		return [
			"",
			"/* Check every constraint this schema states: [must_eq], [max],",
			" * [min], and the reserved-bit policy. Called on parse under",
			" * SITU_CHECKED, and available explicitly in any build. */",
			f"situ_err_t {ident(self.prefix, struct.name, 'validate')}(situ_view_t view);",
		]

	def source(self) -> str:
		lines = [
			*self._banner(),
			f'#include "{self.basename}.h"',
			"",
		]

		for struct in self.resolved.structs.values():
			if struct.layout.is_byte_sized:
				lines.extend(self._validate_body(struct))

		return "\n".join(lines) + "\n"

	def _validate_body(self, struct: ResolvedStruct) -> list[str]:
		lines = [
			f"situ_err_t {ident(self.prefix, struct.name, 'validate')}(situ_view_t view)",
			"{",
		]

		checks = []
		for entry in struct.entries:
			checks.extend(self._checks_for(struct, entry))

		if not checks:
			lines.append("\t(void)view;")
		else:
			lines.extend(checks)

		lines.extend(["\treturn SITU_OK;", "}", ""])
		return lines

	def _checks_for(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None or placement.array_count is not None:
			return []
		if placement.kind == "marker":
			return []
		if "." in placement.path[len(struct.name) + 1 :]:
			return []

		local  = c_name(self._local(struct, placement))
		lines  = []

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				expect = "0" if policy == "must_be_zero" else _all_ones(scalar.bits)
				read   = self._load_expression(scalar, placement, "view.base")
				lines.extend([
					f"\t/* reserved {placement.type_name} [{policy}] */",
					f"\tif ({read} != {expect}) {{",
					"\t\treturn SITU_ERR_CONSTRAINT;",
					"\t}",
				])
			return lines

		getter = ident(self.prefix, struct.name, local, "get")
		env    = self.resolved.layout.env

		for attr in placement.attrs:
			if attr.name not in ("must_eq", "max", "min") or attr.value is None:
				continue

			from situc.expr import evaluate
			expected = evaluate(attr.value, env)
			operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
			lines.extend([
				f"\t/* {placement.path} [{attr.name} = {expected}] */",
				f"\tif ({getter}(view) {operator} {expected}) {{",
				"\t\treturn SITU_ERR_CONSTRAINT;",
				"\t}",
			])

		return lines

	# -- helpers --------------------------------------------------------

	def _local(self, struct: ResolvedStruct, placement: Placement) -> str:
		return placement.path[len(struct.name) + 1 :]

	def _field_ctype(self, placement: Placement) -> str:
		"""The C type a field's accessors use.

		An enum field exposes its typedef rather than the backing width: the
		backing type is mandatory so that the layout is fixed (section 8.7), not
		so that callers have to remember which width it was.
		"""
		if placement.type_name in self.enums:
			return f"{ident(self.prefix, placement.type_name)}_t"

		scalar = placement.scalar
		assert scalar is not None
		return self._ctype(scalar)

	def _ctype(self, scalar: ScalarType) -> str:
		if scalar.kind is ScalarKind.FLOAT:
			return {16: "uint16_t", 32: "float", 64: "double"}[scalar.bits]

		width = _storage_width(scalar.bits)
		return f"int{width}_t" if scalar.signed else f"uint{width}_t"


def _storage_width(bits: int) -> int:
	for width in WORD_WIDTHS:
		if bits <= width:
			return width
	return 64


def _all_ones(bits: int) -> str:
	return f"0x{(1 << bits) - 1:X}u"


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str:
	"""Reserved behaviour, defaulting to must_be_zero (section 8.8).

	The default is deliberate: every ignored bit is a malleability surface, so
	the safe option is the silent one.
	"""
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one", "preserve", "unknown"):
			return attr.name
	return "must_be_zero"


def _host_is_little() -> bool:
	import sys
	return sys.byteorder == "little"
