"""Generate C11 accessors from a resolved schema.

The generated API exposes exactly the operations the capability vector supports
(project.md section 4). Where an operation is refused, the header says why and
what would have to change -- a user grepping for a missing setter has to find
the explanation in the header itself, not only in compiler output (section
20.2).

Principles that shape every line emitted here:

- **Views are values.** A view is a small struct passed by value. No allocation,
  no lifetime management.
- **Field access is a constant offset from the view base.** Accessors are
  `static inline` so they compile to `base + K`.
- **Errors are return codes.** Never errno, never longjmp.
- **Getters for ValueConverted fields return by value only.** A pointer into a
  byte-swapped field is a bug waiting to happen, so none is offered.
- **Nothing allocates, recurses, or uses a VLA.** Ever.
"""

from __future__ import annotations

from dataclasses import dataclass

from situc import ast
from situc.capability import Axis
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.types import ScalarKind, ScalarType

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Generated:
	"""The two files a schema compiles to."""

	header: str
	source: str
	basename: str

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.h": self.header, f"{self.basename}.c": self.source}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> Generated:
	emitter = Emitter(schema, resolved, basename, prefix)
	return Generated(
		header   = emitter.header(),
		source   = emitter.source(),
		basename = basename,
	)


def ident(*parts: str) -> str:
	return "_".join(part for part in parts if part)


def macro(*parts: str) -> str:
	return "_".join(part for part in parts if part).upper()


def c_name(path: str) -> str:
	"""A path rendered as a C identifier fragment.

	Nested paths flatten with underscores, and the synthesised names of
	reserved regions are dropped: they have no accessor.
	"""
	return path.replace(".", "_").replace("[]", "")


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str, prefix: str) -> None:
		self.schema   = schema
		self.resolved = resolved
		self.basename = basename
		self.prefix   = prefix
		self.structs  = {decl.name: decl for decl in schema.structs()}
		self.enums    = {decl.name: decl for decl in schema.enums()}
		self.markers  = {decl.name: decl for decl in schema.markers()}

	# -- header ---------------------------------------------------------

	def header(self) -> str:
		guard = macro(self.prefix, self.basename, "h")
		lines = [
			*self._banner(),
			f"#ifndef {guard}",
			f"#define {guard}",
			"",
			'#include "situ.h"',
			"",
			"#ifdef __cplusplus",
			'extern "C" {',
			"#endif",
		]

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		# Declaration order, not alphabetical: a struct's sub-view accessor
		# refers to the nested struct's SIZE_FIXED macro, so the nested one has
		# to be emitted first. The solver resolves dependencies before their
		# dependents, so its insertion order is already what C needs.
		for struct in self.resolved.structs.values():
			lines.extend(self._struct_header(struct))

		lines.extend([
			"",
			"#ifdef __cplusplus",
			"}",
			"#endif",
			"",
			f"#endif /* {guard} */",
		])
		return "\n".join(lines) + "\n"

	def _banner(self) -> list[str]:
		return [
			f"/* Generated by situc from {self.basename}.situ -- do not edit.",
			" *",
			" * The operations below are exactly the ones this schema's capability",
			" * vectors support. Where one is missing, a comment says why and what",
			" * would have to change; see the committed capability map for the full",
			" * picture.",
			" */",
			"",
		]

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		backing = decl.backing.scalar
		assert backing is not None
		values = self.resolved.layout.env.enums[decl.name]

		lines = [
			"",
			f"/* enum {decl.name} : {decl.backing.name}"
			f" -- unknown values are {decl.effective_default.value} */",
			f"typedef enum {ident(self.prefix, decl.name)} {{",
		]
		for member in decl.members:
			lines.append(f"\t{macro(self.prefix, decl.name, member.name)}"
			             f" = {values[member.name]},")
		lines.append(f"}} {ident(self.prefix, decl.name)}_t;")
		return lines

	def _struct_header(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		lines  = ["", f"/* ---- struct {struct.name} ---- */", ""]

		if not layout.is_byte_sized:
			lines.append(f"/* {struct.name} is {layout.size_bits} bits, not a whole")
			lines.append(" * number of bytes, so no accessors are generated for it. */")
			return lines

		size = layout.size_bytes
		lines.extend([
			f"#define {macro(self.prefix, struct.name, 'SIZE_FIXED')} {size}u",
			f"#define {macro(self.prefix, struct.name, 'SIZE_MIN')}   {size}u",
			f"#define {macro(self.prefix, struct.name, 'SIZE_MAX')}   {size}u",
			"",
			"/* Acquire a view. This is the one bounds check; the field accessors",
			" * below are unchecked constant offsets from the view base. */",
			f"static inline situ_err_t {ident(self.prefix, struct.name, 'view')}"
			"(const situ_msg_t *msg, uint32_t offset, situ_view_t *out)",
			"{",
			f"\treturn situ_view_at(msg, offset, "
			f"{macro(self.prefix, struct.name, 'SIZE_FIXED')}, out);",
			"}",
		])

		for entry in struct.entries:
			lines.extend(self._field(struct, entry))

		lines.extend(self._validate_decl(struct))
		return lines

	# -- one field ------------------------------------------------------

	def _field(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement

		# A nested struct's members are emitted under their own struct, so only
		# the aggregate itself gets an accessor here. Checked before the
		# reserved case, or a nested reserved region would be noted twice.
		if "." in placement.path[len(struct.name) + 1 :]:
			return []

		if placement.kind == "reserved":
			return self._reserved_note(placement)

		lines = ["", *self._field_comment(entry)]

		if placement.kind == "marker":
			lines.extend(self._marker(struct, placement))
			return lines

		if placement.type_name in self.structs:
			lines.extend(self._sub_view(struct, placement))
			return lines

		if placement.array_count is not None:
			lines.extend(self._array(struct, entry))
			return lines

		lines.extend(self._scalar_get(struct, entry))
		lines.extend(self._scalar_set(struct, entry))
		return lines

	def _field_comment(self, entry: Resolved) -> list[str]:
		placement = entry.placement
		vector    = entry.vector
		offset    = vector.get(Axis.OFFSET).render()
		axes      = " ".join(
			f"{axis.value}={vector.get(axis).render()}"
			for axis in (Axis.SIZE, Axis.ALIGN, Axis.REPR, Axis.ATOMIC, Axis.MUTATE))

		return [
			f"/* {placement.path} : {placement.type_name}  at {offset}",
			f" * {axes}",
			" */",
		]

	def _reserved_note(self, placement: Placement) -> list[str]:
		return [
			"",
			f"/* {placement.path} : {placement.type_name} -- reserved, no accessor.",
			" * Reserved regions are validated on parse, not exposed; see the",
			" * validate function below. */",
		]

	def _marker(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		"""The byte-order marker's constants and accessors (section 8.3).

		The marker is compared as a byte sequence, not decoded as a number: it
		has to be readable before its own byte order is known. Reading it big
		endian and comparing against the literal as written is the only
		interpretation that does not presuppose the answer.

		The host constant is what a writer uses instead of hardcoding an order,
		which is what makes the writer deterministic even though the format is
		not canonical.
		"""
		from situc.expr import evaluate

		marker = self.markers[placement.name]
		scalar = placement.scalar
		assert scalar is not None

		env    = self.resolved.layout.env
		little = evaluate(marker.little, env)
		big    = evaluate(marker.big, env)
		width  = scalar.bits
		base   = macro(self.prefix, struct.name, placement.name)
		local  = c_name(self._local(struct, placement))

		return [
			f"#define {base}_LITTLE 0x{little:0{width // 4}X}u",
			f"#define {base}_BIG    0x{big:0{width // 4}X}u",
			"",
			"/* The host's own order, resolved at compile time. A writer stores",
			" * this rather than picking an order, so the writer is deterministic",
			" * even though the format admits both. */",
			"#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__",
			f"#define {base}_HOST {base}_BIG",
			"#else",
			f"#define {base}_HOST {base}_LITTLE",
			"#endif",
			"",
			f"static inline int "
			f"{ident(self.prefix, struct.name, local, 'is_little')}(situ_view_t view)",
			"{",
			f"\treturn situ_get_be{width}(view.base + {placement.offset_bytes}u)"
			f" == {base}_LITTLE;",
			"}",
			f"static inline uint{width}_t "
			f"{ident(self.prefix, struct.name, local, 'host')}(void)",
			"{",
			f"\treturn {base}_HOST;",
			"}",
			f"static inline void "
			f"{ident(self.prefix, struct.name, local, 'set_host')}(situ_view_t view)",
			"{",
			f"\tsitu_put_be{width}(view.base + {placement.offset_bytes}u, {base}_HOST);",
			"}",
		]

	def _sub_view(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		nested = placement.type_name
		return [
			f"static inline situ_err_t "
			f"{ident(self.prefix, struct.name, c_name(self._local(struct, placement)), 'view')}"
			"(situ_view_t view, situ_view_t *out)",
			"{",
			f"\treturn situ_view_sub(view, {placement.offset_bytes}u, "
			f"{macro(self.prefix, nested, 'SIZE_FIXED')}, out);",
			"}",
		]

	def _array(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		local     = c_name(self._local(struct, placement))
		scalar    = placement.scalar
		count     = placement.array_count
		assert scalar is not None and count is not None

		lines = [
			f"#define {macro(self.prefix, struct.name, local, 'COUNT')} {count}u",
		]

		if scalar.bits == BITS_PER_BYTE:
			# A byte array is the bytes: MemoryIdentical, so a pointer is safe
			# and is what callers actually want.
			lines.extend([
				f"static inline uint8_t *"
				f"{ident(self.prefix, struct.name, local, 'ptr')}(situ_view_t view)",
				"{",
				f"\treturn view.base + {placement.offset_bytes}u;",
				"}",
			])
			return lines

		lines.extend([
			f"/* No pointer accessor: the element type is {placement.type_name},",
			" * which is ValueConverted, so a pointer into it would alias bytes",
			" * that are not the value. Index the elements individually. */",
		])
		lines.extend(self._indexed_element(struct, entry, local, scalar))
		return lines

	def _indexed_element(self, struct: ResolvedStruct, entry: Resolved,
			local: str, scalar: ScalarType) -> list[str]:
		placement = entry.placement
		ctype     = self._field_ctype(placement)
		stride    = scalar.bits // BITS_PER_BYTE
		getter    = ident(self.prefix, struct.name, local, "get")

		load = self._load_expression(scalar, placement,
		                             f"view.base + {placement.offset_bytes}u + index * {stride}u")
		return [
			f"static inline {ctype} {getter}(situ_view_t view, uint32_t index)",
			"{",
			f"\treturn ({ctype})({load});",
			"}",
		]

	# -- scalars --------------------------------------------------------

	def _scalar_get(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None:
			return []

		local  = c_name(self._local(struct, placement))
		ctype  = self._field_ctype(placement)
		getter = ident(self.prefix, struct.name, local, "get")
		load   = self._load_expression(scalar, placement, "view.base")

		lines = [
			f"static inline {ctype} {getter}(situ_view_t view)",
			"{",
			f"\treturn ({ctype})({load});",
			"}",
		]

		# A pointer accessor is offered only where the value is literally the
		# bytes. Section 20.2: never hand out a pointer into a converted field.
		if (entry.vector.get(Axis.REPR).base == "MemoryIdentical"
				and not scalar.is_bit_packed
				and placement.kind != "marker"
				and placement.type_name not in self.enums):
			lines.extend([
				f"static inline {self._ctype(scalar)} *"
				f"{ident(self.prefix, struct.name, local, 'ptr')}(situ_view_t view)",
				"{",
				f"\treturn ({self._ctype(scalar)} *)(view.base + {placement.offset_bytes}u);",
				"}",
			])

		return lines

	def _scalar_set(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None:
			return []

		refusal = self._setter_refusal(entry)
		if refusal is not None:
			return refusal

		local = c_name(self._local(struct, placement))
		ctype = self._field_ctype(placement)
		setter = ident(self.prefix, struct.name, local, "set")

		return [
			f"static inline void {setter}(situ_view_t view, {ctype} value)",
			"{",
			f"\t{self._store_statement(scalar, placement, 'view.base', 'value')}",
			"}",
		]

	def _setter_refusal(self, entry: Resolved) -> list[str] | None:
		"""Explain a missing setter, in the header, where it will be looked for.

		A missing setter with no explanation is hostile (project.md section 4).
		The text is the same blame chain `situc explain` prints.
		"""
		mutate = entry.vector.get(Axis.MUTATE)
		if mutate.base in ("InPlaceFixed", "InPlaceSlack"):
			return None

		lines = [f"/* No setter: mutate is {mutate.render()}."]
		for weakening in entry.blame(Axis.MUTATE):
			lines.append(f" *   caused by: {weakening.rule.construct}")
			lines.append(f" *              {weakening.effect.because}")
			if weakening.rule.remedy:
				lines.append(f" *   remedy:    {weakening.rule.remedy}")
		lines.append(" */")
		return lines

	def _load_expression(self, scalar: ScalarType, placement: Placement,
			base: str) -> str:
		offset = placement.offset_bytes

		if placement.marker is not None and not scalar.is_bit_packed \
				and scalar.bits > BITS_PER_BYTE:
			return self._conditional_load(scalar, placement, base)

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			raw   = (f"situ_bits_get_{order}({base}, {placement.offset_bits}u, "
			         f"{scalar.bits}u)")
			if scalar.signed:
				return f"({self._ctype(scalar)})situ_sign_extend({raw}, {scalar.bits}u)"
			return f"({self._ctype(scalar)}){raw}"

		if scalar.bits == BITS_PER_BYTE:
			cast = self._ctype(scalar)
			return f"({cast})({base})[{offset}u]"

		suffix = "le" if placement.endian is ast.Endian.LITTLE else "be"
		if placement.endian is ast.Endian.NATIVE:
			suffix = "le" if _host_is_little() else "be"

		width = scalar.bits
		if width in WORD_WIDTHS:
			raw = f"situ_get_{suffix}{width}({base} + {offset}u)"
			return f"({self._ctype(scalar)}){raw}" if scalar.signed else raw

		# Non-word whole-byte widths (u24, u48) go through the bit path, which
		# handles any width without a special case.
		raw = f"situ_bits_get_msb({base}, {placement.offset_bits}u, {width}u)"
		if placement.endian is ast.Endian.LITTLE:
			raw = f"situ_bits_get_lsb({base}, {placement.offset_bits}u, {width}u)"
		if scalar.signed:
			return f"({self._ctype(scalar)})situ_sign_extend({raw}, {width}u)"
		return f"({self._ctype(scalar)}){raw}"

	def _conditional_load(self, scalar: ScalarType, placement: Placement,
			base: str) -> str:
		"""A parse-time branch on the marker.

		The branch is on a public, layout-irrelevant value, so it is not a side
		channel (section 11.1).
		"""
		predicate = self._marker_predicate(placement)
		width     = scalar.bits
		offset    = placement.offset_bytes
		if width in WORD_WIDTHS:
			return (f"{predicate} ? situ_get_le{width}({base} + {offset}u)"
			        f" : situ_get_be{width}({base} + {offset}u)")

		bits = placement.offset_bits
		return (f"{predicate} ? situ_bits_get_lsb({base}, {bits}u, {width}u)"
		        f" : situ_bits_get_msb({base}, {bits}u, {width}u)")

	def _marker_predicate(self, placement: Placement) -> str:
		owner = placement.path.partition(".")[0]
		return ident(self.prefix, owner, placement.marker or "", "is_little") + "(view)"

	def _store_statement(self, scalar: ScalarType, placement: Placement,
			base: str, value: str) -> str:
		offset = placement.offset_bytes

		if placement.marker is not None and not scalar.is_bit_packed \
				and scalar.bits > BITS_PER_BYTE:
			width     = scalar.bits
			predicate = self._marker_predicate(placement)
			if width in WORD_WIDTHS:
				return (f"if ({predicate}) {{\n"
				        f"\t\tsitu_put_le{width}({base} + {offset}u, "
				        f"(uint{width}_t){value});\n"
				        f"\t}} else {{\n"
				        f"\t\tsitu_put_be{width}({base} + {offset}u, "
				        f"(uint{width}_t){value});\n"
				        f"\t}}")
			bits = placement.offset_bits
			return (f"if ({predicate}) {{\n"
			        f"\t\tsitu_bits_set_lsb({base}, {bits}u, {width}u, "
			        f"(uint64_t){value});\n"
			        f"\t}} else {{\n"
			        f"\t\tsitu_bits_set_msb({base}, {bits}u, {width}u, "
			        f"(uint64_t){value});\n"
			        f"\t}}")

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			return (f"situ_bits_set_{order}({base}, {placement.offset_bits}u, "
			        f"{scalar.bits}u, (uint64_t){value});")

		if scalar.bits == BITS_PER_BYTE:
			return f"({base})[{offset}u] = (uint8_t){value};"

		suffix = "le" if placement.endian is ast.Endian.LITTLE else "be"
		if placement.endian is ast.Endian.NATIVE:
			suffix = "le" if _host_is_little() else "be"

		width = scalar.bits
		if width in WORD_WIDTHS:
			return (f"situ_put_{suffix}{width}({base} + {offset}u, "
			        f"(uint{width}_t){value});")

		order = "lsb" if placement.endian is ast.Endian.LITTLE else "msb"
		return (f"situ_bits_set_{order}({base}, {placement.offset_bits}u, "
		        f"{width}u, (uint64_t){value});")

	# -- validation -----------------------------------------------------

	def _validate_decl(self, struct: ResolvedStruct) -> list[str]:
		return [
			"",
			"/* Check every constraint this schema states: [must_eq], [max],",
			" * [min], and the reserved-bit policy. Called on parse under",
			" * SITU_CHECKED, and available explicitly in any build. */",
			f"situ_err_t {ident(self.prefix, struct.name, 'validate')}(situ_view_t view);",
		]

	def source(self) -> str:
		lines = [
			*self._banner(),
			f'#include "{self.basename}.h"',
			"",
		]

		for struct in self.resolved.structs.values():
			if struct.layout.is_byte_sized:
				lines.extend(self._validate_body(struct))

		return "\n".join(lines) + "\n"

	def _validate_body(self, struct: ResolvedStruct) -> list[str]:
		lines = [
			f"situ_err_t {ident(self.prefix, struct.name, 'validate')}(situ_view_t view)",
			"{",
		]

		checks = []
		for entry in struct.entries:
			checks.extend(self._checks_for(struct, entry))

		if not checks:
			lines.append("\t(void)view;")
		else:
			lines.extend(checks)

		lines.extend(["\treturn SITU_OK;", "}", ""])
		return lines

	def _checks_for(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None or placement.array_count is not None:
			return []
		if placement.kind == "marker":
			return []
		if "." in placement.path[len(struct.name) + 1 :]:
			return []

		local  = c_name(self._local(struct, placement))
		lines  = []

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				expect = "0" if policy == "must_be_zero" else _all_ones(scalar.bits)
				read   = self._load_expression(scalar, placement, "view.base")
				lines.extend([
					f"\t/* reserved {placement.type_name} [{policy}] */",
					f"\tif ({read} != {expect}) {{",
					"\t\treturn SITU_ERR_CONSTRAINT;",
					"\t}",
				])
			return lines

		getter = ident(self.prefix, struct.name, local, "get")
		env    = self.resolved.layout.env

		for attr in placement.attrs:
			if attr.name not in ("must_eq", "max", "min") or attr.value is None:
				continue

			from situc.expr import evaluate
			expected = evaluate(attr.value, env)
			operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
			lines.extend([
				f"\t/* {placement.path} [{attr.name} = {expected}] */",
				f"\tif ({getter}(view) {operator} {expected}) {{",
				"\t\treturn SITU_ERR_CONSTRAINT;",
				"\t}",
			])

		return lines

	# -- helpers --------------------------------------------------------

	def _local(self, struct: ResolvedStruct, placement: Placement) -> str:
		return placement.path[len(struct.name) + 1 :]

	def _field_ctype(self, placement: Placement) -> str:
		"""The C type a field's accessors use.

		An enum field exposes its typedef rather than the backing width: the
		backing type is mandatory so that the layout is fixed (section 8.7), not
		so that callers have to remember which width it was.
		"""
		if placement.type_name in self.enums:
			return f"{ident(self.prefix, placement.type_name)}_t"

		scalar = placement.scalar
		assert scalar is not None
		return self._ctype(scalar)

	def _ctype(self, scalar: ScalarType) -> str:
		if scalar.kind is ScalarKind.FLOAT:
			return {16: "uint16_t", 32: "float", 64: "double"}[scalar.bits]

		width = _storage_width(scalar.bits)
		return f"int{width}_t" if scalar.signed else f"uint{width}_t"


def _storage_width(bits: int) -> int:
	for width in WORD_WIDTHS:
		if bits <= width:
			return width
	return 64


def _all_ones(bits: int) -> str:
	return f"0x{(1 << bits) - 1:X}u"


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str:
	"""Reserved behaviour, defaulting to must_be_zero (section 8.8).

	The default is deliberate: every ignored bit is a malleability surface, so
	the safe option is the silent one.
	"""
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one", "preserve", "unknown"):
			return attr.name
	return "must_be_zero"


def _host_is_little() -> bool:
	import sys
	return sys.byteorder == "little"
