"""Generate C11 accessors from a resolved schema.

The generated API exposes exactly the operations the capability vector supports
(project.md section 4). Where an operation is refused, the header says why and
what would have to change -- a user grepping for a missing setter has to find
the explanation in the header itself, not only in compiler output (section
20.2).

Principles that shape every line emitted here:

- **Views are values.** A view is a small struct passed by value. No allocation,
  no lifetime management.
- **Field access is a constant offset from the view base.** Accessors are
  `static inline` so they compile to `base + K`.
- **Errors are return codes.** Never errno, never longjmp.
- **Getters for ValueConverted fields return by value only.** A pointer into a
  byte-swapped field is a bug waiting to happen, so none is offered.
- **Nothing allocates, recurses, or uses a VLA.** Ever.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c.names import (
	c_name, check_collisions, ident, macro)
from situc.diagnostics import Diagnostic
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.types import ScalarKind, ScalarType

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Generated:
	"""The two files a schema compiles to, and what it had to say about them."""

	header: str
	source: str
	basename: str
	warnings: list[Diagnostic] = field(default_factory=list)

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.h": self.header, f"{self.basename}.c": self.source}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> Generated:
	# Before anything is emitted: two constructs that flatten to one C
	# identifier would otherwise surface as a redefinition error in generated
	# code, naming a function nobody wrote.
	warnings = check_collisions(resolved, prefix, [
		*(("struct", decl.name, decl.span) for decl in schema.structs()),
		*(("enum", decl.name, decl.span) for decl in schema.enums()),
	])

	emitter = Emitter(schema, resolved, basename, prefix)
	return Generated(
		header   = emitter.header(),
		source   = emitter.source(),
		basename = basename,
		warnings = warnings,
	)


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str, prefix: str) -> None:
		self.schema   = schema
		self.resolved = resolved
		self.basename = basename
		self.prefix   = prefix
		self.structs  = {decl.name: decl for decl in schema.structs()}
		self.enums    = {decl.name: decl for decl in schema.enums()}
		self.markers  = {decl.name: decl for decl in schema.markers()}
		self.codecs   = {decl.name: decl for decl in schema.codecs()}

	# -- header ---------------------------------------------------------

	def header(self) -> str:
		guard = macro(self.prefix, self.basename, "h")
		lines = [
			*self._banner(),
			f"#ifndef {guard}",
			f"#define {guard}",
			"",
			'#include "situ.h"',
			"",
			"#ifdef __cplusplus",
			'extern "C" {',
			"#endif",
		]

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		# Declaration order, not alphabetical: a struct's sub-view accessor
		# refers to the nested struct's SIZE_FIXED macro, so the nested one has
		# to be emitted first. The solver resolves dependencies before their
		# dependents, so its insertion order is already what C needs.
		for struct in self.resolved.structs.values():
			lines.extend(self._struct_header(struct))

		lines.extend([
			"",
			"#ifdef __cplusplus",
			"}",
			"#endif",
			"",
			f"#endif /* {guard} */",
		])
		return "\n".join(lines) + "\n"

	def _banner(self) -> list[str]:
		return [
			f"/* Generated by situc from {self.basename}.situ -- do not edit.",
			" *",
			" * The operations below are exactly the ones this schema's capability",
			" * vectors support. Where one is missing, a comment says why and what",
			" * would have to change; see the committed capability map for the full",
			" * picture.",
			" */",
			"",
		]

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		backing = decl.backing.scalar
		assert backing is not None
		values = self.resolved.layout.env.enums[decl.name]

		lines = [
			"",
			f"/* enum {decl.name} : {decl.backing.name}"
			f" -- unknown values are {decl.effective_default.value} */",
			f"typedef enum {ident(self.prefix, decl.name)} {{",
		]
		for member in decl.members:
			lines.append(f"\t{macro(self.prefix, decl.name, member.name)}"
			             f" = {values[member.name]},")
		lines.append(f"}} {ident(self.prefix, decl.name)}_t;")
		return lines

	def _struct_header(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		lines  = ["", f"/* ---- struct {struct.name} ---- */", ""]

		if not layout.is_byte_sized:
			lines.append(f"/* {struct.name} is {layout.size_bits} bits, not a whole")
			lines.append(" * number of bytes, so no accessors are generated for it. */")
			return lines

		lines.extend(self._size_constants(struct))
		lines.extend(self._tag_constants(struct))
		lines.extend(self._view_acquisition(struct))

		for entry in struct.entries:
			lines.extend(self._field(struct, entry))

		lines.extend(self._shifting_setters(struct))
		lines.extend(self._covered_setters(struct))
		lines.extend(self._validate_decl(struct))
		return lines

	# -- the cryptographic model (section 14) ---------------------------

	def _tags(self, struct: ResolvedStruct) -> list[Placement]:
		return [entry.placement for entry in struct.entries
		        if entry.placement.kind in ("tag", "checksum")]

	def _tag_bit(self, struct: ResolvedStruct, name: str) -> str:
		return macro(self.prefix, struct.name, name, "DIRTY")

	def _tag_constants(self, struct: ResolvedStruct) -> list[str]:
		"""One bit per tag, plus the mask of all of them.

		The bits are what a covered setter ORs into the message. Ordered as the
		tags are declared, so the numbering is stable across a rebuild and a
		caller may store one.
		"""
		tags = self._tags(struct)
		if not tags:
			return []

		lines = ["/* Tag dirty bits (section 14.2). A covered write sets one; the",
		         " * message refuses to be transmittable until it is cleared. */"]

		for index, placement in enumerate(tags):
			lines.append(f"#define {self._tag_bit(struct, placement.name)} "
			             f"{hex(1 << index)}u")

		mask = (1 << len(tags)) - 1
		lines.append(f"#define {macro(self.prefix, struct.name, 'DIRTY_MASK')} "
		             f"{hex(mask)}u")
		lines.append("")
		return lines

	def _tag_support(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		"""What a tag needs beyond its bytes: its coverage, and finalize.

		The algorithm is the caller's -- a signature says what a transform does,
		never how (section 13.1) -- so what the compiler contributes is the one
		thing only it knows: which bytes are covered, and whether they are
		currently stale.
		"""
		placement = entry.placement
		local     = c_name(self._local(struct, placement))
		name      = placement.name
		covers    = ", ".join(f"`{region}`" for region in placement.tag_covers)
		spans     = self._covered_spans(struct, placement)

		lines = [
			f"/* {name} covers {covers or 'nothing'}.",
			" *",
			" * The span below is what the algorithm runs over. Write the result",
			f" * through {ident(self.prefix, struct.name, local, 'ptr')}() and then",
			f" * call {ident(self.prefix, struct.name, local, 'finalize')}(), which",
			" * clears the dirty bit. Until then the message is not transmittable. */",
		]

		if spans is None:
			lines.extend([
				f"/* No covered-span accessor for `{name}`: the regions it covers are",
				" * not contiguous in this struct, so there is no single range to",
				" * hand out. Cover a contiguous run of regions instead. */",
			])
		else:
			first, last = spans
			lines.extend([
				f"static inline situ_err_t "
				f"{ident(self.prefix, struct.name, local, 'covered')}"
				"(situ_view_t view, uint32_t *offset, uint32_t *len)",
				"{",
				f"\tuint32_t start = {first};",
				f"\tuint32_t end   = {last};",
				"",
				"\tif (end < start || !situ_in_bounds(view, start, end - start)) {",
				"\t\treturn SITU_ERR_BOUNDS;",
				"\t}",
				"",
				"\t*offset = start;",
				"\t*len    = end - start;",
				"\treturn SITU_OK;",
				"}",
			])

		lines.extend([
			f"static inline int "
			f"{ident(self.prefix, struct.name, local, 'is_dirty')}"
			"(const situ_msg_t *msg)",
			"{",
			f"\treturn (msg->dirty & {self._tag_bit(struct, name)}) != 0u;",
			"}",
			f"static inline void "
			f"{ident(self.prefix, struct.name, local, 'finalize')}(situ_msg_t *msg)",
			"{",
			f"\tsitu_msg_clear_dirty(msg, {self._tag_bit(struct, name)});",
			"}",
		])

		return lines

	def _covered_spans(self, struct: ResolvedStruct,
			tag: Placement) -> tuple[str, str] | None:
		"""The byte range a tag authenticates, as two C expressions.

		Only a contiguous run has one. Nested coverage is contiguous by
		construction and disjoint coverage of adjacent regions usually is, but
		nothing guarantees it, so a gap is reported rather than papered over
		with a range that covers bytes the tag does not.
		"""
		regions = [entry.placement for entry in struct.entries
		           if entry.placement.name in tag.tag_covers
		           and entry.placement.kind in ("authenticated", "sealed")]
		if not regions:
			return None

		ordered = sorted(regions, key=lambda p: struct.layout.placements.index(p))

		for earlier, later in zip(ordered, ordered[1:]):
			if not self._is_adjacent(struct, earlier, later):
				return None

		return self._base_expression(struct, ordered[0]), self._region_end(struct,
		                                                                  ordered[-1])

	def _region_end(self, struct: ResolvedStruct, region: Placement) -> str:
		"""Where a region stops, as a C expression.

		Taken from where the next member starts rather than by summing the
		region's own contents. A region's extent is its interior put through a
		codec's expansion, and reconstructing that in C would duplicate the
		solver -- badly, since the interior is not addressable from outside the
		gate. The member after it already knows, and if nothing follows, the
		region runs to the end of the view.
		"""
		if region.is_fixed_size and region.offset_bits is not None:
			return f"{region.offset_bytes + region.size_bits // BITS_PER_BYTE}u"

		members = self._top_level(struct)
		index   = next(i for i, held in enumerate(members)
		               if held.path == region.path)

		if index + 1 < len(members):
			return self._base_expression(struct, members[index + 1])
		return "view.limit"

	def _is_adjacent(self, struct: ResolvedStruct, earlier: Placement,
			later: Placement) -> bool:
		"""Whether one region ends exactly where the next begins."""
		if (earlier.offset_bits is None or later.offset_bits is None
				or not earlier.is_fixed_size):
			return False
		return earlier.offset_bits + earlier.size_bits == later.offset_bits

	def _sealed_gate(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		"""The stage gate of 14.3, as a type C will not let a caller around.

		The interior accessors take `<struct>_<region>_t` and nothing produces
		one but the open function below, which demands the verification result.
		A caller holding a plain `situ_view_t` cannot reach a single interior
		field -- not by convention, but because the program does not compile.

		The gate wraps the enclosing frame's view rather than a sub-view, so an
		interior field stays the same constant offset it has everywhere else and
		the gate costs nothing at run time.
		"""
		placement = entry.placement
		local     = c_name(self._local(struct, placement))
		gate      = ident(self.prefix, struct.name, local, "t")
		tags      = ", ".join(placement.covered_by) or "its tag"

		if placement.unverified_ok:
			return [
				f"/* `{placement.name}` is `[allow_unverified_read]`: the stage gate",
				" * of section 14.3 is waived, and the interior accessors below take",
				" * an ordinary view. They run on bytes nobody has authenticated.",
				" *",
				" * This is the loud spelling on purpose. Removing the attribute",
				" * makes the interior unreachable before verification, which is the",
				" * single highest-value security property in the design. */",
			]

		return [
			f"/* A verified view into `{placement.name}`.",
			" *",
			" * Every accessor for the interior takes this type, and the only thing",
			f" * that produces one is {ident(self.prefix, struct.name, local, 'open')}(),",
			f" * which will not hand one out until {tags} has verified. Parsing",
			" * attacker-controlled plaintext before authenticating it is therefore",
			" * not discouraged here; it does not compile. */",
			f"typedef struct {gate} {{",
			"\tsitu_view_t view;",
			f"}} {gate};",
			"",
			f"static inline situ_err_t {ident(self.prefix, struct.name, local, 'open')}"
			f"(situ_view_t view, int verified, {gate} *out)",
			"{",
			"\tif (!verified) {",
			"\t\treturn SITU_ERR_TAG;",
			"\t}",
			"",
			"\tout->view = view;",
			"\treturn SITU_OK;",
			"}",
		]

	def _gate_type(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		"""The gated view type an interior field's accessors take, if gated."""
		if placement.sealed_by is None or placement.unverified_ok:
			return None
		return ident(self.prefix, struct.name, c_name(placement.sealed_by), "t")

	def _covered_setters(self, struct: ResolvedStruct) -> list[str]:
		"""Setters that mark a tag dirty, for the fields under one.

		These take the message, as the shifting setters do and for the same
		reason: the cost of the write shows up in the signature rather than in a
		comment somebody may not read. A field under a tag cannot be written
		without acknowledging that the tag now has to be recomputed.
		"""
		# Scalars only. An array's bytes are reached through its pointer
		# accessor, and a setter that wrote one element of it would be a worse
		# API than the pointer plus an explicit mark.
		covered = [entry for entry in struct.entries
		           if entry.placement.covered_by
		           and entry.placement.scalar is not None
		           and entry.placement.kind == "field"
		           and entry.placement.array_count is None
		           and entry.placement.sized_by is None
		           and entry.vector.get(Axis.MUTATE).base in ("InPlaceFixed",
		                                                      "InPlaceSlack")]
		if not covered:
			return []

		lines = ["", "/* Writing any of these leaves an authentication tag stale, so each",
		         " * one takes the message and marks the tag dirty. The message then",
		         " * refuses to be transmittable until the tag is recomputed and",
		         " * finalized (section 14.2). */"]

		for entry in covered:
			placement = entry.placement
			scalar    = placement.scalar
			assert scalar is not None

			local = c_name(self._local(struct, placement))
			ctype = self._field_ctype(placement)
			mask  = " | ".join(self._tag_bit(struct, tag)
			                   for tag in placement.covered_by)
			gate  = self._gate_type(struct, placement)
			view  = f"{gate} gate" if gate else "situ_view_t view"
			base  = self._value_base(struct, placement, gated=gate is not None)

			lines.extend([
				f"static inline void "
				f"{ident(self.prefix, struct.name, local, 'set')}"
				f"(situ_msg_t *msg, {view}, {ctype} value)",
				"{",
				f"\t{self._store_statement(scalar, placement, base, 'value', offset=self._value_offset(placement))}",
				f"\tsitu_msg_mark_dirty(msg, {mask});",
				"}",
			])

		return lines

	def _covered_pointer_note(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""A pointer into covered bytes cannot mark anything by itself.

		The scalar setters take the message and do it for the caller; a pointer
		hands over the bytes and leaves the obligation with them, so the header
		says which bit to set rather than leaving it to be inferred.
		"""
		if not placement.covered_by:
			return []

		mask = " | ".join(self._tag_bit(struct, tag) for tag in placement.covered_by)
		return [
			f"/* COVERAGE: writing through this pointer leaves "
			f"{', '.join(placement.covered_by)} stale.",
			f" * Call situ_msg_mark_dirty(msg, {mask}) after doing so; there is no",
			" * setter that can do it here, because a pointer write is not a call. */",
		]

	def _secret_note(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		"""No debug accessor, and a way to erase it (section 14.6)."""
		placement = entry.placement
		local     = c_name(self._local(struct, placement))
		gate      = self._gate_type(struct, placement)
		taken     = f"{gate} gate" if gate else "situ_view_t view"
		held      = "gate.view" if gate else "view"
		length    = self._length_expression(struct, placement, held)

		return [
			f"/* `{placement.name}` is `[secret]`. No debug or format accessor is",
			" * generated for it at all: that is the most common way key material",
			" * reaches a log. The accessors that do exist branch on nothing they",
			" * read, so the access pattern does not depend on the value.",
			" *",
			" * The erase goes through a volatile pointer, so it is observable",
			" * behaviour the compiler may not drop as a dead store. */",
			f"static inline void "
			f"{ident(self.prefix, struct.name, local, 'zeroize')}({taken})",
			"{",
			f"\tsitu_zeroize({held}.base + "
			f"{self._base_expression(struct, placement, gated=gate is not None)}, "
			f"{length});",
			"}",
		]

	def _size_constants(self, struct: ResolvedStruct) -> list[str]:
		"""So callers can size static buffers without running the compiler.

		SIZE_FIXED is emitted only when there is one. A frame has a range, and
		pretending otherwise would hand a caller a number that is wrong for
		every message but the shortest.
		"""
		layout = struct.layout
		name   = struct.name
		lines  = []

		if layout.is_fixed_size:
			lines.append(f"#define {macro(self.prefix, name, 'SIZE_FIXED')} "
			             f"{layout.size_bytes}u")

		lines.append(f"#define {macro(self.prefix, name, 'SIZE_MIN')}   "
		             f"{layout.size_bytes}u")

		if layout.size_max_bytes is not None:
			lines.append(f"#define {macro(self.prefix, name, 'SIZE_MAX')}   "
			             f"{layout.size_max_bytes}u")
		else:
			lines.extend([
				f"/* No {macro(self.prefix, name, 'SIZE_MAX')}: nothing in the "
				"schema bounds this",
				" * struct's length. Give the driving length field a `[max = N]`",
				" * to make it statically allocatable. */",
			])

		lines.append("")
		return lines

	def _view_acquisition(self, struct: ResolvedStruct) -> list[str]:
		"""One bounds check at the frame boundary (section 12.2).

		A fixed struct knows its own extent. A frame does not: how many bytes it
		occupies depends on the data, so the caller supplies what they have and
		the check is against that.
		"""
		layout = struct.layout
		name   = struct.name

		if layout.is_fixed_size:
			return [
				*self._invalidation_note(struct),
				"/* Acquire a view. This is the one bounds check; the field",
				" * accessors below are constant offsets from the view base. */",
				f"static inline situ_err_t {ident(self.prefix, name, 'view')}"
				"(const situ_msg_t *msg, uint32_t offset, situ_view_t *out)",
				"{",
				f"\treturn situ_view_at(msg, offset, "
				f"{macro(self.prefix, name, 'SIZE_FIXED')}, out);",
				"}",
			]

		lines = [
			*self._invalidation_note(struct),
			"/* Acquire a view. This struct is a frame: its extent depends on the",
			" * data, so the caller supplies the length they have and the bounds",
			" * check is made against that. The fields at a static offset are then",
			" * constant offsets from the base; the rest resolve through their own",
			" * offset functions below. */",
			f"static inline situ_err_t {ident(self.prefix, name, 'view')}"
			"(const situ_msg_t *msg, uint32_t offset, uint32_t length,",
			"\t\tsitu_view_t *out)",
			"{",
		]

		# A minimum of zero would compile to `length < 0u`, which no compiler
		# should have to be told is always false. The check is omitted rather
		# than emitted and suppressed: a check that cannot fire is noise.
		if layout.size_bytes > 0:
			lines.extend([
				f"\tif (length < {macro(self.prefix, name, 'SIZE_MIN')}) {{",
				"\t\treturn SITU_ERR_BOUNDS;",
				"\t}",
				"",
			])
		else:
			lines.append("\t/* No minimum: every member of this struct may be empty. */")

		lines.extend(["\treturn situ_view_at(msg, offset, length, out);", "}"])
		return lines

	def _drivers(self, struct: ResolvedStruct) -> list[str]:
		"""Fields whose value decides where later members start."""
		return sorted({
			placement.sized_by
			for placement in self._top_level(struct)
			if placement.sized_by and placement.sized_by != "remaining"
		})

	def _invalidation_note(self, struct: ResolvedStruct) -> list[str]:
		"""Document, per view type, exactly what invalidates it.

		Section 12.3 asks for this by name. The C type system cannot enforce
		view invalidation, so the generated header has to say what does it --
		otherwise the only record of the rule is in the compiler's head.
		"""
		drivers = self._drivers(struct)

		if not drivers:
			return [
				f"/* INVALIDATION: nothing invalidates a {struct.name} view.",
				" * Every member has a fixed size, so no write can move another.",
				" */",
			]

		listed = ", ".join(f"`{name}`" for name in drivers)
		return [
			f"/* INVALIDATION: a {struct.name} view, and every view derived from",
			f" * it, is invalidated by writing {listed} -- those decide where the",
			" * members after them start. Use the setters at the end of this",
			" * struct's section, which bump the message generation; a stale view",
			" * is then caught on use in a SITU_CHECKED build.",
			" *",
			" * Re-acquire the view after any such write.",
			" */",
		]

	def _shifting_setters(self, struct: ResolvedStruct) -> list[str]:
		"""Setters for fields that drive a length in this struct.

		Writing one of these moves every member after the region it sizes, so
		the message's generation has to be bumped: that is the only thing
		standing between a caller and a stale view (section 12.3). The setter
		therefore takes the message, which also makes the cost visible in the
		signature rather than only in a comment.
		"""
		drivers = self._drivers(struct)
		if not drivers:
			return []

		lines = ["", "/* Writing any of these changes where later members start, so each",
		         " * one bumps the message generation and invalidates outstanding",
		         " * views. In a SITU_CHECKED build a stale view is then caught on",
		         " * use; in a release build the check compiles out. */"]

		for path in drivers:
			target = self.resolved.find(f"{struct.name}.{path}")
			if target is None or target.placement.scalar is None:
				continue

			local = c_name(path)
			ctype = self._field_ctype(target.placement)
			store = self._store_statement(
				target.placement.scalar, target.placement,
				self._value_base(struct, target.placement), "value",
				offset=self._value_offset(target.placement))

			lines.extend([
				f"static inline void "
				f"{ident(self.prefix, struct.name, local, 'set')}"
				f"(situ_msg_t *msg, situ_view_t view, {ctype} value)",
				"{",
				f"\t{store}",
				"\tsitu_msg_touch(msg);",
				"}",
			])

		return lines

	# -- one field ------------------------------------------------------

	def _field(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement

		# An element entry describes every element of an array at once, so it
		# has no accessor of its own: the array field emits an indexed one.
		if placement.kind == "element":
			return []

		# A nested struct's members are emitted under their own struct, so only
		# the aggregate itself gets an accessor here. The interior of a sealed
		# region is the exception: its accessors take the gated view type, which
		# belongs to this struct, and the region's own type is a codec rather
		# than something with a section of its own. Checked before the reserved
		# case, or a nested reserved region would be noted twice.
		nested = "." in placement.path[len(struct.name) + 1 :]
		if nested and placement.sealed_by is None:
			return []

		if placement.kind == "reserved":
			return self._reserved_note(placement)

		lines = ["", *self._field_comment(entry)]

		if placement.kind in ("tag", "checksum"):
			# A tag lands after everything it covers, so its own offset is
			# usually dynamic and has to be resolved before either its bytes or
			# its covered span can be reached.
			if placement.offset_bits is None:
				lines.extend(self._offset_function(struct, placement))
			lines.extend(self._array(struct, entry))
			lines.extend(self._tag_support(struct, entry))
			return lines

		if placement.kind == "sealed":
			lines.extend(self._sealed_gate(struct, entry))
			return lines

		if placement.kind == "authenticated":
			lines.extend(self._authenticated_note(struct, entry))
			return lines

		if placement.kind == "marker":
			lines.extend(self._marker(struct, placement))
			return lines

		if placement.varint is not None:
			lines.extend(self._varint_note(placement))
			return lines

		if placement.kind == "variant":
			lines.extend(self._variant_note(placement))
			return lines

		if placement.kind in ("opaque", "indexed"):
			lines.extend(self._region_note(struct, entry))
			return lines

		# A dynamically placed member needs its offset worked out at runtime
		# before anything can read it.
		if placement.offset_bits is None:
			lines.extend(self._offset_function(struct, placement))

		if placement.type_name in self.structs:
			if self._is_array(placement):
				lines.extend(self._element_view(struct, placement))
			else:
				lines.extend(self._sub_view(struct, placement))
			return lines

		if placement.array_count is not None or placement.sized_by is not None:
			lines.extend(self._array(struct, entry))
			lines.extend(self._covered_pointer_note(struct, placement))
			if _has_attr(placement.attrs, "secret"):
				lines.extend(self._secret_note(struct, entry))
			return lines

		lines.extend(self._scalar_get(struct, entry))
		lines.extend(self._scalar_set(struct, entry))
		if _has_attr(placement.attrs, "secret"):
			lines.extend(self._secret_note(struct, entry))
		return lines

	def _authenticated_note(self, struct: ResolvedStruct,
			entry: Resolved) -> list[str]:
		"""A region with no accessor of its own, and a warning that matters.

		Its members keep their own accessors at their own offsets -- the block
		moves nothing. What it changes is the cost of writing them, and where a
		member is reached through a sub-view of another type that cost is not
		visible in that type's accessors, so it is said here.
		"""
		placement = entry.placement
		tags      = ", ".join(f"`{tag}`" for tag in placement.covered_by)

		return [
			f"/* COVERAGE: the bytes of `{placement.name}` are authenticated by",
			f" * {tags or 'no tag'}. Writing any of them through this struct's",
			" * coverage-aware setters marks the tag dirty; writing them through a",
			" * sub-view of another struct type does not, because that type has no",
			" * coverage of its own. Prefer the setters at the end of this",
			" * struct's section. */",
		]

	def _field_comment(self, entry: Resolved) -> list[str]:
		placement = entry.placement
		vector    = entry.vector
		offset    = vector.get(Axis.OFFSET).render()
		axes      = " ".join(
			f"{axis.value}={vector.get(axis).render()}"
			for axis in (Axis.SIZE, Axis.ALIGN, Axis.REPR, Axis.ATOMIC, Axis.MUTATE))

		return [
			f"/* {placement.path} : {placement.type_name}  at {offset}",
			f" * {axes}",
			" */",
		]

	def _region_note(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		"""An opaque or indexed region: bytes now, structure later.

		An opaque region gets a pointer and a length, which is exactly what its
		capability vector supports -- treat-as-bytes and nothing more. An
		indexed one needs the offset table walked, which is later phase 6 work.
		"""
		placement = entry.placement
		local     = c_name(self._local(struct, placement))
		base      = self._base_expression(struct, placement)

		if placement.kind == "indexed":
			return [
				f"/* No accessor: `{placement.name}` is an `indexed` region, whose",
				" * elements are reached through an offset table. Table walking is",
				" * not generated yet. Insertion is not an operation here at all:",
				" * every offset after the insertion point would have to move. */",
			]

		return [
			"/* Treat-as-bytes, which is the whole of what an `opaque` region",
			" * supports: no interior access, and whole-region replacement only",
			" * at the same size. */",
			f"static inline uint32_t "
			f"{ident(self.prefix, struct.name, local, 'len')}(situ_view_t view)",
			"{",
			f"	return {self._length_expression(struct, placement)};",
			"}",
			f"static inline uint8_t *"
			f"{ident(self.prefix, struct.name, local, 'ptr')}(situ_view_t view)",
			"{",
			f"	return view.base + {base};",
			"}",
		]

	def _variant_note(self, placement: Placement) -> list[str]:
		"""A variant has no accessor of its own: exactly one arm is present.

		Which one depends on the discriminant, so reaching the members means
		reading it first and taking the matching arm's view. Arm dispatch is
		later phase 6 codegen work.
		"""
		arms = ", ".join(f"`{name}`" for name, _ in placement.arm_sizes)
		return [
			f"/* No accessor: `{placement.name}` is a variant, so exactly one of",
			f" * its arms is present{f' ({arms})' if arms else ''}. Arm dispatch",
			" * is not generated yet; read the discriminant and take the matching",
			" * arm's view. */",
		]

	def _varint_note(self, placement: Placement) -> list[str]:
		"""A varint has no constant-offset accessor to generate.

		Its width is not known until it is read, so there is no `base + K` for
		this field and none for anything after it in the same frame. Decoding
		them is phase 6 codegen work; refusing to emit an accessor is better
		than emitting one that pretends the width is fixed.
		"""
		return [
			f"/* No accessor: `{placement.name}` is a `{placement.varint}`, whose",
			" * width is not known until it is read. Varint decoding is not",
			" * generated yet; the capability map already records what the field",
			" * costs. */",
		]

	def _reserved_note(self, placement: Placement) -> list[str]:
		return [
			"",
			f"/* {placement.path} : {placement.type_name} -- reserved, no accessor.",
			" * Reserved regions are validated on parse, not exposed; see the",
			" * validate function below. */",
		]

	def _marker(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		"""The byte-order marker's constants and accessors (section 8.3).

		The marker is compared as a byte sequence, not decoded as a number: it
		has to be readable before its own byte order is known. Reading it big
		endian and comparing against the literal as written is the only
		interpretation that does not presuppose the answer.

		The host constant is what a writer uses instead of hardcoding an order,
		which is what makes the writer deterministic even though the format is
		not canonical.
		"""
		from situc.expr import evaluate

		marker = self.markers[placement.name]
		scalar = placement.scalar
		assert scalar is not None

		env    = self.resolved.layout.env
		little = evaluate(marker.little, env)
		big    = evaluate(marker.big, env)
		width  = scalar.bits
		base   = macro(self.prefix, struct.name, placement.name)
		local  = c_name(self._local(struct, placement))

		return [
			f"#define {base}_LITTLE 0x{little:0{width // 4}X}u",
			f"#define {base}_BIG    0x{big:0{width // 4}X}u",
			"",
			"/* The host's own order, resolved at compile time. A writer stores",
			" * this rather than picking an order, so the writer is deterministic",
			" * even though the format admits both. */",
			"#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__",
			f"#define {base}_HOST {base}_BIG",
			"#else",
			f"#define {base}_HOST {base}_LITTLE",
			"#endif",
			"",
			f"static inline int "
			f"{ident(self.prefix, struct.name, local, 'is_little')}(situ_view_t view)",
			"{",
			f"\treturn situ_get_be{width}(view.base + {placement.offset_bytes}u)"
			f" == {base}_LITTLE;",
			"}",
			f"static inline uint{width}_t "
			f"{ident(self.prefix, struct.name, local, 'host')}(void)",
			"{",
			f"\treturn {base}_HOST;",
			"}",
			f"static inline void "
			f"{ident(self.prefix, struct.name, local, 'set_host')}(situ_view_t view)",
			"{",
			f"\tsitu_put_be{width}(view.base + {placement.offset_bytes}u, {base}_HOST);",
			"}",
		]

	def _value_base(self, struct: ResolvedStruct, placement: Placement,
			gated: bool = False) -> str:
		"""The pointer a scalar accessor loads from.

		A statically placed field reads from the view base at a constant
		displacement. A dynamically placed one has its offset resolved first,
		so the displacement folds into the pointer and the load itself stays a
		single access.

		A gated accessor reads through the wrapper's view, which is the same
		frame view: the gate is a compile-time obligation, not a different base,
		so the load is still `base + K`.
		"""
		base = "gate.view.base" if gated else "view.base"
		if placement.offset_bits is not None:
			return base
		return f"({base} + {self._base_expression(struct, placement, gated)})"

	def _value_offset(self, placement: Placement) -> int | None:
		return None if placement.offset_bits is not None else 0

	def _is_array(self, placement: Placement) -> bool:
		return self.resolved.find(placement.path + "[]") is not None

	def _base_expression(self, struct: ResolvedStruct, placement: Placement,
			gated: bool = False) -> str:
		"""Where this member starts, in bytes, as a C expression."""
		if placement.offset_bits is not None:
			return f"{placement.offset_bytes}u"
		local    = c_name(self._local(struct, placement))
		argument = "gate.view" if gated else "view"
		return f"{ident(self.prefix, struct.name, local, 'offset')}({argument})"

	def _top_level(self, struct: ResolvedStruct) -> list[Placement]:
		"""The struct's own members, in order, partitioning its bytes exactly.

		An `authenticated` region is left out: it consumes no bytes of its own,
		it names bytes its members already account for, and counting both would
		double every offset after it. A `sealed` region stays, because its
		members are the codec's output and are not in this list.
		"""
		return [
			entry.placement for entry in struct.entries
			if entry.placement.kind not in ("element", "authenticated")
			and "." not in entry.placement.path[len(struct.name) + 1 :]
		]

	def _offset_function(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""Resolve a dynamic offset by summing what precedes it.

		Everything before the first variable-length member contributes a
		constant; each variable-length member contributes its own length, read
		from the field that drives it. That field always has a static offset,
		because a size expression may only name a field declared before it and
		everything before the first dynamic member is statically placed.
		"""
		local    = c_name(self._local(struct, placement))
		constant = 0
		terms    = []

		for other in self._top_level(struct):
			if other.path == placement.path:
				break
			if other.is_fixed_size:
				constant += other.size_bits // BITS_PER_BYTE
				continue
			if not self._has_length(struct, other):
				return self._unresolvable_offset(placement, other)
			terms.append(self._length_expression(struct, other))

		lines = [
			f"static inline uint32_t "
			f"{ident(self.prefix, struct.name, local, 'offset')}(situ_view_t view)",
			"{",
			f"\tuint32_t offset = {constant}u;",
		]
		for term in terms:
			lines.append(f"\toffset = offset + ({term});")

		if not terms:
			lines.append("\t(void)view;")

		lines.extend(["", "\treturn offset;", "}"])
		return lines

	def _unresolvable_offset(self, placement: Placement,
			blocker: Placement) -> list[str]:
		"""No offset function, and the reason, where it will be looked for.

		A region whose codec expands by a bounded ratio or without bound has no
		length until it is decoded, so nothing after it has an offset either.
		Emitting arithmetic that ignored that would put every later accessor on
		the wrong bytes, which is the one failure mode worse than a missing
		accessor.
		"""
		return [
			f"/* No accessor for `{placement.name}`: it starts after "
			f"`{blocker.name}`, whose",
			f" * codec `{blocker.type_name}` has no closed-form expansion, so how many",
			" * bytes it occupies is not known until it has been decoded.",
			" *",
			" * A `length_preserving` codec, or one with a fixed or exact-ratio",
			" * expansion, keeps the members after it addressable. */",
		]

	def _length_expression(self, struct: ResolvedStruct, placement: Placement,
			held: str = "view") -> str:
		"""How many bytes a variable-length member occupies, at runtime.

		`held` names the view in scope, which is `gate.view` inside a sealed
		region: the length is read from a plaintext field at the same offsets,
		through whichever view the caller holds.
		"""
		gated = held != "view"

		if placement.kind in ("coded", "sealed"):
			length = self._region_length(struct, placement, held)
			assert length is not None, "callers check _has_length first"
			return length

		if placement.kind == "opaque":
			# An opaque region's size expression is already a byte count; there
			# are no elements to multiply by.
			return f"(uint32_t){self._count_expression(struct, placement, held)}"

		element = (placement.element_bits or BITS_PER_BYTE) // BITS_PER_BYTE

		if placement.sized_by == "remaining":
			return (f"{held}.limit - "
			        f"{self._base_expression(struct, placement, gated)}")

		count = self._count_expression(struct, placement, held)
		return f"(uint32_t){count}" if element == 1 else f"(uint32_t){count} * {element}u"

	def _region_length(self, struct: ResolvedStruct, region: Placement,
			held: str = "view") -> str | None:
		"""How many bytes a coded or sealed region occupies, at runtime.

		Its interior extent put through the codec's expansion, which is the
		same rule the solver applies and the only one available: the region's
		bytes are the transform's output, so nothing in them can be read to find
		out how many there are.

		None where the expansion has no closed form -- a bounded ratio or an
		unbounded one -- because then the length genuinely is not computable
		without decoding, and a wrong number here would silently misplace every
		member after it.
		"""
		codec = self.codecs.get(region.type_name)
		if codec is None:
			return None

		prefix   = region.path + "."
		interior = [entry.placement for entry in struct.entries
		            if entry.placement.path.startswith(prefix)
		            and "." not in entry.placement.path[len(prefix):]
		            and entry.placement.kind != "element"]

		constant = 0
		terms    = []
		for member in interior:
			if member.is_fixed_size:
				constant += member.size_bits // BITS_PER_BYTE
			else:
				terms.append(self._length_expression(struct, member, held))

		inner = " + ".join([f"{constant}u", *(f"({term})" for term in terms)])

		if codec.expansion is ast.Expansion.PRESERVING:
			return inner
		if codec.expansion is ast.Expansion.FIXED_ADD:
			return f"({inner}) + {codec.expansion_add}u"
		if codec.expansion is ast.Expansion.RATIO_EXACT:
			assert codec.ratio is not None
			out, into = codec.ratio
			return f"(({inner}) * {out}u) / {into}u"

		return None

	def _has_length(self, struct: ResolvedStruct, placement: Placement) -> bool:
		"""Whether a member's runtime extent has a closed form."""
		if placement.kind not in ("coded", "sealed"):
			return True
		return self._region_length(struct, placement) is not None

	def _count_expression(self, struct: ResolvedStruct, placement: Placement,
			held: str = "view") -> str:
		"""Read the field that drives a member's length.

		Usually a constant-offset load, but not always: the driving field has to
		precede the member it sizes, which does not mean it precedes every
		dynamic member. A second variable-length region can be counted by a
		field that is itself dynamically placed, so this goes through the same
		base resolution as any other read.
		"""
		if placement.sized_by is None:
			return f"{placement.array_count or 0}u"

		target = self.resolved.find(f"{struct.name}.{placement.sized_by}")
		if target is None or target.placement.scalar is None:
			return f"{placement.array_count or 0}u"

		loaded = self._load_expression(
			target.placement.scalar, target.placement,
			self._value_base(struct, target.placement, gated=held != "view"),
			offset=self._value_offset(target.placement))
		return f"({loaded})"

	def _element_view(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""Indexed access to one element of an array of structs.

		Acquiring the element view is the bounds check; the fields inside it are
		then constant offsets from its base (section 12.2). That is what gives a
		dynamically positioned static struct its static capabilities back, and
		why the accessors inside `Record` are the same ones a standalone
		`Record` would have.
		"""
		local  = c_name(self._local(struct, placement))
		nested = placement.type_name
		base   = self._base_expression(struct, placement)
		lines  = []

		if placement.array_count is not None:
			lines.append(f"#define {macro(self.prefix, struct.name, local, 'COUNT')} "
			             f"{placement.array_count}u")
		else:
			lines.extend([
				f"static inline uint32_t "
				f"{ident(self.prefix, struct.name, local, 'count')}(situ_view_t view)",
				"{",
				f"\treturn (uint32_t){self._count_expression(struct, placement)};",
				"}",
			])

		lines.extend([
			f"static inline situ_err_t "
			f"{ident(self.prefix, struct.name, local, 'at')}"
			"(situ_view_t view, uint32_t index, situ_view_t *out)",
			"{",
			f"\tconst uint32_t stride = {macro(self.prefix, nested, 'SIZE_FIXED')};",
			f"\tconst uint32_t base   = {base};",
			"",
			"\treturn situ_view_sub(view, base + index * stride, stride, out);",
			"}",
		])
		return lines

	def _sub_view(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		nested = placement.type_name
		base   = self._base_expression(struct, placement)
		return [
			f"static inline situ_err_t "
			f"{ident(self.prefix, struct.name, c_name(self._local(struct, placement)), 'view')}"
			"(situ_view_t view, situ_view_t *out)",
			"{",
			f"\treturn situ_view_sub(view, {base}, "
			f"{macro(self.prefix, nested, 'SIZE_FIXED')}, out);",
			"}",
		]

	def _array(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		local     = c_name(self._local(struct, placement))
		scalar    = placement.scalar
		count     = placement.array_count
		assert scalar is not None

		gate  = self._gate_type(struct, placement)
		taken = f"{gate} gate" if gate else "situ_view_t view"
		held  = "gate.view" if gate else "view"

		lines = []
		if count is not None:
			lines.append(
				f"#define {macro(self.prefix, struct.name, local, 'COUNT')} {count}u")
		else:
			# A run-time length: the count comes from the field that drives it,
			# and `remaining` measures to the end of the view.
			lines.extend([
				f"static inline uint32_t "
				f"{ident(self.prefix, struct.name, local, 'len')}({taken})",
				"{",
				f"\treturn {self._length_expression(struct, placement, held)};",
				"}",
			])

		if scalar.bits == BITS_PER_BYTE:
			# A byte array is the bytes: MemoryIdentical, so a pointer is safe
			# and is what callers actually want.
			lines.extend(self._address_note(entry))
			lines.extend([
				f"static inline uint8_t *"
				f"{ident(self.prefix, struct.name, local, 'ptr')}({taken})",
				"{",
				f"\treturn {held}.base + "
				f"{self._base_expression(struct, placement, gated=gate is not None)};",
				"}",
			])
			return lines

		lines.extend([
			f"/* No pointer accessor: the element type is {placement.type_name},",
			" * which is ValueConverted, so a pointer into it would alias bytes",
			" * that are not the value. Index the elements individually. */",
		])
		lines.extend(self._indexed_element(struct, entry, local, scalar))
		return lines

	def _indexed_element(self, struct: ResolvedStruct, entry: Resolved,
			local: str, scalar: ScalarType) -> list[str]:
		placement = entry.placement
		ctype     = self._field_ctype(placement)
		stride    = scalar.bits // BITS_PER_BYTE
		getter    = ident(self.prefix, struct.name, local, "get")

		base = self._base_expression(struct, placement)
		load = self._load_expression(
			scalar, placement, f"view.base + {base} + index * {stride}u", offset=0)
		return [
			f"static inline {ctype} {getter}(situ_view_t view, uint32_t index)",
			"{",
			f"\treturn ({ctype})({load});",
			"}",
		]

	# -- scalars --------------------------------------------------------

	def _scalar_get(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None:
			return []

		local  = c_name(self._local(struct, placement))
		ctype  = self._field_ctype(placement)
		getter = ident(self.prefix, struct.name, local, "get")
		gate   = self._gate_type(struct, placement)
		taken  = f"{gate} gate" if gate else "situ_view_t view"
		base   = self._value_base(struct, placement, gated=gate is not None)
		load   = self._load_expression(scalar, placement, base,
		                               offset=self._value_offset(placement))

		lines = [
			f"static inline {ctype} {getter}({taken})",
			"{",
			f"\treturn ({ctype})({load});",
			"}",
		]

		# A pointer accessor is offered only where the value is literally the
		# bytes. Section 20.2: never hand out a pointer into a converted field.
		if (entry.vector.get(Axis.REPR).base == "MemoryIdentical"
				and not scalar.is_bit_packed
				and placement.kind != "marker"
				and placement.type_name not in self.enums):
			lines.extend(self._address_note(entry))
			lines.extend([
				f"static inline {self._ctype(scalar)} *"
				f"{ident(self.prefix, struct.name, local, 'ptr')}({taken})",
				"{",
				f"\treturn ({self._ctype(scalar)} *)"
				f"({'gate.view.base' if gate else 'view.base'} + "
				f"{self._base_expression(struct, placement, gated=gate is not None)});",
				"}",
			])

		return lines

	def _scalar_set(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None:
			return []

		refusal = self._setter_refusal(entry)
		if refusal is not None:
			return refusal

		# A field that drives a length gets one setter, not two: writing it
		# moves later members, so it has to bump the generation. The shifting
		# setter at the end of this struct's section is that one.
		local_path = self._local(struct, placement)
		if local_path in self._drivers(struct):
			return [
				f"/* No plain setter: `{local_path}` decides where later members",
				" * start, so writing it must invalidate outstanding views. Use",
				f" * {ident(self.prefix, struct.name, c_name(local_path), 'set')}(),",
				" * which takes the message and bumps its generation. */",
			]

		# A field under a tag gets one setter, not two: writing it leaves the tag
		# stale, so it has to mark the message dirty. The coverage-aware setter
		# at the end of this struct's section is that one.
		if placement.covered_by:
			return [
				f"/* No plain setter: `{placement.name}` is covered by "
				f"{', '.join(placement.covered_by)}, so",
				" * writing it leaves the tag stale. Use",
				f" * {ident(self.prefix, struct.name, c_name(self._local(struct, placement)), 'set')}(),",
				" * which takes the message and marks the tag dirty. */",
			]

		local = c_name(self._local(struct, placement))
		ctype = self._field_ctype(placement)
		setter = ident(self.prefix, struct.name, local, "set")

		base = self._value_base(struct, placement)
		return [
			f"static inline void {setter}(situ_view_t view, {ctype} value)",
			"{",
			f"\t{self._store_statement(scalar, placement, base, 'value', offset=self._value_offset(placement))}",
			"}",
		]

	def _address_note(self, entry: Resolved) -> list[str]:
		"""Say how long a pointer stays good.

		The pointer is valid now; what varies is what invalidates it. Section
		11.1's address axis exists to answer exactly that, so the answer belongs
		beside the accessor rather than only in the map.
		"""
		address = entry.vector.get(Axis.ADDRESS).base

		if address == "Stable":
			return []

		if address == "FrameStable":
			return ["/* The returned pointer is valid while the enclosing frame's",
			        " * base does not move. */"]

		return ["/* The returned pointer is invalidated by any write that changes",
		        " * the length of what precedes this field; see the INVALIDATION",
		        " * note on this struct's view accessor. */"]

	def _setter_refusal(self, entry: Resolved) -> list[str] | None:
		"""Explain a missing setter, in the header, where it will be looked for.

		A missing setter with no explanation is hostile (project.md section 4).
		The text is the same blame chain `situc explain` prints.
		"""
		mutate = entry.vector.get(Axis.MUTATE)
		if mutate.base in ("InPlaceFixed", "InPlaceSlack"):
			return None

		lines = [f"/* No setter: mutate is {mutate.render()}."]
		for weakening in entry.blame(Axis.MUTATE):
			lines.append(f" *   caused by: {weakening.rule.construct}")
			lines.append(f" *              {weakening.effect.because}")
			if weakening.rule.remedy:
				lines.append(f" *   remedy:    {weakening.rule.remedy}")
		lines.append(" */")
		return lines

	def _load_expression(self, scalar: ScalarType, placement: Placement,
			base: str, offset: int | None = None) -> str:
		offset = placement.offset_bytes if offset is None else offset

		if placement.marker is not None and not scalar.is_bit_packed \
				and scalar.bits > BITS_PER_BYTE:
			return self._conditional_load(scalar, placement, base)

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			raw   = (f"situ_bits_get_{order}({base}, {placement.offset_bits}u, "
			         f"{scalar.bits}u)")
			if scalar.signed:
				return f"({self._ctype(scalar)})situ_sign_extend({raw}, {scalar.bits}u)"
			return f"({self._ctype(scalar)}){raw}"

		if scalar.bits == BITS_PER_BYTE:
			cast = self._ctype(scalar)
			return f"({cast})({base})[{offset}u]"

		suffix = "le" if placement.endian is ast.Endian.LITTLE else "be"
		if placement.endian is ast.Endian.NATIVE:
			suffix = "le" if _host_is_little() else "be"

		width = scalar.bits
		if width in WORD_WIDTHS:
			raw = f"situ_get_{suffix}{width}({base} + {offset}u)"
			return f"({self._ctype(scalar)}){raw}" if scalar.signed else raw

		# Non-word whole-byte widths (u24, u48) go through the bit path, which
		# handles any width without a special case.
		raw = f"situ_bits_get_msb({base}, {placement.offset_bits}u, {width}u)"
		if placement.endian is ast.Endian.LITTLE:
			raw = f"situ_bits_get_lsb({base}, {placement.offset_bits}u, {width}u)"
		if scalar.signed:
			return f"({self._ctype(scalar)})situ_sign_extend({raw}, {width}u)"
		return f"({self._ctype(scalar)}){raw}"

	def _conditional_load(self, scalar: ScalarType, placement: Placement,
			base: str) -> str:
		"""A parse-time branch on the marker.

		The branch is on a public, layout-irrelevant value, so it is not a side
		channel (section 11.1).
		"""
		predicate = self._marker_predicate(placement)
		width     = scalar.bits
		offset    = placement.offset_bytes
		if width in WORD_WIDTHS:
			return (f"{predicate} ? situ_get_le{width}({base} + {offset}u)"
			        f" : situ_get_be{width}({base} + {offset}u)")

		bits = placement.offset_bits
		return (f"{predicate} ? situ_bits_get_lsb({base}, {bits}u, {width}u)"
		        f" : situ_bits_get_msb({base}, {bits}u, {width}u)")

	def _marker_predicate(self, placement: Placement) -> str:
		owner = placement.path.partition(".")[0]
		return ident(self.prefix, owner, placement.marker or "", "is_little") + "(view)"

	def _store_statement(self, scalar: ScalarType, placement: Placement,
			base: str, value: str, offset: int | None = None) -> str:
		offset = placement.offset_bytes if offset is None else offset

		if placement.marker is not None and not scalar.is_bit_packed \
				and scalar.bits > BITS_PER_BYTE:
			width     = scalar.bits
			predicate = self._marker_predicate(placement)
			if width in WORD_WIDTHS:
				return (f"if ({predicate}) {{\n"
				        f"\t\tsitu_put_le{width}({base} + {offset}u, "
				        f"(uint{width}_t){value});\n"
				        f"\t}} else {{\n"
				        f"\t\tsitu_put_be{width}({base} + {offset}u, "
				        f"(uint{width}_t){value});\n"
				        f"\t}}")
			bits = placement.offset_bits
			return (f"if ({predicate}) {{\n"
			        f"\t\tsitu_bits_set_lsb({base}, {bits}u, {width}u, "
			        f"(uint64_t){value});\n"
			        f"\t}} else {{\n"
			        f"\t\tsitu_bits_set_msb({base}, {bits}u, {width}u, "
			        f"(uint64_t){value});\n"
			        f"\t}}")

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			return (f"situ_bits_set_{order}({base}, {placement.offset_bits}u, "
			        f"{scalar.bits}u, (uint64_t){value});")

		if scalar.bits == BITS_PER_BYTE:
			return f"({base})[{offset}u] = (uint8_t){value};"

		suffix = "le" if placement.endian is ast.Endian.LITTLE else "be"
		if placement.endian is ast.Endian.NATIVE:
			suffix = "le" if _host_is_little() else "be"

		width = scalar.bits
		if width in WORD_WIDTHS:
			return (f"situ_put_{suffix}{width}({base} + {offset}u, "
			        f"(uint{width}_t){value});")

		order = "lsb" if placement.endian is ast.Endian.LITTLE else "msb"
		return (f"situ_bits_set_{order}({base}, {placement.offset_bits}u, "
		        f"{width}u, (uint64_t){value});")

	# -- validation -----------------------------------------------------

	def _validate_decl(self, struct: ResolvedStruct) -> list[str]:
		return [
			"",
			"/* Check every constraint this schema states: [must_eq], [max],",
			" * [min], and the reserved-bit policy. Called on parse under",
			" * SITU_CHECKED, and available explicitly in any build. */",
			f"situ_err_t {ident(self.prefix, struct.name, 'validate')}(situ_view_t view);",
		]

	def source(self) -> str:
		lines = [
			*self._banner(),
			f'#include "{self.basename}.h"',
			"",
		]

		for struct in self.resolved.structs.values():
			if struct.layout.is_byte_sized:
				lines.extend(self._validate_body(struct))

		return "\n".join(lines) + "\n"

	def _validate_body(self, struct: ResolvedStruct) -> list[str]:
		lines = [
			f"situ_err_t {ident(self.prefix, struct.name, 'validate')}(situ_view_t view)",
			"{",
		]

		checks = []
		for entry in struct.entries:
			checks.extend(self._checks_for(struct, entry))

		if not checks:
			lines.append("\t(void)view;")
		else:
			lines.extend(checks)

		lines.extend(["\treturn SITU_OK;", "}", ""])
		return lines

	def _checks_for(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		if scalar is None or placement.array_count is not None:
			return []
		if placement.kind == "marker":
			return []
		if "." in placement.path[len(struct.name) + 1 :]:
			return []

		local  = c_name(self._local(struct, placement))
		lines  = []

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				expect = "0" if policy == "must_be_zero" else _all_ones(scalar.bits)
				read   = self._load_expression(scalar, placement, "view.base")
				lines.extend([
					f"\t/* reserved {placement.type_name} [{policy}] */",
					f"\tif ({read} != {expect}) {{",
					"\t\treturn SITU_ERR_CONSTRAINT;",
					"\t}",
				])
			return lines

		getter = ident(self.prefix, struct.name, local, "get")
		env    = self.resolved.layout.env

		for attr in placement.attrs:
			if attr.name not in ("must_eq", "max", "min") or attr.value is None:
				continue

			from situc.expr import evaluate
			expected = evaluate(attr.value, env)
			operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
			lines.extend([
				f"\t/* {placement.path} [{attr.name} = {expected}] */",
				f"\tif ({getter}(view) {operator} {expected}) {{",
				"\t\treturn SITU_ERR_CONSTRAINT;",
				"\t}",
			])

		return lines

	# -- helpers --------------------------------------------------------

	def _local(self, struct: ResolvedStruct, placement: Placement) -> str:
		return placement.path[len(struct.name) + 1 :]

	def _field_ctype(self, placement: Placement) -> str:
		"""The C type a field's accessors use.

		An enum field exposes its typedef rather than the backing width: the
		backing type is mandatory so that the layout is fixed (section 8.7), not
		so that callers have to remember which width it was.
		"""
		if placement.type_name in self.enums:
			return f"{ident(self.prefix, placement.type_name)}_t"

		scalar = placement.scalar
		assert scalar is not None
		return self._ctype(scalar)

	def _ctype(self, scalar: ScalarType) -> str:
		if scalar.kind is ScalarKind.FLOAT:
			return {16: "uint16_t", 32: "float", 64: "double"}[scalar.bits]

		width = _storage_width(scalar.bits)
		return f"int{width}_t" if scalar.signed else f"uint{width}_t"


def _storage_width(bits: int) -> int:
	for width in WORD_WIDTHS:
		if bits <= width:
			return width
	return 64


def _all_ones(bits: int) -> str:
	return f"0x{(1 << bits) - 1:X}u"


def _has_attr(attrs: tuple[ast.Attr, ...], name: str) -> bool:
	return any(attr.name == name for attr in attrs)


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str:
	"""Reserved behaviour, defaulting to must_be_zero (section 8.8).

	The default is deliberate: every ignored bit is a malleability surface, so
	the safe option is the silent one.
	"""
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one", "preserve", "unknown"):
			return attr.name
	return "must_be_zero"


def _host_is_little() -> bool:
	import sys
	return sys.byteorder == "little"
