"""Generate a fuzz harness per parseable struct.

Parse safety is the top risk in a protocol parser (project.md section 20.3), and
a harness the schema author has to write themselves is a harness that does not
get written. This one is derived from the layout, so it exercises every accessor
the schema has without anybody maintaining a list.

The entry point is libFuzzer's, because that is what the CI in section 22 runs.
A standalone `main` reading stdin is emitted alongside it under
`SITU_FUZZ_STANDALONE`, so the harness can be compiled and smoke-tested with a
plain compiler -- a harness nobody can build is the other way this rots.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.c.names import c_name, ident, macro
from situc.layout import Placement
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import has_computable_extent, own_entries


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> str:
	# A register is a bus transaction, not bytes off a wire: it has no view,
	# no `validate`, and its accessors take a device handle rather than one.
	# `gen-dissector` has excluded them since it was written and this did not,
	# which cost nothing while no register schema was fuzzed.
	# `size_bytes > 0` was here too, and it dropped the one schema whose
	# whole point is a construct nothing else in the tree has:
	# `examples/protobuf` is a bare `tlv` region, so its minimum size is zero
	# and it was filtered out of fuzzing entirely. The harness still compiled,
	# still ran under the smoke test, and exercised nothing -- 16 million
	# executions at coverage 1, which is what an empty `LLVMFuzzerTestOneInput`
	# looks like from the outside. A struct with nothing to read is skipped
	# below, where that is decided by what it reads rather than by a bound.
	structs = [struct for struct in resolved.structs.values()
	           if struct.layout.is_byte_sized
	           and struct.layout.register is None
	           and not (struct.layout.is_fixed_size
	                    and struct.layout.size_bytes == 0)]

	# The harnesses first: whether the sink is needed is a question about what
	# they read, and a `static` function nobody calls is `-Werror` under
	# `-Wunused-function`. A schema of nothing but `tlv` regions reads no
	# scalar at all, and the harness did not compile -- which nobody saw,
	# because that schema was not one of the two built here.
	bodies: list[str] = []
	for struct in structs:
		bodies.extend(_harness(struct, prefix, resolved))

	lines = [
		f"/* Generated by situc from {basename}.situ -- do not edit.",
		" *",
		" * A fuzz harness over every parseable struct in the schema. Build it",
		" * with a sanitizer and a fuzzing engine:",
		" *",
		f" *   clang -g -O1 -fsanitize=fuzzer,address -I. {basename}_fuzz.c \\",
		f" *       {basename}.c situ.c -o {basename}_fuzz",
		" *",
		" * or standalone, to check it still builds:",
		" *",
		f" *   cc -DSITU_FUZZ_STANDALONE -I. {basename}_fuzz.c {basename}.c \\",
		f" *       situ.c -o {basename}_fuzz",
		" */",
		"",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <string.h>",
		"",
		f'#include "{basename}.h"',
		"",
	]

	if any("situ_fuzz_sink(" in line for line in bodies):
		lines.extend([
			"/* Keeps the reads below from being optimised away. Declared before",
			" * the harnesses that call it, since C is a one-pass language. */",
			"static volatile uint64_t situ_fuzz_black_hole;",
			"",
			"static void situ_fuzz_sink(uint64_t value)",
			"{",
			"\tsitu_fuzz_black_hole = value;",
			"}",
			"",
		])

	lines.extend(bodies)
	lines.extend(_entry_point(structs, basename, prefix))
	lines.extend(_standalone(basename))
	return "\n".join(lines) + "\n"


def _harness(struct: ResolvedStruct, prefix: str,
		resolved: ResolvedSchema) -> list[str]:
	"""Read every field of one struct and discard the results.

	The reads are what matter: an out-of-bounds accessor, a bit extraction that
	runs off the end of the buffer, or a validate that reads before it checks
	will trip the sanitizer here. The values are deliberately unused, funnelled
	through a volatile sink so the optimiser cannot delete the loads.
	"""
	if struct.layout.is_fixed_size:
		lines = _fixed_preamble(struct, prefix)
	else:
		lines = _variable_preamble(struct, prefix)

	lines += [
		"",
		"\t/* Validation must be safe on arbitrary bytes: it is the first thing",
		"\t * a parser runs and the last thing an attacker controls. */",
		f"\t(void){ident(prefix, struct.name, 'validate')}(view);",
		"",
	]

	reads = _reads(struct, prefix, resolved)
	if reads:
		lines.extend(reads)
	else:
		lines.append("\t(void)view;")

	lines.extend(["}", ""])
	return lines


def _fixed_preamble(struct: ResolvedStruct, prefix: str) -> list[str]:
	size = macro(prefix, struct.name, "SIZE_FIXED")
	return [
		f"static void fuzz_{struct.name}(const uint8_t *data, size_t size)",
		"{",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		f"\tuint8_t     buf[{size}];",
		"",
		f"\tif (size < {size}) {{",
		"\t\treturn;",
		"\t}",
		"",
		f"\tmemcpy(buf, data, {size});",
		f"\tsitu_msg_init(&msg, buf, {size});",
		"",
		f"\tif ({ident(prefix, struct.name, 'view')}(&msg, 0, &view) != SITU_OK) {{",
		"\t\treturn;",
		"\t}",
	]


#: How much of the fuzzer's input an unbounded struct is given, and the ceiling
#: on what a bounded one may ask for.
#:
#: There is no `SIZE_MAX` for an unbounded struct, and the harness has to
#: declare a buffer.
#: Large enough that a scan or a length field has somewhere to run, small
#: enough that a corpus entry stays a size a fuzzer will actually generate.
UNBOUNDED_EXTENT = 4096


def _variable_preamble(struct: ResolvedStruct, prefix: str) -> list[str]:
	"""A struct with no single size, which is most of the interesting ones.

	This is what the harness could not do at all: it declared
	`buf[SITU_X_SIZE_FIXED]` for every struct, and that macro is emitted only
	where a struct has one size. So `gen-fuzz` produced C that did not compile
	for exactly the structs most likely to have a parsing bug -- anything with
	a length field, a `[remaining]` tail, or a delimiter -- and nothing
	noticed, because the only harness the build compiles is over a
	fixed-size schema.

	The extent is the fuzzer's own input length rather than a constant, which
	is also better fuzzing: the length that reaches the bounds check is one
	the fuzzer chose and can shrink.
	"""
	# A bounded struct gets its own bound, unless the bound is one no stack
	# will hold: a member sized by a 64-bit varint has a worst case of 2^64-1
	# bytes, and `uint8_t buf[SITU_X_SIZE_MAX]` for that is a constant too
	# large for its type before it is an allocation nobody can make. The
	# fuzzer's own input length is what reaches the bounds check either way.
	most = struct.layout.size_max_bytes
	cap  = (macro(prefix, struct.name, "SIZE_MAX")
	        if most is not None and most <= UNBOUNDED_EXTENT
	        else str(UNBOUNDED_EXTENT))
	least = macro(prefix, struct.name, "SIZE_MIN")

	# Skipped where the minimum is zero, for the reason the accessors skip it:
	# `size < 0u` is always false and `-Wtype-limits` says so under `-Werror`.
	# A bare `tlv` region is exactly that struct, and it reached here the day
	# the zero-minimum ones stopped being filtered out of fuzzing.
	floor = [] if struct.layout.size_bytes == 0 else [
		f"\tif (size < {least}) {{",
		"\t\treturn;",
		"\t}",
		"",
	]

	return [
		f"static void fuzz_{struct.name}(const uint8_t *data, size_t size)",
		"{",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		f"\tuint8_t     buf[{cap}];",
		"\tuint32_t    extent;",
		"",
		*floor,
		"\t/* As much of the input as fits. The extent that reaches the bounds",
		"\t * check is then one the fuzzer chose, and one it can shrink. */",
		"\textent = size < sizeof buf ? (uint32_t)size : (uint32_t)sizeof buf;",
		"\tmemcpy(buf, data, extent);",
		"\tsitu_msg_init(&msg, buf, extent);",
		"",
		f"\tif ({ident(prefix, struct.name, 'view')}(&msg, 0, extent, &view)"
		" != SITU_OK) {",
		"\t\treturn;",
		"\t}",
	]


def _reads(struct: ResolvedStruct, prefix: str,
		resolved: ResolvedSchema) -> list[str]:
	lines = []
	# `own_entries` rather than `struct.entries`: an array's `[]` entry
	# describes every element at once and owns no bytes, so reading it here
	# emitted an accessor for a member that does not exist. The shared walk
	# knows that (invariant 20); this loop had its own copy that did not.
	for entry in own_entries(struct):
		placement = entry.placement
		if placement.kind == "reserved":
			continue

		local = c_name(placement.path[len(struct.name) + 1 :])

		# Before the scalar case, and before the counted-array one. A member
		# whose extent the data decides has no `_get`: it has a pointer and a
		# length, and those are the two the fuzzer most wants exercised --
		# the length is attacker-controlled and the pointer is what it aims.
		if placement.since is not None:
			lines.extend(_versioned_read(struct, placement, local, prefix))
			continue

		if placement.repeat_while is not None:
			# Walking the run is the read that can run off the end, and this
			# is the harness whose whole job is to try. Falling through to the
			# nested-struct branch named a `_view` accessor a run does not
			# have.
			lines.extend(_walk_read(struct, local, prefix))
			continue

		# Before the data-sized branch, which this looks like from the
		# outside: an `indexed` region is `sized_by` its count field and is
		# not an array. It reached for `_len` and `_ptr`, which an offset
		# table does not have, and the harness stopped compiling the day the
		# first indexed example landed. What it does have is the pair a
		# fuzzer most wants: a count the data chooses and an offset it aims.
		if placement.kind == "indexed":
			lines.extend(_indexed_read(struct, local, prefix))
			continue

		# A `tlv` region: the tag, the length and the wire type all come off
		# the wire, which makes the walk the most attacker-facing loop the
		# language generates. It reached the `else` below and got a comment
		# saying there was no sub-view to take.
		if placement.kind == "tlv":
			lines.extend(_tlv_read(struct, local, prefix))
			continue

		# A member the *data* sizes. `sized_by` alone is not that test: it
		# also names a compile-time constant, and where the count is known the
		# accessors are the fixed-array ones -- a `[CHANNEL_COUNT]` array got
		# `_len` and `_count`, which are emitted only for a runtime length.
		# `array_count` is the honest question, now that it is never a guess.
		if placement.array_count is None \
				and (placement.delimiter is not None
				     or placement.sized_by is not None):
			lines.extend(_variable_read(frozenset(resolved.structs), struct,
			                            placement, local, prefix))
			continue

		if placement.kind == "marker":
			lines.append(f"\tsitu_fuzz_sink(("
			             f"uint64_t){ident(prefix, struct.name, local, 'is_little')}(view));")
		elif placement.radix is not None:
			# A text number, fixed-width: `decimal u16 code[3]` is one number
			# in three digits, not three numbers. Its accessor parses and
			# returns an error, and the array branch below called it with an
			# index and a `_COUNT` macro that is not emitted for one.
			lines.extend([
				"\t{",
				f"\t\t{_ctype_of(placement)} parsed = 0;",
				f"\t\tif ({ident(prefix, struct.name, local, 'get')}"
				"(view, &parsed) == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)parsed);",
				"\t\t}",
				"\t}",
			])
		elif placement.array_count is not None and placement.scalar is None:
			# A constant-length array of structs: an indexed accessor over a
			# count the header carries as a macro.
			count = macro(prefix, struct.name, local, "COUNT")
			at    = ident(prefix, struct.name, local, "at")
			lines.extend([
				"\t{",
				"\t\tsitu_view_t element;",
				"",
				f"\t\tfor (uint32_t i = 0u; i < {count}; i++) {{",
				f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
				"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
				"\t\t\t}",
				"\t\t}",
				"\t}",
			])
		elif placement.array_count is not None and placement.scalar is not None:
			if placement.scalar.bits == 8:
				# Through a NULL check, because the pointer is one now: a
				# counted array at an offset the message chose may not be in
				# the view at all, and the accessor says so by handing back
				# NULL. Dereferencing it anyway is not merely a trap -- at
				# `-O1` the compiler takes the deref as proof the branch it
				# guards cannot be taken, folds the check away, and the read
				# lands past the buffer. Which is how this was found: the
				# harness kept crashing after the accessor was fixed.
				pointer = ident(prefix, struct.name, local, "ptr")
				lines.extend([
					"\t{",
					f"\t\tconst uint8_t *held = {pointer}(view);",
					"",
					"\t\tif (held != NULL) {",
					"\t\t\tsitu_fuzz_sink((uint64_t)*held);",
					"\t\t}",
					"\t}",
				])
			else:
				count = macro(prefix, struct.name, local, "COUNT")
				lines.extend([
					f"\tfor (size_t i = 0; i < {count}; i++) {{",
					f"\t\tsitu_fuzz_sink((uint64_t)"
					f"{ident(prefix, struct.name, local, 'get')}(view, (uint32_t)i));",
					"\t}",
				])
		elif placement.scalar is not None:
			lines.append(f"\tsitu_fuzz_sink((uint64_t)"
			             f"{ident(prefix, struct.name, local, 'get')}(view));")
		elif _has_sub_view(resolved, struct, placement):
			# A nested struct: take the sub-view, which is itself a bounds check.
			lines.extend([
				"\t{",
				"\t\tsitu_view_t sub;",
				f"\t\tif ({ident(prefix, struct.name, local, 'view')}"
				"(view, &sub) == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)sub.limit);",
				"\t\t}",
				"\t}",
			])
		else:
			lines.append(f"\t/* {placement.path}: no sub-view to reach"
			             " through; `validate` above covers it. */")

	return lines


def _has_sub_view(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> bool:
	"""Whether the header offers a `_view` for this member.

	The fifth consumer to need this and the fourth to get it wrong on its own.
	A `variant` is not a scalar and not a nested struct: exactly one arm is
	present, so there is no single sub-view and none is emitted -- and the
	`else` here assumed anything without a scalar had one. A nested struct
	nothing can measure has none either, for the reason in `emit`.
	"""
	nested = resolved.structs.get(placement.type_name or "")
	if nested is None:
		return False
	return nested.layout.is_fixed_size \
		or has_computable_extent(resolved.structs, nested)


def _indexed_read(struct: ResolvedStruct, local: str,
		prefix: str) -> list[str]:
	"""Read every entry of an offset table, and one past it.

	The count comes from the data, so a hostile page can claim more entries
	than the table holds; reading them all is what proves the bound is checked
	rather than trusted.
	"""
	count  = ident(prefix, struct.name, local, "count")
	offset = ident(prefix, struct.name, local, "offset")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {count}(view);",
		"\t\tuint32_t i;",
		"",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tfor (i = 0; i < n; i++) {",
		"\t\t\tuint32_t found = 0;",
		"",
		f"\t\t\tif ({offset}(view, i, &found) == SITU_OK) {{",
		"\t\t\t\tsitu_fuzz_sink((uint64_t)found);",
		"\t\t\t}",
		"\t\t}",
		"\t\t{",
		"\t\t\tuint32_t past = 0;",
		"",
		f"\t\t\tsitu_fuzz_sink((uint64_t){offset}(view, n, &past));",
		"\t\t}",
		"\t}",
	]


def _tlv_read(struct: ResolvedStruct, local: str, prefix: str) -> list[str]:
	"""Walk a `tlv` region item by item, and count it.

	Every number in the loop is the message's: the tag is a varint the input
	chooses, the length is another, and the value extent is where those two
	put it. Walking to the end is what proves an item claiming more than the
	region holds is refused rather than followed -- and `_count`, which walks
	it again, is the same question asked by a second loop that has to agree.
	"""
	item  = ident(prefix, struct.name, local, "item_t")
	first = ident(prefix, struct.name, local, "first")
	nxt   = ident(prefix, struct.name, local, "next")
	count = ident(prefix, struct.name, local, "count")

	return [
		"\t{",
		f"\t\t{item} item;",
		f"\t\tsitu_err_t walked = {first}(view, &item);",
		"",
		"\t\twhile (walked == SITU_OK) {",
		"\t\t\tsitu_fuzz_sink((uint64_t)item.tag);",
		"\t\t\tsitu_fuzz_sink((uint64_t)item.value_at);",
		"\t\t\tsitu_fuzz_sink((uint64_t)item.value_len);",
		f"\t\t\twalked = {nxt}(&item);",
		"\t\t}",
		f"\t\tsitu_fuzz_sink((uint64_t){count}(view));",
		"\t}",
	]


def _walk_read(struct: ResolvedStruct, local: str, prefix: str) -> list[str]:
	"""Count a run and reach every element of it."""
	count = ident(prefix, struct.name, local, "count")
	at    = ident(prefix, struct.name, local, "at")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {count}(view);",
		"\t\tsitu_view_t element;",
		"",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tfor (uint32_t i = 0u; i < n; i++) {",
		f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
		"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
		"\t\t\t}",
		"\t\t}",
		"\t}",
	]


def _versioned_read(struct: ResolvedStruct, placement: Placement, local: str,
		prefix: str) -> list[str]:
	"""A member the version decides is there (section 19.4).

	Its getter returns an error rather than a value, so the plain sink call
	did not compile -- and the read worth fuzzing is the refusal: a version
	byte the fuzzer chose deciding whether four bytes at a fixed offset are
	this message's.
	"""
	return [
		"\t{",
		f"\t\t{_ctype_of(placement)} held = 0;",
		f"\t\tif ({ident(prefix, struct.name, local, 'get')}(view, &held)"
		" == SITU_OK) {",
		"\t\t\tsitu_fuzz_sink((uint64_t)held);",
		"\t\t}",
		"\t}",
	]


def _variable_read(structs: frozenset[str], struct: ResolvedStruct,
		placement: Placement, local: str, prefix: str) -> list[str]:
	"""Exercise a member the data sizes, without assuming it has a value.

	A run of records has neither a pointer nor a length -- it has a count and
	an indexed accessor -- so it is walked instead, which is the read that can
	run off the end and therefore the one worth fuzzing.
	"""
	if placement.type_name in structs:
		# A run of records has a count and an indexed accessor rather than a
		# pointer and a length. Walking it is the read that can run off the
		# end, so it is the one worth fuzzing.
		#
		# What bounds the run -- a delimiter, a length field, a condition --
		# does not change that, and this asked for a delimiter as well. So a
		# `recs[n]` of structs reached for `_len` and `_ptr` and the harness
		# did not compile, in a schema that had been in the tree since phase
		# 5 and was never fuzzed.
		count = ident(prefix, struct.name, local, "count")
		at    = ident(prefix, struct.name, local, "at")
		return [
			"\t{",
			f"\t\tconst uint32_t n = {count}(view);",
			"\t\tsitu_view_t element;",
			"",
			"\t\tsitu_fuzz_sink((uint64_t)n);",
			"\t\tfor (uint32_t i = 0u; i < n; i++) {",
			f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
			"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
			"\t\t\t}",
			"\t\t}",
			"\t}",
		]

	if placement.delimiter is not None and placement.radix is not None:
		# A text number: the parse is the interesting part, and it returns an
		# error rather than a value.
		return [
			"\t{",
			f"\t\t{_ctype_of(placement)} parsed = 0;",
			f"\t\tif ({ident(prefix, struct.name, local, 'get')}(view, &parsed)"
			" == SITU_OK) {",
			"\t\t\tsitu_fuzz_sink((uint64_t)parsed);",
			"\t\t}",
			"\t}",
		]

	length = ident(prefix, struct.name, local, "len")
	ptr    = ident(prefix, struct.name, local, "ptr")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {length}(view);",
		"",
		"\t\t/* The length is the attacker's and the pointer is where it",
		"\t\t * aims, so read the last byte it claims rather than the",
		"\t\t * first: an off-by-one in the extent shows up there. */",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tif (n > 0u) {",
		f"\t\t\tsitu_fuzz_sink((uint64_t){ptr}(view)[n - 1u]);",
		"\t\t}",
		"\t}",
	]


def _ctype_of(placement: Placement) -> str:
	scalar = placement.scalar
	assert scalar is not None
	return f"uint{max(8, scalar.bits)}_t"


def _entry_point(structs: list[ResolvedStruct], basename: str,
		prefix: str) -> list[str]:
	lines = [
		"int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);",
		"",
		"int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)",
		"{",
	]

	if not structs:
		lines.extend(["\t(void)data;", "\t(void)size;"])
	else:
		# The first byte selects a struct, so one corpus drives every parser in
		# the schema rather than needing a binary each.
		lines.extend([
			"\tif (size < 1u) {",
			"\t\treturn 0;",
			"\t}",
			"",
			f"\tswitch (data[0] % {len(structs)}u) {{",
		])
		for index, struct in enumerate(structs):
			lines.append(f"\tcase {index}u:")
			lines.append(f"\t\tfuzz_{struct.name}(data + 1, size - 1u);")
			lines.append("\t\tbreak;")
		lines.extend(["\tdefault:", "\t\tbreak;", "\t}"])

	lines.extend(["", "\treturn 0;", "}", ""])
	return lines


def _standalone(basename: str) -> list[str]:
	return [
		"#ifdef SITU_FUZZ_STANDALONE",
		"",
		"#include <stdio.h>",
		"",
		"/* One input from stdin, so the harness can be built and run without a",
		" * fuzzing engine. This is what keeps it from rotting between runs. */",
		"int main(void)",
		"{",
		"\tuint8_t buf[4096];",
		"\tsize_t  n = fread(buf, 1, sizeof(buf), stdin);",
		"",
		"\treturn LLVMFuzzerTestOneInput(buf, n);",
		"}",
		"",
		"#endif /* SITU_FUZZ_STANDALONE */",
	]
