"""Generate a fuzz harness per parseable struct.

Parse safety is the top risk in a protocol parser (project.md section 20.3), and
a harness the schema author has to write themselves is a harness that does not
get written. This one is derived from the layout, so it exercises every accessor
the schema has without anybody maintaining a list.

The entry point is libFuzzer's, because that is what the CI in section 22 runs.
A standalone `main` reading stdin is emitted alongside it under
`SITU_FUZZ_STANDALONE`, so the harness can be compiled and smoke-tested with a
plain compiler -- a harness nobody can build is the other way this rots.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.c.names import c_name, ident, macro
from situc.layout import Placement
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import has_computable_extent, own_entries


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> str:
	# A register is a bus transaction, not bytes off a wire: it has no view,
	# no `validate`, and its accessors take a device handle rather than one.
	# `gen-dissector` has excluded them since it was written and this did not,
	# which cost nothing while no register schema was fuzzed.
	structs = [struct for struct in resolved.structs.values()
	           if struct.layout.is_byte_sized and struct.layout.size_bytes > 0
	           and struct.layout.register is None]

	# The harnesses first: whether the sink is needed is a question about what
	# they read, and a `static` function nobody calls is `-Werror` under
	# `-Wunused-function`. A schema of nothing but `tlv` regions reads no
	# scalar at all, and the harness did not compile -- which nobody saw,
	# because that schema was not one of the two built here.
	bodies: list[str] = []
	for struct in structs:
		bodies.extend(_harness(struct, prefix, resolved))

	lines = [
		f"/* Generated by situc from {basename}.situ -- do not edit.",
		" *",
		" * A fuzz harness over every parseable struct in the schema. Build it",
		" * with a sanitizer and a fuzzing engine:",
		" *",
		f" *   clang -g -O1 -fsanitize=fuzzer,address -I. {basename}_fuzz.c \\",
		f" *       {basename}.c situ.c -o {basename}_fuzz",
		" *",
		" * or standalone, to check it still builds:",
		" *",
		f" *   cc -DSITU_FUZZ_STANDALONE -I. {basename}_fuzz.c {basename}.c \\",
		f" *       situ.c -o {basename}_fuzz",
		" */",
		"",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <string.h>",
		"",
		f'#include "{basename}.h"',
		"",
	]

	if any("situ_fuzz_sink(" in line for line in bodies):
		lines.extend([
			"/* Keeps the reads below from being optimised away. Declared before",
			" * the harnesses that call it, since C is a one-pass language. */",
			"static volatile uint64_t situ_fuzz_black_hole;",
			"",
			"static void situ_fuzz_sink(uint64_t value)",
			"{",
			"\tsitu_fuzz_black_hole = value;",
			"}",
			"",
		])

	lines.extend(bodies)
	lines.extend(_entry_point(structs, basename, prefix))
	lines.extend(_standalone(basename))
	return "\n".join(lines) + "\n"


def _harness(struct: ResolvedStruct, prefix: str,
		resolved: ResolvedSchema) -> list[str]:
	"""Read every field of one struct and discard the results.

	The reads are what matter: an out-of-bounds accessor, a bit extraction that
	runs off the end of the buffer, or a validate that reads before it checks
	will trip the sanitizer here. The values are deliberately unused, funnelled
	through a volatile sink so the optimiser cannot delete the loads.
	"""
	if struct.layout.is_fixed_size:
		lines = _fixed_preamble(struct, prefix)
	else:
		lines = _variable_preamble(struct, prefix)

	lines += [
		"",
		"\t/* Validation must be safe on arbitrary bytes: it is the first thing",
		"\t * a parser runs and the last thing an attacker controls. */",
		f"\t(void){ident(prefix, struct.name, 'validate')}(view);",
		"",
	]

	reads = _reads(struct, prefix, resolved)
	if reads:
		lines.extend(reads)
	else:
		lines.append("\t(void)view;")

	lines.extend(["}", ""])
	return lines


def _fixed_preamble(struct: ResolvedStruct, prefix: str) -> list[str]:
	size = macro(prefix, struct.name, "SIZE_FIXED")
	return [
		f"static void fuzz_{struct.name}(const uint8_t *data, size_t size)",
		"{",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		f"\tuint8_t     buf[{size}];",
		"",
		f"\tif (size < {size}) {{",
		"\t\treturn;",
		"\t}",
		"",
		f"\tmemcpy(buf, data, {size});",
		f"\tsitu_msg_init(&msg, buf, {size});",
		"",
		f"\tif ({ident(prefix, struct.name, 'view')}(&msg, 0, &view) != SITU_OK) {{",
		"\t\treturn;",
		"\t}",
	]


#: How much of the fuzzer's input an unbounded struct is given.
#:
#: There is no `SIZE_MAX` for one, and the harness has to declare a buffer.
#: Large enough that a scan or a length field has somewhere to run, small
#: enough that a corpus entry stays a size a fuzzer will actually generate.
UNBOUNDED_EXTENT = 4096


def _variable_preamble(struct: ResolvedStruct, prefix: str) -> list[str]:
	"""A struct with no single size, which is most of the interesting ones.

	This is what the harness could not do at all: it declared
	`buf[SITU_X_SIZE_FIXED]` for every struct, and that macro is emitted only
	where a struct has one size. So `gen-fuzz` produced C that did not compile
	for exactly the structs most likely to have a parsing bug -- anything with
	a length field, a `[remaining]` tail, or a delimiter -- and nothing
	noticed, because the only harness the build compiles is over a
	fixed-size schema.

	The extent is the fuzzer's own input length rather than a constant, which
	is also better fuzzing: the length that reaches the bounds check is one
	the fuzzer chose and can shrink.
	"""
	most = struct.layout.size_max_bytes
	cap  = (macro(prefix, struct.name, "SIZE_MAX") if most is not None
	        else str(UNBOUNDED_EXTENT))
	least = macro(prefix, struct.name, "SIZE_MIN")

	return [
		f"static void fuzz_{struct.name}(const uint8_t *data, size_t size)",
		"{",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		f"\tuint8_t     buf[{cap}];",
		"\tuint32_t    extent;",
		"",
		f"\tif (size < {least}) {{",
		"\t\treturn;",
		"\t}",
		"",
		"\t/* As much of the input as fits. The extent that reaches the bounds",
		"\t * check is then one the fuzzer chose, and one it can shrink. */",
		"\textent = size < sizeof buf ? (uint32_t)size : (uint32_t)sizeof buf;",
		"\tmemcpy(buf, data, extent);",
		"\tsitu_msg_init(&msg, buf, extent);",
		"",
		f"\tif ({ident(prefix, struct.name, 'view')}(&msg, 0, extent, &view)"
		" != SITU_OK) {",
		"\t\treturn;",
		"\t}",
	]


def _reads(struct: ResolvedStruct, prefix: str,
		resolved: ResolvedSchema) -> list[str]:
	lines = []
	# `own_entries` rather than `struct.entries`: an array's `[]` entry
	# describes every element at once and owns no bytes, so reading it here
	# emitted an accessor for a member that does not exist. The shared walk
	# knows that (invariant 20); this loop had its own copy that did not.
	for entry in own_entries(struct):
		placement = entry.placement
		if placement.kind == "reserved":
			continue

		local = c_name(placement.path[len(struct.name) + 1 :])

		# Before the scalar case, and before the counted-array one. A member
		# whose extent the data decides has no `_get`: it has a pointer and a
		# length, and those are the two the fuzzer most wants exercised --
		# the length is attacker-controlled and the pointer is what it aims.
		if placement.since is not None:
			lines.extend(_versioned_read(struct, placement, local, prefix))
			continue

		if placement.repeat_while is not None:
			# Walking the run is the read that can run off the end, and this
			# is the harness whose whole job is to try. Falling through to the
			# nested-struct branch named a `_view` accessor a run does not
			# have.
			lines.extend(_walk_read(struct, local, prefix))
			continue

		# A member the *data* sizes. `sized_by` alone is not that test: it
		# also names a compile-time constant, and where the count is known the
		# accessors are the fixed-array ones -- a `[CHANNEL_COUNT]` array got
		# `_len` and `_count`, which are emitted only for a runtime length.
		# `array_count` is the honest question, now that it is never a guess.
		if placement.array_count is None \
				and (placement.delimiter is not None
				     or placement.sized_by is not None):
			lines.extend(_variable_read(frozenset(resolved.structs), struct,
			                            placement, local, prefix))
			continue

		if placement.kind == "marker":
			lines.append(f"\tsitu_fuzz_sink(("
			             f"uint64_t){ident(prefix, struct.name, local, 'is_little')}(view));")
		elif placement.radix is not None:
			# A text number, fixed-width: `decimal u16 code[3]` is one number
			# in three digits, not three numbers. Its accessor parses and
			# returns an error, and the array branch below called it with an
			# index and a `_COUNT` macro that is not emitted for one.
			lines.extend([
				"\t{",
				f"\t\t{_ctype_of(placement)} parsed = 0;",
				f"\t\tif ({ident(prefix, struct.name, local, 'get')}"
				"(view, &parsed) == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)parsed);",
				"\t\t}",
				"\t}",
			])
		elif placement.array_count is not None and placement.scalar is None:
			# A constant-length array of structs: an indexed accessor over a
			# count the header carries as a macro.
			count = macro(prefix, struct.name, local, "COUNT")
			at    = ident(prefix, struct.name, local, "at")
			lines.extend([
				"\t{",
				"\t\tsitu_view_t element;",
				"",
				f"\t\tfor (uint32_t i = 0u; i < {count}; i++) {{",
				f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
				"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
				"\t\t\t}",
				"\t\t}",
				"\t}",
			])
		elif placement.array_count is not None and placement.scalar is not None:
			if placement.scalar.bits == 8:
				lines.append(f"\tsitu_fuzz_sink(("
				             f"uint64_t)*{ident(prefix, struct.name, local, 'ptr')}(view));")
			else:
				count = macro(prefix, struct.name, local, "COUNT")
				lines.extend([
					f"\tfor (size_t i = 0; i < {count}; i++) {{",
					f"\t\tsitu_fuzz_sink((uint64_t)"
					f"{ident(prefix, struct.name, local, 'get')}(view, (uint32_t)i));",
					"\t}",
				])
		elif placement.scalar is not None:
			lines.append(f"\tsitu_fuzz_sink((uint64_t)"
			             f"{ident(prefix, struct.name, local, 'get')}(view));")
		elif _has_sub_view(resolved, struct, placement):
			# A nested struct: take the sub-view, which is itself a bounds check.
			lines.extend([
				"\t{",
				"\t\tsitu_view_t sub;",
				f"\t\tif ({ident(prefix, struct.name, local, 'view')}"
				"(view, &sub) == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)sub.limit);",
				"\t\t}",
				"\t}",
			])
		else:
			lines.append(f"\t/* {placement.path}: no sub-view to reach"
			             " through; `validate` above covers it. */")

	return lines


def _has_sub_view(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> bool:
	"""Whether the header offers a `_view` for this member.

	The fifth consumer to need this and the fourth to get it wrong on its own.
	A `variant` is not a scalar and not a nested struct: exactly one arm is
	present, so there is no single sub-view and none is emitted -- and the
	`else` here assumed anything without a scalar had one. A nested struct
	nothing can measure has none either, for the reason in `emit`.
	"""
	nested = resolved.structs.get(placement.type_name or "")
	if nested is None:
		return False
	return nested.layout.is_fixed_size \
		or has_computable_extent(resolved.structs, nested)


def _walk_read(struct: ResolvedStruct, local: str, prefix: str) -> list[str]:
	"""Count a run and reach every element of it."""
	count = ident(prefix, struct.name, local, "count")
	at    = ident(prefix, struct.name, local, "at")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {count}(view);",
		"\t\tsitu_view_t element;",
		"",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tfor (uint32_t i = 0u; i < n; i++) {",
		f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
		"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
		"\t\t\t}",
		"\t\t}",
		"\t}",
	]


def _versioned_read(struct: ResolvedStruct, placement: Placement, local: str,
		prefix: str) -> list[str]:
	"""A member the version decides is there (section 19.4).

	Its getter returns an error rather than a value, so the plain sink call
	did not compile -- and the read worth fuzzing is the refusal: a version
	byte the fuzzer chose deciding whether four bytes at a fixed offset are
	this message's.
	"""
	return [
		"\t{",
		f"\t\t{_ctype_of(placement)} held = 0;",
		f"\t\tif ({ident(prefix, struct.name, local, 'get')}(view, &held)"
		" == SITU_OK) {",
		"\t\t\tsitu_fuzz_sink((uint64_t)held);",
		"\t\t}",
		"\t}",
	]


def _variable_read(structs: frozenset[str], struct: ResolvedStruct,
		placement: Placement, local: str, prefix: str) -> list[str]:
	"""Exercise a member the data sizes, without assuming it has a value.

	A run of records has neither a pointer nor a length -- it has a count and
	an indexed accessor -- so it is walked instead, which is the read that can
	run off the end and therefore the one worth fuzzing.
	"""
	if placement.type_name in structs:
		# A run of records has a count and an indexed accessor rather than a
		# pointer and a length. Walking it is the read that can run off the
		# end, so it is the one worth fuzzing.
		#
		# What bounds the run -- a delimiter, a length field, a condition --
		# does not change that, and this asked for a delimiter as well. So a
		# `recs[n]` of structs reached for `_len` and `_ptr` and the harness
		# did not compile, in a schema that had been in the tree since phase
		# 5 and was never fuzzed.
		count = ident(prefix, struct.name, local, "count")
		at    = ident(prefix, struct.name, local, "at")
		return [
			"\t{",
			f"\t\tconst uint32_t n = {count}(view);",
			"\t\tsitu_view_t element;",
			"",
			"\t\tsitu_fuzz_sink((uint64_t)n);",
			"\t\tfor (uint32_t i = 0u; i < n; i++) {",
			f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
			"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
			"\t\t\t}",
			"\t\t}",
			"\t}",
		]

	if placement.delimiter is not None and placement.radix is not None:
		# A text number: the parse is the interesting part, and it returns an
		# error rather than a value.
		return [
			"\t{",
			f"\t\t{_ctype_of(placement)} parsed = 0;",
			f"\t\tif ({ident(prefix, struct.name, local, 'get')}(view, &parsed)"
			" == SITU_OK) {",
			"\t\t\tsitu_fuzz_sink((uint64_t)parsed);",
			"\t\t}",
			"\t}",
		]

	length = ident(prefix, struct.name, local, "len")
	ptr    = ident(prefix, struct.name, local, "ptr")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {length}(view);",
		"",
		"\t\t/* The length is the attacker's and the pointer is where it",
		"\t\t * aims, so read the last byte it claims rather than the",
		"\t\t * first: an off-by-one in the extent shows up there. */",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tif (n > 0u) {",
		f"\t\t\tsitu_fuzz_sink((uint64_t){ptr}(view)[n - 1u]);",
		"\t\t}",
		"\t}",
	]


def _ctype_of(placement: Placement) -> str:
	scalar = placement.scalar
	assert scalar is not None
	return f"uint{max(8, scalar.bits)}_t"


def _entry_point(structs: list[ResolvedStruct], basename: str,
		prefix: str) -> list[str]:
	lines = [
		"int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);",
		"",
		"int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)",
		"{",
	]

	if not structs:
		lines.extend(["\t(void)data;", "\t(void)size;"])
	else:
		# The first byte selects a struct, so one corpus drives every parser in
		# the schema rather than needing a binary each.
		lines.extend([
			"\tif (size < 1u) {",
			"\t\treturn 0;",
			"\t}",
			"",
			f"\tswitch (data[0] % {len(structs)}u) {{",
		])
		for index, struct in enumerate(structs):
			lines.append(f"\tcase {index}u:")
			lines.append(f"\t\tfuzz_{struct.name}(data + 1, size - 1u);")
			lines.append("\t\tbreak;")
		lines.extend(["\tdefault:", "\t\tbreak;", "\t}"])

	lines.extend(["", "\treturn 0;", "}", ""])
	return lines


def _standalone(basename: str) -> list[str]:
	return [
		"#ifdef SITU_FUZZ_STANDALONE",
		"",
		"#include <stdio.h>",
		"",
		"/* One input from stdin, so the harness can be built and run without a",
		" * fuzzing engine. This is what keeps it from rotting between runs. */",
		"int main(void)",
		"{",
		"\tuint8_t buf[4096];",
		"\tsize_t  n = fread(buf, 1, sizeof(buf), stdin);",
		"",
		"\treturn LLVMFuzzerTestOneInput(buf, n);",
		"}",
		"",
		"#endif /* SITU_FUZZ_STANDALONE */",
	]
