"""Generate a fuzz harness per parseable struct.

Parse safety is the top risk in a protocol parser (project.md section 20.3), and
a harness the schema author has to write themselves is a harness that does not
get written. This one is derived from the layout, so it exercises every accessor
the schema has without anybody maintaining a list.

The entry point is libFuzzer's, because that is what the CI in section 22 runs.
A standalone `main` reading stdin is emitted alongside it under
`SITU_FUZZ_STANDALONE`, so the harness can be compiled and smoke-tested with a
plain compiler -- a harness nobody can build is the other way this rots.
"""

from __future__ import annotations

from situc import __version__

from collections.abc import Mapping

from situc import ast, relation
from situc.codegen.c.names import c_name, ident, macro
from situc.layout import BITS_PER_BYTE, Placement
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import (
	arm_members, data_sized, has_computable_extent, indexed_elements,
	own_entries,
)


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> str:
	# A register is a bus transaction, not bytes off a wire: it has no view,
	# no `validate`, and its accessors take a device handle rather than one.
	# `gen-dissector` has excluded them since it was written and this did not,
	# which cost nothing while no register schema was fuzzed.
	# `size_bytes > 0` was here too, and it dropped the one schema whose
	# whole point is a construct nothing else in the tree has:
	# `example/protobuf` is a bare `tlv` region, so its minimum size is zero
	# and it was filtered out of fuzzing entirely. The harness still compiled,
	# still ran under the smoke test, and exercised nothing -- 16 million
	# executions at coverage 1, which is what an empty `LLVMFuzzerTestOneInput`
	# looks like from the outside. A struct with nothing to read is skipped
	# below, where that is decided by what it reads rather than by a bound.
	structs = [struct for struct in resolved.structs.values()
	           if struct.layout.is_byte_sized
	           and struct.layout.register is None
	           and not (struct.layout.is_fixed_size
	                    and struct.layout.size_bytes == 0)]

	# The harnesses first: whether the sink is needed is a question about what
	# they read, and a `static` function nobody calls is `-Werror` under
	# `-Wunused-function`. A schema of nothing but `tlv` regions reads no
	# scalar at all, and the harness did not compile -- which nobody saw,
	# because that schema was not one of the two built here.
	bodies: list[str] = []
	for struct in structs:
		bodies.extend(_harness(struct, prefix, resolved))

	lines = [
		f"/* Generated by situc {__version__} from {basename}.situ -- do not edit.",
		" *",
		" * A fuzz harness over every parseable struct in the schema. Build it",
		" * with a sanitizer and a fuzzing engine:",
		" *",
		f" *   clang -g -O1 -fsanitize=fuzzer,address -I. {basename}_fuzz.c \\",
		f" *       {basename}.c situ.c -o {basename}_fuzz",
		" *",
		" * or standalone, to check it still builds:",
		" *",
		f" *   cc -DSITU_FUZZ_STANDALONE -I. {basename}_fuzz.c {basename}.c \\",
		f" *       situ.c -o {basename}_fuzz",
		" */",
		"",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <stdlib.h>",
		"#include <string.h>",
		"",
		f'#include "{basename}.h"',
		"",
	]

	relation_lines, relation_names = _relation_harnesses(schema, resolved, prefix)

	if any("situ_fuzz_sink(" in line
	       for line in bodies + relation_lines):
		lines.extend([
			"/* Keeps the reads below from being optimised away. Declared before",
			" * the harnesses that call it, since C is a one-pass language. */",
			"static volatile uint64_t situ_fuzz_black_hole;",
			"",
			"static void situ_fuzz_sink(uint64_t value)",
			"{",
			"\tsitu_fuzz_black_hole = value;",
			"}",
			"",
		])

	if relation_names:
		# Stated here rather than discovered at the first build: the predicate
		# is rung 3's output, so this file needs what `--layer relate` emits.
		lines.insert(lines.index(f'#include "{basename}.h"') + 1,
		             f'#include "{basename}_relate.h"\t/* situc build --layer relate */')

	lines.extend(bodies)
	lines.extend(relation_lines)
	lines.extend(_entry_point(structs, basename, prefix, relation_names))
	lines.extend(_standalone(basename))
	return "\n".join(lines) + "\n"


def _harness(struct: ResolvedStruct, prefix: str,
		resolved: ResolvedSchema) -> list[str]:
	"""Read every field of one struct and discard the results.

	The reads are what matter: an out-of-bounds accessor, a bit extraction that
	runs off the end of the buffer, or a validate that reads before it checks
	will trip the sanitizer here. The values are deliberately unused, funnelled
	through a volatile sink so the optimiser cannot delete the loads.
	"""
	if struct.layout.is_fixed_size:
		lines = _fixed_preamble(struct, prefix)
	else:
		lines = _variable_preamble(struct, prefix)

	lines += [
		"",
		"\t/* Validation must be safe on arbitrary bytes: it is the first thing",
		"\t * a parser runs and the last thing an attacker controls. */",
		f"\t(void){ident(prefix, struct.name, 'validate')}(view);",
		"",
	]

	reads = _reads(struct, prefix, resolved)
	if reads:
		lines.extend(reads)
	else:
		lines.append("\t(void)view;")

	# After every read, because these WRITE. The erasers were the one family
	# of accessor this harness never called, and its docstring says it
	# "exercises every accessor the schema has without anybody maintaining a
	# list" -- which was a claim about how the walk is derived rather than a
	# fact about what it reaches. They are also the only accessors that write
	# a span the DATA chose, which makes them the ones a fuzzer most wants:
	# C's erased what the wire asked for without clamping it (26.316).
	lines.extend(_erases(struct, prefix))

	if not struct.layout.is_fixed_size:
		lines.append("\tfree(buf);")
	lines.extend(["}", ""])
	return lines


def _fixed_preamble(struct: ResolvedStruct, prefix: str) -> list[str]:
	size = macro(prefix, struct.name, "SIZE_FIXED")
	return [
		f"static void fuzz_{c_name(struct.name)}(const uint8_t *data, size_t size)",
		"{",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		f"\tuint8_t     buf[{size}];",
		"",
		f"\tif (size < {size}) {{",
		"\t\treturn;",
		"\t}",
		"",
		f"\tmemcpy(buf, data, {size});",
		f"\tsitu_msg_init(&msg, buf, {size});",
		"",
		f"\tif ({ident(prefix, struct.name, 'view')}(&msg, 0, &view) != SITU_OK) {{",
		"\t\treturn;",
		"\t}",
	]


#: How much of the fuzzer's input an unbounded struct is given, and the ceiling
#: on what a bounded one may ask for.
#:
#: There is no `SIZE_MAX` for an unbounded struct, and the harness has to
#: declare a buffer.
#: Large enough that a scan or a length field has somewhere to run, small
#: enough that a corpus entry stays a size a fuzzer will actually generate.
UNBOUNDED_EXTENT = 4096


def _variable_preamble(struct: ResolvedStruct, prefix: str) -> list[str]:
	"""A struct with no single size, which is most of the interesting ones.

	This is what the harness could not do at all: it declared
	`buf[SITU_X_SIZE_FIXED]` for every struct, and that macro is emitted only
	where a struct has one size. So `gen-fuzz` produced C that did not compile
	for exactly the structs most likely to have a parsing bug -- anything with
	a length field, a `[remaining]` tail, or a delimiter -- and nothing
	noticed, because the only harness the build compiles is over a
	fixed-size schema.

	The extent is the fuzzer's own input length rather than a constant, which
	is also better fuzzing: the length that reaches the bounds check is one
	the fuzzer chose and can shrink.
	"""
	# A bounded struct gets its own bound, unless the bound is one no stack
	# will hold: a member sized by a 64-bit varint has a worst case of 2^64-1
	# bytes, and `uint8_t buf[SITU_X_SIZE_MAX]` for that is a constant too
	# large for its type before it is an allocation nobody can make. The
	# fuzzer's own input length is what reaches the bounds check either way.
	most = struct.layout.size_max_bytes
	cap  = (macro(prefix, struct.name, "SIZE_MAX")
	        if most is not None and most <= UNBOUNDED_EXTENT
	        else str(UNBOUNDED_EXTENT))
	least = macro(prefix, struct.name, "SIZE_MIN")

	# Skipped where the minimum is zero, for the reason the accessors skip it:
	# `size < 0u` is always false and `-Wtype-limits` says so under `-Werror`.
	# A bare `tlv` region is exactly that struct, and it reached here the day
	# the zero-minimum ones stopped being filtered out of fuzzing.
	floor = [] if struct.layout.size_bytes == 0 else [
		f"\tif (size < {least}) {{",
		"\t\treturn;",
		"\t}",
		"",
	]

	return [
		f"static void fuzz_{c_name(struct.name)}(const uint8_t *data, size_t size)",
		"{",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		"\tuint8_t    *buf;",
		"\tuint32_t    extent;",
		"",
		*floor,
		"\t/* As much of the input as fits. The extent that reaches the bounds",
		"\t * check is then one the fuzzer chose, and one it can shrink. */",
		f"\textent = size < {cap} ? (uint32_t)size : (uint32_t){cap};",
		"\tif (extent == 0u) {",
		"\t\treturn;",
		"\t}",
		"",
		"\t/* Allocated to the EXTENT, not to the struct's maximum. A",
		"\t * `buf[SIZE_MAX]` holds the frame and a tail of slack, so an",
		"\t * accessor running past the frame lands in that slack and no",
		"\t * sanitizer says anything: measured, an unclamped eraser wrote",
		"\t * 194 bytes past a six-byte frame into a 258-byte buffer and",
		"\t * ASan stayed silent, while the same code over a six-byte",
		"\t * allocation tripped it at once. Past the frame has to be past",
		"\t * the allocation or this harness can only see the overruns that",
		"\t * are bigger than the struct. */",
		"\tbuf = (uint8_t *)malloc(extent);",
		"\tif (buf == NULL) {",
		"\t\treturn;",
		"\t}",
		"\tmemcpy(buf, data, extent);",
		"\tsitu_msg_init(&msg, buf, extent);",
		"",
		f"\tif ({ident(prefix, struct.name, 'view')}(&msg, 0, extent, &view)"
		" != SITU_OK) {",
		"\t\tfree(buf);",
		"\t\treturn;",
		"\t}",
	]


#: Emitted where a sealed region holds a member in a shape this does not
#: know how to reach. Nothing in the corpus produces it, and a test asserts
#: that -- so a new shape appearing inside a region is a failing test rather
#: than a member that quietly stops being fuzzed, which is how the erasers
#: came to be missing for as long as they were.
UNREACHED = "UNREACHED interior shape"


def _interior_member(struct: ResolvedStruct, placement: Placement,
		prefix: str, on: str, tab: str) -> list[str]:
	"""One member inside a region, read through `on`.

	`on` is the gate where the region has one and the view where it does not,
	which is the only difference between the two cases: a gate is a struct
	holding the same view, so every accessor below is the same accessor with
	a different first argument.

	The four shapes are the corpus's, enumerated by reading the emitted
	header for all ten interior members rather than inferred from the
	placement -- a `u16` run has `_count` and `_get(gate, i)` where a `u8`
	run has `_len` and `_ptr`, and guessing that wrong is a call to a
	function the header does not declare.
	"""
	local  = c_name(placement.path[len(struct.name) + 1 :])
	scalar = placement.scalar

	if scalar is None:
		return [f"{tab}/* {UNREACHED}: {placement.path} (no scalar) */"]

	# A constant-count byte array: one pointer, and it is NULL when the
	# offset the message chose puts it outside the frame. Dereferencing it
	# anyway is what `_reads` records costing it a crash at -O1.
	if placement.array_count is not None and scalar.bits == BITS_PER_BYTE:
		ptr = ident(prefix, struct.name, local, "ptr")
		return [
			f"{tab}{{",
			f"{tab}\tconst uint8_t *reached = {ptr}({on});",
			"",
			f"{tab}\tif (reached != NULL) {{",
			f"{tab}\t\tsitu_fuzz_sink((uint64_t)*reached);",
			f"{tab}\t}}",
			f"{tab}}}",
		]

	if data_sized(placement) and scalar.bits == BITS_PER_BYTE:
		length = ident(prefix, struct.name, local, "len")
		ptr    = ident(prefix, struct.name, local, "ptr")
		return [
			f"{tab}{{",
			f"{tab}\tconst uint32_t n = {length}({on});",
			"",
			f"{tab}\tsitu_fuzz_sink((uint64_t)n);",
			f"{tab}\tif (n > 0u) {{",
			f"{tab}\t\tsitu_fuzz_sink((uint64_t){ptr}({on})[n - 1u]);",
			f"{tab}\t}}",
			f"{tab}}}",
		]

	# A run of wider scalars: no pointer, because the elements are not
	# bytes. `_count` is how many, `_get` is one of them.
	if data_sized(placement):
		count = ident(prefix, struct.name, local, "count")
		get   = ident(prefix, struct.name, local, "get")
		return [
			f"{tab}{{",
			f"{tab}\tconst uint32_t n = {count}({on});",
			f"{tab}\tuint32_t i;",
			"",
			f"{tab}\tsitu_fuzz_sink((uint64_t)n);",
			f"{tab}\tfor (i = 0u; i < n; i++) {{",
			f"{tab}\t\tsitu_fuzz_sink((uint64_t){get}({on}, i));",
			f"{tab}\t}}",
			f"{tab}}}",
		]

	if placement.array_count is not None:
		count = macro(prefix, struct.name, local, "COUNT")
		get   = ident(prefix, struct.name, local, "get")
		return [
			f"{tab}{{",
			f"{tab}\tuint32_t i;",
			"",
			f"{tab}\tfor (i = 0u; i < {count}; i++) {{",
			f"{tab}\t\tsitu_fuzz_sink((uint64_t){get}({on}, i));",
			f"{tab}\t}}",
			f"{tab}}}",
		]

	return [f"{tab}situ_fuzz_sink((uint64_t)"
	        f"{ident(prefix, struct.name, local, 'get')}({on}));"]


def _sealed_read(struct: ResolvedStruct, region: Placement,
		prefix: str) -> list[str]:
	"""Open a sealed region and read what it protects.

	Nothing reached these before. The interior members are not in
	`own_entries` -- they belong to the region, not to the struct -- so the
	walk never saw them, and the region itself fell through to "no sub-view
	to reach through". Measured across the corpus: 13 members behind a
	verified gate, and `keystore`'s `secret_key` appeared nowhere in its own
	harness.

	**`verified` is 1, and that is the decision this makes.** The gate exists
	to refuse an unverified interior, and the generated `_open` does exactly
	that and nothing else -- the tag is never computed here, so passing 0
	only exercises a two-line refusal that `test_packet.c` already covers by
	hand. What is worth fuzzing is the parsing on the far side, which is
	reachable no other way and which runs on bytes an attacker chose whenever
	they hold a key or a forgery succeeds. Passing 1 is not a claim that the
	tag verified; it is the harness declining to test the gate in order to
	test what the gate protects.
	"""
	interiors = [entry.placement for entry in struct.entries
	             if entry.placement.sealed_by == region.sealed_by
	             and entry.placement.path != region.path
	             and entry.placement.kind != "element"]
	if not interiors:
		return []

	local   = c_name(region.path[len(struct.name) + 1 :])
	secrets = [p for p in interiors
	           if any(attr.name == "secret" for attr in p.attrs)]

	if region.unverified_ok:
		# `[unverified_ok]`: the interior is readable without a gate, so its
		# accessors take the view like any other member's.
		lines = [f"\t/* {region.path}: readable unverified, so no gate. */"]
		for placement in interiors:
			lines.extend(_interior_member(struct, placement, prefix,
			                              "view", "\t"))
		for placement in secrets:
			lines.append(f"\t{ident(prefix, struct.name, c_name(placement.path[len(struct.name) + 1 :]), 'zeroize')}(view);")
		return lines

	gate_type = ident(prefix, struct.name, local, "t")
	opener    = ident(prefix, struct.name, local, "open")
	lines = [
		"\t{",
		f"\t\t{gate_type} gate;",
		"",
		"\t\t/* Verified, because the gate is not the subject: `_open`",
		"\t\t * checks the flag and copies the view, and refusing is two",
		"\t\t * lines the hand-written tests already cover. The parsing on",
		"\t\t * the far side is reachable no other way, and it runs on",
		"\t\t * bytes somebody chose. */",
		f"\t\tif ({opener}(view, 1, &gate) == SITU_OK) {{",
	]
	for placement in interiors:
		lines.extend(_interior_member(struct, placement, prefix,
		                              "gate", "\t\t\t"))
	if secrets:
		lines.append("")
		lines.append("\t\t\t/* Last, because these write. */")
		for placement in secrets:
			member = c_name(placement.path[len(struct.name) + 1 :])
			lines.append(
				f"\t\t\t{ident(prefix, struct.name, member, 'zeroize')}(gate);")
	lines.extend(["\t\t}", "\t}"])
	return lines


def _erases(struct: ResolvedStruct, prefix: str) -> list[str]:
	"""Call every `[secret]` member's eraser, last.

	Gated members are skipped: an interior sealed behind a verified tag takes
	a gate this harness never opens, so its accessors are not callable from
	here at all -- which is why `keystore`'s `secret_key` appears nowhere in
	its harness. That is a wider gap than the erasers and belongs to whoever
	teaches this to open a gate.
	"""
	lines: list[str] = []
	for entry in own_entries(struct):
		placement = entry.placement
		if not any(attr.name == "secret" for attr in placement.attrs):
			continue
		if placement.sealed_by is not None and not placement.unverified_ok:
			continue

		local = c_name(placement.path[len(struct.name) + 1 :])
		if not lines:
			lines.append("")
			lines.append("\t/* Last, because these write. The span an eraser")
			lines.append("\t * clears is the one the data declares, so a")
			lines.append("\t * missing clamp is an out-of-frame write here. */")
		lines.append(f"\t{ident(prefix, struct.name, local, 'zeroize')}(view);")
	return lines


def _arm_reads(struct: ResolvedStruct, placement: Placement, prefix: str,
		resolved: ResolvedSchema) -> list[str]:
	"""Every arm of a variant, through the accessor its shape gets.

	`own_entries` drops a dotted path, so an arm member never reached the
	walk on its own and this harness had asked about none of them -- the
	same gap the sealed interiors had, one family over (26.318). It is why
	`dnsname`'s `label.body.pointer_low` read a byte past a one-byte frame
	for as long as it did: the C harness could not call it, and the defect
	surfaced only when the C++ backend got a harness built from the
	differential's driver, which does probe arms (26.325).

	The four shapes are the four `_arm_member` emits, in its order, so this
	names an accessor exactly when that one wrote it. Anything else gets no
	call rather than a guess -- a harness naming a function the backend
	declined to emit is a build failure across every schema, which is a
	loud way to learn the dispatch has a fifth branch.
	"""
	lines: list[str] = []
	for _arm, member in arm_members(struct, placement):
		if member is None:
			continue
		scalar = member.scalar
		local  = c_name(member.path[len(struct.name) + 1 :])

		# 1. A plain scalar arm.
		if scalar is not None and member.array_count is None \
				and member.sized_by is None and not data_sized(member):
			lines.extend([
				"\t{",
				f"\t\t{_ctype_of(member)} held = 0;",
				"",
				f"\t\tif ({ident(prefix, struct.name, local, 'get')}"
				"(view, &held) == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)held);",
				"\t\t}",
				"\t}",
			])
			continue

		# 2. A byte run. The LAST byte it claims, for the reason `_reads`
		# gives: the length is the attacker's and an off-by-one in the
		# extent shows up at the end rather than the start.
		if scalar is not None and scalar.bits == BITS_PER_BYTE \
				and not indexed_elements(member):
			lines.extend([
				"\t{",
				"\t\tconst uint8_t *held = NULL;",
				"\t\tuint32_t       n    = 0u;",
				"",
				f"\t\tif ({ident(prefix, struct.name, local, 'ptr')}"
				"(view, &held, &n) == SITU_OK",
				"\t\t\t\t&& held != NULL && n != 0u) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)held[n - 1u]);",
				"\t\t}",
				"\t}",
			])
			continue

		# 3. A run of values wider than a byte: a count and an indexed
		# getter, the bytes not being the values.
		if scalar is not None and indexed_elements(member):
			lines.extend([
				"\t{",
				"\t\tuint32_t n = 0u;",
				"",
				f"\t\tif ({ident(prefix, struct.name, local, 'count')}"
				"(view, &n) == SITU_OK) {",
				"\t\t\tuint32_t i;",
				"",
				"\t\t\tfor (i = 0u; i < n && i < 64u; i++) {",
				f"\t\t\t\t{_ctype_of(member)} held = 0;",
				"",
				f"\t\t\t\tif ({ident(prefix, struct.name, local, 'get')}"
				"(view, i, &held) == SITU_OK) {",
				"\t\t\t\t\tsitu_fuzz_sink((uint64_t)held);",
				"\t\t\t\t}",
				"\t\t\t}",
				"\t\t}",
				"\t}",
			])
			continue

		# 4. A struct-typed arm: the sub-view, which is itself the bounds
		# check. Its own members belong to its type and are fuzzed under
		# that struct's own harness.
		nested = resolved.structs.get(member.type_name or "")
		if nested is not None and member.array_count is None \
				and member.sized_by is None \
				and (nested.layout.is_fixed_size
				     or has_computable_extent(resolved.structs, nested)):
			lines.extend([
				"\t{",
				"\t\tsitu_view_t arm;",
				"",
				f"\t\tif ({ident(prefix, struct.name, local, 'view')}"
				"(view, &arm) == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)arm.limit);",
				"\t\t}",
				"\t}",
			])
	return lines


def _reads(struct: ResolvedStruct, prefix: str,
		resolved: ResolvedSchema) -> list[str]:
	lines = []
	# `own_entries` rather than `struct.entries`: an array's `[]` entry
	# describes every element at once and owns no bytes, so reading it here
	# emitted an accessor for a member that does not exist. The shared walk
	# knows that (invariant 20); this loop had its own copy that did not.
	for entry in own_entries(struct):
		placement = entry.placement
		if placement.kind == "reserved":
			continue

		local = c_name(placement.path[len(struct.name) + 1 :])

		# Before the scalar case, and before the counted-array one. A member
		# whose extent the data decides has no `_get`: it has a pointer and a
		# length, and those are the two the fuzzer most wants exercised --
		# the length is attacker-controlled and the pointer is what it aims.
		if placement.since is not None:
			lines.extend(_versioned_read(struct, placement, local, prefix,
			                             resolved.layout.env.enums))
			continue

		if placement.repeat_while is not None:
			# Walking the run is the read that can run off the end, and this
			# is the harness whose whole job is to try. Falling through to the
			# nested-struct branch named a `_view` accessor a run does not
			# have.
			lines.extend(_walk_read(struct, local, prefix))
			continue

		# Before the data-sized branch, and for the same reason: a located
		# member is sized by a field and reached through a `_view` that takes
		# the message as well as the frame (9.8), so `_len` and `_ptr` are not
		# what it has. Its accessor is the one a fuzzer most wants pointed at
		# it -- an offset the *data* chooses, bounds-checked on every call.
		if placement.located is not None:
			lines.extend(_located_read(struct, local, prefix))
			continue

		# Before the data-sized branch, which this looks like from the
		# outside: an `indexed` region is `sized_by` its count field and is
		# not an array. It reached for `_len` and `_ptr`, which an offset
		# table does not have, and the harness stopped compiling the day the
		# first indexed example landed. What it does have is the pair a
		# fuzzer most wants: a count the data chooses and an offset it aims.
		if placement.kind == "indexed":
			lines.extend(_indexed_read(struct, local, prefix))
			continue

		# A `tlv` region: the tag, the length and the wire type all come off
		# the wire, which makes the walk the most attacker-facing loop the
		# language generates. It reached the `else` below and got a comment
		# saying there was no sub-view to take.
		if placement.kind == "tlv":
			lines.extend(_tlv_read(struct, local, prefix))
			continue

		# A member the *data* sizes. `sized_by` alone is not that test: it
		# also names a compile-time constant, and where the count is known the
		# accessors are the fixed-array ones -- a `[CHANNEL_COUNT]` array got
		# `_len` and `_count`, which are emitted only for a runtime length.
		# `array_count` is the honest question, now that it is never a guess.
		# `data_sized` rather than `sized_by`, which is the same question with
		# one spelling missing: a length written as arithmetic reached the
		# scalar branch below and asked for a `_get` that takes no index.
		if placement.array_count is None \
				and (placement.delimiters
				     or data_sized(placement)):
			lines.extend(_variable_read(frozenset(resolved.structs), struct,
			                            placement, local, prefix))
			continue

		if placement.kind == "sealed":
			lines.extend(_sealed_read(struct, placement, prefix))
			continue

		if placement.kind == "variant":
			lines.extend(_arm_reads(struct, placement, prefix, resolved))
			continue

		if placement.kind == "marker":
			lines.append(f"\tsitu_fuzz_sink(("
			             f"uint64_t){ident(prefix, struct.name, local, 'is_little')}(view));")
		elif placement.radix is not None:
			# A text number, fixed-width: `decimal u16 code[3]` is one number
			# in three digits, not three numbers. Its accessor parses and
			# returns an error, and the array branch below called it with an
			# index and a `_COUNT` macro that is not emitted for one.
			#
			# A scaled one reports two numbers, so its getter takes a second
			# out-parameter and both go to the sink: fuzzing the significand
			# and dropping the exponent would leave half the parse unreached
			# (0056).
			lines.extend([
				"\t{",
				f"\t\t{_ctype_of(placement)} parsed = 0;",
				*(["\t\tint32_t power = 0;"] if placement.scaled else []),
				f"\t\tif ({ident(prefix, struct.name, local, 'get')}"
				+ ("(view, &parsed, &power)" if placement.scaled
				   else "(view, &parsed)")
				+ " == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)parsed);",
				*(["\t\t\tsitu_fuzz_sink((uint64_t)power);"]
				  if placement.scaled else []),
				"\t\t}",
				"\t}",
			])
		elif placement.array_count is not None and placement.scalar is None:
			# A constant-length array of structs: an indexed accessor over a
			# count the header carries as a macro.
			count = macro(prefix, struct.name, local, "COUNT")
			at    = ident(prefix, struct.name, local, "at")
			lines.extend([
				"\t{",
				"\t\tsitu_view_t element;",
				"",
				f"\t\tfor (uint32_t i = 0u; i < {count}; i++) {{",
				f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
				"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
				"\t\t\t}",
				"\t\t}",
				"\t}",
			])
		elif placement.array_count is not None and placement.scalar is not None:
			if placement.scalar.bits == 8:
				# Through a NULL check, because the pointer is one now: a
				# counted array at an offset the message chose may not be in
				# the view at all, and the accessor says so by handing back
				# NULL. Dereferencing it anyway is not merely a trap -- at
				# `-O1` the compiler takes the deref as proof the branch it
				# guards cannot be taken, folds the check away, and the read
				# lands past the buffer. Which is how this was found: the
				# harness kept crashing after the accessor was fixed.
				pointer = ident(prefix, struct.name, local, "ptr")
				lines.extend([
					"\t{",
					f"\t\tconst uint8_t *held = {pointer}(view);",
					"",
					"\t\tif (held != NULL) {",
					"\t\t\tsitu_fuzz_sink((uint64_t)*held);",
					"\t\t}",
					"\t}",
				])
			else:
				count = macro(prefix, struct.name, local, "COUNT")
				lines.extend([
					f"\tfor (size_t i = 0; i < {count}; i++) {{",
					f"\t\tsitu_fuzz_sink((uint64_t)"
					f"{ident(prefix, struct.name, local, 'get')}(view, (uint32_t)i));",
					"\t}",
				])
		elif placement.scalar is not None:
			lines.append(f"\tsitu_fuzz_sink((uint64_t)"
			             f"{ident(prefix, struct.name, local, 'get')}(view));")
		elif _has_sub_view(resolved, struct, placement):
			# A nested struct: take the sub-view, which is itself a bounds check.
			lines.extend([
				"\t{",
				"\t\tsitu_view_t sub;",
				f"\t\tif ({ident(prefix, struct.name, local, 'view')}"
				"(view, &sub) == SITU_OK) {",
				"\t\t\tsitu_fuzz_sink((uint64_t)sub.limit);",
				"\t\t}",
				"\t}",
			])
		else:
			lines.append(f"\t/* {placement.path}: no sub-view to reach"
			             " through; `validate` above covers it. */")

	return lines


def _has_sub_view(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> bool:
	"""Whether the header offers a `_view` for this member.

	The fifth consumer to need this and the fourth to get it wrong on its own.
	A `variant` is not a scalar and not a nested struct: exactly one arm is
	present, so there is no single sub-view and none is emitted -- and the
	`else` here assumed anything without a scalar had one. A nested struct
	nothing can measure has none either, for the reason in `emit`.
	"""
	nested = resolved.structs.get(placement.type_name or "")
	if nested is None:
		return False
	return nested.layout.is_fixed_size \
		or has_computable_extent(resolved.structs, nested)


def _located_read(struct: ResolvedStruct, local: str, prefix: str) -> list[str]:
	"""A member the data positions: take its view and read what it reached."""
	view = ident(prefix, struct.name, local, "view")
	return [
		f"\t/* {struct.name}.{local}: placed where the data says. */",
		"\t{",
		"\t\tsitu_view_t placed;",
		"",
		f"\t\tif ({view}(&msg, view, &placed) == SITU_OK) {{",
		"\t\t\tsitu_fuzz_sink((uint64_t)placed.limit);",
		"\t\t\tif (placed.limit > 0u) {",
		"\t\t\t\tsitu_fuzz_sink((uint64_t)placed.base[0]);",
		"\t\t\t\tsitu_fuzz_sink((uint64_t)placed.base[placed.limit - 1u]);",
		"\t\t\t}",
		"\t\t}",
		"\t}",
	]


def _indexed_read(struct: ResolvedStruct, local: str,
		prefix: str) -> list[str]:
	"""Read every entry of an offset table, and one past it.

	The count comes from the data, so a hostile page can claim more entries
	than the table holds; reading them all is what proves the bound is checked
	rather than trusted.
	"""
	count  = ident(prefix, struct.name, local, "count")
	offset = ident(prefix, struct.name, local, "offset")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {count}(view);",
		"\t\tuint32_t i;",
		"",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tfor (i = 0; i < n; i++) {",
		"\t\t\tuint32_t found = 0;",
		"",
		f"\t\t\tif ({offset}(view, i, &found) == SITU_OK) {{",
		"\t\t\t\tsitu_fuzz_sink((uint64_t)found);",
		"\t\t\t}",
		"\t\t}",
		"\t\t{",
		"\t\t\tuint32_t past = 0;",
		"",
		f"\t\t\tsitu_fuzz_sink((uint64_t){offset}(view, n, &past));",
		"\t\t}",
		"\t}",
	]


def _tlv_read(struct: ResolvedStruct, local: str, prefix: str) -> list[str]:
	"""Walk a `tlv` region item by item, and count it.

	Every number in the loop is the message's: the tag is a varint the input
	chooses, the length is another, and the value extent is where those two
	put it. Walking to the end is what proves an item claiming more than the
	region holds is refused rather than followed -- and `_count`, which walks
	it again, is the same question asked by a second loop that has to agree.
	"""
	item  = ident(prefix, struct.name, local, "item_t")
	first = ident(prefix, struct.name, local, "first")
	nxt   = ident(prefix, struct.name, local, "next")
	count = ident(prefix, struct.name, local, "count")

	return [
		"\t{",
		f"\t\t{item} item;",
		f"\t\tsitu_err_t walked = {first}(view, &item);",
		"",
		"\t\twhile (walked == SITU_OK) {",
		"\t\t\tsitu_fuzz_sink((uint64_t)item.tag);",
		"\t\t\tsitu_fuzz_sink((uint64_t)item.value_at);",
		"\t\t\tsitu_fuzz_sink((uint64_t)item.value_len);",
		f"\t\t\twalked = {nxt}(&item);",
		"\t\t}",
		f"\t\tsitu_fuzz_sink((uint64_t){count}(view));",
		"\t}",
	]


def _walk_read(struct: ResolvedStruct, local: str, prefix: str) -> list[str]:
	"""Count a run and reach every element of it."""
	count = ident(prefix, struct.name, local, "count")
	at    = ident(prefix, struct.name, local, "at")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {count}(view);",
		"\t\tsitu_view_t element;",
		"",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tfor (uint32_t i = 0u; i < n; i++) {",
		f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
		"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
		"\t\t\t}",
		"\t\t}",
		"\t}",
	]


def _versioned_read(struct: ResolvedStruct, placement: Placement, local: str,
		prefix: str, enums: Mapping[str, object]) -> list[str]:
	"""A member the version decides is there (section 19.4).

	Its getter returns an error rather than a value, so the plain sink call
	did not compile -- and the read worth fuzzing is the refusal: a version
	byte the fuzzer chose deciding whether four bytes at a fixed offset are
	this message's.
	"""
	# The accessor's own type, not the backing scalar. An enum member's
	# out-parameter is `situ_dialect_t *`, and `uint8_t *` is not that -- the
	# harness declared the width and the header declared the type, which
	# nothing noticed while no versioned member had ever been an enum.
	held = (ident(prefix, placement.type_name or "") + "_t"
	        if placement.type_name in enums else _ctype_of(placement))

	return [
		"\t{",
		f"\t\t{held} held = 0;",
		f"\t\tif ({ident(prefix, struct.name, local, 'get')}(view, &held)"
		" == SITU_OK) {",
		"\t\t\tsitu_fuzz_sink((uint64_t)held);",
		"\t\t}",
		"\t}",
	]


def _variable_read(structs: frozenset[str], struct: ResolvedStruct,
		placement: Placement, local: str, prefix: str) -> list[str]:
	"""Exercise a member the data sizes, without assuming it has a value.

	A run of records has neither a pointer nor a length -- it has a count and
	an indexed accessor -- so it is walked instead, which is the read that can
	run off the end and therefore the one worth fuzzing.
	"""
	if placement.type_name in structs:
		# A run of records has a count and an indexed accessor rather than a
		# pointer and a length. Walking it is the read that can run off the
		# end, so it is the one worth fuzzing.
		#
		# What bounds the run -- a delimiter, a length field, a condition --
		# does not change that, and this asked for a delimiter as well. So a
		# `recs[n]` of structs reached for `_len` and `_ptr` and the harness
		# did not compile, in a schema that had been in the tree since phase
		# 5 and was never fuzzed.
		count = ident(prefix, struct.name, local, "count")
		at    = ident(prefix, struct.name, local, "at")
		return [
			"\t{",
			f"\t\tconst uint32_t n = {count}(view);",
			"\t\tsitu_view_t element;",
			"",
			"\t\tsitu_fuzz_sink((uint64_t)n);",
			"\t\tfor (uint32_t i = 0u; i < n; i++) {",
			f"\t\t\tif ({at}(view, i, &element) == SITU_OK) {{",
			"\t\t\t\tsitu_fuzz_sink((uint64_t)element.limit);",
			"\t\t\t}",
			"\t\t}",
			"\t}",
		]

	if placement.delimiters and placement.radix is not None:
		# A text number: the parse is the interesting part, and it returns an
		# error rather than a value.
		#
		# A scaled one reports two numbers, so its getter takes a second
		# out-parameter and both go to the sink: fuzzing the significand and
		# dropping the exponent would leave half the parse unreached (0056).
		return [
			"\t{",
			f"\t\t{_ctype_of(placement)} parsed = 0;",
			*(["\t\tint32_t power = 0;"] if placement.scaled else []),
			f"\t\tif ({ident(prefix, struct.name, local, 'get')}(view,"
			+ (" &parsed, &power)" if placement.scaled else " &parsed)")
			+ " == SITU_OK) {",
			"\t\t\tsitu_fuzz_sink((uint64_t)parsed);",
			*(["\t\t\tsitu_fuzz_sink((uint64_t)power);"]
			  if placement.scaled else []),
			"\t\t}",
			"\t}",
		]

	if indexed_elements(placement):
		# An element wider than a byte has no pointer -- it is ValueConverted,
		# so the bytes are not the values -- and this asked for one anyway, so
		# the harness for any schema with a `u16 x[n]` did not compile. Nothing
		# noticed because no schema here had one until somebody wrote it to see
		# what would happen.
		count  = ident(prefix, struct.name, local, "count")
		getter = ident(prefix, struct.name, local, "get")
		return [
			"\t{",
			f"\t\tconst uint32_t n = {count}(view);",
			"",
			"\t\t/* The count is the attacker's. Read the last element it",
			"\t\t * claims rather than the first: an off-by-one in the",
			"\t\t * extent shows up there. */",
			"\t\tsitu_fuzz_sink((uint64_t)n);",
			"\t\tif (n > 0u) {",
			f"\t\t\tsitu_fuzz_sink((uint64_t){getter}(view, n - 1u));",
			"\t\t}",
			"\t}",
		]

	length = ident(prefix, struct.name, local, "len")
	ptr    = ident(prefix, struct.name, local, "ptr")

	return [
		"\t{",
		f"\t\tconst uint32_t n = {length}(view);",
		"",
		"\t\t/* The length is the attacker's and the pointer is where it",
		"\t\t * aims, so read the last byte it claims rather than the",
		"\t\t * first: an off-by-one in the extent shows up there. */",
		"\t\tsitu_fuzz_sink((uint64_t)n);",
		"\t\tif (n > 0u) {",
		f"\t\t\tsitu_fuzz_sink((uint64_t){ptr}(view)[n - 1u]);",
		"\t\t}",
		"\t}",
	]


def _ctype_of(placement: Placement) -> str:
	"""The holder for a value this harness reads back.

	Signed where the member is, which nothing here asked until a text
	number could be: the getter takes `int16_t *` for `decimal i16`, and a
	`uint16_t` handed to it is `-Werror=pointer-sign` rather than a wrong
	number -- so the harness for any schema carrying one did not compile.
	"""
	scalar = placement.scalar
	assert scalar is not None
	return f"{'int' if scalar.signed else 'uint'}{max(8, scalar.bits)}_t"


def _key_bytes(resolved: ResolvedSchema, struct_name: str,
		path: str) -> tuple[int, int] | None:
	"""(offset, width) of one key field, or None where it is not a constant."""
	struct = resolved.structs.get(struct_name)
	if struct is None:
		return None
	member = path.partition(".")[2]
	for entry in struct.entries:
		placement = entry.placement
		if placement.path != f"{struct_name}.{member}":
			continue
		if (placement.offset_bits is None or placement.size_bits is None
				or placement.offset_bits % 8 or placement.size_bits % 8):
			return None
		return (placement.offset_bits // 8, placement.size_bits // 8)
	return None


def _relation_harnesses(schema: ast.Schema, resolved: ResolvedSchema,
		prefix: str) -> tuple[list[str], list[str]]:
	"""A harness per relation, and the names of the ones emitted.

	**The copy is the whole point.** A relation says a reply echoes an
	identifier, and a fuzzer that has to rediscover that by luck never gets
	past the first check -- a `u16` match is one draw in 65536, and a varint
	is worse. So the harness splits its input in two and *copies* the key
	bytes from the first message into the second before calling the
	predicate, which is the same equality constraint the dissector reads as a
	conversation key. Without it the target reaches nothing, and a target
	that reaches nothing looks exactly like a clean run.

	It needs the `--layer relate` header, which is stated in the file rather
	than discovered at the first build.
	"""
	lines: list[str] = []
	names: list[str] = []

	for decl in schema.relations():
		try:
			relation.plan(decl, resolved)
		except relation.Refused:
			continue

		pairs  = relation.conversation_key(decl)
		first, second = (param.type_name for param in decl.params)
		copies = [(_key_bytes(resolved, first, a), _key_bytes(resolved, second, b))
		          for a, b in pairs]
		usable = [(x, y) for x, y in copies if x is not None and y is not None]
		if not pairs or len(usable) != len(copies):
			lines += ["", f"/* No harness for relation {decl.name}: a key field "
			              "has no",
			          " * constant offset, so there is no byte range to copy. */"]
			continue

		name = c_name(decl.name)
		names.append(name)
		half = f"situ_rel_{name}_half"
		lines += [
			"",
			f"static void fuzz_rel_{name}(const uint8_t *data, size_t size)",
			"{",
			f"\tconst size_t {half} = size / 2u;",
			f"\tif ({half} == 0u) {{",
			"\t\treturn;",
			"\t}",
			"",
			"\tuint8_t a[512], b[512];",
			f"\tconst size_t n = {half} < sizeof(a) ? {half} : sizeof(a);",
			"",
			"\tmemset(a, 0, sizeof(a));",
			"\tmemset(b, 0, sizeof(b));",
			"\tmemcpy(a, data, n);",
			f"\tmemcpy(b, data + {half}, n);",
			"",
			"\t/* The copy the relation asks for, so the predicate can get",
			"\t * past its own equality and exercise what follows. */",
		]
		for (src, _w1), (dst, width) in usable:
			lines.append(f"\tif ({dst}u + {width}u <= n) {{")
			lines.append(f"\t\tmemcpy(b + {dst}u, a + {src}u, {width}u);")
			lines.append("\t}")

		lines += [
			"",
			"\tsitu_msg_t ma, mb;",
			"\tsitu_view_t va, vb;",
			"\tsitu_msg_init(&ma, a, (uint32_t)n);",
			"\tsitu_msg_init(&mb, b, (uint32_t)n);",
			f"\tif ({ident(prefix, first, 'view')}(&ma, 0u, &va) != SITU_OK) {{",
			"\t\treturn;",
			"\t}",
			f"\tif ({ident(prefix, second, 'view')}(&mb, 0u, &vb) != SITU_OK) {{",
			"\t\treturn;",
			"\t}",
			"",
			f"\tsitu_fuzz_sink((uint64_t){ident(prefix, 'rel', name)}(va, vb));",
			"}",
		]

	return lines, names


def _entry_point(structs: list[ResolvedStruct], basename: str,
		prefix: str, relations: list[str] | None = None) -> list[str]:
	lines = [
		"int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);",
		"",
		"int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)",
		"{",
	]

	targets = list(relations or [])

	if not structs and not targets:
		lines.extend(["\t(void)data;", "\t(void)size;"])
	else:
		# The first byte selects a struct, so one corpus drives every parser in
		# the schema rather than needing a binary each.
		calls = [f"fuzz_{c_name(struct.name)}(data + 1, size - 1u)"
		         for struct in structs]
		calls += [f"fuzz_rel_{name}(data + 1, size - 1u)" for name in targets]

		lines.extend([
			"\tif (size < 1u) {",
			"\t\treturn 0;",
			"\t}",
			"",
			f"\tswitch (data[0] % {len(calls)}u) {{",
		])
		for index, call in enumerate(calls):
			lines.append(f"\tcase {index}u:")
			lines.append(f"\t\t{call};")
			lines.append("\t\tbreak;")
		lines.extend(["\tdefault:", "\t\tbreak;", "\t}"])

	lines.extend(["", "\treturn 0;", "}", ""])
	return lines


def _standalone(basename: str) -> list[str]:
	return [
		"#ifdef SITU_FUZZ_STANDALONE",
		"",
		"#include <stdio.h>",
		"",
		"/* One input from stdin, so the harness can be built and run without a",
		" * fuzzing engine. This is what keeps it from rotting between runs. */",
		"int main(void)",
		"{",
		"\tuint8_t buf[4096];",
		"\tsize_t  n = fread(buf, 1, sizeof(buf), stdin);",
		"",
		"\treturn LLVMFuzzerTestOneInput(buf, n);",
		"}",
		"",
		"#endif /* SITU_FUZZ_STANDALONE */",
	]
