"""The tamper harness: watch the gate refuse (suggestion/netcfgd.md, 26.131).

The strongest thing in the crypto model is that the verify gate is a type --
and the adopter who said so also said that a gate nobody has watched fail is
not evidence. Their whole method breaks every check on purpose before
trusting it, and the question a prospective adopter asks early is exactly
"how do I demonstrate that the gate actually refuses?".

This generates the demonstration. For each struct carrying a tag, a function
that takes a message the caller's verifier accepts, flips one byte at a time
through the tag's coverage and through the tag's own bytes, and requires the
verifier to refuse every single one -- restoring the byte after each flip.
Where the struct is statically fixed, it also flips every byte *outside*
coverage and requires the verifier to keep accepting, which is what catches a
verifier covering more than the schema says. That half is emitted only for
fixed layouts, deliberately: outside a fixed layout, a flipped byte can be a
length, and a parse that legitimately moved is not an over-covering verifier.

THE DIVISION OF LABOUR IS 14.6's. The verifier -- the primitive, its key,
its constant-time comparison -- is the caller's, passed in as a callback.
What this file contributes is the geometry: which bytes must matter and
which must not, read through the same generated `_covered` helpers the
caller's own recompute uses, so there is one answer to "which bytes" in the
whole program.

WHAT A PASS MEANS, AND WHAT IT CANNOT. A verifier that survives says: every
byte the schema declares covered is a byte your verifier notices, and (for
fixed layouts) no byte outside it is. It does not say the primitive is
strong, the key is secret, or the comparison is constant time -- those are
the caller's, per 14.6, and no generated test can reach them.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.c.names import c_name, ident, macro
from situc.layout import Placement
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc import __version__

__all__ = ["generate"]


def _tags(resolved_struct: ResolvedStruct) -> list[Placement]:
	return [entry.placement for entry in resolved_struct.entries
	        if entry.placement.kind == "tag"]


def _is_fixed(resolved_struct: ResolvedStruct) -> bool:
	layout = resolved_struct.layout
	return layout.size_bits == getattr(layout, "size_max_bits", layout.size_bits)


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> dict[str, str]:
	"""The tamper header, or nothing where no struct carries a tag."""
	ready = [(name, struct) for name, struct in sorted(resolved.structs.items())
	         if _tags(struct)]
	if not ready:
		return {}

	guard = macro(prefix, basename, "TAMPER_H")
	lines = [
		f"/* Generated by situc {__version__} from {basename}.situ"
		" -- do not edit.",
		" *",
		" * The tamper harness: every byte the schema declares covered must",
		" * matter to your verifier, one flip at a time. The verifier is",
		" * yours -- the primitive, the key, the constant-time comparison",
		" * (14.6) -- and the geometry is the schema's, read through the same",
		" * generated helpers your recompute uses.",
		" *",
		" * A gate nobody has watched fail is not evidence; this is the",
		" * watching, generated so it cannot drift from the coverage.",
		" */",
		"",
		f"#ifndef {guard}",
		f"#define {guard}",
		"",
		"#include \"situ.h\"",
		f"#include \"{basename}.h\"",
		"",
		"#ifdef __cplusplus",
		"extern \"C\" {",
		"#endif",
		"",
		"/* Your verifier: 1 where the message's tags verify, 0 where they",
		" * do not. `ctx` is yours and is passed through untouched. */",
		f"typedef int (*{prefix}_verify_fn)(situ_view_t view, void *ctx);",
		"",
	]

	for name, struct in ready:
		lines.extend(_harness(name, struct, prefix))

	lines += [
		"#ifdef __cplusplus",
		"}",
		"#endif",
		"",
		f"#endif /* {guard} */",
	]

	return {f"{basename}_tamper.h": "\n".join(lines) + "\n"}


def _harness(name: str, struct: ResolvedStruct, prefix: str) -> list[str]:
	tags  = _tags(struct)
	fixed = _is_fixed(struct)
	fn    = ident(prefix, c_name(name), "tamper")
	view_fn = ident(prefix, c_name(name), "view")

	view_call = (f"{view_fn}(&msg, 0u, &view)" if fixed
	             else f"{view_fn}(&msg, 0u, len, &view)")

	lines = [
		f"/** Watch `{name}`'s gate refuse.",
		" *",
		" * `bytes` must hold a message your verifier accepts; every flip is",
		" * restored before the next, so the buffer is unchanged on return.",
		" *",
		" * SITU_OK              the verifier notices every covered byte" +
		("" if not fixed else ",\n *                      and only those"),
		" * SITU_ERR_TAG         the message did not verify on entry",
		" * SITU_ERR_CONSTRAINT  a flip the verifier should have refused",
		" *                      was accepted" +
		("" if not fixed else ", or one it should have\n"
		 " *                      accepted was refused") + "; `*failed_at`",
		" *                      names the byte",
		" * SITU_ERR_BOUNDS      the buffer does not hold one message",
		" */",
		f"static inline situ_err_t {fn}(uint8_t *bytes, uint32_t len,",
		f"                              {prefix}_verify_fn verify, void *ctx,",
		"                              uint32_t *failed_at)",
		"{",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		"",
		"\tsitu_msg_init(&msg, bytes, len);",
		f"\tif ({view_call} != SITU_OK) {{",
		"\t\treturn SITU_ERR_BOUNDS;",
		"\t}",
		"\tif (!verify(view, ctx)) {",
		"\t\treturn SITU_ERR_TAG;",
		"\t}",
		"",
	]

	# One flip loop per span that must matter: each tag's coverage, and each
	# tag's own bytes -- a verifier that ignores its own stored tag accepts
	# every forgery whose payload it likes.
	for tag in tags:
		covered = ident(prefix, c_name(name), c_name(tag.name), "covered")
		tag_ptr = ident(prefix, c_name(name), c_name(tag.name), "ptr")
		width   = (tag.size_bits or 0) // 8
		lines += [
			"\t{",
			f"\t\tuint32_t at   = 0u;",
			f"\t\tuint32_t span = 0u;",
			"",
			f"\t\tif ({covered}(view, &at, &span) != SITU_OK) {{",
			"\t\t\treturn SITU_ERR_BOUNDS;",
			"\t\t}",
			"\t\tfor (uint32_t i = at; i < at + span; i++) {",
			"\t\t\tbytes[i] ^= 0xFFu;",
			"\t\t\tif (verify(view, ctx)) {",
			"\t\t\t\tbytes[i] ^= 0xFFu;",
			"\t\t\t\t*failed_at = i;",
			"\t\t\t\treturn SITU_ERR_CONSTRAINT;",
			"\t\t\t}",
			"\t\t\tbytes[i] ^= 0xFFu;",
			"\t\t}",
			"",
			f"\t\t/* {tag.path}'s own bytes: a verifier that ignores the",
			"\t\t * stored tag accepts every forgery whose payload it",
			"\t\t * likes. */",
			"\t\t{",
			f"\t\t\tconst uint32_t self = (uint32_t)"
			f"({tag_ptr}(view) - view.base);",
			"",
			f"\t\t\tfor (uint32_t i = self; i < self + {width}u; i++) {{",
			"\t\t\t\tbytes[i] ^= 0xFFu;",
			"\t\t\t\tif (verify(view, ctx)) {",
			"\t\t\t\t\tbytes[i] ^= 0xFFu;",
			"\t\t\t\t\t*failed_at = i;",
			"\t\t\t\t\treturn SITU_ERR_CONSTRAINT;",
			"\t\t\t\t}",
			"\t\t\t\tbytes[i] ^= 0xFFu;",
			"\t\t\t}",
			"\t\t}",
			"\t}",
			"",
		]

	if fixed:
		# The over-coverage half: outside every covered span and every tag,
		# a flip must leave the verifier's answer alone. Only for a fixed
		# layout -- outside one, a flipped byte can be a length, and a parse
		# that legitimately moved is not an over-covering verifier.
		checks = []
		for tag in tags:
			covered = ident(prefix, c_name(name), c_name(tag.name), "covered")
			tag_ptr = ident(prefix, c_name(name), c_name(tag.name), "ptr")
			width   = (tag.size_bits or 0) // 8
			checks += [
				f"\t\t\tif ({covered}(view, &at, &span) != SITU_OK) {{",
				"\t\t\t\treturn SITU_ERR_BOUNDS;",
				"\t\t\t}",
				"\t\t\tinside = inside || (i >= at && i < at + span);",
				f"\t\t\tself = (uint32_t)({tag_ptr}(view) - view.base);",
				f"\t\t\tinside = inside || (i >= self && i < self + {width}u);",
			]
		lines += [
			"\t/* And only those: outside coverage a flip must not change",
			"\t * the answer, which is what catches a verifier covering",
			"\t * more than the schema says. */",
			"\tfor (uint32_t i = 0u; i < len; i++) {",
			"\t\tint      inside = 0;",
			"\t\tuint32_t at     = 0u;",
			"\t\tuint32_t span   = 0u;",
			"\t\tuint32_t self   = 0u;",
			"",
			"\t\t{",
			*checks,
			"\t\t}",
			"\t\tif (inside) {",
			"\t\t\tcontinue;",
			"\t\t}",
			"\t\tbytes[i] ^= 0xFFu;",
			"\t\tif (!verify(view, ctx)) {",
			"\t\t\tbytes[i] ^= 0xFFu;",
			"\t\t\t*failed_at = i;",
			"\t\t\treturn SITU_ERR_CONSTRAINT;",
			"\t\t}",
			"\t\tbytes[i] ^= 0xFFu;",
			"\t}",
			"",
		]

	lines += [
		"\t(void)len;",
		"\treturn SITU_OK;",
		"}",
		"",
	]
	return lines
