"""Generate cmocka golden-vector tests from a schema plus hex vectors.

"The only reliable way to know a layout change broke the wire format"
(project.md section 20.3). A capability map catches a change to what the
compiler *believes*; a golden vector catches a change to what it *emits*, and
those are different failures.

Vector file format, deliberately small enough to write by hand:

    # comments run to end of line
    Header  basic  01 02 E8 05 DC DE AD BE EF
        version = 1
        length  = 1500
        seq     = 0xDEADBEEF

A case is a struct name, a case name, and the bytes. Indented lines that follow
are expectations: a field path relative to the struct, and the value its getter
must return. A case with no expectations still asserts that the bytes are the
right length, that a view can be taken, that validation accepts them, and that
reading and writing every field back leaves the buffer byte-identical.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from situc import ast
from situc.codegen.c.names import c_name, ident, macro
from situc.diagnostics import Source, Span, error
from situc.resolve import ResolvedSchema, ResolvedStruct

EXPECTATION = re.compile(r"\A\s*([A-Za-z_][A-Za-z0-9_.]*)\s*=\s*(\S+)\s*\Z")


@dataclass
class Case:
	struct: str
	name: str
	data: bytes
	expectations: list[tuple[str, str]] = field(default_factory=list)
	line: int = 0


def parse_vectors(source: Source) -> list[Case]:
	"""Read a vector file, reporting problems the way the compiler does."""
	cases: list[Case] = []

	for number, raw in enumerate(source.text.splitlines(), start=1):
		line = raw.split("//")[0].split("#")[0].rstrip()
		if not line.strip():
			continue

		if line[0].isspace():
			if not cases:
				raise _error(source, number, raw,
				             "expectation before any vector",
				             "an indented line belongs to the case above it")
			cases[-1].expectations.append(_expectation(source, number, raw))
			continue

		cases.append(_case(source, number, line))

	return cases


def _case(source: Source, number: int, line: str) -> Case:
	parts = line.split()
	if len(parts) < 3:
		raise _error(source, number, line, "malformed vector",
		             "expected `<struct> <case-name> <hex bytes>`")

	struct, name = parts[0], parts[1]
	digits = "".join(parts[2:])

	if len(digits) % 2 != 0:
		raise _error(source, number, line, "hex vector has an odd number of digits",
		             "every byte needs two digits")

	try:
		data = bytes.fromhex(digits)
	except ValueError as exc:
		raise _error(source, number, line, f"malformed hex: {exc}",
		             "expected pairs of hex digits, optionally spaced") from exc

	return Case(struct=struct, name=name, data=data, line=number)


def _expectation(source: Source, number: int, raw: str) -> tuple[str, str]:
	match = EXPECTATION.match(raw)
	if match is None:
		raise _error(source, number, raw, "malformed expectation",
		             "expected `field = value`")
	return match.group(1), match.group(2)


def _error(source: Source, number: int, line: str, message: str, label: str):  # type: ignore[no-untyped-def]
	starts = source.line_starts()
	begin  = starts[number - 1] if number <= len(starts) else 0
	return error(message, Span(source, begin, begin + len(line)), label=label)


def generate(schema: ast.Schema, resolved: ResolvedSchema, cases: list[Case],
		basename: str, prefix: str = "situ") -> str:
	for case in cases:
		_check(resolved, case)

	lines = [
		f"/* Generated by situc from {basename}.situ and its vectors -- do not edit.",
		" *",
		" * A capability map catches a change to what the compiler believes. These",
		" * catch a change to what it emits, which is a different failure.",
		" */",
		"",
		"#include <setjmp.h>",
		"#include <stdarg.h>",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <string.h>",
		"",
		"#include <cmocka.h>",
		"",
		f'#include "{basename}.h"',
		"",
	]

	for case in cases:
		lines.extend(_case_body(resolved, case, prefix))

	lines.extend(_main(cases))
	return "\n".join(lines) + "\n"


def _check(resolved: ResolvedSchema, case: Case) -> None:
	struct = resolved.find_struct(case.struct)
	if struct is None:
		raise ValueError(f"vector `{case.name}` names unknown struct `{case.struct}`")

	expected = struct.layout.size_bytes
	if not struct.layout.is_byte_sized:
		raise ValueError(f"`{case.struct}` is not a whole number of bytes")

	if len(case.data) != expected:
		raise ValueError(
			f"vector `{case.name}` is {len(case.data)} bytes, but "
			f"`{case.struct}` is {expected}")

	for path, _ in case.expectations:
		if resolved.find(f"{case.struct}.{path}") is None:
			raise ValueError(
				f"vector `{case.name}` names unknown field `{case.struct}.{path}`")


def _case_body(resolved: ResolvedSchema, case: Case, prefix: str) -> list[str]:
	struct = resolved.find_struct(case.struct)
	assert struct is not None

	size  = macro(prefix, case.struct, "SIZE_FIXED")
	bytes_ = ", ".join(f"0x{byte:02X}" for byte in case.data)

	lines = [
		f"/* {case.struct} / {case.name} */",
		f"static const uint8_t vector_{case.name}[{size}] = {{",
		f"\t{bytes_},",
		"};",
		"",
		f"static void test_{case.name}(void **state)",
		"{",
		f"\tuint8_t     buf[{size}];",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		"",
		"\t(void)state;",
		f"\tmemcpy(buf, vector_{case.name}, sizeof(buf));",
		f"\tsitu_msg_init(&msg, buf, {size});",
		f"\tassert_int_equal({ident(prefix, case.struct, 'view')}(&msg, 0, &view),"
		" SITU_OK);",
		f"\tassert_int_equal({ident(prefix, case.struct, 'validate')}(view), SITU_OK);",
		"",
	]

	for path, value in case.expectations:
		local = c_name(path)
		lines.append(f"\tassert_int_equal({ident(prefix, case.struct, local, 'get')}"
		             f"(view), {value});")

	if case.expectations:
		lines.append("")

	lines.extend(_round_trip(resolved, struct, case, prefix))
	lines.extend(["}", ""])
	return lines


def _round_trip(resolved: ResolvedSchema, struct: ResolvedStruct, case: Case,
		prefix: str) -> list[str]:
	"""Read every settable field, write it back, require the bytes unchanged.

	Reserved regions are excluded: they carry no information and no accessor
	restores them, which is the whole point of them being reserved.
	"""
	writes = []
	for entry in struct.entries:
		placement = entry.placement
		if placement.kind != "field" or placement.scalar is None:
			continue
		if placement.array_count is not None:
			continue
		if "." in placement.path[len(struct.name) + 1 :]:
			continue

		local  = c_name(placement.path[len(struct.name) + 1 :])
		getter = ident(prefix, struct.name, local, "get")
		setter = ident(prefix, struct.name, local, "set")
		writes.append(f"\t{setter}(view, {getter}(view));")

	if not writes:
		return ["\t/* No settable scalar fields to round-trip. */"]

	return [
		"\t/* Every value written back through its own setter must reproduce the",
		"\t * bytes it came from. This is what catches a layout change. */",
		*writes,
		f"\tassert_memory_equal(buf, vector_{case.name}, sizeof(buf));",
	]


def _main(cases: list[Case]) -> list[str]:
	lines = ["int main(void)", "{", "\tconst struct CMUnitTest tests[] = {"]
	for case in cases:
		lines.append(f"\t\tcmocka_unit_test(test_{case.name}),")
	lines.extend([
		"\t};",
		"",
		"\treturn cmocka_run_group_tests(tests, NULL, NULL);",
		"}",
	])
	return lines
