"""Generate cmocka golden-vector tests from a schema plus hex vectors.

"The only reliable way to know a layout change broke the wire format"
(project.md section 20.3). A capability map catches a change to what the
compiler *believes*; a golden vector catches a change to what it *emits*, and
those are different failures.

Vector file format, deliberately small enough to write by hand:

    # comments run to end of line
    Header  basic  01 02 E8 05 DC DE AD BE EF
        version = 1
        length  = 1500
        seq     = 0xDEADBEEF

A case is a struct name, a case name, and the bytes. Indented lines that follow
are expectations: a field path relative to the struct, and the value its getter
must return. A case with no expectations still asserts that the bytes are the
right length, that a view can be taken, that validation accepts them, and that
reading and writing every field back leaves the buffer byte-identical.

An expectation takes the form its field admits, which is decided here against
the layout rather than guessed from how the value is spelled:

    mac    = 00:1A:2B:3C:4D:5E    a byte run, compared as bytes
    a.s    = 42                   a nested struct's field, through its own view

Both were written as though every field were a scalar. The first is why ARP --
twenty of its twenty-eight bytes addresses -- could state almost nothing about
itself; the second emitted C naming a getter that does not exist, since a
nested struct's accessors belong to its type (26.35).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from situc import ast
from situc.codegen.c.names import c_name, ident, macro
from situc.diagnostics import Source, Span, error
from situc.resolve import ResolvedSchema, ResolvedStruct

#: The value runs to the end of the line rather than being one token: a byte
#: run is written as bytes, and `00 1A 2B 3C 4D 5E` is six of them. Which of
#: the two a value is depends on the field it names, not on how it is spelled,
#: so the decision is made against the layout in `_expectation_lines`.
EXPECTATION = re.compile(r"\A\s*([A-Za-z_][A-Za-z0-9_.]*)\s*=\s*(\S.*?)\s*\Z")


@dataclass
class Case:
	struct: str
	name: str
	data: bytes
	expectations: list[tuple[str, str]] = field(default_factory=list)
	line: int = 0


def parse_vectors(source: Source) -> list[Case]:
	"""Read a vector file, reporting problems the way the compiler does."""
	cases: list[Case] = []

	for number, raw in enumerate(source.text.splitlines(), start=1):
		line = raw.split("//")[0].split("#")[0].rstrip()
		if not line.strip():
			continue

		if line[0].isspace():
			if not cases:
				raise _error(source, number, raw,
				             "expectation before any vector",
				             "an indented line belongs to the case above it")
			cases[-1].expectations.append(_expectation(source, number, raw))
			continue

		cases.append(_case(source, number, line))

	return cases


def _case(source: Source, number: int, line: str) -> Case:
	parts = line.split()
	if len(parts) < 3:
		raise _error(source, number, line, "malformed vector",
		             "expected `<struct> <case-name> <hex bytes>`")

	struct, name = parts[0], parts[1]
	digits = "".join(parts[2:])

	if len(digits) % 2 != 0:
		raise _error(source, number, line, "hex vector has an odd number of digits",
		             "every byte needs two digits")

	try:
		data = bytes.fromhex(digits)
	except ValueError as exc:
		raise _error(source, number, line, f"malformed hex: {exc}",
		             "expected pairs of hex digits, optionally spaced") from exc

	return Case(struct=struct, name=name, data=data, line=number)


def _expectation(source: Source, number: int, raw: str) -> tuple[str, str]:
	match = EXPECTATION.match(raw)
	if match is None:
		raise _error(source, number, raw, "malformed expectation",
		             "expected `field = value`")
	return match.group(1), match.group(2)


def _error(source: Source, number: int, line: str, message: str, label: str):  # type: ignore[no-untyped-def]
	starts = source.line_starts()
	begin  = starts[number - 1] if number <= len(starts) else 0
	return error(message, Span(source, begin, begin + len(line)), label=label)


def generate(schema: ast.Schema, resolved: ResolvedSchema, cases: list[Case],
		basename: str, prefix: str = "situ") -> str:
	for case in cases:
		_check(resolved, case)

	lines = [
		f"/* Generated by situc from {basename}.situ and its vectors -- do not edit.",
		" *",
		" * A capability map catches a change to what the compiler believes. These",
		" * catch a change to what it emits, which is a different failure.",
		" */",
		"",
		"#include <setjmp.h>",
		"#include <stdarg.h>",
		"#include <stddef.h>",
		"#include <stdint.h>",
		"#include <string.h>",
		"",
		"#include <cmocka.h>",
		"",
		f'#include "{basename}.h"',
		"",
	]

	for case in cases:
		lines.extend(_case_body(resolved, case, prefix))

	lines.extend(_main(cases))
	return "\n".join(lines) + "\n"


def _check(resolved: ResolvedSchema, case: Case) -> None:
	struct = resolved.find_struct(case.struct)
	if struct is None:
		raise ValueError(f"vector `{case.name}` names unknown struct `{case.struct}`")

	expected = struct.layout.size_bytes
	if not struct.layout.is_byte_sized:
		raise ValueError(f"`{case.struct}` is not a whole number of bytes")

	if len(case.data) != expected:
		raise ValueError(
			f"vector `{case.name}` is {len(case.data)} bytes, but "
			f"`{case.struct}` is {expected}")

	for path, value in case.expectations:
		if resolved.find(f"{case.struct}.{path}") is None:
			raise ValueError(
				f"vector `{case.name}` names unknown field `{case.struct}.{path}`")

		count = _byte_run(resolved, case.struct, path)
		if count is None:
			continue

		# A byte run compares as bytes, so a value that is not bytes, or is
		# the wrong number of them, is caught here rather than as C that does
		# not compile or -- worse -- compiles and compares a prefix.
		try:
			data = _hex(value)
		except ValueError as exc:
			raise ValueError(
				f"vector `{case.name}`: `{path}` is {count} bytes, so its "
				f"expectation is bytes and `{value}` is not ({exc})") from exc

		if len(data) != count:
			raise ValueError(
				f"vector `{case.name}`: `{path}` is {count} bytes and its "
				f"expectation is {len(data)}")


def _case_body(resolved: ResolvedSchema, case: Case, prefix: str) -> list[str]:
	struct = resolved.find_struct(case.struct)
	assert struct is not None

	size  = macro(prefix, case.struct, "SIZE_FIXED")
	bytes_ = ", ".join(f"0x{byte:02X}" for byte in case.data)

	lines = [
		f"/* {case.struct} / {case.name} */",
		f"static const uint8_t vector_{case.name}[{size}] = {{",
		f"\t{bytes_},",
		"};",
		"",
		f"static void test_{case.name}(void **state)",
		"{",
		f"\tuint8_t     buf[{size}];",
		"\tsitu_msg_t  msg;",
		"\tsitu_view_t view;",
		"",
		"\t(void)state;",
		f"\tmemcpy(buf, vector_{case.name}, sizeof(buf));",
		f"\tsitu_msg_init(&msg, buf, {size});",
		f"\tassert_int_equal({ident(prefix, case.struct, 'view')}(&msg, 0, &view),"
		" SITU_OK);",
		f"\tassert_int_equal({ident(prefix, case.struct, 'validate')}(view), SITU_OK);",
		"",
	]

	for path, value in case.expectations:
		lines.extend(_expectation_lines(resolved, case, path, value, prefix))

	if case.expectations:
		lines.append("")

	lines.extend(_round_trip(resolved, struct, case, prefix))
	lines.extend(["}", ""])
	return lines


def _byte_run(resolved: ResolvedSchema, struct: str, path: str) -> int | None:
	"""How many bytes a member is, where it is a run of them.

	`None` for anything a getter returns a value for, which is what the
	scalar form of an expectation is written against.
	"""
	found = resolved.find(f"{struct}.{path}")
	if found is None:
		return None
	placement = found.placement
	scalar    = placement.scalar
	if scalar is None or scalar.bits != 8 or placement.array_count is None:
		return None
	return placement.array_count


def _nested_of(resolved: ResolvedSchema, struct: str,
		path: str) -> tuple[str, str, str] | None:
	"""A member of a nested struct, as (member, its type, the inner path).

	`None` where the path names one of this struct's own members. A nested
	struct's fields are reached through its own accessors on a sub-view, so
	`reference.seconds` is not `situ_ntp_packet_reference_seconds_get` -- that
	function does not exist, and writing the expectation produced C that named
	it anyway. NTP is thirty-two of its forty-eight bytes timestamps, so the
	member most worth stating was the one that could not be.
	"""
	if "." not in path:
		return None

	head, rest = path.split(".", 1)
	found = resolved.find(f"{struct}.{head}")
	if found is None or found.placement.scalar is not None:
		return None
	inner = found.placement.type_name or ""
	if resolved.find_struct(inner) is None:
		return None
	return head, inner, rest


def _expectation_lines(resolved: ResolvedSchema, case: Case, path: str,
		value: str, prefix: str, held: str = "view") -> list[str]:
	"""One expectation, in the form the field it names admits.

	A scalar compares as a number; a byte run compares as bytes. The second
	was not expressible at all, so a format that is mostly addresses -- ARP is
	twenty of its twenty-eight bytes -- could state almost nothing about
	itself, and the one marker in `examples/bmp` had to be checked by hand
	beside the generated suite (26.35).
	"""
	nested = _nested_of(resolved, case.struct, path)
	if nested is not None:
		member, inner, rest = nested
		return [
			"\t{",
			"\t\tsitu_view_t sub;",
			"",
			f"\t\tassert_int_equal({ident(prefix, case.struct, member, 'view')}"
			f"({held}, &sub), SITU_OK);",
			*[f"\t{line}" for line in
			  _expectation_lines(resolved, Case(inner, case.name, b""),
			                     rest, value, prefix, "sub")],
			"\t}",
		]

	local = c_name(path)
	count = _byte_run(resolved, case.struct, path)

	if count is None:
		return [f"\tassert_int_equal({ident(prefix, case.struct, local, 'get')}"
		        f"({held}), {value});"]

	data = _hex(value)
	return [
		"\t{",
		f"\t\tstatic const uint8_t want[] = {{"
		f" {', '.join(f'0x{byte:02X}' for byte in data)} }};",
		"",
		f"\t\tassert_memory_equal({ident(prefix, case.struct, local, 'ptr')}"
		f"({held}), want, sizeof(want));",
		"\t}",
	]


def _hex(value: str) -> bytes:
	"""The bytes of an expectation, spaced or colon-separated or neither."""
	digits = value.replace(":", "").replace("-", "").replace(" ", "")
	if digits.lower().startswith("0x"):
		digits = digits[2:]
	return bytes.fromhex(digits)


def _round_trip(resolved: ResolvedSchema, struct: ResolvedStruct, case: Case,
		prefix: str) -> list[str]:
	"""Read every settable field, write it back, require the bytes unchanged.

	Reserved regions are excluded: they carry no information and no accessor
	restores them, which is the whole point of them being reserved.
	"""
	writes = []
	for entry in struct.entries:
		placement = entry.placement
		if placement.kind != "field" or placement.scalar is None:
			continue
		if placement.array_count is not None:
			continue
		if "." in placement.path[len(struct.name) + 1 :]:
			continue

		local  = c_name(placement.path[len(struct.name) + 1 :])
		getter = ident(prefix, struct.name, local, "get")
		setter = ident(prefix, struct.name, local, "set")
		writes.append(f"\t{setter}(view, {getter}(view));")

	if not writes:
		return ["\t/* No settable scalar fields to round-trip. */"]

	return [
		"\t/* Every value written back through its own setter must reproduce the",
		"\t * bytes it came from. This is what catches a layout change. */",
		*writes,
		f"\tassert_memory_equal(buf, vector_{case.name}, sizeof(buf));",
	]


def _main(cases: list[Case]) -> list[str]:
	lines = ["int main(void)", "{", "\tconst struct CMUnitTest tests[] = {"]
	for case in cases:
		lines.append(f"\t\tcmocka_unit_test(test_{case.name}),")
	lines.extend([
		"\t};",
		"",
		"\treturn cmocka_run_group_tests(tests, NULL, NULL);",
		"}",
	])
	return lines
