"""Matching a reply to its request in C++ (26.97).

The C table's design, with the parameters typed: `record` takes the request's
own class rather than a bare view, so the two halves of an exchange cannot be
passed the wrong way round. C cannot do that -- every view there is a
`situ_view_t` -- and it is the same trade the C++ predicate already makes.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.c.names import c_name
from situc.codegen.cpp.names import class_name
from situc.relation import Read, Refused, Side, key_sides
from situc.resolve import ResolvedSchema

__all__ = ["generate", "refusals"]


def refusals(schema: ast.Schema,
		resolved: ResolvedSchema) -> list[tuple[str, str]]:
	found = []
	for relation in schema.relations():
		try:
			key_sides(relation, resolved)
		except Refused as why:
			found.append((relation.name, str(why)))
	return found


def _key(sides: Side, view: str, resolved: ResolvedSchema) -> list[str]:
	lines = ["\t\tstd::uint64_t key = 0u;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, Read):
				lines.append(f"\t\tkey = (key << {width}u) | "
				             f"static_cast<std::uint64_t>("
				             f"{source}.{c_name(step.member)}());"
				             f"\t/* {step.path} */")
			else:
				held  = class_name(resolved.structs[step.into])
				local = f"held_{c_name(step.member)}"
				lines += [
					f"\t\t::situ::{held} {local};",
					f"\t\tif ({source}.{c_name(step.member)}({local}) != "
					"::situ::rt::err::ok) {",
					"\t\t\treturn ::situ::rt::err::bounds;",
					"\t\t}",
				]
				source = local
	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	ready = []
	for relation in schema.relations():
		try:
			ready.append((relation, key_sides(relation, resolved)))
		except Refused:
			continue
	if not ready:
		return {}

	guard = f"SITU_{c_name(basename).upper()}_CONVERSE_HPP"
	lines = [
		f"/* Generated by situc from {basename}.situ -- do not edit.",
		" *",
		" * Conversations: a pending table per relation. The schema states",
		" * the pairing and this holds the set. A separate header -- a rung",
		" * adds files rather than changing them (decision 0032).",
		" */",
		"",
		f"#ifndef {guard}",
		f"#define {guard}",
		"",
		"#include <cstdint>",
		"",
		f"#include \"{basename}.hpp\"",
		"",
		"namespace situ {",
		"",
	]

	for relation, (request, response) in ready:
		name  = f"{c_name(relation.name)}_table"
		first, second = relation.params
		req   = class_name(resolved.structs[first.type_name])
		resp  = class_name(resolved.structs[second.type_name])
		lines += [
			f"/** Pending requests for `{relation.name}`.",
			" *",
			" * The slots are yours and so is their number: a full table",
			" * answers `err::bounds` rather than evicting an exchange you",
			" * still wanted. Nothing is allocated.",
			" *",
			" * The parameters are typed, so the two halves of an exchange",
			" * cannot be passed the wrong way round.",
			" */",
			f"class {name} {{",
			"public:",
			"\tstruct slot {",
			"\t\tstd::uint64_t key;",
			"\t\tstd::uint32_t id;",
			"\t\tbool          live;",
			"\t};",
			"",
			f"\t{name}(slot *slots, std::uint32_t cap) noexcept",
			"\t\t: slots_(slots), cap_(cap)",
			"\t{",
			"\t\tfor (std::uint32_t i = 0u; i < cap_; i++) {",
			"\t\t\tslots_[i].live = false;",
			"\t\t}",
			"\t}",
			"",
			f"\t[[nodiscard]] ::situ::rt::err record(const ::situ::{req} "
			f"&{first.name},",
			"\t                                     std::uint32_t id) noexcept",
			"\t{",
			*_key(request, first.name, resolved),
			"",
			"\t\tfor (std::uint32_t i = 0u; i < cap_; i++) {",
			"\t\t\tif (!slots_[i].live) {",
			"\t\t\t\tslots_[i] = slot{key, id, true};",
			"\t\t\t\treturn ::situ::rt::err::ok;",
			"\t\t\t}",
			"\t\t}",
			"\t\treturn ::situ::rt::err::bounds;",
			"\t}",
			"",
			f"\t[[nodiscard]] ::situ::rt::err take(const ::situ::{resp} "
			f"&{second.name},",
			"\t                                   std::uint32_t &id) noexcept",
			"\t{",
			*_key(response, second.name, resolved),
			"",
			"\t\tfor (std::uint32_t i = 0u; i < cap_; i++) {",
			"\t\t\tif (slots_[i].live && slots_[i].key == key) {",
			"\t\t\t\tid = slots_[i].id;",
			"\t\t\t\tslots_[i].live = false;",
			"\t\t\t\treturn ::situ::rt::err::ok;",
			"\t\t\t}",
			"\t\t}",
			"\t\treturn ::situ::rt::err::constraint;",
			"\t}",
			"",
			"private:",
			"\tslot          *slots_;",
			"\tstd::uint32_t  cap_;",
			"};",
			"",
		]

	lines += ["}  /* namespace situ */", "", f"#endif /* {guard} */"]
	return {f"{basename}_converse.hpp": "\n".join(lines) + "\n"}
