"""Retransmission in C++ (26.98).

I/O is an abstract interface rather than a struct of function pointers: the
caller implements `io` and passes a reference. That is C's vtable said in the
language that has one, and it keeps the same property -- the shipped path and
the tested path differ in what implements this and in nothing else.

Otherwise the C driver's shape, with the parameters typed so the two halves
of an exchange cannot be passed the wrong way round.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.c.names import c_name
from situc.codegen.cpp.names import class_name
from situc.relation import Read, KeyLayout, ReadBytes, Refused, Side, SubView, key_layout
from situc.resolve import ResolvedSchema

__all__ = ["generate"]


def _policy(relation: ast.Relation) -> tuple[int, int] | None:
	found: dict[str, int] = {}
	for attr in relation.attrs:
		value = getattr(attr.value, "value", None)
		if attr.name in ("timeout_ms", "retries") and isinstance(value, int):
			found[attr.name] = value
	return (found["timeout_ms"], found["retries"]) if len(found) == 2 else None


def _key(sides: Side, view: str, resolved: ResolvedSchema) -> list[str]:
	lines = ["\t\tstd::uint64_t key = 0u;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, Read):
				lines.append(f"\t\tkey = (key << {width}u) | "
				             f"static_cast<std::uint64_t>("
				             f"{source}.{c_name(step.member)}());")
			elif isinstance(step, SubView):
				held  = class_name(resolved.structs[step.into])
				local = f"held_{c_name(step.member)}"
				lines += [
					f"\t\t::situ::{held} {local};",
					f"\t\tif ({source}.{c_name(step.member)}({local}) != "
					"::situ::rt::err::ok) {",
					"\t\t\treturn ::situ::rt::err::bounds;",
					"\t\t}",
				]
				source = local
	return lines


def _key_bytes(sides: Side, view: str, resolved: ResolvedSchema,
		total: int) -> list[str]:
	"""The exact-bytes key (0042); see the converse twin for the layout."""
	lines = [f"\t\tstd::uint8_t key[{total}u];",
	         "\t\tstd::uint32_t at = 0u;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, ReadBytes):
				count = width // 8
				lines += [
					f"\t\tconst ::situ::rt::const_bytes b_{step.target} = "
					f"{source}.{c_name(step.member)}();",
					f"\t\tfor (std::uint32_t b = 0u; b < {count}u; b++) {{",
					f"\t\t\tkey[at + b] = b_{step.target}[b];",
					"\t\t}",
					f"\t\tat += {count}u;",
				]
			elif isinstance(step, Read):
				count = (width + 7) // 8
				lines += [
					f"\t\tconst std::uint64_t v_{step.target} = "
					f"static_cast<std::uint64_t>("
					f"{source}.{c_name(step.member)}());",
					f"\t\tfor (std::uint32_t b = 0u; b < {count}u; b++) {{",
					f"\t\t\tkey[at + b] = static_cast<std::uint8_t>("
					f"v_{step.target} >> (8u * ({count}u - 1u - b)));",
					"\t\t}",
					f"\t\tat += {count}u;",
				]
			elif isinstance(step, SubView):
				held  = class_name(resolved.structs[step.into])
				local = f"held_{c_name(step.member)}"
				lines += [
					f"\t\t::situ::{held} {local};",
					f"\t\tif ({source}.{c_name(step.member)}({local}) != "
					"::situ::rt::err::ok) {",
					"\t\t\treturn ::situ::rt::err::bounds;",
					"\t\t}",
				]
				source = local
	lines.append("\t\t(void)at;")
	return lines


def _key_equal(total: int) -> str:
	return (f"[&]() {{ for (std::uint32_t b = 0u; b < {total}u; b++) "
	        "{ if (slots_[i].key[b] != key[b]) return false; } "
	        "return true; }()")


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	ready = []
	for relation in schema.relations():
		policy = _policy(relation)
		if policy is None:
			continue
		try:
			ready.append((relation, policy, key_layout(relation, resolved)))
		except Refused:
			continue
	if not ready:
		return {}

	guard = f"SITU_{c_name(basename).upper()}_DRIVE_HPP"
	lines = [
		f"/* Generated by situc from {basename}.situ -- do not edit.",
		" *",
		" * Retransmission and timeout. Owns I/O through an interface you",
		" * implement and never owns the clock. Nothing allocates.",
		" */",
		"",
		f"#ifndef {guard}",
		f"#define {guard}",
		"",
		"#include <cstdint>",
		"",
		f"#include \"{basename}.hpp\"",
		"",
		"namespace situ {",
		"",
		"/** Where the bytes go. Yours, so a test substitutes a transcript",
		" * and never opens a socket. */",
		"class io {",
		"public:",
		"\tvirtual ~io() = default;",
		"\t[[nodiscard]] virtual ::situ::rt::err submit(",
		"\t\tconst std::uint8_t *data, std::uint32_t len) noexcept = 0;",
		"};",
		"",
	]

	for relation, (timeout, retries), layout in ready:
		request, response = layout.request, layout.response
		name = f"{c_name(relation.name)}_driver"
		first, second = relation.params
		req  = class_name(resolved.structs[first.type_name])
		resp = class_name(resolved.structs[second.type_name])
		lines += [
			f"#define SITU_{c_name(relation.name).upper()}_TIMEOUT_MS {timeout}u",
			f"#define SITU_{c_name(relation.name).upper()}_RETRIES {retries}u",
			"",
			f"/** Retransmission for `{relation.name}`. */",
			f"class {name} {{",
			"public:",
			"\tstruct slot {",
			"\t\tconst std::uint8_t *bytes;",
			"\t\tstd::uint32_t len;",
			("\t\tstd::uint64_t key;" if layout.packed
			 else f"\t\tstd::uint8_t  key[{layout.total_bytes}u];"),
			"\t\tstd::uint32_t id;",
			"\t\tstd::uint32_t deadline_ms;",
			"\t\tstd::uint32_t left;",
			"\t\tbool          live;",
			"\t};",
			"",
			f"\t{name}(slot *slots, std::uint32_t cap, ::situ::io &sink,",
			"\t       std::uint32_t timeout_ms, std::uint32_t retries) noexcept",
			"\t\t: slots_(slots), cap_(cap), io_(sink),",
			"\t\t  timeout_ms_(timeout_ms), retries_(retries)",
			"\t{",
			"\t\tfor (std::uint32_t i = 0u; i < cap_; i++) {",
			"\t\t\tslots_[i].live = false;",
			"\t\t}",
			"\t}",
			"",
			f"\t[[nodiscard]] ::situ::rt::err send(const ::situ::{req} "
			f"&{first.name},",
			"\t                                   const std::uint8_t *bytes,",
			"\t                                   std::uint32_t len,",
			"\t                                   std::uint32_t id,",
			"\t                                   std::uint32_t now_ms) noexcept",
			"\t{",
			*(_key(request, first.name, resolved) if layout.packed else
			  _key_bytes(request, first.name, resolved, layout.total_bytes)),
			"",
			"\t\tfor (std::uint32_t i = 0u; i < cap_; i++) {",
			"\t\t\tif (!slots_[i].live) {",
			*(["\t\t\t\tslots_[i] = slot{bytes, len, key, id,",
			   "\t\t\t\t                 now_ms + timeout_ms_, retries_, true};"]
			  if layout.packed else [
			  "\t\t\t\tslots_[i].bytes = bytes;",
			  "\t\t\t\tslots_[i].len   = len;",
			  f"\t\t\t\tfor (std::uint32_t b = 0u; b < {layout.total_bytes}u; b++) {{",
			  "\t\t\t\t\tslots_[i].key[b] = key[b];",
			  "\t\t\t\t}",
			  "\t\t\t\tslots_[i].id          = id;",
			  "\t\t\t\tslots_[i].deadline_ms = now_ms + timeout_ms_;",
			  "\t\t\t\tslots_[i].left        = retries_;",
			  "\t\t\t\tslots_[i].live        = true;"]),
			"\t\t\t\treturn io_.submit(bytes, len);",
			"\t\t\t}",
			"\t\t}",
			"\t\treturn ::situ::rt::err::bounds;",
			"\t}",
			"",
			f"\t[[nodiscard]] ::situ::rt::err on_message(const ::situ::{resp} "
			f"&{second.name},",
			"\t                                         std::uint32_t &id) noexcept",
			"\t{",
			*(_key(response, second.name, resolved) if layout.packed else
			  _key_bytes(response, second.name, resolved, layout.total_bytes)),
			"",
			"\t\tfor (std::uint32_t i = 0u; i < cap_; i++) {",
			("\t\t\tif (slots_[i].live && slots_[i].key == key) {"
			 if layout.packed else
			 f"\t\t\tif (slots_[i].live && {_key_equal(layout.total_bytes)}) {{"),
			"\t\t\t\tid = slots_[i].id;",
			"\t\t\t\tslots_[i].live = false;",
			"\t\t\t\treturn ::situ::rt::err::ok;",
			"\t\t\t}",
			"\t\t}",
			"\t\treturn ::situ::rt::err::constraint;",
			"\t}",
			"",
			"\t/** Retransmit what is due; `next_ms` is when to come back.",
			"\t * `err::truncated` where nothing is outstanding. */",
			"\t[[nodiscard]] ::situ::rt::err step(std::uint32_t now_ms,",
			"\t                                   std::uint32_t &next_ms,",
			"\t                                   std::uint32_t &expired) noexcept",
			"\t{",
			"\t\tstd::uint32_t soonest = 0u;",
			"\t\tbool any = false;",
			"",
			"\t\texpired = 0u;",
			"\t\tfor (std::uint32_t i = 0u; i < cap_; i++) {",
			"\t\t\tif (!slots_[i].live) {",
			"\t\t\t\tcontinue;",
			"\t\t\t}",
			"\t\t\tif (now_ms >= slots_[i].deadline_ms) {",
			"\t\t\t\tif (slots_[i].left == 0u) {",
			"\t\t\t\t\tslots_[i].live = false;",
			"\t\t\t\t\texpired += 1u;",
			"\t\t\t\t\tcontinue;",
			"\t\t\t\t}",
			"\t\t\t\tslots_[i].left -= 1u;",
			"\t\t\t\tslots_[i].deadline_ms = now_ms + timeout_ms_;",
			"\t\t\t\t(void)io_.submit(slots_[i].bytes, slots_[i].len);",
			"\t\t\t}",
			"\t\t\tif (!any || slots_[i].deadline_ms < soonest) {",
			"\t\t\t\tsoonest = slots_[i].deadline_ms;",
			"\t\t\t\tany = true;",
			"\t\t\t}",
			"\t\t}",
			"",
			"\t\tif (!any) {",
			"\t\t\treturn ::situ::rt::err::truncated;",
			"\t\t}",
			"\t\tnext_ms = soonest;",
			"\t\treturn ::situ::rt::err::ok;",
			"\t}",
			"",
			"private:",
			"\tslot          *slots_;",
			"\tstd::uint32_t  cap_;",
			"\t::situ::io    &io_;",
			"\tstd::uint32_t  timeout_ms_;",
			"\tstd::uint32_t  retries_;",
			"};",
			"",
		]

	lines += ["}  /* namespace situ */", "", f"#endif /* {guard} */"]
	return {f"{basename}_drive.hpp": "\n".join(lines) + "\n"}
