"""The C++ backend (section 26.16).

C++ is the second backend because it is the largest population after C, and
because parts of the capability lattice that C can only document it can
enforce. Three, specifically:

  * a byte array is a `situ::span`, so its length travels with its pointer
  * an error is `[[nodiscard]]`, so ignoring one is a diagnostic
  * a sealed region's view has no public constructor, so it cannot be made
    except by the function that verifies the tag -- in C the struct is there
    for anybody determined enough to fill in

What it deliberately does not do is reinvent anything. The layout, the
propagation table and the runtime arithmetic are the same ones the C backend
uses; this emits a different surface over identical bytes. A view is a value
for the same reason it is in C -- it owns nothing, so a destructor would be a
lie about what it is -- and errors are return codes rather than exceptions
because the target may have neither unwinding nor a heap.

Header-only. Every accessor is a constant offset from a base and inlines to
nothing, so there is no translation unit worth having; `validate` is the one
function with a body and it is `inline` too.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c.names import c_name
from situc.diagnostics import Diagnostic
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.invariant import derived as derived_by
from situc.invariant import expression as invariant_expression
from situc.traverse import (
	refuse_delimited,
	Check, Member, classify, classify_check, local_name, obligation,
	obligations, own_entries, own_members,
)
from situc.types import ScalarKind, ScalarType
from situc.unparse import expr_to_source as unparse_expr

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Generated:
	"""What a schema compiles to. One file: C++ needs no second one here."""

	header: str
	basename: str
	warnings: list[Diagnostic] = field(default_factory=list)

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.hpp": self.header}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		namespace: str = "situ") -> Generated:
	refuse_delimited(schema, resolved, "C++")
	return Generated(
		header   = Emitter(schema, resolved, basename, namespace).header(),
		basename = basename,
	)


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str, namespace: str) -> None:
		self.schema    = schema
		self.resolved  = resolved
		self.basename  = basename
		self.namespace = namespace
		self.enums     = {decl.name: decl for decl in schema.enums()}
		self.structs   = set(resolved.structs)

	# -- the file ------------------------------------------------------

	def header(self) -> str:
		guard = f"SITU_{c_name(self.basename).upper()}_HPP"
		lines = [
			f"/* Generated by situc from {self.basename}.situ -- do not edit.",
			" *",
			" * The operations below are exactly the ones this schema's capability",
			" * vectors support. Where one is missing, a comment says why.",
			" */",
			"",
			f"#ifndef {guard}",
			f"#define {guard}",
			"",
			'#include "situ.hpp"',
			"",
			f"namespace {self.namespace} {{",
		]

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		for name in self._struct_order():
			lines.extend(self._struct(self.resolved.structs[name]))

		lines.extend(["", f"}}  /* namespace {self.namespace} */", "",
		              f"#endif /* {guard} */"])
		return "\n".join(lines) + "\n"

	def _struct_order(self) -> list[str]:
		"""Structs before the structs that contain them.

		A class has to be complete before another names it by value, which C
		sidesteps by handing out offsets rather than types. Declaration order in
		the schema is not required to respect containment, so it is sorted here
		rather than demanded of the author.
		"""
		order: list[str] = []
		seen: set[str]   = set()

		def visit(name: str) -> None:
			if name in seen:
				return
			seen.add(name)
			for entry in own_entries(self.resolved.structs[name]):
				nested = entry.placement.type_name
				if nested in self.structs and nested != name:
					visit(nested)
			order.append(name)

		for name in sorted(self.structs):
			visit(name)
		return order

	# -- enums ---------------------------------------------------------

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		backing = decl.backing.scalar
		assert backing is not None
		values = self.resolved.layout.env.enums[decl.name]

		lines = [
			"",
			f"/* enum {decl.name} : {decl.backing.name}"
			f" -- unknown values are {decl.effective_default.value} */",
			f"enum class {c_name(decl.name)} : {self._ctype(backing)} {{",
		]
		lines.extend(f"\t{c_name(member.name)} = {values[member.name]},"
		             for member in decl.members)
		lines.append("};")

		# Section 8.7 makes `default = error` the default and says unknown
		# values are rejected on parse. Every backend emitted that as a comment
		# and validated nothing until now.
		name = c_name(decl.name)
		lines.extend([
			"",
			f"/* Whether a value names a member of {decl.name} (section 8.7). */",
			f"constexpr bool is_known({name} value) noexcept",
			"{",
			"\tswitch (value) {",
			*[f"\tcase {name}::{c_name(member.name)}:" for member in decl.members],
			"\t\treturn true;",
			"\tdefault:",
			"\t\treturn false;",
			"\t}",
			"}",
		])
		return lines

	# -- structs -------------------------------------------------------

	def _struct(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		name   = c_name(struct.name)

		if layout.register is not None:
			return self._register(struct)

		lines = ["", *self._struct_comment(struct),
		         f"class {name} : public ::situ::rt::view {{", "public:"]
		lines.extend(self._acquire(struct))
		lines.extend([
			"",
			f"\tconstexpr {name}() noexcept = default;",
			f"\texplicit constexpr {name}(situ_view_t raw) noexcept"
			f" : ::situ::rt::view(raw) {{}}",
		])
		lines.extend(self._dirty_constants(struct))

		for entry in own_entries(struct):
			lines.extend(self._member(struct, entry))

		lines.extend(self._invariants(struct))
		lines.extend(self._validate(struct))
		lines.extend(self._gates(struct))
		lines.append("};")
		return lines

	def _register(self, struct: ResolvedStruct) -> list[str]:
		"""A memory-mapped register (section 15).

		The whole-word read and the field composition are separate types,
		because they are separate things: a `word` is a copy of the bits and a
		register is a place on a bus. That split is what section 15's headline
		asks for -- where a field cannot be written alone, the remedy is to
		compose the whole word and write it once, and here that remedy is the
		only shape the API has.

		`with_x()` returns a new word rather than mutating, so composing reads
		as one expression and the write is visibly one transaction:

		    r.write(r.read().with_enable(1).with_mode(3));
		"""
		info = struct.layout.register
		assert info is not None

		name  = c_name(struct.name)
		word  = self._ctype_for_bits(info.width)
		lines = [
			"",
			f"/* register {struct.name}"
			+ (f" at {info.address:#x}" if info.address is not None else "")
			+ f": {info.width} bits, {info.access_width}-bit bus access"
			+ (", volatile" if info.volatile else "")
			+ (", no read-modify-write" if info.no_rmw else "") + ". */",
			f"class {name} {{",
			"public:",
		]
		if info.address is not None:
			lines.append(f"\tstatic constexpr std::uint32_t address = {info.address:#x};")
		lines.extend([
			f"\tstatic constexpr std::uint32_t width = {info.width};",
			"",
			"\t/* A word: a copy of the bits, not the register. Composing one",
			"\t * costs no bus transaction; writing it costs exactly one. */",
			"\tclass word {",
			"\tpublic:",
			f"\t\tconstexpr explicit word({word} raw) noexcept : raw_(raw) {{}}",
			f"\t\tconstexpr {word} raw() const noexcept {{ return raw_; }}",
		])

		for entry in own_entries(struct):
			lines.extend(self._register_field(entry, word))

		lines.extend([
			"",
			"\tprivate:",
			f"\t\t{word} raw_;",
			"\t};",
			"",
			f"\texplicit constexpr {name}(volatile std::uint8_t *block) noexcept",
			"\t\t: block_(block) {}",
			"",
		])
		lines.extend(self._register_access(struct, info, word))
		lines.extend([
			"",
			"private:",
			f"\tvolatile {word} *at() const noexcept",
			"\t{",
			f"\t\treturn reinterpret_cast<volatile {word} *>(block_ + "
			f"{info.address or 0:#x});",
			"\t}",
			"",
			"\tvolatile std::uint8_t *block_;",
			"};",
		])
		return lines

	def _register_access(self, struct: ResolvedStruct, info: object,
			word: str) -> list[str]:
		"""Read, write, and the operations that are neither."""
		lines = [
			"\t[[nodiscard]] word read() const noexcept",
			"\t{",
			"\t\treturn word(*at());",
			"\t}",
			"",
			"\tvoid write(word value) const noexcept",
			"\t{",
			"\t\t*at() = value.raw();",
			"\t}",
		]

		for entry in own_entries(struct):
			placement = entry.placement
			mode      = placement.access_mode
			if placement.kind == "reserved" or placement.scalar is None:
				continue

			name  = c_name(local_name(struct, placement))
			shift = placement.offset_bits or 0
			mask  = (1 << placement.scalar.bits) - 1

			if placement.on_write is not ast.SideEffect.NONE:
				lines.extend([
					"",
					f"\t/* {placement.path} has on_write ="
					f" {placement.on_write.value}: the write is the event, and",
					"\t * the value written is not a value the field then holds. */",
					f"\tvoid trigger_{name}() const noexcept",
					"\t{",
					f"\t\t*at() = static_cast<{word}>({mask:#x}u << {shift}u);",
					"\t}",
				])
			elif mode is ast.AccessMode.W1C:
				lines.extend([
					"",
					f"\t/* {placement.path} is w1c: writing a one clears it, so",
					"\t * this is a clear rather than an assignment. Every other",
					"\t * bit is left zero, which leaves neighbouring w1c fields",
					"\t * alone. */",
					f"\tvoid clear_{name}() const noexcept",
					"\t{",
					f"\t\t*at() = static_cast<{word}>({mask:#x}u << {shift}u);",
					"\t}",
				])
		return lines

	def _register_field(self, entry: Resolved, word: str) -> list[str]:
		"""A field's getter and composer, if its access mode admits them."""
		placement = entry.placement
		scalar    = placement.scalar

		if placement.kind == "reserved":
			return ["",
			        f"\t\t/* {placement.path} is reserved: no accessor, and its",
			        "\t\t * bits are carried through a compose untouched. */"]
		if scalar is None:
			return []

		name  = c_name(placement.path.rsplit(".", 1)[-1])
		mode  = placement.access_mode or ast.AccessMode.RW
		shift = placement.offset_bits or 0
		mask  = (1 << scalar.bits) - 1
		ctype = self._field_ctype(placement)
		lines = ["", f"\t\t/* {placement.path}: {mode.value},"
		         f" bits {shift}..{shift + scalar.bits - 1} */"]

		if mode.readable:
			raw = f"(raw_ >> {shift}u) & {mask:#x}u"
			cast = (f"static_cast<{ctype}>({raw})" if placement.type_name in self.enums
			        else f"static_cast<{ctype}>({raw})")
			lines.extend([
				f"\t\t[[nodiscard]] constexpr {ctype} {name}() const noexcept",
				"\t\t{",
				f"\t\t\treturn {cast};",
				"\t\t}",
			])
		else:
			lines.append(f"\t\t/* No {name}(): the mode is"
			             f" {mode.value}, so a read returns nothing the field holds. */")

		if mode.writable and mode.is_assignment:
			value = ("static_cast<std::uint32_t>(value)"
			         if placement.type_name in self.enums else "value")
			lines.extend([
				f"\t\t[[nodiscard]] constexpr word with_{name}({ctype} value)"
				f" const noexcept",
				"\t\t{",
				f"\t\t\treturn word(static_cast<{word}>(",
				f"\t\t\t\t(raw_ & ~static_cast<{word}>({mask:#x}u << {shift}u))",
				f"\t\t\t\t| ((static_cast<{word}>({value}) & {mask:#x}u)"
				f" << {shift}u)));",
				"\t\t}",
			])
		elif mode.writable:
			lines.append(f"\t\t/* No with_{name}(): `{mode.value}` is not an"
			             f" assignment. See the register's own method. */")
		else:
			lines.append(f"\t\t/* No with_{name}(): the mode is {mode.value}. */")
		return lines

	def _ctype_for_bits(self, bits: int) -> str:
		return f"std::uint{_storage_width(bits)}_t"

	# -- obligations (sections 14.2 and 16.1) ---------------------------

	def _dirty_constants(self, struct: ResolvedStruct) -> list[str]:
		"""One bit per obligation over this struct's bytes.

		Scoped constants rather than the C backend's macros: the numbering is
		shared with C (`traverse.obligations`) but the spelling need not be,
		and a macro named after a member is exactly the sort of thing that
		collides with a member somewhere else in a translation unit.
		"""
		held = obligations(self.schema, struct)
		if not held:
			return []

		lines = ["",
		         "\t/* Dirty bits. A covered write sets one; the message refuses",
		         "\t * to be transmittable until it is cleared -- a tag by being",
		         "\t * recomputed and finalized, a derived field by its recompute. */"]
		lines.extend(
			f"\tstatic constexpr std::uint32_t dirty_{c_name(one.name)}"
			f" = {hex(1 << one.bit)}u;"
			for one in held)
		lines.append(
			f"\tstatic constexpr std::uint32_t dirty_mask = {hex((1 << len(held)) - 1)}u;")
		return lines

	def _invariants(self, struct: ResolvedStruct) -> list[str]:
		"""A derived field, and the one thing allowed to write it.

		The lattice has already refused the plain setter -- `mutate` is
		Immutable -- so without this the schema could state a relationship and
		never satisfy it.

		`recompute_x()` takes the message, as every covered write here does:
		it clears a dirty bit, and the bit lives on the message rather than on
		the view.
		"""
		lines: list[str] = []

		for decl in derived_by(self.schema, struct):
			field = decl.derived.partition(".")[2]
			entry = next((e for e in struct.entries
			              if e.placement.path == f"{struct.name}.{field}"), None)
			if entry is None or entry.placement.scalar is None:
				continue

			name  = c_name(field)
			value = invariant_expression(struct, decl.expr, self)
			if value is None:
				lines.extend([
					"",
					f"\t/* No recompute_{name}(): this backend cannot evaluate",
					f"\t * `{unparse_expr(decl.expr)}` at run time. The refusal to",
					"\t * write the field directly still stands, so the invariant",
					"\t * cannot be broken -- only left unsatisfiable here. */",
				])
				continue

			scalar = entry.placement.scalar
			stored = f"static_cast<{self._ctype(scalar)}>({value})"

			lines.extend([
				"",
				f"\t/* {decl.derived} == {unparse_expr(decl.expr)}",
				"\t *",
				f"\t * Writing anything the right side reads sets dirty_{name},",
				"\t * and the message refuses to be transmittable until this",
				"\t * recomputes (section 16.1). */",
				f"\tvoid recompute_{name}(::situ::rt::message &msg) noexcept",
				"\t{",
				f"\t\t{self._store(scalar, entry.placement, stored)}",
				f"\t\tmsg.clear_dirty(dirty_{name});",
				"\t}",
				"",
				f"\t[[nodiscard]] bool {name}_is_stale("
				"const ::situ::rt::message &msg) const noexcept",
				"\t{",
				f"\t\treturn msg.is_stale(dirty_{name});",
				"\t}",
			])

		return lines

	# -- invariant.Terms, in C++ ----------------------------------------

	def literal(self, value: int) -> str:
		return f"{value}u"

	def binary(self, op: str, left: str, right: str) -> str:
		return f"({left} {op} {right})"

	def offset(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		return (f"{placement.offset_bytes}u" if placement.offset_bits is not None
		        else None)

	def size(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		if placement.is_fixed_size:
			return f"{placement.size_bits // BITS_PER_BYTE}u"
		return self._length_expression(struct, placement)

	def count(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		return self._count_expression(struct, placement)

	def _struct_comment(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		if layout.is_fixed_size:
			return [f"/* struct {struct.name}: {layout.size_bytes} bytes, fixed. */"]

		return [
			f"/* struct {struct.name}: {layout.size_bytes} bytes and up, so its",
			" * extent is the caller's to establish -- a length it knows from the",
			" * frame this arrived in. That is the one bounds check, and",
			" * everything below trusts it. */",
		]

	def _acquire(self, struct: ResolvedStruct) -> list[str]:
		"""The factory. Fixed-size structs know their own extent; the rest are
		told it, because nothing in the bytes says where the frame ends."""
		layout = struct.layout
		name   = c_name(struct.name)

		if layout.is_fixed_size:
			return [
				f"\tstatic constexpr std::uint32_t size_bytes = {layout.size_bytes};",
				"",
				"\t[[nodiscard]] static ::situ::rt::err at(::situ::rt::message &msg,",
				f"\t\t\tstd::uint32_t offset, {name} &out) noexcept",
				"\t{",
				"\t\tsitu_view_t raw;",
				"\t\tconst situ_err_t e = situ_view_at(msg.raw(), offset,"
				" size_bytes, &raw);",
				"",
				"\t\tif (e == SITU_OK) {",
				f"\t\t\tout = {name}(raw);",
				"\t\t}",
				"\t\treturn static_cast<::situ::rt::err>(e);",
				"\t}",
			]

		return [
			f"\tstatic constexpr std::uint32_t size_min = {layout.size_bytes};",
			"",
			"\t[[nodiscard]] static ::situ::rt::err at(::situ::rt::message &msg,",
			f"\t\t\tstd::uint32_t offset, std::uint32_t length,"
			f" {name} &out) noexcept",
			"\t{",
			"\t\tsitu_view_t raw;",
			"\t\tconst situ_err_t e = situ_view_at(msg.raw(), offset,"
			" length, &raw);",
			"",
			"\t\tif (e == SITU_OK) {",
			f"\t\t\tout = {name}(raw);",
			"\t\t}",
			"\t\treturn static_cast<::situ::rt::err>(e);",
			"\t}",
		]

	def _gates(self, struct: ResolvedStruct) -> list[str]:
		"""Sealed regions, as a type that cannot be made without verifying.

		Section 14.3 asks that a sealed interior be unreachable before its tag
		verifies. C gets close: the accessors take a struct nobody but `_open`
		is supposed to fill in, and anybody determined enough can fill it in
		anyway. C++ can close it.

		The gate has no public constructor and no public factory. The only way
		to obtain one is to be handed it, inside a callback that runs only on
		the verified branch -- so there is no expression a caller can write
		that names a gate object outside that branch. Not discouraged: absent.
		"""
		regions = [entry.placement for entry in struct.entries
		           if entry.placement.kind == "sealed"]
		if not regions:
			return []

		lines: list[str] = []
		for region in regions:
			lines.extend(self._gate(struct, region))
		return lines

	def _gate(self, struct: ResolvedStruct, region: Placement) -> list[str]:
		name    = c_name(local_name(struct, region))
		holder  = f"{name}_gate"
		# Scalars only for now. A variable-length member inside a sealed region
		# needs its length read through the gate's own view, which is the next
		# piece rather than this one.
		inside  = [entry for entry in struct.entries
		           if entry.placement.sealed_by == region.name
		           and entry.placement.kind == "field"
		           and entry.placement.scalar is not None
		           and entry.placement.offset_bits is not None
		           and entry.placement.array_count is None
		           and entry.placement.sized_by is None]

		rest    = [entry.placement for entry in struct.entries
		           if entry.placement.sealed_by == region.name
		           and entry.placement.kind == "field"
		           and (entry.placement.array_count is not None
		                or entry.placement.sized_by is not None)]
		secret  = [placement.path for placement in rest
		           if any(attr.name == "secret" for attr in placement.attrs)]
		skipped = [placement.path for placement in rest
		           if placement.path not in secret]

		lines = [
			"",
			f"\t/* {region.path}, sealed by {region.codec or 'a codec'}"
			f" and covered by {', '.join(region.covered_by) or 'a tag'}.",
			"\t *",
			"\t * This type has no public constructor and no public factory. A",
			f"\t * caller reaches the interior through with_{name}() below, which",
			"\t * runs the callback only once the tag has verified -- so there is",
			"\t * no expression that names one of these outside that branch.",
			"\t * Parsing attacker-controlled plaintext before authenticating it",
			"\t * is not discouraged here; it cannot be written. */",
			f"\tclass {holder} {{",
			"\tpublic:",
		]

		for entry in inside:
			lines.extend(self._gated_accessor(entry))

		if not inside:
			lines.append("\t\t/* Nothing in this region has a scalar accessor. */")
		for path in secret:
			lines.extend(["",
			              f"\t\t/* {path} is [secret]: no debug accessor is",
			              "\t\t * generated for it at all (section 14.6). */"])
		for placement in rest:
			if placement.path in secret:
				continue
			lines.extend(self._gated_span(struct, placement))

		lines.extend([
			"",
			"\tprivate:",
			f"\t\tfriend class {c_name(struct.name)};",
			f"\t\texplicit constexpr {holder}(situ_view_t raw) noexcept"
			f" : raw_(raw) {{}}",
			"",
			"\t\tsitu_view_t raw_;",
			"\t};",
			"",
			f"\t/* Runs `fn` over the sealed interior, and only if `verified`.",
			"\t *",
			"\t * The result is whatever the callback needs it to be: it may",
			"\t * capture. What it may not do is outlive the check, because the",
			"\t * gate it is handed cannot be copied out of the namespace it has",
			"\t * no constructor in. */",
			"\ttemplate <typename F>",
			f"\t[[nodiscard]] ::situ::rt::err with_{name}(bool verified,"
			f" F &&fn) const",
			"\t{",
			"\t\tif (!verified) {",
			"\t\t\treturn ::situ::rt::err::tag;",
			"\t\t}",
			"",
			f"\t\tfn({holder}(raw()));",
			"\t\treturn ::situ::rt::err::ok;",
			"\t}",
		])
		return lines

	def _gated_span(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""A byte run inside a sealed region.

		Its length is read through the gate's own view: the field that sizes it
		is plaintext at the same offsets, so the arithmetic is the struct's and
		only the view it is read through differs.
		"""
		scalar = placement.scalar
		if scalar is None or scalar.bits != BITS_PER_BYTE:
			return ["", f"\t\t/* {placement.path}: element type"
			        f" {placement.type_name} is not reachable through the gate. */"]

		name  = c_name(placement.path.rsplit(".", 1)[-1])
		start = self._offset_expression(struct, placement)
		count = (str(placement.array_count) if placement.array_count is not None
		         else self._count_expression(struct, placement))

		if start is None or count is None:
			return ["", f"\t\t/* {placement.path}: this backend cannot resolve"
			        f" its extent. */"]

		# Inside the gate the view is `raw_`, not `base()`.
		start = start.replace("base()", "raw_.base")
		count = count.replace("base()", "raw_.base")

		return [
			"",
			f"\t\t/* {placement.path}: {placement.array_count or placement.sized_by}"
			f" bytes, reached through the gate. */",
			f"\t\t[[nodiscard]] ::situ::rt::bytes {name}() const noexcept",
			"\t\t{",
			f"\t\t\treturn ::situ::rt::bytes(raw_.base + ({start}), {count});",
			"\t\t}",
		]

	def _gated_accessor(self, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		assert scalar is not None

		name  = c_name(placement.path.rsplit(".", 1)[-1])
		ctype = self._field_ctype(placement)

		if any(attr.name == "secret" for attr in placement.attrs):
			return ["",
			        f"\t\t/* {name} is [secret]: no debug accessor is generated"
			        f" for it",
			        "\t\t * at all (section 14.6). */"]

		load = self._raw_load(scalar, placement, f"raw_.base + {placement.offset_bytes}")
		load = load.replace("base()", "raw_.base")
		if placement.type_name in self.enums:
			load = f"static_cast<{ctype}>({load})"

		return [
			"",
			f"\t\t[[nodiscard]] {ctype} {name}() const noexcept",
			"\t\t{",
			f"\t\t\treturn {load};",
			"\t\t}",
		]

	def _offset_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		"""Where a member starts, as a C++ expression.

		The same walk the C backend does: everything before the first
		variable-length member contributes a constant, and each variable one
		contributes its own length, read from the field that drives it. That
		field always has a static offset, because a size expression may only
		name a field declared before it.
		"""
		if placement.offset_bits is not None:
			return str(placement.offset_bits // BITS_PER_BYTE)

		constant = 0
		terms: list[str] = []

		for other in own_members(struct):
			if other.path == placement.path:
				break
			if other.is_fixed_size:
				constant += other.size_bits // BITS_PER_BYTE
				continue
			length = self._length_expression(struct, other)
			if length is None:
				return None
			terms.append(length)

		return " + ".join([str(constant), *terms])

	def _length_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		"""How many bytes a variable-length member occupies, at run time."""
		if placement.sized_by == "remaining":
			start = self._offset_expression(struct, placement)
			return None if start is None else f"(limit() - ({start}))"
		if placement.sized_by is None:
			return None

		count = self._count_expression(struct, placement)
		if count is None:
			return None

		element = self._element_bytes(placement)
		if element is None:
			return None
		return f"({count})" if element == 1 else f"({count}) * {element}"

	def _count_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		"""The value of the field that sizes a member, read at run time."""
		driver = self.resolved.find(f"{struct.name}.{placement.sized_by}")
		if driver is None or driver.placement.scalar is None:
			return None
		if driver.placement.offset_bits is None:
			return None

		return (f"static_cast<std::uint32_t>("
		        f"{self._raw_load(driver.placement.scalar, driver.placement, 'base() + '
		        f'{driver.placement.offset_bytes}')})")

	def _element_bytes(self, placement: Placement) -> int | None:
		nested = self.resolved.structs.get(placement.type_name or "")
		if nested is not None:
			return (int(nested.layout.size_bytes)
			        if nested.layout.is_fixed_size else None)
		if placement.scalar is not None and placement.scalar.bits % BITS_PER_BYTE == 0:
			return max(placement.scalar.bits // BITS_PER_BYTE, 1)
		return None

	def _variable(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		"""A member whose extent the data decides: a counted array, or the rest."""
		name   = c_name(local_name(struct, placement))
		start  = self._offset_expression(struct, placement)
		length = self._length_expression(struct, placement)

		if start is None or length is None:
			return ["", f"\t/* {placement.path}: sized by"
			        f" `{placement.sized_by}`, which this backend cannot resolve"
			        f" yet. */"]

		nested = self.resolved.structs.get(placement.type_name or "")
		lines  = ["",
		          f"\t/* {placement.path}: offset and extent both from the data. */",
		          f"\t[[nodiscard]] std::uint32_t {name}_offset() const noexcept",
		          "\t{",
		          f"\t\treturn {start};",
		          "\t}"]

		if nested is None:
			lines.extend([
				f"\t[[nodiscard]] ::situ::rt::bytes {name}() const noexcept",
				"\t{",
				f"\t\treturn ::situ::rt::bytes(base() + {name}_offset(), {length});",
				"\t}",
			])
			return lines

		count = self._count_expression(struct, placement)
		inner = f"::{self.namespace}::{c_name(placement.type_name or '')}"
		lines.extend([
			f"\t[[nodiscard]] std::uint32_t {name}_count() const noexcept",
			"\t{",
			f"\t\treturn {count};",
			"\t}",
			"",
			f"\t/* Element `index`, or an error past the end. The count is",
			"\t * checked as well as the extent: bytes after the array are",
			"\t * inside the view and are not elements. */",
			f"\t[[nodiscard]] ::situ::rt::err {name}_at(std::uint32_t index,",
			f"\t\t\t{inner} &out) const noexcept",
			"\t{",
			f"\t\tif (index >= {name}_count()) {{",
			"\t\t\treturn ::situ::rt::err::bounds;",
			"\t\t}",
			"",
			"\t\tsitu_view_t raw;",
			f"\t\tconst situ_err_t e = situ_view_sub(this->raw(),",
			f"\t\t\t{name}_offset() + index * {inner}::size_bytes,",
			f"\t\t\t{inner}::size_bytes, &raw);",
			"",
			"\t\tif (e == SITU_OK) {",
			f"\t\t\tout = {inner}(raw);",
			"\t\t}",
			"\t\treturn static_cast<::situ::rt::err>(e);",
			"\t}",
		])
		return lines

	def _member(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement

		# The order is `traverse.classify`'s rather than this file's: three
		# backends shipped the same two mistakes when each kept its own.
		kind = classify(struct, placement, self.structs)

		if kind is Member.RESERVED:
			return ["",
			        f"\t/* {placement.path} is reserved: no accessor, and"
			        f" `validate` holds it to",
			        "\t * the pattern the schema declares. */"]
		if kind is Member.VARIABLE:
			return self._variable(struct, placement)
		if kind is Member.NESTED:
			return self._nested(struct, placement)
		if kind is Member.ARRAY:
			return self._array(struct, placement)
		if kind is Member.SCALAR:
			return self._scalar(struct, entry)
		if kind is Member.NOTHING:
			return []

		return ["", f"\t/* {placement.path}: not in the static subset yet. */"]

	def _scalar(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		assert scalar is not None

		# A member after a variable-length one is placed at run time. Its own
		# arithmetic is the struct's -- the same walk `_offset_expression`
		# does -- so the only difference from a static field is where `base()`
		# is measured from.
		offset = (None if placement.offset_bits is not None
		          else self._offset_expression(struct, placement))

		# A bit-packed field cannot land at a dynamic offset: the layout
		# solver refuses the construct outright, because a bit phase across a
		# dynamic boundary is not something it computes (`layout.py`,
		# check_alignment). This is an assertion of that rule rather than a gap
		# in this backend -- if the rule is ever relaxed, it fires here instead
		# of emitting a wrong bit offset, which is undetectable at run time.
		assert not (placement.offset_bits is None and scalar.is_bit_packed), \
			f"{placement.path}: bit-packed at a dynamic offset"

		if placement.offset_bits is None and offset is None:
			return ["", f"\t/* {placement.path}: its offset cannot be"
			        f" resolved. */"]

		name  = c_name(local_name(struct, placement))
		ctype = self._field_ctype(placement)
		lines = ["", *self._axes_comment(entry)]

		load = self._load(scalar, placement, offset)
		if placement.type_name in self.enums:
			load = f"static_cast<{ctype}>({load})"

		lines.extend([
			f"\t[[nodiscard]] {ctype} {name}() const noexcept",
			"\t{",
			f"\t\treturn {load};",
			"\t}",
		])

		if entry.vector.get(Axis.MUTATE).base != "InPlaceFixed":
			lines.extend([
				f"\t/* No setter: mutate is"
				f" {entry.vector.get(Axis.MUTATE).render()}. */",
			])
			return lines

		stored = "value"
		if placement.type_name in self.enums:
			backing = self._ctype(scalar)
			stored  = f"static_cast<{backing}>(value)"

		# A covered write takes the message, because it has to mark a bit that
		# lives there. This backend used to emit the plain setter for these
		# too, so a C++ caller could write a tag-covered byte and have
		# `transmittable()` go on saying the message was ready to send -- the
		# capability map's `auth = Covered(t)` is a claim that writing marks
		# `t` stale, and here it was not true. C and Python both refuse it.
		if placement.covered_by:
			bits = self._dirty_bits(struct, placement)
			what = ", ".join(placement.covered_by)
			lines.extend([
				f"\t/* Writing this leaves {what} stale, so it takes the message",
				"\t * and marks the bit. The cost is in the signature rather than",
				"\t * in a comment somebody may not read. */",
				f"\tvoid set_{name}(::situ::rt::message &msg, {ctype} value) noexcept",
				"\t{",
				f"\t\t{self._store(scalar, placement, stored, offset)}",
				f"\t\tmsg.mark_dirty({bits});",
				"\t}",
			])
			return lines

		lines.extend([
			f"\tvoid set_{name}({ctype} value) noexcept",
			"\t{",
			f"\t\t{self._store(scalar, placement, stored, offset)}",
			"\t}",
		])
		return lines

	def _dirty_bits(self, struct: ResolvedStruct, placement: Placement) -> str:
		"""The bits every obligation over this field stands for, ORed.

		Every one, not the first: a field under a tag *and* an invariant leaves
		both stale, and marking one of the two is a message that reports itself
		ready to send while a covered byte no longer matches what
		authenticates it.
		"""
		names = [f"dirty_{c_name(held.name)}"
		         for label in placement.covered_by
		         if (held := obligation(self.schema, struct, label)) is not None]
		return " | ".join(names) if names else "0u"

	def _load(self, scalar: ScalarType, placement: Placement,
			offset: str | None = None) -> str:
		base   = f"base() + {offset if offset is not None else placement.offset_bytes}"
		ctype  = self._ctype(scalar)

		if scalar.is_bcd:
			raw = self._raw_load(scalar, placement, base)
			return (f"static_cast<{ctype}>(situ_bcd_decode("
			        f"static_cast<std::uint64_t>({raw}), {scalar.digits}))")
		return self._raw_load(scalar, placement, base)

	def _raw_load(self, scalar: ScalarType, placement: Placement,
			base: str) -> str:
		ctype = self._ctype(scalar)

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			raw   = (f"situ_bits_get_{order}(base(), {placement.offset_bits},"
			         f" {scalar.bits})")
			if scalar.signed:
				return (f"static_cast<{ctype}>(situ_sign_extend({raw},"
				        f" {scalar.bits}))")
			return f"static_cast<{ctype}>({raw})"

		if scalar.bits == BITS_PER_BYTE:
			return f"static_cast<{ctype}>(*({base}))"

		suffix = _order_suffix(placement.endian)
		if scalar.bits in WORD_WIDTHS:
			return f"static_cast<{ctype}>(situ_get_{suffix}{scalar.bits}({base}))"

		assembly = "lsb" if placement.endian is ast.Endian.LITTLE else "msb"
		return (f"static_cast<{ctype}>(situ_bits_get_{assembly}(base(),"
		        f" {placement.offset_bits}, {scalar.bits}))")

	def _store(self, scalar: ScalarType, placement: Placement,
			value: str, offset: str | None = None) -> str:
		base = f"base() + {offset if offset is not None else placement.offset_bytes}"

		if scalar.is_bcd:
			value = (f"situ_bcd_encode(static_cast<std::uint64_t>({value}),"
			         f" {scalar.digits})")

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			return (f"situ_bits_set_{order}(base(), {placement.offset_bits},"
			        f" {scalar.bits}, static_cast<std::uint64_t>({value}));")

		if scalar.bits == BITS_PER_BYTE:
			return f"*({base}) = static_cast<std::uint8_t>({value});"

		suffix = _order_suffix(placement.endian)
		if scalar.bits in WORD_WIDTHS:
			return (f"situ_put_{suffix}{scalar.bits}({base},"
			        f" static_cast<std::uint{scalar.bits}_t>({value}));")

		assembly = "lsb" if placement.endian is ast.Endian.LITTLE else "msb"
		return (f"situ_bits_set_{assembly}(base(), {placement.offset_bits},"
		        f" {scalar.bits}, static_cast<std::uint64_t>({value}));")

	# -- aggregates ----------------------------------------------------

	def _nested(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		nested = f"::{self.namespace}::{c_name(placement.type_name or '')}"
		return [
			"",
			f"\t/* {placement.path} at {placement.offset_bytes}. Its own class",
			"\t * carries its accessors; this is where the parent puts it. */",
			f"\t[[nodiscard]] {nested} {name}() const noexcept",
			"\t{",
			f"\t\treturn {nested}(situ_view_t{{ base() + {placement.offset_bytes},",
			f"\t\t\t{nested}::size_bytes, raw().generation }});",
			"\t}",
		]

	def _array(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		scalar = placement.scalar
		count  = placement.array_count or 0

		if scalar is None or scalar.bits != BITS_PER_BYTE:
			return ["", f"\t/* {placement.path}: element type"
			        f" {placement.type_name} is not in the static subset yet. */"]

		lines = [
			"",
			f"\t/* {placement.path}: {count} bytes, MemoryIdentical, so the",
			"\t * pointer and the length travel together. */",
			f"\t[[nodiscard]] ::situ::rt::bytes {name}() const noexcept",
			"\t{",
			f"\t\treturn ::situ::rt::bytes(base() + {placement.offset_bytes},"
			f" {count});",
			"\t}",
		]

		if any(attr.name == "nul_terminated" for attr in placement.attrs):
			lines.extend([
				"",
				f"\t/* Content length: to the first zero byte, or {count}. */",
				f"\t[[nodiscard]] std::uint32_t {name}_len() const noexcept",
				"\t{",
				f"\t\treturn situ_nul_len(base() + {placement.offset_bytes},"
				f" {count});",
				"\t}",
			])
		return lines

	# -- validation ----------------------------------------------------

	def _validate(self, struct: ResolvedStruct) -> list[str]:
		checks: list[str] = []

		for entry in own_entries(struct):
			checks.extend(self._check(struct, entry))

		lines = [
			"",
			"\t/* Every constraint the schema declares, on parse. */",
			"\t[[nodiscard]] ::situ::rt::err validate() const noexcept",
			"\t{",
		]
		if not checks:
			lines.append("\t\t/* Nothing in this struct is constrained. */")
		lines.extend(checks)
		lines.extend(["\t\treturn ::situ::rt::err::ok;", "\t}"])
		return lines

	def _check(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		from situc.expr import evaluate

		placement = entry.placement
		scalar    = placement.scalar

		check = classify_check(struct, placement, self.structs)

		if check is Check.NOTHING:
			return []
		if check is Check.REPEATED:
			assert scalar is not None
			return self._array_checks(struct, placement, scalar)
		if check is Check.NESTED:
			name = c_name(local_name(struct, placement))
			return [
				f"\t\tif (const ::situ::rt::err e = {name}().validate();"
				f" e != ::situ::rt::err::ok) {{",
				"\t\t\treturn e;",
				"\t\t}",
			]

		assert scalar is not None
		lines: list[str] = []

		if check is Check.RESERVED:
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				want = "0" if policy == "must_be_zero" \
					else f"0x{(1 << scalar.bits) - 1:X}"
				lines.extend([
					f"\t\t/* reserved {placement.type_name} [{policy}] */",
					f"\t\tif ({self._raw_load(scalar, placement, f'base() + {placement.offset_bytes}')}"
					f" != {want}) {{",
					"\t\t\treturn ::situ::rt::err::constraint;",
					"\t\t}",
				])
			return lines

		name = c_name(local_name(struct, placement))

		enum = self.enums.get(placement.type_name or "")
		if enum is not None and enum.effective_default is ast.EnumDefault.ERROR:
			lines.extend([
				f"\t\t/* {placement.path}: `{enum.name}` rejects unknown values"
				f" (section 8.7) */",
				f"\t\tif (!is_known({name}())) {{",
				"\t\t\treturn ::situ::rt::err::constraint;",
				"\t\t}",
			])

		for attr in placement.attrs:
			if attr.name not in ("must_eq", "max", "min") or attr.value is None:
				continue
			expected = evaluate(attr.value, self.resolved.layout.env)
			operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
			cast     = (f"static_cast<{self._ctype(scalar)}>({name}())"
			            if placement.type_name in self.enums else f"{name}()")
			lines.extend([
				f"\t\t/* {placement.path} [{attr.name} = {expected}] */",
				f"\t\tif ({cast} {operator} {expected}) {{",
				"\t\t\treturn ::situ::rt::err::constraint;",
				"\t\t}",
			])
		return lines

	def _array_checks(self, struct: ResolvedStruct, placement: Placement,
			scalar: ScalarType) -> list[str]:
		if scalar.bits != BITS_PER_BYTE:
			return []

		name  = c_name(local_name(struct, placement))
		count = placement.array_count or 0
		lines: list[str] = []

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				want = "0" if policy == "must_be_zero" else "0xFF"
				lines.extend([
					f"\t\t/* reserved {placement.type_name}[{count}] [{policy}] */",
					f"\t\tfor (std::uint32_t i = 0; i < {count}; i++) {{",
					f"\t\t\tif (*(base() + {placement.offset_bytes} + i) != {want}) {{",
					"\t\t\t\treturn ::situ::rt::err::constraint;",
					"\t\t\t}",
					"\t\t}",
				])
			return lines

		for attr in placement.attrs:
			if attr.name == "encoding":
				named = getattr(attr.value, "name", None)
				if named in ("ascii", "utf8"):
					lines.extend([
						f"\t\t/* {placement.path} [encoding = {named}] */",
						f"\t\tif (!situ_{named}_valid({name}().data(),"
						f" {count})) {{",
						"\t\t\treturn ::situ::rt::err::constraint;",
						"\t\t}",
					])
			if attr.name == "nul_terminated":
				lines.extend([
					f"\t\t/* {placement.path} [nul_terminated] */",
					f"\t\tif (!situ_nul_terminated({name}().data(), {count})) {{",
					"\t\t\treturn ::situ::rt::err::constraint;",
					"\t\t}",
				])
		return lines

	# -- helpers -------------------------------------------------------

	def _axes_comment(self, entry: Resolved) -> list[str]:
		vector = entry.vector
		axes   = " ".join(f"{axis.value}={vector.get(axis).render()}"
		                  for axis in (Axis.SIZE, Axis.ALIGN, Axis.REPR,
		                               Axis.ATOMIC, Axis.MUTATE))
		return [f"\t/* {entry.placement.path} at"
		        f" {vector.get(Axis.OFFSET).render()}",
		        f"\t * {axes} */"]

	def _field_ctype(self, placement: Placement) -> str:
		"""The type an accessor uses, enums fully qualified.

		A field may share a name with its own enum -- IPv4's `protocol` field
		has type `protocol` -- and an unqualified use inside the class would
		change what that name means partway through it, which C++ rejects
		outright. Qualifying costs nothing and the hazard is not the author's
		to avoid (decision 0013).
		"""
		if placement.type_name in self.enums:
			return f"::{self.namespace}::{c_name(placement.type_name)}"
		scalar = placement.scalar
		assert scalar is not None
		return self._ctype(scalar)

	def _ctype(self, scalar: ScalarType) -> str:
		if scalar.kind is ScalarKind.FLOAT:
			return {16: "std::uint16_t", 32: "float", 64: "double"}[scalar.bits]
		width = _storage_width(scalar.bits)
		return f"std::int{width}_t" if scalar.signed else f"std::uint{width}_t"


def _storage_width(bits: int) -> int:
	for width in WORD_WIDTHS:
		if bits <= width:
			return width
	return 64


def _order_suffix(endian: ast.Endian | None) -> str:
	if endian is ast.Endian.NATIVE:
		return "ne"
	return "le" if endian is ast.Endian.LITTLE else "be"


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str | None:
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one"):
			return str(attr.name)
		if attr.name in ("preserve", "unknown"):
			return None
	return "must_be_zero"
