"""The C++ backend (section 26.16).

C++ is the second backend because it is the largest population after C, and
because parts of the capability lattice that C can only document it can
enforce. Three, specifically:

  * a byte array is a `situ::span`, so its length travels with its pointer
  * an error is `[[nodiscard]]`, so ignoring one is a diagnostic
  * a sealed region's view has no public constructor, so it cannot be made
    except by the function that verifies the tag -- in C the struct is there
    for anybody determined enough to fill in

What it deliberately does not do is reinvent anything. The layout, the
propagation table and the runtime arithmetic are the same ones the C backend
uses; this emits a different surface over identical bytes. A view is a value
for the same reason it is in C -- it owns nothing, so a destructor would be a
lie about what it is -- and errors are return codes rather than exceptions
because the target may have neither unwinding nor a heap.

Header-only. Every accessor is a constant offset from a base and inlines to
nothing, so there is no translation unit worth having; `validate` is the one
function with a body and it is `inline` too.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c.names import c_name
from situc.diagnostics import Diagnostic
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import local_name, own_entries
from situc.types import ScalarKind, ScalarType

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Generated:
	"""What a schema compiles to. One file: C++ needs no second one here."""

	header: str
	basename: str
	warnings: list[Diagnostic] = field(default_factory=list)

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.hpp": self.header}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		namespace: str = "situ") -> Generated:
	return Generated(
		header   = Emitter(schema, resolved, basename, namespace).header(),
		basename = basename,
	)


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str, namespace: str) -> None:
		self.schema    = schema
		self.resolved  = resolved
		self.basename  = basename
		self.namespace = namespace
		self.enums     = {decl.name: decl for decl in schema.enums()}
		self.structs   = set(resolved.structs)

	# -- the file ------------------------------------------------------

	def header(self) -> str:
		guard = f"SITU_{c_name(self.basename).upper()}_HPP"
		lines = [
			f"/* Generated by situc from {self.basename}.situ -- do not edit.",
			" *",
			" * The operations below are exactly the ones this schema's capability",
			" * vectors support. Where one is missing, a comment says why.",
			" */",
			"",
			f"#ifndef {guard}",
			f"#define {guard}",
			"",
			'#include "situ.hpp"',
			"",
			f"namespace {self.namespace} {{",
		]

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		for name in self._struct_order():
			lines.extend(self._struct(self.resolved.structs[name]))

		lines.extend(["", f"}}  /* namespace {self.namespace} */", "",
		              f"#endif /* {guard} */"])
		return "\n".join(lines) + "\n"

	def _struct_order(self) -> list[str]:
		"""Structs before the structs that contain them.

		A class has to be complete before another names it by value, which C
		sidesteps by handing out offsets rather than types. Declaration order in
		the schema is not required to respect containment, so it is sorted here
		rather than demanded of the author.
		"""
		order: list[str] = []
		seen: set[str]   = set()

		def visit(name: str) -> None:
			if name in seen:
				return
			seen.add(name)
			for entry in own_entries(self.resolved.structs[name]):
				nested = entry.placement.type_name
				if nested in self.structs and nested != name:
					visit(nested)
			order.append(name)

		for name in sorted(self.structs):
			visit(name)
		return order

	# -- enums ---------------------------------------------------------

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		backing = decl.backing.scalar
		assert backing is not None
		values = self.resolved.layout.env.enums[decl.name]

		lines = [
			"",
			f"/* enum {decl.name} : {decl.backing.name}"
			f" -- unknown values are {decl.effective_default.value} */",
			f"enum class {c_name(decl.name)} : {self._ctype(backing)} {{",
		]
		lines.extend(f"\t{c_name(member.name)} = {values[member.name]},"
		             for member in decl.members)
		lines.append("};")
		return lines

	# -- structs -------------------------------------------------------

	def _struct(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		name   = c_name(struct.name)

		if layout.register is not None:
			return ["", f"/* {struct.name} is a register (section 15). The C++",
			        " * backend does not emit those yet; use the C header. */"]
		if not layout.is_fixed_size:
			return ["", f"/* {struct.name} is not fixed size. The C++ backend",
			        " * covers the static subset so far; use the C header. */"]

		lines = [
			"",
			f"/* struct {struct.name}: {layout.size_bytes} bytes, fixed. */",
			f"class {name} : public ::situ::rt::view {{",
			"public:",
			f"\tstatic constexpr std::uint32_t size_bytes = {layout.size_bytes};",
			"",
			"\t/* The one bounds check. Everything below trusts it, which is why",
			"\t * it is the only thing that can fail. */",
			f"\t[[nodiscard]] static ::situ::rt::err at(::situ::rt::message &msg,",
			f"\t\t\tstd::uint32_t offset, {name} &out) noexcept",
						"\t{",
			"\t\tsitu_view_t raw;",
			"\t\tconst situ_err_t e = situ_view_at(msg.raw(), offset,"
			" size_bytes, &raw);",
			"",
			"\t\tif (e == SITU_OK) {",
			f"\t\t\tout = {name}(raw);",
			"\t\t}",
			"\t\treturn static_cast<::situ::rt::err>(e);",
			"\t}",
			"",
			f"\tconstexpr {name}() noexcept = default;",
			f"\texplicit constexpr {name}(situ_view_t raw) noexcept"
			f" : ::situ::rt::view(raw) {{}}",
		]

		for entry in own_entries(struct):
			lines.extend(self._member(struct, entry))

		lines.extend(self._validate(struct))
		lines.append("};")
		return lines

	def _member(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement

		if placement.kind == "reserved":
			return ["",
			        f"\t/* {placement.path} is reserved: no accessor, and"
			        f" `validate` holds it to",
			        "\t * the pattern the schema declares. */"]
		if placement.kind != "field" or placement.offset_bits is None:
			return ["", f"\t/* {placement.path}: not in the static subset yet. */"]

		if placement.type_name in self.structs:
			return self._nested(struct, placement)
		if placement.array_count is not None:
			return self._array(struct, placement)
		if placement.scalar is None:
			return []

		return self._scalar(struct, entry)

	# -- one scalar ----------------------------------------------------

	def _scalar(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		assert scalar is not None

		name  = c_name(local_name(struct, placement))
		ctype = self._field_ctype(placement)
		lines = ["", *self._axes_comment(entry)]

		load = self._load(scalar, placement)
		if placement.type_name in self.enums:
			load = f"static_cast<{ctype}>({load})"

		lines.extend([
			f"\t[[nodiscard]] {ctype} {name}() const noexcept",
			"\t{",
			f"\t\treturn {load};",
			"\t}",
		])

		if entry.vector.get(Axis.MUTATE).base != "InPlaceFixed":
			lines.extend([
				f"\t/* No setter: mutate is"
				f" {entry.vector.get(Axis.MUTATE).render()}. */",
			])
			return lines

		stored = "value"
		if placement.type_name in self.enums:
			backing = self._ctype(scalar)
			stored  = f"static_cast<{backing}>(value)"

		lines.extend([
			f"\tvoid set_{name}({ctype} value) noexcept",
			"\t{",
			f"\t\t{self._store(scalar, placement, stored)}",
			"\t}",
		])
		return lines

	def _load(self, scalar: ScalarType, placement: Placement) -> str:
		base   = f"base() + {placement.offset_bytes}"
		ctype  = self._ctype(scalar)

		if scalar.is_bcd:
			raw = self._raw_load(scalar, placement, base)
			return (f"static_cast<{ctype}>(situ_bcd_decode("
			        f"static_cast<std::uint64_t>({raw}), {scalar.digits}))")
		return self._raw_load(scalar, placement, base)

	def _raw_load(self, scalar: ScalarType, placement: Placement,
			base: str) -> str:
		ctype = self._ctype(scalar)

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			raw   = (f"situ_bits_get_{order}(base(), {placement.offset_bits},"
			         f" {scalar.bits})")
			if scalar.signed:
				return (f"static_cast<{ctype}>(situ_sign_extend({raw},"
				        f" {scalar.bits}))")
			return f"static_cast<{ctype}>({raw})"

		if scalar.bits == BITS_PER_BYTE:
			return f"static_cast<{ctype}>(*({base}))"

		suffix = _order_suffix(placement.endian)
		if scalar.bits in WORD_WIDTHS:
			return f"static_cast<{ctype}>(situ_get_{suffix}{scalar.bits}({base}))"

		assembly = "lsb" if placement.endian is ast.Endian.LITTLE else "msb"
		return (f"static_cast<{ctype}>(situ_bits_get_{assembly}(base(),"
		        f" {placement.offset_bits}, {scalar.bits}))")

	def _store(self, scalar: ScalarType, placement: Placement,
			value: str) -> str:
		base = f"base() + {placement.offset_bytes}"

		if scalar.is_bcd:
			value = (f"situ_bcd_encode(static_cast<std::uint64_t>({value}),"
			         f" {scalar.digits})")

		if scalar.is_bit_packed:
			order = "lsb" if placement.bit_order is ast.BitOrder.LSB_FIRST else "msb"
			return (f"situ_bits_set_{order}(base(), {placement.offset_bits},"
			        f" {scalar.bits}, static_cast<std::uint64_t>({value}));")

		if scalar.bits == BITS_PER_BYTE:
			return f"*({base}) = static_cast<std::uint8_t>({value});"

		suffix = _order_suffix(placement.endian)
		if scalar.bits in WORD_WIDTHS:
			return (f"situ_put_{suffix}{scalar.bits}({base},"
			        f" static_cast<std::uint{scalar.bits}_t>({value}));")

		assembly = "lsb" if placement.endian is ast.Endian.LITTLE else "msb"
		return (f"situ_bits_set_{assembly}(base(), {placement.offset_bits},"
		        f" {scalar.bits}, static_cast<std::uint64_t>({value}));")

	# -- aggregates ----------------------------------------------------

	def _nested(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		nested = f"::{self.namespace}::{c_name(placement.type_name or '')}"
		return [
			"",
			f"\t/* {placement.path} at {placement.offset_bytes}. Its own class",
			"\t * carries its accessors; this is where the parent puts it. */",
			f"\t[[nodiscard]] {nested} {name}() const noexcept",
			"\t{",
			f"\t\treturn {nested}(situ_view_t{{ base() + {placement.offset_bytes},",
			f"\t\t\t{nested}::size_bytes, raw().generation }});",
			"\t}",
		]

	def _array(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		scalar = placement.scalar
		count  = placement.array_count or 0

		if scalar is None or scalar.bits != BITS_PER_BYTE:
			return ["", f"\t/* {placement.path}: element type"
			        f" {placement.type_name} is not in the static subset yet. */"]

		lines = [
			"",
			f"\t/* {placement.path}: {count} bytes, MemoryIdentical, so the",
			"\t * pointer and the length travel together. */",
			f"\t[[nodiscard]] ::situ::rt::bytes {name}() const noexcept",
			"\t{",
			f"\t\treturn ::situ::rt::bytes(base() + {placement.offset_bytes},"
			f" {count});",
			"\t}",
		]

		if any(attr.name == "nul_terminated" for attr in placement.attrs):
			lines.extend([
				"",
				f"\t/* Content length: to the first zero byte, or {count}. */",
				f"\t[[nodiscard]] std::uint32_t {name}_len() const noexcept",
				"\t{",
				f"\t\treturn situ_nul_len(base() + {placement.offset_bytes},"
				f" {count});",
				"\t}",
			])
		return lines

	# -- validation ----------------------------------------------------

	def _validate(self, struct: ResolvedStruct) -> list[str]:
		checks: list[str] = []

		for entry in own_entries(struct):
			checks.extend(self._check(struct, entry))

		lines = [
			"",
			"\t/* Every constraint the schema declares, on parse. */",
			"\t[[nodiscard]] ::situ::rt::err validate() const noexcept",
			"\t{",
		]
		if not checks:
			lines.append("\t\t/* Nothing in this struct is constrained. */")
		lines.extend(checks)
		lines.extend(["\t\treturn ::situ::rt::err::ok;", "\t}"])
		return lines

	def _check(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		from situc.expr import evaluate

		placement = entry.placement
		scalar    = placement.scalar

		if placement.type_name in self.structs and scalar is None:
			name = c_name(local_name(struct, placement))
			return [
				f"\t\tif (const ::situ::rt::err e = {name}().validate();"
				f" e != ::situ::rt::err::ok) {{",
				"\t\t\treturn e;",
				"\t\t}",
			]

		if scalar is None or placement.offset_bits is None:
			return []

		lines: list[str] = []

		if placement.kind == "reserved" and placement.array_count is None:
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				want = "0" if policy == "must_be_zero" \
					else f"0x{(1 << scalar.bits) - 1:X}"
				lines.extend([
					f"\t\t/* reserved {placement.type_name} [{policy}] */",
					f"\t\tif ({self._raw_load(scalar, placement, f'base() + {placement.offset_bytes}')}"
					f" != {want}) {{",
					"\t\t\treturn ::situ::rt::err::constraint;",
					"\t\t}",
				])
			return lines

		if placement.array_count is not None:
			return self._array_checks(struct, placement, scalar)

		name = c_name(local_name(struct, placement))
		for attr in placement.attrs:
			if attr.name not in ("must_eq", "max", "min") or attr.value is None:
				continue
			expected = evaluate(attr.value, self.resolved.layout.env)
			operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
			cast     = (f"static_cast<{self._ctype(scalar)}>({name}())"
			            if placement.type_name in self.enums else f"{name}()")
			lines.extend([
				f"\t\t/* {placement.path} [{attr.name} = {expected}] */",
				f"\t\tif ({cast} {operator} {expected}) {{",
				"\t\t\treturn ::situ::rt::err::constraint;",
				"\t\t}",
			])
		return lines

	def _array_checks(self, struct: ResolvedStruct, placement: Placement,
			scalar: ScalarType) -> list[str]:
		if scalar.bits != BITS_PER_BYTE:
			return []

		name  = c_name(local_name(struct, placement))
		count = placement.array_count or 0
		lines: list[str] = []

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				want = "0" if policy == "must_be_zero" else "0xFF"
				lines.extend([
					f"\t\t/* reserved {placement.type_name}[{count}] [{policy}] */",
					f"\t\tfor (std::uint32_t i = 0; i < {count}; i++) {{",
					f"\t\t\tif (*(base() + {placement.offset_bytes} + i) != {want}) {{",
					"\t\t\t\treturn ::situ::rt::err::constraint;",
					"\t\t\t}",
					"\t\t}",
				])
			return lines

		for attr in placement.attrs:
			if attr.name == "encoding":
				named = getattr(attr.value, "name", None)
				if named in ("ascii", "utf8"):
					lines.extend([
						f"\t\t/* {placement.path} [encoding = {named}] */",
						f"\t\tif (!situ_{named}_valid({name}().data(),"
						f" {count})) {{",
						"\t\t\treturn ::situ::rt::err::constraint;",
						"\t\t}",
					])
			if attr.name == "nul_terminated":
				lines.extend([
					f"\t\t/* {placement.path} [nul_terminated] */",
					f"\t\tif (!situ_nul_terminated({name}().data(), {count})) {{",
					"\t\t\treturn ::situ::rt::err::constraint;",
					"\t\t}",
				])
		return lines

	# -- helpers -------------------------------------------------------

	def _axes_comment(self, entry: Resolved) -> list[str]:
		vector = entry.vector
		axes   = " ".join(f"{axis.value}={vector.get(axis).render()}"
		                  for axis in (Axis.SIZE, Axis.ALIGN, Axis.REPR,
		                               Axis.ATOMIC, Axis.MUTATE))
		return [f"\t/* {entry.placement.path} at"
		        f" {vector.get(Axis.OFFSET).render()}",
		        f"\t * {axes} */"]

	def _field_ctype(self, placement: Placement) -> str:
		"""The type an accessor uses, enums fully qualified.

		A field may share a name with its own enum -- IPv4's `protocol` field
		has type `protocol` -- and an unqualified use inside the class would
		change what that name means partway through it, which C++ rejects
		outright. Qualifying costs nothing and the hazard is not the author's
		to avoid (decision 0013).
		"""
		if placement.type_name in self.enums:
			return f"::{self.namespace}::{c_name(placement.type_name)}"
		scalar = placement.scalar
		assert scalar is not None
		return self._ctype(scalar)

	def _ctype(self, scalar: ScalarType) -> str:
		if scalar.kind is ScalarKind.FLOAT:
			return {16: "std::uint16_t", 32: "float", 64: "double"}[scalar.bits]
		width = _storage_width(scalar.bits)
		return f"std::int{width}_t" if scalar.signed else f"std::uint{width}_t"


def _storage_width(bits: int) -> int:
	for width in WORD_WIDTHS:
		if bits <= width:
			return width
	return 64


def _order_suffix(endian: ast.Endian | None) -> str:
	if endian is ast.Endian.NATIVE:
		return "ne"
	return "le" if endian is ast.Endian.LITTLE else "be"


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str | None:
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one"):
			return str(attr.name)
		if attr.name in ("preserve", "unknown"):
			return None
	return "must_be_zero"
