"""Stream framing in C++ (26.96).

Not a translation of the C reader. C++ acquires a view through
`T::at(rt::message &owner, offset, out)` rather than from a raw pointer, so
the reader owns the `rt::message` over its own buffer and hands out views of
it. `required` takes `need` by reference here rather than by pointer, which
is the only part that is merely spelling.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.c.frame import framed_structs
from situc.codegen.c.names import c_name
from situc.codegen.cpp.names import class_name
from situc.resolve import ResolvedSchema
from situc import __version__

__all__ = ["generate"]


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	structs = framed_structs(resolved)
	if not structs:
		return {}

	guard = f"SITU_{c_name(basename).upper()}_FRAME_HPP"
	lines = [
		f"/* Generated by situc {__version__} from {basename}.situ -- do not edit.",
		" *",
		" * Stream framing: a byte stream in, whole messages out. The buffer",
		" * is the caller's and nothing here allocates. A separate header --",
		" * a rung adds files rather than changing them (decision 0032).",
		" */",
		"",
		f"#ifndef {guard}",
		f"#define {guard}",
		"",
		"#include <cstdint>",
		"",
		f"#include \"{basename}.hpp\"",
		"",
		"namespace situ {",
		"",
	]

	for struct in structs:
		held = class_name(struct)
		name = f"{c_name(struct.name)}_reader"
		lines += [
			f"/** A stream reader for `{struct.name}`.",
			" *",
			" * Push bytes as they arrive, call `next` until it answers",
			" * `err::truncated`, and call `advance` when done with each",
			" * message.",
			" *",
			" * THE VIEW `next` FILLS DIES AT THE FOLLOWING `advance` OR",
			" * `push`: it points into this buffer, and dropping a message",
			" * moves what follows down over it.",
			" */",
			f"class {name} {{",
			"public:",
			f"\t{name}(std::uint8_t *buf, std::uint32_t cap) noexcept",
			"\t\t: buf_(buf), cap_(cap), have_(0u), ready_(0u), owner_(buf, cap)",
			"\t{}",
			"",
			"\tvoid advance() noexcept",
			"\t{",
			"\t\tif (ready_ == 0u) {",
			"\t\t\treturn;",
			"\t\t}",
			"\t\tfor (std::uint32_t i = ready_; i < have_; i++) {",
			"\t\t\tbuf_[i - ready_] = buf_[i];",
			"\t\t}",
			"\t\thave_ -= ready_;",
			"\t\tready_ = 0u;",
			"\t}",
			"",
			"\t[[nodiscard]] ::situ::rt::err push(const std::uint8_t *data,",
			"\t                                   std::uint32_t len) noexcept",
			"\t{",
			"\t\tadvance();",
			"\t\tif (len > cap_ - have_) {",
			"\t\t\treturn ::situ::rt::err::bounds;",
			"\t\t}",
			"\t\tfor (std::uint32_t i = 0u; i < len; i++) {",
			"\t\t\tbuf_[have_ + i] = data[i];",
			"\t\t}",
			"\t\thave_ += len;",
			"\t\treturn ::situ::rt::err::ok;",
			"\t}",
			"",
			f"\t[[nodiscard]] ::situ::rt::err next(::situ::{held} &out) noexcept",
			"\t{",
			"\t\tadvance();",
			"",
			"\t\tstd::uint32_t need = 0u;",
			f"\t\tconst ::situ::rt::err err = ::situ::{held}::required(",
			"\t\t\tbuf_, have_, need);",
			"\t\tif (err != ::situ::rt::err::ok) {",
			"\t\t\tif (need > cap_) {",
			"\t\t\t\treturn ::situ::rt::err::bounds;",
			"\t\t\t}",
			"\t\t\treturn err;",
			"\t\t}",
			"",
			f"\t\tconst ::situ::rt::err got = ::situ::{held}::at(owner_, 0u, out);",
			"\t\tif (got != ::situ::rt::err::ok) {",
			"\t\t\treturn got;",
			"\t\t}",
			"\t\tready_ = need;",
			"\t\treturn ::situ::rt::err::ok;",
			"\t}",
			"",
			"private:",
			"\tstd::uint8_t      *buf_;",
			"\tstd::uint32_t      cap_;",
			"\tstd::uint32_t      have_;",
			"\tstd::uint32_t      ready_;",
			"\t::situ::rt::message owner_;",
			"};",
			"",
		]

	lines += ["}  /* namespace situ */", "", f"#endif /* {guard} */"]
	return {f"{basename}_frame.hpp": "\n".join(lines) + "\n"}
