"""Cross-message relations in C++ (26.95).

The walk is `situc.relation`'s; this decides only how C++ spells one. What
differs from C is the parameter type: a view there is one `situ_view_t`
whatever it views, and here it is the struct's own class, so the predicate
cannot be handed the wrong message by accident. That is the same trade the
C++ backend already makes everywhere else, and it is why the header table in
section 26 calls out what each language can enforce rather than document.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.c.names import c_name
from situc.codegen.cpp.names import class_name
from situc.relation import (Constraint, Read, ReadBytes, SubView, plans,
                            refusals, render)
from situc.resolve import ResolvedSchema
from situc import __version__

__all__ = ["generate", "refusals", "signature"]


def _local(name: str) -> str:
	return f"v{name}"


def _source(name: str) -> str:
	return _local(name) if name.startswith("_") else name


def signature(relation: ast.Relation, resolved: ResolvedSchema) -> str:
	params = ", ".join(
		f"const ::situ::{class_name(resolved.structs[param.type_name])} "
		f"&{param.name}"
		for param in relation.params)
	return (f"[[nodiscard]] inline ::situ::rt::err "
	        f"rel_{c_name(relation.name)}({params}) noexcept")


def _binding(bind: SubView | Read | ReadBytes, cast: str,
		resolved: ResolvedSchema) -> list[str]:
	source = _source(bind.source)
	target = _local(bind.target)

	if isinstance(bind, SubView):
		held = f"{target}_held"
		return [
			f"\t::situ::{class_name(resolved.structs[bind.into])} {held};"
			f"\t/* {bind.path} */",
			f"\tif (const ::situ::rt::err e = {source}.{c_name(bind.member)}"
			f"({held}); e != ::situ::rt::err::ok) {{",
			"\t\treturn e;",
			"\t}",
			f"\tconst ::situ::{class_name(resolved.structs[bind.into])} "
			f"&{target} = {held};",
		]

	if isinstance(bind, ReadBytes):
		# The accessor already returns a span; the comparison is over what it
		# points at rather than over the span object.
		return [f"\tconst ::situ::rt::bytes {target} = "
		        f"{source}.{c_name(bind.member)}();\t/* {bind.path} */"]

	return [f"\tconst {cast} {target} = static_cast<{cast}>"
	        f"({source}.{c_name(bind.member)}());\t/* {bind.path} */"]


def _body(constraints: list[Constraint],
		resolved: ResolvedSchema) -> list[str]:
	lines: list[str] = []

	for constraint in constraints:
		cast  = "std::int64_t" if constraint.signed else "std::uint64_t"
		block: list[str] = []

		for bind in constraint.bindings:
			block += _binding(bind, cast, resolved)

		if constraint.bytes_equal is not None:
			same = constraint.bytes_equal
			test = "!=" if not same.negated else "=="
			block += [
				f"\tif (std::memcmp({_local(same.left)}.data(), "
				f"{_local(same.right)}.data(), {same.length}u) {test} 0) {{",
				"\t\treturn ::situ::rt::err::constraint;",
				"\t}",
			]
			lines += ["\t{", *[f"\t{line}" for line in block], "\t}", ""]
			continue

		assert constraint.expr is not None
		locals_for = {path: _local(name)
		              for path, name in constraint.locals_for.items()}
		block += [
			f"\tif (!{render(constraint.expr, locals_for)}) {{",
			"\t\treturn ::situ::rt::err::constraint;",
			"\t}",
		]

		lines += ["\t{", *[f"\t{line}" for line in block], "\t}", ""]

	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	"""The relation header, or nothing if no relation is expressible."""
	ready = plans(schema, resolved)
	if not ready:
		return {}

	guard = f"SITU_{c_name(basename).upper()}_RELATE_HPP"
	lines = [
		f"/* Generated by situc {__version__} from {basename}.situ -- do not edit.",
		" *",
		" * Cross-message relations: a pure predicate per relation, over two",
		" * views the caller already holds. A separate header on purpose --",
		" * a rung adds files rather than changing them (decision 0032).",
		" */",
		"",
		f"#ifndef {guard}",
		f"#define {guard}",
		"",
		"#include <cstdint>",
		# Only where a constraint compares bytes: a header a freestanding
		# target may not want, for a function nothing else here calls.
		*(["#include <cstring>"]
		  if any(one.bytes_equal is not None
		         for _, cs in ready for one in cs) else []),
		"",
		f"#include \"{basename}.hpp\"",
		"",
		"namespace situ {",
		"",
	]

	for relation, constraints in ready:
		first, second = relation.params
		lines += [
			f"/** Whether `{second.name}` is a well-formed counterpart to "
			f"`{first.name}`.",
			" *",
			" * Pure: reads two views, holds nothing, allocates nothing. The",
			" * caller owns the pairing; this answers only whether one is well",
			f" * formed. Parameter order is temporal -- `{first.name}` is the",
			" * message seen first.",
			" */",
			signature(relation, resolved),
			"{",
			*_body(constraints, resolved),
			"\treturn ::situ::rt::err::ok;",
			"}",
			"",
		]

	lines += ["}  /* namespace situ */", "", f"#endif /* {guard} */"]

	return {f"{basename}_relate.hpp": "\n".join(lines) + "\n"}
