"""Matching a reply to its request in Python (26.97).

**The capacity is not optional here, and that is a departure from framing.**
26.96's Python reader takes no buffer size, because a `bytearray` grows and a
limit the language does not need is a limit not worth imposing. A pending
table is different: its bound is not about representation but about refusing
an attacker who opens exchanges and never answers them. That reason is the
same in every language, so the cap is required here as it is in the other
three, and the table raises when it fills.

Beyond that this is the ordinary Python shape -- a dict keyed by the packed
key, and an exception where the others return a code.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.python.emit import py_name
from situc.relation import Read, Refused, Side, key_sides
from situc.resolve import ResolvedSchema

__all__ = ["generate", "refusals"]


def refusals(schema: ast.Schema,
		resolved: ResolvedSchema) -> list[tuple[str, str]]:
	found = []
	for relation in schema.relations():
		try:
			key_sides(relation, resolved)
		except Refused as why:
			found.append((relation.name, str(why)))
	return found


def _key(sides: Side, view: str) -> list[str]:
	lines = ["\t\tkey = 0"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, Read):
				lines.append(f"\t\tkey = (key << {width}) | "
				             f"{source}.{py_name(step.member)}"
				             f"\t# {step.path}")
			else:
				local = f"_{py_name(step.member)}"
				lines.append(f"\t\t{local} = {source}.{py_name(step.member)}")
				source = local
	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	ready = []
	for relation in schema.relations():
		try:
			ready.append((relation, key_sides(relation, resolved)))
		except Refused:
			continue
	if not ready:
		return {}

	lines = [
		f'"""Generated by situc from {basename}.situ -- do not edit.',
		"",
		"Conversations: a pending table per relation. The schema states the",
		"pairing and this holds the set. A separate module -- a rung adds",
		"files rather than changing them (decision 0032).",
		'"""',
		"",
		"from __future__ import annotations",
		"",
		"from situ_runtime import BoundsError, ConstraintError",
		"",
		f"from {basename} import *  # noqa: F403",
		"",
	]

	for relation, (request, response) in ready:
		name = py_name(relation.name)
		first, second = relation.params
		lines += [
			"",
			f"class {name}_table:",
			f'\t"""Pending requests for `{relation.name}`.',
			"",
			"\tThe capacity is required, unlike the framing reader's buffer.",
			"\tA reader's size is about representation and a `bytearray`",
			"\tgrows; a pending table's bound is about refusing somebody who",
			"\topens exchanges and never answers them, which is the same",
			"\tproblem in every language.",
			'\t"""',
			"",
			"\t__slots__ = (\"_cap\", \"_live\")",
			"",
			"\tdef __init__(self, cap: int) -> None:",
			"\t\tself._cap  = cap",
			"\t\tself._live: dict[int, int] = {}",
			"",
			f"\tdef record(self, {first.name}: "
			f"{py_name(first.type_name)}, id: int) -> None:",
			f'\t\t"""Remember `{first.name}`. Raises BoundsError when full."""',
			*_key(request, first.name),
			"",
			"\t\tif key not in self._live and len(self._live) >= self._cap:",
			"\t\t\traise BoundsError(",
			f"\t\t\t\t\"{relation.name}: {{}} exchanges already pending\""
			".format(self._cap),",
			"\t\t\t\tself._cap)",
			"\t\tself._live[key] = id",
			"",
			f"\tdef take(self, {second.name}: "
			f"{py_name(second.type_name)}) -> int:",
			f'\t\t"""The request `{second.name}` answers, forgotten as it is',
			"",
			"\t\treturned. A duplicate or late reply names an exchange that",
			'\t\tis over, and raises ConstraintError."""',
			*_key(response, second.name),
			"",
			"\t\tif key not in self._live:",
			"\t\t\traise ConstraintError(",
			f"\t\t\t\t\"{relation.name}: no exchange is waiting for this\")",
			"\t\treturn self._live.pop(key)",
		]

	return {f"{basename}_converse.py": "\n".join(lines).rstrip("\n") + "\n"}
