"""Derived codec implementations in Python (section 13.4).

The arithmetic is `codegen.kernel_math`'s, shared with the C and Rust
backends, so three languages cannot disagree about what a polynomial
means. What is here is the rendering.

Two families, deliberately. `polynomial` and `ones_complement` are what a
`checksum ... is <codec>` binding can name (0053), and until this existed
that binding was refused outright for Python -- a schema C honoured and
Python could not read. The other five decline with a note, exactly as C
does for a kernel it cannot generate: the properties are still derived and
still correct, and an `extern` impl supplies the code.

One difference from the other two backends, and it is the whole of what
Python changes. A C or Rust register is a machine word that wraps, so the
mask a narrow width needs is arithmetic those backends can skip when the
width fills its word. Python's integers are unbounded: nothing wraps, so
`crc << 8` grows for ever and every width -- 64 included -- is masked.

Each codec emits three entry points, as C does. The plain one is the whole
interface most callers want; the `_holed` one takes the hole a `[self_as]`
checksum needs (14.2); and `_spans` takes two spans, because a checksum may
cover bytes the message does not contain -- UDP's and TCP's pseudo-headers
are summed before the datagram (14.2a). The outer two are calls to `_spans`
with an empty second span and a zero-length hole.

Neither the hole nor the second span is an edited buffer: the hole is a
parameter and the spans are read through one helper that indexes their
concatenation, so nothing here allocates a copy of what it is summing.
"""

from __future__ import annotations

from math import lcm

from situc import ast
from situc.codegen.kernel_math import (crc_register, crc_shift, crc_start,
                                       crc_table, crc_width, number, reverse)
from situc.codegen.python.emit import py_name
from situc import __version__


def _ident(prefix: str, name: str) -> str:
	"""`situ_crc32` in C is `crc32` in a module that is already the schema's.

	Python has modules, so the prefix a C symbol carries to stay out of the
	linker's way is noise here. `py_name` rather than the name itself,
	because a codec called `lambda` is a name situ accepts and `def lambda`
	is not a line Python parses.
	"""
	del prefix
	return py_name(name)


def generate(schema: ast.Schema, basename: str, prefix: str = "situ") -> str:
	"""Emit every derived implementation the schema binds, as Python."""
	# `impls()` and `codecs()` decide everything this emits, and every
	# helper below takes a `CodecDecl`: no struct and no member is read
	# here, so a `parameter` -- an argument the caller supplies (0050) --
	# has no path into the output and needs no refusal.
	bound = {impl.codec for impl in schema.impls()
	         if impl.kind is ast.ImplKind.DERIVED}

	lines = [
		f'"""Generated by situc {__version__} from {basename}.situ'
		' -- do not edit.',
		"",
		"Implementations derived from kernel descriptions (section 13.4).",
		"The properties in the capability map and the code below come from",
		"one description, so they cannot disagree.",
		'"""',
		"",
		"from __future__ import annotations",
	]
	lines.extend(span_byte())
	# Only where a TABLE codec is bound, for the reason Rust's copy gives:
	# emitting it anyway grew every derived module in the corpus by thirty
	# lines nothing in them calls (26.451).
	# ... and an UNPADDED one: the padded base codes accumulate whole bytes and call neither helper, so a base64-only schema was carrying two dead functions (26.452).
	if any(decl.name in bound and decl.kernel is not None
	       and _reads_bits(decl)
	       for decl in schema.codecs()):
		lines.extend(bits_access())

	for decl in schema.codecs():
		if decl.name not in bound or decl.kernel is None:
			continue

		body = _for_kernel(decl, prefix)
		if body is None:
			# Two blank lines and a wrap that survives a long codec name,
			# because this is Python a person reads rather than a note in a
			# language where the line happens to be shorter.
			lines.extend([
				"",
				"",
				f"# No implementation for `{decl.name}`:",
				f"# a {decl.kernel.family.value} kernel is described but not"
				" yet generated in",
				"# Python. Its properties are derived and correct; bind an",
				f"# `impl {decl.name} extern \"...\"` to supply the code.",
			])
			continue

		lines.extend(body)

	return "\n".join(lines) + "\n"


def bits_access() -> list[str]:
	"""MSB-first bit access, which a symbol map needs and a CRC does not.

	A table code's symbols are not byte-aligned -- 4b5b is five bits out
	for four in -- so encoding walks bits rather than bytes. C keeps these
	in its runtime; a generated Python module has none to reach into, so
	they are emitted here once, for the reason `span_byte` gives.

	MSB-first because that is the order a line code is transmitted in and
	the order C's runtime uses. A decoder agreeing on the table and
	disagreeing on the bit order yields a plausible stream that is not the
	one sent, which nothing downstream can see.
	"""
	return [
		"",
		"",
		"def _bits_get_msb(data: bytes, at: int, width: int) -> int:",
		'\t"""`width` bits starting at bit `at`, most significant first."""',
		"\tvalue = 0",
		"",
		"\tfor i in range(width):",
		"\t\tbit  = at + i",
		"\t\tbyte = data[bit // 8] if bit // 8 < len(data) else 0",
		"\t\tvalue = (value << 1) | ((byte >> (7 - bit % 8)) & 1)",
		"",
		"\treturn value",
		"",
		"",
		"def _bits_set_msb(out: bytearray, at: int, width: int,",
		"\t\tvalue: int) -> None:",
		'\t"""Write `width` bits of `value` at bit `at`, most significant',
		'\tfirst."""',
		"\tfor i in range(width):",
		"\t\tbit = at + i",
		"",
		"\t\tif bit // 8 >= len(out):",
		"\t\t\treturn",
		"",
		"\t\tmask = 1 << (7 - bit % 8)",
		"",
		"\t\tif (value >> (width - 1 - i)) & 1:",
		"\t\t\tout[bit // 8] |= mask",
		"\t\telse:",
		"\t\t\tout[bit // 8] &= ~mask & 0xFF",
	]


def _smtp_dot(decl: ast.CodecDecl, prefix: str) -> list[str]:
	"""RFC 5321 section 4.5.2, with C's two deliberate departures kept.

	A line end is tested as LF ALONE, which is what keeps this a stream:
	a CR ending one call and an LF starting the next would otherwise be
	missed. And the decoder strips a leading period unconditionally where
	the RFC strips it only when other characters follow -- a line of
	exactly `.` is the terminator and the framing scan stops before it,
	so it never arrives here. Both are preconditions, not liberties.
	"""
	name = _ident(prefix, decl.name)

	return [
		"",
		"",
		f"#: `{decl.name}`: SMTP dot-stuffing, RFC 5321 section 4.5.2. A",
		"#: period at the start of a line is doubled. The terminator is",
		"#: neither written nor consumed here.",
		f"def {name}_encode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		"\twritten = 0",
		"\t# The body starts at the start of a line.",
		"\tat_line_start = True",
		"",
		"\tfor read in range(length):",
		"\t\tif at_line_start and data[read] == 0x2E:",
		"\t\t\tout[written] = 0x2E",
		"\t\t\twritten += 1",
		"",
		"\t\tout[written] = data[read]",
		"\t\twritten += 1",
		"\t\tat_line_start = data[read] == 0x0A",
		"",
		"\treturn written",
		"",
		"",
		f"def {name}_decode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		'\t"""The inverse."""',
		"\twritten = 0",
		"\tat_line_start = True",
		"",
		"\tfor read in range(length):",
		"\t\tif at_line_start and data[read] == 0x2E:",
		"\t\t\t# Drop the added one and keep what follows.",
		"\t\t\tat_line_start = False",
		"\t\t\tcontinue",
		"",
		"\t\tout[written] = data[read]",
		"\t\twritten += 1",
		"\t\tat_line_start = data[read] == 0x0A",
		"",
		"\treturn written",
	]


def _linear_block(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""Hamming(7,4): a nibble in, a byte out.

	Unlike every other family here it is not `(in, len, out)` -- it is a
	symbol map with a correction step. Python returns the corrected flag
	in a tuple where C takes an out-parameter.

	Single-error CORRECTING, not detecting: the syndrome's "no error"
	entry is unreachable from the error branch, so a double-bit error is
	miscorrected and still reports True. d_min is 3, so that is the code
	behaving as it must, and the flag means "the syndrome was nonzero".
	"""
	from situc.codegen.c.derived import (DERIVED_LINEAR, _HAMMING_PARITY,
	                                     _named_code)

	if _named_code(decl) not in DERIVED_LINEAR:
		return None

	name = _ident(prefix, decl.name)

	syndrome = [7] * 8
	for position in range(7):
		codeword = 1 << position
		value = 0
		for row, mask in enumerate(_HAMMING_PARITY):
			parity = bin((codeword & 0xF) & mask).count("1") & 1
			parity ^= (codeword >> (4 + row)) & 1
			value |= parity << row
		syndrome[value] = position

	table = []
	for nibble in range(16):
		word = nibble
		for row, mask in enumerate(_HAMMING_PARITY):
			word |= (bin(nibble & mask).count("1") & 1) << (4 + row)
		table.append(word)

	masks = ", ".join(f"0x{mask:02X}" for mask in _HAMMING_PARITY)

	return [
		"",
		"",
		f"#: `{decl.name}`: Hamming(7,4), systematic. The low nibble of a",
		"#: codeword is the data; the three high bits are parity.",
		f"{name.upper()}_ENCODE_TABLE = (",
		"\t" + ", ".join(f"0x{value:02X}" for value in table) + ",",
		")",
		"",
		"#: Syndrome to the bit it accuses; 7 means no error.",
		f"{name.upper()}_SYNDROME = ("
		+ ", ".join(str(value) for value in syndrome) + ",)",
		"",
		f"_MASKS_{name.upper()} = ({masks},)",
		"",
		"",
		f"def {name}_encode(nibble: int) -> int:",
		f"\treturn {name.upper()}_ENCODE_TABLE[nibble & 0x0F]",
		"",
		"",
		f"def {name}_decode(codeword: int) -> tuple[int, bool]:",
		'\t"""The nibble, and whether a bit was corrected.',
		"",
		"\tA DOUBLE error is miscorrected and still reports True: d_min is",
		"\t3, so this code corrects one bit and cannot report `detected",
		'\tbut not correctable`."""',
		"\tvalue = codeword & 0x7F",
		"\tcheck = 0",
		"",
		"\tfor row in range(3):",
		f"\t\tbits   = value & _MASKS_{name.upper()}[row]",
		"\t\tparity = 0",
		"",
		"\t\twhile bits:",
		"\t\t\tparity ^= bits & 1",
		"\t\t\tbits  >>= 1",
		"",
		"\t\tparity ^= (value >> (4 + row)) & 1",
		"\t\tcheck  |= parity << row",
		"",
		"\tif check == 0:",
		"\t\treturn value & 0x0F, False",
		"",
		f"\tat = {name.upper()}_SYNDROME[check]",
		"",
		"\tif at < 7:",
		"\t\tvalue ^= 1 << at",
		"",
		"\treturn value & 0x0F, True",
	]


def _permutation(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""A block interleaver: written row-major, read column-major.

	`rows` is the discriminator -- a permutation declared only by extent
	has a span and no mapping, so the properties follow and the code
	cannot. A partial block is REFUSED rather than padded, and 0 is also
	the answer for an empty input, so a caller cannot tell those apart.
	C's behaviour, kept.
	"""
	kernel = decl.kernel
	assert kernel is not None

	if kernel.argument("rows") is None:
		return None

	rows    = number(decl, "rows")
	columns = number(decl, "columns")
	block   = rows * columns
	name    = _ident(prefix, decl.name)

	def loop(target: str, source: str) -> list[str]:
		return [
			f"\t\tfor row in range({rows}):",
			f"\t\t\tfor column in range({columns}):",
			f"\t\t\t\tout[at + {target}] = data[at + {source}]",
		]

	forward = f"column * {rows} + row", f"row * {columns} + column"

	return [
		"",
		"",
		f"#: `{decl.name}`: a {rows}x{columns} block interleaver, written",
		"#: row-major and read column-major. Length-preserving, and the",
		"#: input must be a whole number of blocks.",
		f"{name.upper()}_BLOCK = {block}",
		"",
		"",
		f"def {name}_encode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		"\t# Whole blocks only: a partial one has no defined permutation.",
		f"\tif length % {block} != 0:",
		"\t\treturn 0",
		"",
		f"\tfor at in range(0, length, {block}):",
		*loop(*forward),
		"",
		"\treturn length",
		"",
		"",
		f"def {name}_decode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		'\t"""The same loop with the two index expressions swapped.',
		"",
		"\tAt 4x4 that is the SAME permutation -- a square interleaver is",
		"\tits own inverse -- so a round trip cannot tell this from",
		'\t`encode`, and only a non-square case can."""',
		f"\tif length % {block} != 0:",
		"\t\treturn 0",
		"",
		f"\tfor at in range(0, length, {block}):",
		*loop(forward[1], forward[0]),
		"",
		"\treturn length",
	]


def _reads_bits(decl: ast.CodecDecl) -> bool:
	"""Whether this codec's body calls the MSB bit helpers.

	An UNPADDED table code walks bits, and so does bit stuffing. The
	padded base codes accumulate whole bytes and call neither, which is
	why the question is asked per codec rather than per family -- a
	base64-only module carrying two dead helpers is a diff its reader
	has to explain (26.452).
	"""
	from situc.codegen.c.derived import BIT_STUFFING, _named_code

	kernel = decl.kernel
	if kernel is None:
		return False
	if kernel.family is ast.KernelFamily.TABLE:
		return not isinstance(kernel.argument("pad"), ast.IntLiteral)
	if kernel.family is ast.KernelFamily.STUFFING:
		return _named_code(decl) in BIT_STUFFING
	return False


def _bit_stuffing(decl: ast.CodecDecl, prefix: str,
		code: str) -> list[str]:
	"""HDLC and USB bit stuffing: a zero after `run` contiguous ones.

	Lengths are in BITS in both directions, not bytes, and the bit order
	is MSB-first and hardcoded -- the codec consumes a bit stream and
	does not consult the schema's bit order. Both standards TRANSMIT
	octets least-significant-bit first, so a vector taken from a real
	capture needs each byte reversed on one side; a vector written as a
	bit string does not.

	Re-spelled from C including two behaviours a port could reasonably
	get wrong. Truncation is NOT an error: an input ending exactly where
	the stuffed bit belongs simply ends. And the decoder's only failure
	is 0, which is also the answer for empty input, so the two are
	indistinguishable -- C's, kept, because a differential compares them.
	"""
	from situc.codegen.c.derived import BIT_STUFFING

	run = BIT_STUFFING[code][0]
	name = _ident(prefix, decl.name)

	return [
		"",
		"",
		f"#: `{decl.name}`: a zero after {run} contiguous ones, so"
		f" {run + 1} cannot",
		"#: appear in the body. Lengths are in BITS and so is the return.",
		f"def {name}_encode(data: bytes, bits: int,"
		" out: bytearray) -> int:",
		f'\t"""`out` needs bits + bits // {run} + 1 bits, and is',
		"\tread-modify-written: bits past the end of the last byte keep",
		'\twhatever the caller left there."""',
		"\twritten = 0",
		"\tones    = 0",
		"",
		"\tfor at in range(bits):",
		"\t\tbit = _bits_get_msb(data, at, 1)",
		"",
		"\t\t_bits_set_msb(out, written, 1, bit)",
		"\t\twritten += 1",
		"",
		"\t\tif bit:",
		"\t\t\tones += 1",
		"",
		f"\t\t\tif ones == {run}:",
		"\t\t\t\t_bits_set_msb(out, written, 1, 0)",
		"\t\t\t\twritten += 1",
		"\t\t\t\tones = 0",
		"\t\telse:",
		"\t\t\tones = 0",
		"",
		"\treturn written",
		"",
		"",
		f"def {name}_decode(data: bytes, bits: int,"
		" out: bytearray) -> int:",
		f'\t"""Returns 0 where {run + 1} contiguous ones appear, which the',
		"\tencoder cannot produce -- and 0 is also the answer for empty",
		'\tinput, so a caller cannot tell those apart."""',
		"\twritten = 0",
		"\tones    = 0",
		"",
		"\tfor at in range(bits):",
		"\t\tbit = _bits_get_msb(data, at, 1)",
		"",
		f"\t\tif ones == {run}:",
		"\t\t\t# A stuffed zero, which the encoder put there.",
		"\t\t\tones = 0",
		"",
		"\t\t\tif bit:",
		"\t\t\t\treturn 0",
		"",
		"\t\t\tcontinue",
		"",
		"\t\t_bits_set_msb(out, written, 1, bit)",
		"\t\twritten += 1",
		"\t\tones = ones + 1 if bit else 0",
		"",
		"\treturn written",
	]


def _stuffing(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""COBS and the escape-stuffed byte codes (SLIP, PPP async).

	Bit stuffing and SMTP dot-stuffing are still declined: they are the
	other two shapes in this family and are their own tranche.

	Re-spelled from C, including its reasons -- COBS flushes a full group
	only when more input follows, because opening one at the very end
	would spend a second overhead byte, which is the one thing COBS
	promises not to do; and PPP's escape is a transformation rather than
	a table, so its decoder reverses escapes this generator never
	enumerated, which a peer with a non-zero ACCM will send.
	"""
	from situc.codegen.c.derived import ESCAPE_STUFFING, _named_code

	code = _named_code(decl)
	name = _ident(prefix, decl.name)

	if code == "cobs":
		return [
			"",
			"",
			f"#: `{decl.name}`: COBS (Cheshire and Baker). A zero byte",
			"#: becomes a pointer to the next one, so no zero survives in the",
			"#: body and a zero can delimit the frame.",
			f"def {name}_encode(data: bytes, length: int,"
			" out: bytearray) -> int:",
			'\t"""`out` needs length + length // 254 + 2 bytes."""',
			"\tcode_at = 0",
			"\twritten = 1",
			"\tcode    = 1",
			"",
			"\tfor read in range(length):",
			"\t\tif data[read] != 0:",
			"\t\t\tout[written] = data[read]",
			"\t\t\twritten += 1",
			"\t\t\tcode    += 1",
			"",
			"\t\t\t# A full group is flushed only when more input follows:",
			"\t\t\t# at the very end there is nothing for a new group to",
			"\t\t\t# hold, and opening one would spend a second overhead",
			"\t\t\t# byte, which COBS promises not to do.",
			"\t\t\tif code != 0xFF or read + 1 >= length:",
			"\t\t\t\tcontinue",
			"",
			"\t\tout[code_at] = code",
			"\t\tcode_at = written",
			"\t\twritten += 1",
			"\t\tcode     = 1",
			"",
			"\tout[code_at] = code",
			"\tout[written] = 0            # the delimiter",
			"\treturn written + 1",
			"",
			"",
			f"def {name}_decode(data: bytes, length: int,"
			" out: bytearray) -> int:",
			"\tread    = 0",
			"\twritten = 0",
			"",
			"\twhile read < length:",
			"\t\tcode = data[read]",
			"",
			"\t\tif code == 0:",
			"\t\t\tbreak               # the delimiter ends the frame",
			"",
			"\t\tread += 1",
			"",
			"\t\tfor _ in range(1, code):",
			"\t\t\tif read >= length:",
			"\t\t\t\treturn 0        # truncated: a code ran past the end",
			"",
			"\t\t\tout[written] = data[read]",
			"\t\t\twritten += 1",
			"\t\t\tread    += 1",
			"",
			"\t\tif code != 0xFF and read < length and data[read] != 0:",
			"\t\t\tout[written] = 0",
			"\t\t\twritten += 1",
			"",
			"\treturn written",
		]

	from situc.codegen.c.derived import BIT_STUFFING

	if code in BIT_STUFFING:
		return _bit_stuffing(decl, prefix, code)

	if code == "smtp_dot":
		return _smtp_dot(decl, prefix)

	if code not in ESCAPE_STUFFING:
		return None

	title, delim, esc, xor, pairs = ESCAPE_STUFFING[code]
	table = ", ".join(f"0x{literal:02X}: 0x{escaped:02X}"
	                  for literal, escaped in pairs)
	back  = ", ".join(f"0x{escaped:02X}: 0x{literal:02X}"
	                  for literal, escaped in pairs)

	if xor is None:
		undo = ["\t\tif data[read] not in _BACK_" + name.upper() + ":",
		        "\t\t\t# An escape this code does not define. Refusing",
		        "\t\t\t# beats inventing a byte: the frame is not what",
		        "\t\t\t# it claims.",
		        "\t\t\treturn 0",
		        "",
		        f"\t\tout[written] = _BACK_{name.upper()}[data[read]]"]
		tables = [f"_BACK_{name.upper()} = {{{back}}}", ""]
	else:
		undo = [f"\t\t# RFC 1662: an escaped byte is the original",
		        f"\t\t# exclusive-ored with 0x{xor:02X}, so undoing it is",
		        "\t\t# the same operation again -- which reverses escapes",
		        "\t\t# this generator never enumerated, as a peer with a",
		        "\t\t# non-zero ACCM will send.",
		        f"\t\tout[written] = data[read] ^ 0x{xor:02X}"]
		tables = []

	return [
		"",
		"",
		f"#: `{decl.name}`: {title}. A payload byte equal to the delimiter",
		f"#: (0x{delim:02X}) or the escape (0x{esc:02X}) is sent as the escape",
		"#: followed by a substitute.",
		f"_ESCAPE_{name.upper()} = {{{table}}}",
		*tables,
		"",
		f"def {name}_encode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		'\t"""`out` needs 2 * length + 1 bytes."""',
		"\twritten = 0",
		"",
		"\tfor read in range(length):",
		f"\t\tswap = _ESCAPE_{name.upper()}.get(data[read])",
		"",
		"\t\tif swap is None:",
		"\t\t\tout[written] = data[read]",
		"\t\t\twritten += 1",
		"\t\t\tcontinue",
		"",
		f"\t\tout[written]     = 0x{esc:02X}",
		"\t\tout[written + 1] = swap",
		"\t\twritten += 2",
		"",
		f"\tout[written] = 0x{delim:02X}       # the frame delimiter",
		"\treturn written + 1",
		"",
		"",
		f"def {name}_decode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		'\t"""The inverse, stopping at the delimiter."""',
		"\tread    = 0",
		"\twritten = 0",
		"",
		"\twhile read < length:",
		"\t\tbyte  = data[read]",
		"\t\tread += 1",
		"",
		f"\t\tif byte == 0x{delim:02X}:",
		"\t\t\tbreak               # the delimiter ends the frame",
		"",
		f"\t\tif byte != 0x{esc:02X}:",
		"\t\t\tout[written] = byte",
		"\t\t\twritten += 1",
		"\t\t\tcontinue",
		"",
		"\t\tif read >= length:",
		"\t\t\treturn 0            # truncated: an escape ended the input",
		"",
		*undo,
		"\t\twritten += 1",
		"\t\tread    += 1",
		"",
		"\treturn written",
	]


def _shift_register(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""An LFSR, additive or multiplicative depending on the feedback.

	Re-spelled from C's `_shift_register`, which is where the width
	handling and the complement rule are argued. Python has no fixed word,
	so the mask that C gets from its type is written out at every shift.
	"""
	kernel = decl.kernel
	assert kernel is not None

	taps  = number(decl, "taps")
	width = number(decl, "width", 16)
	seed  = number(decl, "seed", (1 << width) - 1)

	if not taps or not 1 <= width <= 64:
		return None

	source       = kernel.argument("feedback")
	additive     = isinstance(source, ast.NameRef) and source.name == "input"
	complemented = kernel.flag("complement_feedback")
	name         = _ident(prefix, decl.name)
	mask         = (1 << width) - 1

	feedback = f"_parity_{name}(state & 0x{taps:X})"
	if complemented:
		feedback = f"({feedback} ^ 1)"

	head = [
		"",
		"",
		f"#: `{decl.name}`: a {width}-bit LFSR, taps 0x{taps:X}, seed"
		f" 0x{seed:X}.",
		("#: Additive: the register runs on its own state, startable"
		 " anywhere"
		 if additive else
		 "#: Multiplicative: the register is fed from the scrambled"
		 " output, so"),
		("#: and its own inverse." if additive else
		 "#: a receiver synchronises without being told the state."),
	]

	if additive:
		return head + [
			"",
			f"def _step_{name}(state: int) -> int:",
			"	bit  = state & 1",
			"	next_state = state >> 1",
			"",
			"	if bit:",
			f"		next_state ^= 0x{taps:X}",
			"",
			"	return next_state",
			"",
			"",
			f"def {name}_encode(data: bytes, length: int,"
			" out: bytearray) -> int:",
			f"	state = 0x{seed:X}",
			"",
			"	for at in range(length):",
			"		key = 0",
			"",
			"		for bit in range(8):",
			"			key |= (state & 1) << bit",
			f"			state = _step_{name}(state)",
			"",
			"		out[at] = data[at] ^ key",
			"",
			"	return length",
			"",
			"",
			f"def {name}_decode(data: bytes, length: int,"
			" out: bytearray) -> int:",
			'	"""Its own inverse: the keystream does not depend on the',
			'	data."""',
			f"	return {name}_encode(data, length, out)",
		]

	return head + [
		"",
		f"def _parity_{name}(value: int) -> int:",
		"	bits = 0",
		"",
		"	while value:",
		"		bits ^= value & 1",
		"		value >>= 1",
		"",
		"	return bits",
		"",
		"",
		f"def {name}_encode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		f"	state = 0x{seed:X}",
		"",
		"	for at in range(length):",
		"		coded = 0",
		"",
		"		for bit in range(8):",
		"			plain  = (data[at] >> bit) & 1",
		f"			output = plain ^ {feedback}",
		"",
		"			coded |= output << bit",
		"			# The scrambled bit goes into the register: that is what",
		"			# makes a receiver self-synchronising.",
		f"			state  = ((state << 1) | output) & 0x{mask:X}",
		"",
		"		out[at] = coded",
		"",
		"	return length",
		"",
		"",
		f"def {name}_decode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		'	"""Not its own inverse: the register is fed from the scrambled',
		'	side, so decoding shifts in what it received."""',
		f"	state = 0x{seed:X}",
		"",
		"	for at in range(length):",
		"		plain = 0",
		"",
		"		for bit in range(8):",
		"			coded  = (data[at] >> bit) & 1",
		"",
		f"			plain |= (coded ^ {feedback}) << bit",
		f"			state  = ((state << 1) | coded) & 0x{mask:X}",
		"",
		"		out[at] = plain",
		"",
		"	return length",
	]


def _padded_table(decl: ast.CodecDecl, prefix: str, inputs: int,
		outputs: int, mapping: list[int], pad: int) -> list[str] | None:
	"""A base-N code: whole groups, with a partial one filled out.

	base32 and base64, re-spelled from C's `_padded_table`: same group
	size, same fill rule, same reverse table. C's note is worth repeating
	because it says what the tests must cover -- an encoder wrong only for
	inputs of length 3n+1 looks right in casual testing.
	"""
	if outputs != 8 or inputs >= 8:
		return None

	name       = _ident(prefix, decl.name)
	group_bits = lcm(8, inputs)
	group_in   = group_bits // 8
	symbols    = group_bits // inputs
	mask       = (1 << inputs) - 1

	reverse = [0xFF] * 256
	for symbol, value in enumerate(mapping):
		reverse[value] = symbol

	return [
		"",
		"",
		f"#: `{decl.name}`: RFC 4648 base{1 << inputs}. {group_in} input",
		f"#: bytes make {symbols} output bytes; a shorter final group is",
		f"#: filled with 0x{pad:02X}.",
		f"{name.upper()}_ALPHABET = bytes((",
		"\t" + ", ".join(f"0x{value:02X}" for value in mapping) + ",",
		"))",
		"",
		"#: Symbol for each byte, 0xFF where it is not in the alphabet.",
		f"{name.upper()}_SYMBOL = bytes((",
		"\t" + ", ".join(f"0x{value:02X}" for value in reverse) + ",",
		"))",
		"",
		"",
		f"def {name}_encode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		'\t"""Encode `length` bytes into `out`, padding the final group."""',
		"\twritten = 0",
		"\tstart   = 0",
		"",
		"\twhile start < length:",
		f"\t\thave = min(length - start, {group_in})",
		"\t\tacc  = 0",
		"",
		f"\t\tfor i in range({group_in}):",
		"\t\t\tacc = (acc << 8) | (data[start + i] if i < have else 0)",
		"",
		"\t\t# Symbols that carry data; the rest are padding.",
		f"\t\tfull = (have * 8 + {inputs - 1}) // {inputs}",
		"",
		f"\t\tfor i in range({symbols}):",
		f"\t\t\tshift = {group_bits} - {inputs} * (i + 1)",
		"",
		"\t\t\tout[written + i] = (",
		f"\t\t\t\t{name.upper()}_ALPHABET[(acc >> shift)"
		f" & 0x{mask:02X}]",
		f"\t\t\t\tif i < full else 0x{pad:02X})",
		"",
		f"\t\twritten += {symbols}",
		f"\t\tstart   += {group_in}",
		"",
		"\treturn written",
		"",
		"",
		f"def {name}_decode(data: bytes, length: int,"
		" out: bytearray) -> int:",
		'\t"""Returns the number of bytes decoded, or 0 for input that is',
		"\tnot a whole number of groups or carries a byte outside the",
		'\talphabet."""',
		"\twritten = 0",
		"\tstart   = 0",
		"",
		f"\tif length % {symbols} != 0:",
		"\t\treturn 0",
		"",
		"\twhile start < length:",
		"\t\tacc  = 0",
		"\t\tkept = 0",
		"",
		f"\t\twhile kept < {symbols}"
		f" and data[start + kept] != 0x{pad:02X}:",
		"\t\t\tkept += 1",
		"",
		f"\t\tfor i in range({symbols}):",
		"\t\t\tsymbol = 0",
		"",
		"\t\t\tif i < kept:",
		f"\t\t\t\tsymbol = {name.upper()}_SYMBOL[data[start + i]]",
		"",
		"\t\t\t\tif symbol == 0xFF:",
		"\t\t\t\t\treturn 0",
		"",
		f"\t\t\tacc = (acc << {inputs}) | symbol",
		"",
		f"\t\tnbytes = kept * {inputs} // 8",
		"",
		"\t\tfor i in range(nbytes):",
		f"\t\t\tshift = {group_bits} - 8 * (i + 1)",
		"",
		"\t\t\tout[written + i] = (acc >> shift) & 0xFF",
		"",
		"\t\twritten += nbytes",
		f"\t\tstart   += {symbols}",
		"",
		"\treturn written",
	]


def _table(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""A symbol map, encoded and decoded a symbol at a time.

	The derivation is `c.derived._symbol_map` and `NAMED_CODES`, imported
	rather than repeated: 0017's amendment says a second backend re-spells
	and does not re-derive, and a second copy of the 4b5b table is a second
	table to be wrong. Only the spelling below is Python's.

	A PADDED code is declined, as C declines it from this path into one of
	its own: the last group's symbol count depends on how much input was
	left, which symbol-at-a-time cannot express. base32 and base64 are that
	shape; base16 is not, and is generated.
	"""
	from situc.codegen.c.derived import _symbol_map

	kernel = decl.kernel
	assert kernel is not None

	inputs  = number(decl, "input_bits")
	outputs = number(decl, "output_bits")
	mapping = _symbol_map(decl, inputs, outputs)

	if mapping is None or inputs > 8 or outputs > 16:
		return None
	pad = kernel.argument("pad")
	if isinstance(pad, ast.IntLiteral):
		return _padded_table(decl, prefix, inputs, outputs, mapping,
		                     pad.value)

	name  = _ident(prefix, decl.name)
	size  = 1 << inputs
	whole = ([f"\tif bits % {inputs} != 0:", "\t\treturn 0", ""]
	         if inputs > 1 else [])

	return [
		"",
		"",
		f"#: `{decl.name}`: {inputs} bits in, {outputs} bits out, ratio"
		f" {outputs}:{inputs}.",
		"#: The ratio is exact, so an output position is a linear function",
		"#: of an input one.",
		f"{name.upper()}_ENCODE_TABLE = (",
		"\t" + ", ".join(f"0x{mapping[symbol]:X}" for symbol in range(size))
		+ ",",
		")",
		"",
		"",
		f"def {name}_encode(data: bytes, bits: int,"
		" out: bytearray) -> int:",
		f'\t"""Encode `bits` input bits into `out`. Returns the output bits',
		f"\twritten, exactly bits * {outputs} // {inputs}"
		+ ('" ""' if False else ""),
		*(["\t-- or 0 if `bits` is not a whole number of symbols, which has",
		   '\tno encoding the way a partial block has none."""']
		  if inputs > 1 else ['\t."""']),
		"\twritten = 0",
		"\tat      = 0",
		"",
		*whole,
		f"\twhile at + {inputs} <= bits:",
		f"\t\tsymbol = _bits_get_msb(data, at, {inputs})",
		"",
		f"\t\t_bits_set_msb(out, written, {outputs},",
		f"\t\t\t{name.upper()}_ENCODE_TABLE[symbol])",
		f"\t\twritten += {outputs}",
		f"\t\tat      += {inputs}",
		"",
		"\treturn written",
		"",
		"",
		f"def {name}_decode(data: bytes, bits: int,"
		" out: bytearray) -> int:",
		'\t"""Decode. Returns the input bits recovered, or 0 on a symbol the',
		"\tcode does not define, or on a length that is not a whole number of",
		"\tsymbols -- both are a corrupted stream rather than a decodable one,",
		'\tand neither is something to decode part of."""',
		"\twritten = 0",
		"\tat      = 0",
		"",
		f"\tif bits % {outputs} != 0:",
		"\t\treturn 0",
		"",
		f"\twhile at + {outputs} <= bits:",
		f"\t\tcode  = _bits_get_msb(data, at, {outputs})",
		"\t\tfound = False",
		"",
		f"\t\tfor symbol in range({size}):",
		f"\t\t\tif {name.upper()}_ENCODE_TABLE[symbol] == code:",
		f"\t\t\t\t_bits_set_msb(out, written, {inputs}, symbol)",
		f"\t\t\t\twritten += {inputs}",
		"\t\t\t\tfound = True",
		"\t\t\t\tbreak",
		"",
		"\t\tif not found:",
		"\t\t\treturn 0",
		"",
		f"\t\tat += {outputs}",
		"",
		"\treturn written",
	]


def span_byte() -> list[str]:
	"""The module-level helper every `_spans` entry point reads through.

	C's `situ_span_byte`, in Python and with the same reasoning. Both
	families route every byte read through it, so there is one place that
	knows what a hole is rather than two that agree.

	Two spans rather than one, and `index` walks their concatenation: a
	checksum may cover bytes the message does not contain, which is what
	`prefix(...)` says (14.2a). Reading through the helper is what keeps
	that free -- `a + b` would be a copy of both, and the no-copy property
	is the point rather than a nicety.

	Public, and not folded into `generate`, because `generate` is not the
	only caller. The single-file backend asks `_for_kernel` for one codec
	at a time and never calls `generate` at all, so it emits this itself --
	and a second copy of the idea in `emit.py` is exactly the shape that
	drifts.
	"""
	return [
		"",
		"",
		"# A checksum that covers its own field runs the algorithm with",
		"# those bytes taken as a constant (14.2, `[self_as]`). The bytes",
		"# are still there and generated code never allocates a copy, so",
		"# the hole is a parameter rather than an edited buffer: every",
		"# `_spans` entry point below reads through this, and the simpler",
		"# ones pass a zero-length hole.",
		"#",
		"# Two spans rather than one, because a checksum may cover bytes",
		"# the message does not contain: UDP's and TCP's pseudo-headers",
		"# are built by the caller and summed before the datagram (14.2a).",
		"# `index` walks the concatenation, so the hole is measured against",
		"# it -- and the two are never joined, which is what makes summing",
		"# a pseudo-header cost no copy of the datagram.",
		# One line, however long: a continuation aligned under an open paren
		# at column zero is leading spaces with no tab in front, which the
		# generated-source convention gate reads as space indentation --
		# correctly, since there is no indentation for it to align against.
		"def _span_byte(a: bytes, b: bytes, index: int, hole_at: int,"
		" hole_len: int, fill: int) -> int:",
		"\tif hole_at <= index < hole_at + hole_len:",
		"\t\treturn fill",
		"\treturn a[index] if index < len(a) else b[index - len(a)]",
	]


def _for_kernel(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	kernel = decl.kernel
	assert kernel is not None

	if kernel.family is ast.KernelFamily.POLYNOMIAL:
		# A polynomial over an extension field is Reed-Solomon, which is a
		# different code and not one of the two this backend generates.
		if kernel.argument("field") is not None:
			return None
		return _polynomial(decl, prefix)
	if kernel.family is ast.KernelFamily.ONES_COMPLEMENT:
		return _ones_complement(decl, prefix)
	if kernel.family is ast.KernelFamily.TABLE:
		return _table(decl, prefix)
	if kernel.family is ast.KernelFamily.SHIFT:
		return _shift_register(decl, prefix)
	if kernel.family is ast.KernelFamily.STUFFING:
		return _stuffing(decl, prefix)
	if kernel.family is ast.KernelFamily.LINEAR:
		return _linear_block(decl, prefix)
	if kernel.family is ast.KernelFamily.PERMUTATION:
		return _permutation(decl, prefix)

	# No fallthrough: the branches above are every member of
	# `KernelFamily`, which mypy proved by calling a trailing
	# `return None` unreachable. This backend now DISPATCHES every
	# family C does -- the declines that remain are inside the handlers
	# (Reed-Solomon in `_polynomial`, an unnamed linear or permutation
	# code) rather than a family nobody wrote. A family added later
	# falls off the end and declines, which is the same answer the
	# unreachable line gave.


def _polynomial(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""A table-driven CRC, with the table computed rather than copied."""
	width = crc_width(decl)
	if width is None:
		return None

	poly = number(decl, "poly")
	if not poly:
		return None

	kernel = decl.kernel
	assert kernel is not None
	reflect = kernel.flag("reflect")
	init    = number(decl, "init")
	xorout  = number(decl, "xorout")

	table  = crc_table(width, poly, reflect)
	name   = _ident(prefix, decl.name)
	mask   = (1 << width) - 1
	digits = width // 4
	# A left-aligned register is a byte wide whatever the code's width, so
	# its table entries and its initial value are written in the REGISTER's
	# digits rather than the code's: `crc7_mmc`'s table holds 8-bit values
	# and `width // 4` would print them one digit short (26.369).
	shift  = crc_shift(width, reflect)
	holds  = crc_register(width, reflect) // 4

	# The table is module-private and underscored, which keeps it out of a
	# `from <module> import *` as well as saying so: the function is the
	# interface and the table is how it happens to be implemented.
	label = f"_{name.upper()}_TABLE"

	lines = [
		"",
		"",
		f"# {decl.name}: width={width} poly=0x{poly:0{digits}X} "
		f"init=0x{init:0{digits}X}",
		f"# xorout=0x{xorout:0{digits}X} "
		f"reflect={'yes' if reflect else 'no'}",
		"#",
		"# Computed from the polynomial, not copied from one.",
		f"{label}: list[int] = [",
	]
	for row in range(0, 256, 4):
		entries = ", ".join(f"0x{table[row + column]:0{holds}X}"
		                    for column in range(4))
		lines.append(f"\t{entries},")
	lines.append("]")

	started = crc_start(init, width, reflect)
	article = "an" if width == 8 else "a"
	lines.extend([
		"",
		"",
		f"def {name}(data: bytes) -> int:",
		f'\t"""The {decl.name} of `data`, as {article} {width}-bit integer."""',
		f"\treturn {name}_holed(data, 0, 0, 0)",
		"",
		"",
		f"def {name}_holed(data: bytes, hole_at: int, hole_len: int,"
		f" fill: int) -> int:",
		f'\t"""The {decl.name} of `data`, with a hole read as `fill`.',
		"",
		"\tThe `hole_len` bytes at `hole_at` read as `fill` rather than as",
		"\twhat is there, which is what a checksum covering its own field",
		"\tneeds (14.2). No copy is made: the hole is a parameter, so a",
		"\tcaller holding a read-only view sums it without allocating one.",
		'\t"""',
		f"\treturn {name}_spans(data, b\"\", hole_at, hole_len, fill)",
		"",
		"",
		f"def {name}_spans(a: bytes, b: bytes, hole_at: int, hole_len: int,"
		f" fill: int) -> int:",
		f'\t"""The {decl.name} of `a` followed by `b`, with a hole in it.',
		"",
		"\tTwo spans because a checksum may cover bytes the message does",
		"\tnot contain -- a pseudo-header, which the caller builds and this",
		"\truns over first (14.2a). `hole_at` is measured against the two",
		"\ttaken together, and neither is copied.",
		'\t"""',
		f"\tcrc = 0x{started:0{holds}X}",
		"",
		"\tfor index in range(len(a) + len(b)):",
		"\t\tbyte = _span_byte(a, b, index, hole_at, hole_len, fill)",
	])

	# Every branch masks, including the widest. A Python integer does not
	# wrap, so the mask is not the narrow-width correction it is in C and
	# Rust -- it is the machine word those two get for free.
	if reflect:
		lines.append(f"\t\tcrc = ({label}[(crc ^ byte) & 0xFF]"
		             f" ^ (crc >> 8)) & 0x{mask:X}")
	elif width == 8 or shift:
		# The index is already a byte and the table holds bytes, so this one
		# cannot leave the width even without a mask. A left-aligned register
		# runs the identical loop, which is the whole point of aligning it.
		lines.append(f"\t\tcrc = {label}[crc ^ byte]")
	else:
		lines.append(f"\t\tcrc = ({label}[((crc >> {width - 8}) ^ byte) & 0xFF]"
		             f" ^ (crc << 8)) & 0x{mask:X}")

	# And back down to the code's own width before the final xor, which the
	# catalogue's value is written in.
	held = f"(crc >> {shift})" if shift else "crc"
	lines.extend([
		"",
		f"\treturn ({held} ^ 0x{xorout:0{digits}X}) & 0x{mask:X}",
	])
	lines.extend(_polynomial_bits(decl, name, width, poly, init, xorout,
	                              reflect, digits))
	return lines


def _polynomial_bits(decl: ast.CodecDecl, name: str, width: int, poly: int,
		init: int, xorout: int, reflect: bool, digits: int) -> list[str]:
	"""The same code over a span that is not a whole number of bytes.

	USB's token is eleven bits and its CRC covers all of them, so a
	byte-length entry point cannot say what the algorithm runs over (0046).
	One bit at a time rather than a second table, and checked against the
	table function at every whole-byte length (26.373).
	"""
	mask = (1 << width) - 1
	if reflect:
		started = reverse(init, width)
		taken   = "\t\tbit = (data[index >> 3] >> (index & 7)) & 1"
		body    = [
			"\t\tlow = (crc ^ bit) & 1",
			"\t\tcrc >>= 1",
			"\t\tif low:",
			f"\t\t\tcrc ^= 0x{reverse(poly, width):0{digits}X}",
		]
	else:
		started = init
		taken   = "\t\tbit = (data[index >> 3] >> (7 - (index & 7))) & 1"
		body    = [
			f"\t\tfire = ((crc >> {width - 1}) ^ bit) & 1",
			f"\t\tcrc = (crc << 1) & 0x{mask:X}",
			"\t\tif fire:",
			f"\t\t\tcrc ^= 0x{poly:0{digits}X}",
		]

	return [
		"",
		"",
		f"def {name}_bits(data: bytes, bit_at: int, bit_len: int) -> int:",
		f'\t"""The {decl.name} of `bit_len` bits from `bit_at`.',
		"",
		"\tFor a span that is not a whole number of bytes. The bits are",
		"\ttaken in the order the code runs them: least significant first",
		'\twhere it is reflected, most significant first where it is not."""',
		f"\tcrc = 0x{started:0{digits}X}",
		"",
		"\tfor index in range(bit_at, bit_at + bit_len):",
		taken,
		*body,
		"",
		f"\treturn (crc ^ 0x{xorout:0{digits}X}) & 0x{mask:X}",
	]


def _ones_complement(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""RFC 1071's sum. The C backend's comments carry the reasoning."""
	kernel = decl.kernel
	assert kernel is not None

	name       = _ident(prefix, decl.name)
	complement = kernel.flag("complement")

	# `~total` is negative in Python and masking it is what makes it the
	# 16-bit complement the RFC means, rather than a sign error nobody sees
	# until a value happens to be printed.
	final = "~total & 0xFFFF" if complement else "total & 0xFFFF"

	return [
		"",
		"",
		f"def {name}(data: bytes) -> int:",
		f'\t"""The {decl.name} of `data`, as a 16-bit integer.',
		"",
		"\tRFC 1071's sum with end-around carry"
		+ (", complemented." if complement else "."),
		'\t"""',
		f"\treturn {name}_holed(data, 0, 0, 0)",
		"",
		"",
		f"def {name}_holed(data: bytes, hole_at: int, hole_len: int,"
		f" fill: int) -> int:",
		f'\t"""The {decl.name} of `data`, with a hole read as `fill`.',
		"",
		"\tThe `hole_len` bytes at `hole_at` read as `fill` rather than as",
		"\twhat is there. This is the case RFC 1071 exists for: IPv4, ICMP",
		"\tand UDP put the sum inside its own coverage, so a sum over the",
		"\tspan as it stands reads the stored value and is wrong for every",
		"\tmessage. No copy is made -- the hole is a parameter.",
		'\t"""',
		f"\treturn {name}_spans(data, b\"\", hole_at, hole_len, fill)",
		"",
		"",
		f"def {name}_spans(a: bytes, b: bytes, hole_at: int, hole_len: int,"
		f" fill: int) -> int:",
		f'\t"""The {decl.name} of `a` followed by `b`, with a hole in it.',
		"",
		"\tUDP and TCP sum a pseudo-header the datagram does not contain",
		"\tand the caller builds (14.2a); it is `a` and the message is `b`.",
		"\t`hole_at` is measured against the two taken together, and the",
		"\ttwo are never joined -- reading through `_span_byte` is what",
		"\tkeeps that from copying the message.",
		'\t"""',
		"\t# No accumulator width to choose: a Python integer cannot",
		"\t# overflow, so the fold below is the only thing bounding it.",
		"\tcount = len(a) + len(b)",
		"\ttotal = 0",
		"\tindex = 0",
		"",
		"\twhile index + 1 < count:",
		"\t\thigh = _span_byte(a, b, index, hole_at, hole_len, fill)",
		"\t\tlow  = _span_byte(a, b, index + 1, hole_at, hole_len, fill)",
		"\t\ttotal += (high << 8) | low",
		"\t\tindex += 2",
		"\tif index < count:",
		"\t\t# The odd byte is the HIGH half of a final word.",
		"\t\ttotal += _span_byte("
		"a, b, index, hole_at, hole_len, fill) << 8",
		"",
		"\t# A loop, because a fold can carry again.",
		"\twhile total >> 16:",
		"\t\ttotal = (total & 0xFFFF) + (total >> 16)",
		f"\treturn {final}",
	]
