"""Derived codec implementations in Python (section 13.4).

The arithmetic is `codegen.kernel_math`'s, shared with the C and Rust
backends, so three languages cannot disagree about what a polynomial
means. What is here is the rendering.

Two families, deliberately. `polynomial` and `ones_complement` are what a
`checksum ... is <codec>` binding can name (0053), and until this existed
that binding was refused outright for Python -- a schema C honoured and
Python could not read. The other five decline with a note, exactly as C
does for a kernel it cannot generate: the properties are still derived and
still correct, and an `extern` impl supplies the code.

One difference from the other two backends, and it is the whole of what
Python changes. A C or Rust register is a machine word that wraps, so the
mask a narrow width needs is arithmetic those backends can skip when the
width fills its word. Python's integers are unbounded: nothing wraps, so
`crc << 8` grows for ever and every width -- 64 included -- is masked.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.kernel_math import (crc_start, crc_table, crc_width,
                                       number)
from situc.codegen.python.emit import py_name
from situc import __version__


def _ident(prefix: str, name: str) -> str:
	"""`situ_crc32` in C is `crc32` in a module that is already the schema's.

	Python has modules, so the prefix a C symbol carries to stay out of the
	linker's way is noise here. `py_name` rather than the name itself,
	because a codec called `lambda` is a name situ accepts and `def lambda`
	is not a line Python parses.
	"""
	del prefix
	return py_name(name)


def generate(schema: ast.Schema, basename: str, prefix: str = "situ") -> str:
	"""Emit every derived implementation the schema binds, as Python."""
	bound = {impl.codec for impl in schema.impls()
	         if impl.kind is ast.ImplKind.DERIVED}

	lines = [
		f'"""Generated by situc {__version__} from {basename}.situ'
		' -- do not edit.',
		"",
		"Implementations derived from kernel descriptions (section 13.4).",
		"The properties in the capability map and the code below come from",
		"one description, so they cannot disagree.",
		'"""',
		"",
		"from __future__ import annotations",
	]

	for decl in schema.codecs():
		if decl.name not in bound or decl.kernel is None:
			continue

		body = _for_kernel(decl, prefix)
		if body is None:
			# Two blank lines and a wrap that survives a long codec name,
			# because this is Python a person reads rather than a note in a
			# language where the line happens to be shorter.
			lines.extend([
				"",
				"",
				f"# No implementation for `{decl.name}`:",
				f"# a {decl.kernel.family.value} kernel is described but not"
				" yet generated in",
				"# Python. Its properties are derived and correct; bind an",
				f"# `impl {decl.name} extern \"...\"` to supply the code.",
			])
			continue

		lines.extend(body)

	return "\n".join(lines) + "\n"


def _for_kernel(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	kernel = decl.kernel
	assert kernel is not None

	if kernel.family is ast.KernelFamily.POLYNOMIAL:
		# A polynomial over an extension field is Reed-Solomon, which is a
		# different code and not one of the two this backend generates.
		if kernel.argument("field") is not None:
			return None
		return _polynomial(decl, prefix)
	if kernel.family is ast.KernelFamily.ONES_COMPLEMENT:
		return _ones_complement(decl, prefix)
	return None


def _polynomial(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""A table-driven CRC, with the table computed rather than copied."""
	width = crc_width(decl)
	if width is None:
		return None

	poly = number(decl, "poly")
	if not poly:
		return None

	kernel = decl.kernel
	assert kernel is not None
	reflect = kernel.flag("reflect")
	init    = number(decl, "init")
	xorout  = number(decl, "xorout")

	table  = crc_table(width, poly, reflect)
	name   = _ident(prefix, decl.name)
	mask   = (1 << width) - 1
	digits = width // 4

	# The table is module-private and underscored, which keeps it out of a
	# `from <module> import *` as well as saying so: the function is the
	# interface and the table is how it happens to be implemented.
	label = f"_{name.upper()}_TABLE"

	lines = [
		"",
		"",
		f"# {decl.name}: width={width} poly=0x{poly:0{digits}X} "
		f"init=0x{init:0{digits}X}",
		f"# xorout=0x{xorout:0{digits}X} "
		f"reflect={'yes' if reflect else 'no'}",
		"#",
		"# Computed from the polynomial, not copied from one.",
		f"{label}: list[int] = [",
	]
	for row in range(0, 256, 4):
		entries = ", ".join(f"0x{table[row + column]:0{digits}X}"
		                    for column in range(4))
		lines.append(f"\t{entries},")
	lines.append("]")

	started = crc_start(init, width, reflect)
	article = "an" if width == 8 else "a"
	lines.extend([
		"",
		"",
		f"def {name}(data: bytes) -> int:",
		f'\t"""The {decl.name} of `data`, as {article} {width}-bit integer."""',
		f"\tcrc = 0x{started:0{digits}X}",
		"",
		"\tfor byte in data:",
	])

	# Every branch masks, including the widest. A Python integer does not
	# wrap, so the mask is not the narrow-width correction it is in C and
	# Rust -- it is the machine word those two get for free.
	if reflect:
		lines.append(f"\t\tcrc = ({label}[(crc ^ byte) & 0xFF]"
		             f" ^ (crc >> 8)) & 0x{mask:X}")
	elif width == 8:
		# The index is already a byte and the table holds bytes, so this one
		# cannot leave the width even without a mask.
		lines.append(f"\t\tcrc = {label}[crc ^ byte]")
	else:
		lines.append(f"\t\tcrc = ({label}[((crc >> {width - 8}) ^ byte) & 0xFF]"
		             f" ^ (crc << 8)) & 0x{mask:X}")

	lines.extend([
		"",
		f"\treturn (crc ^ 0x{xorout:0{digits}X}) & 0x{mask:X}",
	])
	return lines


def _ones_complement(decl: ast.CodecDecl, prefix: str) -> list[str] | None:
	"""RFC 1071's sum. The C backend's comments carry the reasoning."""
	kernel = decl.kernel
	assert kernel is not None

	name       = _ident(prefix, decl.name)
	complement = kernel.flag("complement")

	# `~total` is negative in Python and masking it is what makes it the
	# 16-bit complement the RFC means, rather than a sign error nobody sees
	# until a value happens to be printed.
	final = "~total & 0xFFFF" if complement else "total & 0xFFFF"

	return [
		"",
		"",
		f"def {name}(data: bytes) -> int:",
		f'\t"""The {decl.name} of `data`, as a 16-bit integer.',
		"",
		"\tRFC 1071's sum with end-around carry"
		+ (", complemented." if complement else "."),
		'\t"""',
		"\t# No accumulator width to choose: a Python integer cannot",
		"\t# overflow, so the fold below is the only thing bounding it.",
		"\ttotal = 0",
		"\tindex = 0",
		"",
		"\twhile index + 1 < len(data):",
		"\t\ttotal += (data[index] << 8) | data[index + 1]",
		"\t\tindex += 2",
		"\tif index < len(data):",
		"\t\t# The odd byte is the HIGH half of a final word.",
		"\t\ttotal += data[index] << 8",
		"",
		"\t# A loop, because a fold can carry again.",
		"\twhile total >> 16:",
		"\t\ttotal = (total & 0xFFFF) + (total >> 16)",
		f"\treturn {final}",
	]
