"""Retransmission in Python (26.98).

I/O is a callable, not an interface. A protocol class would be ceremony
around one function, and `submit(bytes) -> None` is the whole obligation --
which is also what makes a transcript a lambda in a test rather than a class.

The clock is a parameter here as everywhere else on this rung. That is what
lets the same ten simulated minutes run in every backend and answer the same
thing, and it is not something Python's dynamism gets to relax.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.python.emit import py_name
from situc.relation import Read, KeyLayout, ReadBytes, Refused, Side, SubView, key_layout
from situc.resolve import ResolvedSchema
from situc import __version__

__all__ = ["generate"]


def _policy(relation: ast.Relation) -> tuple[int, int] | None:
	found = {}
	for attr in relation.attrs:
		value = getattr(attr.value, "value", None)
		if attr.name in ("timeout_ms", "retries") and isinstance(value, int):
			found[attr.name] = value
	return (found["timeout_ms"], found["retries"]) if len(found) == 2 else None


def _key(sides: Side, view: str) -> list[str]:
	lines = ["\t\tkey = 0"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, Read):
				lines.append(f"\t\tkey = (key << {width}) | "
				             f"{source}.{py_name(step.member)}")
			elif isinstance(step, SubView):
				local = f"_{py_name(step.member)}"
				lines.append(f"\t\t{local} = {source}.{py_name(step.member)}")
				source = local
	return lines


def _key_bytes(sides: Side, view: str) -> list[str]:
	"""The exact-bytes key (0042); see the converse twin for the layout."""
	lines = ["\t\tparts = []"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, ReadBytes):
				lines.append(f"\t\tparts.append(bytes({source}."
				             f"{py_name(step.member)}))\t# {step.path}")
			elif isinstance(step, Read):
				count = (width + 7) // 8
				lines.append(f"\t\tparts.append(int({source}."
				             f"{py_name(step.member)}).to_bytes({count}, "
				             f"\"big\"))\t# {step.path}")
			elif isinstance(step, SubView):
				local = f"_{py_name(step.member)}"
				lines.append(f"\t\t{local} = {source}.{py_name(step.member)}")
				source = local
	lines.append('\t\tkey = b"".join(parts)')
	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	ready = []
	for relation in schema.relations():
		policy = _policy(relation)
		if policy is None:
			continue
		try:
			ready.append((relation, policy, key_layout(relation, resolved)))
		except Refused:
			continue
	if not ready:
		return {}

	lines = [
		f'"""Generated by situc {__version__} from {basename}.situ -- do not edit.',
		"",
		"Retransmission and timeout. Owns I/O through a callable you supply",
		"and never owns the clock: every entry point takes `now_ms`.",
		'"""',
		"",
		"from __future__ import annotations",
		"",
		"from typing import Callable",
		"",
		"from situ_runtime import BoundsError, ConstraintError",
		"",
		f"from {basename} import *  # noqa: F403",
		"",
	]

	for relation, (timeout, retries), layout in ready:
		request, response = layout.request, layout.response
		name = py_name(relation.name)
		first, second = relation.params
		lines += [
			"",
			f"{name.upper()}_TIMEOUT_MS = {timeout}",
			f"{name.upper()}_RETRIES = {retries}",
			"",
			"",
			f"class {name}_driver:",
			f'\t"""Retransmission for `{relation.name}`.',
			"",
			"\tThe bytes you hand `send` are kept for the retransmission, so",
			"\tthey must not change until the exchange ends.",
			'\t"""',
			"",
			"\t__slots__ = (\"_cap\", \"_live\", \"_submit\", \"_timeout\", \"_retries\")",
			"",
			"\tdef __init__(self, submit: Callable[[bytes], None], cap: int,",
			f"\t             timeout_ms: int = {timeout},",
			f"\t             retries: int = {retries}) -> None:",
			"\t\tself._submit  = submit",
			"\t\tself._cap     = cap",
			"\t\tself._timeout = timeout_ms",
			"\t\tself._retries = retries",
			(f"\t\tself._live: dict[{'int' if layout.packed else 'bytes'}, "
			 "list[object]] = {}"),
			"",
			f"\tdef send(self, {first.name}: {py_name(first.type_name)},",
			"\t         data: bytes, id: int, now_ms: int) -> None:",
			*(_key(request, first.name) if layout.packed
			  else _key_bytes(request, first.name)),
			"",
			"\t\tif key not in self._live and len(self._live) >= self._cap:",
			"\t\t\traise BoundsError(",
			f"\t\t\t\t\"{relation.name}: {{}} exchanges already pending\""
			".format(self._cap), self._cap)",
			"\t\tself._live[key] = [data, id, now_ms + self._timeout,",
			"\t\t                   self._retries]",
			"\t\tself._submit(data)",
			"",
			f"\tdef on_message(self, {second.name}: "
			f"{py_name(second.type_name)}) -> int:",
			*(_key(response, second.name) if layout.packed
			  else _key_bytes(response, second.name)),
			"",
			"\t\tif key not in self._live:",
			"\t\t\traise ConstraintError(",
			f"\t\t\t\t\"{relation.name}: no exchange is waiting for this\")",
			"\t\treturn int(self._live.pop(key)[1])  # type: ignore[arg-type]",
			"",
			"\tdef step(self, now_ms: int) -> tuple[int | None, int]:",
			'\t\t"""Retransmit what is due; return (next deadline, given up).',
			"",
			"\t\tThe deadline is None where nothing is outstanding, and the",
			"\t\tcount is returned either way -- an exchange that gave up on",
			"\t\tthe call that emptied the table is one the caller still has",
			"\t\tto hear about. C writes it through a pointer for the same",
			'\t\treason, alongside SITU_ERR_TRUNCATED."""',
			"\t\tsoonest: int | None = None",
			"\t\texpired = 0",
			"\t\tdue: list[bytes] = []",
			"",
			"\t\tfor key in list(self._live):",
			"\t\t\tdata, _id, deadline, left = self._live[key]",
			"\t\t\tif now_ms >= int(deadline):  # type: ignore[call-overload]",
			"\t\t\t\tif int(left) == 0:  # type: ignore[call-overload]",
			"\t\t\t\t\tdel self._live[key]",
			"\t\t\t\t\texpired += 1",
			"\t\t\t\t\tcontinue",
			"\t\t\t\tdeadline = now_ms + self._timeout",
			"\t\t\t\tleft = int(left) - 1  # type: ignore[call-overload]",
			"\t\t\t\tself._live[key] = [data, _id, deadline, left]",
			"\t\t\t\tdue.append(bytes(data))  # type: ignore[arg-type]",
			"\t\t\tat = int(deadline)  # type: ignore[call-overload]",
			"\t\t\tif soonest is None or at < soonest:",
			"\t\t\t\tsoonest = at",
			"",
			"\t\tfor data in due:",
			"\t\t\tself._submit(data)",
			"",
			"\t\treturn (soonest, expired)",
		]

	return {f"{basename}_drive.py": "\n".join(lines).rstrip("\n") + "\n"}
