"""The Python backend (section 26.17).

Python reaches people who would otherwise not describe their format at all,
and it enforces the least of the lattice of any target situ has. Both are
reasons to build it; section 20.1 asks only that the second be said rather than
left for a reader to discover.

The surface is properties, not `get_x()` methods, because a Python caller who
has to write `packet.version()` will write the parser by hand instead -- and a
backend nobody uses enforces nothing at all. The cost that syntax hides is
recorded where situ records every cost: the capability map, and a docstring on
each field that quotes it.

`validate()` raises rather than returning a code, for the same reason. Idiom is
not a capability, and a return code a Python caller silently drops is worse
than an exception they have to catch.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c.names import c_name
from situc.diagnostics import Diagnostic
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.invariant import derived as derived_by
from situc.invariant import expression as invariant_expression
from situc.traverse import (
	refuse_delimited,
	Check, Member, classify, classify_check, local_name, obligation,
	own_entries, own_members,
)
from situc.unparse import expr_to_source as unparse_expr
from situc.types import ScalarType


@dataclass
class Generated:
	"""One module per schema."""

	module: str
	basename: str
	warnings: list[Diagnostic] = field(default_factory=list)

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.py": self.module}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> Generated:
	refuse_delimited(schema, resolved, "Python")
	return Generated(module=Emitter(schema, resolved, basename).module(),
	                 basename=basename)


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str) -> None:
		self.schema   = schema
		self.resolved = resolved
		self.basename = basename
		self.enums    = {decl.name: decl for decl in schema.enums()}
		self.structs  = set(resolved.structs)

	def module(self) -> str:
		lines = [
			f'"""Generated by situc from {self.basename}.situ -- do not edit.',
			"",
			"The operations below are the ones this schema's capability vectors",
			"support. Two axes do not survive the trip into Python and say so",
			"here rather than in each docstring: `atomic` means nothing, because",
			"Python has no single-instruction access, and `repr` costs what the",
			"map says it costs even though a property makes it look free.",
			'"""',
			"",
			"from __future__ import annotations",
			"",
			"import enum",
			"",
			"from situ_runtime import (",
			"\tConstraintError, Gate, Message, View, acquire, as_enum,",
			"\tascii_valid, bcd_decode, bcd_encode, bcd_valid, known_enum,",
			"\tcompose, nul_len, open_gate, utf8_valid,",
			")",
			"",
			"__all__ = [",
		]
		exported = [c_name(decl.name) for decl in self.schema.enums()]
		exported += [c_name(name) for name in sorted(self.structs)]
		lines.extend(f'\t"{name}",' for name in exported)
		lines.extend(["]", ""])

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		for name in self._order():
			lines.extend(self._struct(self.resolved.structs[name]))

		return "\n".join(lines) + "\n"

	def _order(self) -> list[str]:
		"""Contained structs first: a class body names them at definition time."""
		order: list[str] = []
		seen: set[str]   = set()

		def visit(name: str) -> None:
			if name in seen:
				return
			seen.add(name)
			for entry in own_entries(self.resolved.structs[name]):
				nested = entry.placement.type_name
				if nested in self.structs and nested != name:
					visit(nested)
			order.append(name)

		for name in sorted(self.structs):
			visit(name)
		return order

	# -- enums ---------------------------------------------------------

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		values = self.resolved.layout.env.enums[decl.name]
		lines  = [
			"",
			f"class {c_name(decl.name)}(enum.IntEnum):",
			f'\t"""enum {decl.name} : {decl.backing.name} --'
			f' unknown values are {decl.effective_default.value}."""',
			"",
		]
		lines.extend(f"\t{c_name(member.name)} = {values[member.name]}"
		             for member in decl.members)
		lines.append("")
		return lines

	# -- structs -------------------------------------------------------

	def _struct(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		name   = c_name(struct.name)

		if layout.register is not None:
			return self._register(struct)

		lines = ["", f"class {name}(View):", *self._class_doc(struct)]
		lines.extend(self._acquire(struct))

		for entry in own_entries(struct):
			lines.extend(self._member(struct, entry))

		lines.extend(self._invariants(struct))
		lines.extend(self._validate(struct))
		lines.extend(self._gates(struct))
		lines.append("")
		return lines

	# -- invariants (section 16.1) --------------------------------------

	def _invariants(self, struct: ResolvedStruct) -> list[str]:
		"""A derived field, and the one thing allowed to write it.

		The property has no setter -- `mutate` is Immutable and the docstring
		says which invariant decided that -- so without this the schema could
		state a relationship and never satisfy it.

		`recompute_x` rather than a `x.setter` on purpose. Assignment syntax
		for something that also clears a dirty bit reads as though it were
		free, and the C backend makes the same refusal for the same reason: a
		schema that means one thing in C must not mean another here.
		"""
		lines: list[str] = []

		for decl in derived_by(self.schema, struct):
			field = decl.derived.partition(".")[2]
			entry = next((e for e in struct.entries
			              if e.placement.path == f"{struct.name}.{field}"), None)
			if entry is None or entry.placement.scalar is None:
				continue

			name  = c_name(field)
			value = invariant_expression(struct, decl.expr, self)
			if value is None:
				lines.extend([
					"",
					f"\t# No recompute_{name}: this backend cannot evaluate",
					f"\t# `{unparse_expr(decl.expr)}` at run time. The refusal to",
					"\t# write the field directly still stands, so the invariant",
					"\t# cannot be broken -- only left unsatisfiable here.",
				])
				continue

			held = obligation(self.schema, struct, f"invariant {field}")
			assert held is not None, "the layout solver recorded this"
			bit = 1 << held.bit

			lines.extend([
				"",
				f"\tdef recompute_{name}(self) -> None:",
				f'\t\t"""{decl.derived} == {unparse_expr(decl.expr)}.',
				"",
				"\t\tWriting anything the right side reads marks this stale, and",
				"\t\t`Message.transmittable` refuses until this has run.",
				'\t\t"""',
				"\t\tself._check()",
				f"\t\tvalue = {value}",
				f"\t\t{self._store(entry.placement, entry.placement.scalar)}",
				f"\t\tself._msg.clear_dirty({bit})",
				"",
				f"\tdef {name}_is_stale(self) -> bool:",
				f"\t\treturn bool(self._msg.dirty & {bit})",
			])

		return lines

	# -- invariant.Terms, in Python -------------------------------------

	def literal(self, value: int) -> str:
		return str(value)

	def binary(self, op: str, left: str, right: str) -> str:
		# `/` is float division in Python and integer division everywhere else
		# situ emits. A size is a whole number of bytes in every backend, so
		# this is the one place the same expression needs different spelling
		# rather than a different meaning.
		return f"({left} {'//' if op == '/' else op} {right})"

	def offset(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		return (str(placement.offset_bytes) if placement.offset_bits is not None
		        else None)

	def size(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		if placement.is_fixed_size:
			return str(placement.size_bits // BITS_PER_BYTE)
		return self._length_expression(struct, placement)

	def count(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		return self._count_expression(struct, placement)

	def _register(self, struct: ResolvedStruct) -> list[str]:
		"""A register's word composition, without pretending to be a driver.

		Python cannot promise `volatile` -- there is no way to tell the
		interpreter that a read has a side effect. What it can do exactly is the
		arithmetic: compose a whole word from its fields and hand it back for
		the caller to write however they reach the bus. That is the shape
		section 15's headline asks for anyway, since a partial-width field in a
		`no_rmw` register cannot be written alone.
		"""
		info = struct.layout.register
		assert info is not None

		name  = c_name(struct.name)
		lines = [
			"",
			f"class {name}:",
			f'\t"""register {struct.name}'
			+ (f" at {info.address:#x}" if info.address is not None else "")
			+ f': {info.width} bits.',
			"",
			"\tPython cannot promise `volatile`, so this composes words and does",
			"\tnot drive a bus. Read and write through whatever addresses the",
			"\tdevice -- an mmap of /dev/mem, a probe, a simulator -- and use",
			'\t`word` to build what you send."""',
			"",
			f"\tWIDTH = {info.width}",
		]
		if info.address is not None:
			lines.append(f"\tADDRESS = {info.address:#x}")

		lines.extend([
			"",
			"\tclass word:",
			'\t\t"""A copy of the bits. Composing costs no transaction."""',
			"",
			"\t\t__slots__ = (\"raw\",)",
			"",
			"\t\tdef __init__(self, raw: int = 0) -> None:",
			"\t\t\tself.raw = raw",
		])

		for entry in own_entries(struct):
			lines.extend(self._register_field(entry))

		lines.append("")
		return lines

	def _register_field(self, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar

		if placement.kind == "reserved":
			return ["",
			        f"\t\t# {placement.path} is reserved: no accessor, and its",
			        "\t\t# bits are carried through a compose untouched."]
		if scalar is None:
			return []

		name  = c_name(placement.path.rsplit(".", 1)[-1])
		mode  = placement.access_mode or ast.AccessMode.RW
		shift = placement.offset_bits or 0
		mask  = (1 << scalar.bits) - 1
		lines = ["", f"\t\t# {placement.path}: {mode.value},"
		         f" bits {shift}..{shift + scalar.bits - 1}"]

		if mode.readable:
			lines.extend([
				"\t\t@property",
				f"\t\tdef {name}(self) -> int:",
				f"\t\t\treturn (self.raw >> {shift}) & {mask:#x}",
			])
		else:
			lines.append(f"\t\t# No {name}: the mode is {mode.value}, so a read"
			             f" returns nothing the field holds.")

		if mode.writable and mode.is_assignment:
			lines.extend([
				f"\t\tdef with_{name}(self, value: int) -> \"{{}}\":".format(
					c_name(entry.placement.path.split(".")[0]) + ".word"),
				f'\t\t\t"""A new word with {name} set; the rest untouched."""',
				f"\t\t\treturn type(self)(compose(self.raw, int(value),"
				f" {shift}, {mask:#x}))",
			])
		elif mode.writable:
			lines.append(f"\t\t# No with_{name}: `{mode.value}` is not an"
			             f" assignment.")
		else:
			lines.append(f"\t\t# No with_{name}: the mode is {mode.value}.")
		return lines

	def _class_doc(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		extent = (f"{layout.size_bytes} bytes, fixed" if layout.is_fixed_size
		          else f"{layout.size_bytes} bytes and up")
		return [f'\t"""struct {struct.name}: {extent}."""', ""]

	def _acquire(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout

		if layout.is_fixed_size:
			return [
				f"\tSIZE_BYTES = {layout.size_bytes}",
				"",
				"\t@classmethod",
				f"\tdef at(cls, msg: Message, offset: int = 0) -> \"{c_name(struct.name)}\":",
				'\t\t"""The one bounds check. Everything after it trusts the extent."""',
				"\t\treturn acquire(cls, msg, offset, cls.SIZE_BYTES)"
				f"  # type: ignore[return-value]",
			]

		return [
			f"\tSIZE_MIN = {layout.size_bytes}",
			"",
			"\t@classmethod",
			f"\tdef at(cls, msg: Message, offset: int, length: int)"
			f" -> \"{c_name(struct.name)}\":",
			'\t\t"""Nothing in the bytes says where the frame ends, so the',
			'\t\tcaller supplies it. That is the one bounds check."""',
			"\t\treturn acquire(cls, msg, offset, length)"
			f"  # type: ignore[return-value]",
		]

	# -- members -------------------------------------------------------

	def _member(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement

		kind = classify(struct, placement, self.structs)

		if kind is Member.RESERVED:
			return ["", f"\t# {placement.path} is reserved: no accessor, and",
			        "\t# validate() holds it to the pattern the schema declares."]
		if kind is Member.VARIABLE:
			return self._variable(struct, placement)
		if kind is Member.NESTED:
			return self._nested(struct, placement)
		if kind is Member.ARRAY:
			return self._array(struct, placement)
		if kind is Member.SCALAR:
			return self._scalar(struct, entry)
		if kind is Member.NOTHING:
			return []

		return ["", f"\t# {placement.path}: not emitted by this backend yet."]

	def _scalar(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		assert scalar is not None

		name   = c_name(local_name(struct, placement))
		hint   = self._hint(placement)
		offset = (None if placement.offset_bits is not None
		          else self._offset_expression(struct, placement))

		# The layout solver refuses a bit-packed field at a dynamic offset, so
		# this asserts that rule rather than declaring a gap this backend has.
		assert not (placement.offset_bits is None and scalar.is_bit_packed), \
			f"{placement.path}: bit-packed at a dynamic offset"

		if placement.offset_bits is None and offset is None:
			return ["", f"\t# {placement.path}: its offset cannot be resolved."]

		lines = ["", "\t@property", f"\tdef {name}(self) -> {hint}:",
		         *self._field_doc(entry),
		         f"\t\treturn {self._load(placement, scalar, offset)}"]

		if entry.vector.get(Axis.MUTATE).base != "InPlaceFixed":
			lines.extend([
				"",
				f"\t# No {name} setter: mutate is"
				f" {entry.vector.get(Axis.MUTATE).render()}.",
			])
			return lines

		# A covered write leaves a tag stale, so it is not an assignment and is
		# not spelled as one. The C backend makes the same refusal, and the two
		# have to agree: a schema that means one thing in C must not mean
		# another here.
		if placement.covered_by:
			tags = ", ".join(placement.covered_by)
			lines.extend([
				"",
				f"\t# No {name} setter: writing it leaves {tags} stale.",
				f"\t# Use set_{name}(msg, value), which marks the bit.",
				"",
				f"\tdef set_{name}(self, msg: Message, value: {hint}) -> None:",
				f'\t\t"""Write {placement.path} and mark {tags} stale."""',
				f"\t\t{self._store(placement, scalar, offset)}",
				f"\t\tmsg.mark_dirty({self._tag_bit(struct, placement)})",
			])
			return lines

		lines.extend([
			"",
			f"\t@{name}.setter",
			f"\tdef {name}(self, value: {hint}) -> None:",
			f"\t\t{self._store(placement, scalar, offset)}",
		])
		return lines

	def _tag_bit(self, struct: ResolvedStruct, placement: Placement) -> str:
		"""The bits every obligation over this field stands for, ORed.

		Every one of them, not the first. A field under a tag *and* an
		invariant leaves both stale when it is written, and marking one of the
		two is a message that reports itself ready to send while a covered byte
		no longer matches what authenticates it.

		The numbering is `traverse.obligations`, which is also where C gets it.
		This used to index a list of tags alone and fall back to bit 0 for
		anything it did not find -- and bit 0 is the first tag's, so an
		invariant marked the tag dirty and nothing else.
		"""
		bits = 0
		for label in placement.covered_by:
			held = obligation(self.schema, struct, label)
			if held is not None:
				bits |= 1 << held.bit
		return str(bits or 1)

	def _field_doc(self, entry: Resolved) -> list[str]:
		"""What the property syntax hides, said where a reader will find it."""
		vector = entry.vector
		axes   = " ".join(f"{axis.value}={vector.get(axis).render()}"
		                  for axis in (Axis.OFFSET, Axis.SIZE, Axis.REPR,
		                               Axis.MUTATE))
		return [f'\t\t"""{entry.placement.path}: {axes}."""']

	def _load(self, placement: Placement, scalar: ScalarType,
			offset: str | None = None) -> str:
		raw = self._raw_load(placement, scalar, offset)

		if scalar.is_bcd:
			raw = f"bcd_decode({raw}, {scalar.digits})"
		if placement.type_name in self.enums:
			return f"as_enum({c_name(placement.type_name)}, {raw})"
		return raw

	def _raw_load(self, placement: Placement, scalar: ScalarType,
			offset: str | None = None) -> str:
		big = placement.endian is not ast.Endian.LITTLE

		if scalar.is_bit_packed:
			if placement.offset_bits is None:
				return "0  # dynamic bit offset: not resolved by this backend"
			msb = placement.bit_order is not ast.BitOrder.LSB_FIRST
			return (f"self._bits({placement.offset_bits}, {scalar.bits},"
			        f" msb={msb}, signed={scalar.signed})")

		at = offset if offset is not None else str(placement.offset_bytes)
		return (f"self._read({at}, {scalar.bits // BITS_PER_BYTE},"
		        f" signed={scalar.signed}, big={big})")

	def _store(self, placement: Placement, scalar: ScalarType,
			offset: str | None = None) -> str:
		big   = placement.endian is not ast.Endian.LITTLE
		value = "int(value)"

		if scalar.is_bcd:
			value = f"bcd_encode({value}, {scalar.digits})"

		if scalar.is_bit_packed:
			msb = placement.bit_order is not ast.BitOrder.LSB_FIRST
			return (f"self._set_bits({placement.offset_bits}, {scalar.bits},"
			        f" {value}, msb={msb})")

		at = offset if offset is not None else str(placement.offset_bytes)
		return (f"self._write({at}, {scalar.bits // BITS_PER_BYTE}, {value},"
		        f" signed={scalar.signed}, big={big})")

	def _hint(self, placement: Placement) -> str:
		"""An enum field may hold a value that is not a member.

		Section 8.7's `default = error` says such a value is rejected on parse,
		not that a getter cannot return it -- and a `default = pass` schema
		admits it outright. So the hint is honest about both.
		"""
		if placement.type_name in self.enums:
			return f"{c_name(placement.type_name)} | int"
		return "int"

	def _nested(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		nested = c_name(placement.type_name or "")
		return [
			"", "\t@property", f"\tdef {name}(self) -> {nested}:",
			f'\t\t"""{placement.path} at {placement.offset_bytes}."""',
			f"\t\treturn {nested}(self._msg, self._at + {placement.offset_bytes},",
			f"\t\t\t{nested}.SIZE_BYTES)",
		]

	def _array(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		scalar = placement.scalar
		count  = placement.array_count or 0

		if scalar is None or scalar.bits != BITS_PER_BYTE:
			nested = c_name(placement.type_name or "")
			if placement.type_name not in self.structs:
				return ["", f"\t# {placement.path}: element type"
				        f" {placement.type_name} is not emitted yet."]
			return [
				"", f"\tdef {name}(self, index: int) -> {nested}:",
				f'\t\t"""Element `index` of {count}. Bounded by the count as',
				'\t\twell as the extent: bytes after the array are inside the',
				'\t\tview and are not elements."""',
				f"\t\tif not 0 <= index < {count}:",
				f"\t\t\traise IndexError(f\"{placement.path}[{{index}}] of {count}\")",
				f"\t\treturn {nested}(self._msg,",
				f"\t\t\tself._at + {placement.offset_bytes}"
				f" + index * {nested}.SIZE_BYTES, {nested}.SIZE_BYTES)",
			]

		lines = [
			"", "\t@property", f"\tdef {name}(self) -> memoryview:",
			f'\t\t"""{placement.path}: {count} bytes, zero copy and writable."""',
			"\t\tself._check()",
			f"\t\tstart = self._at + {placement.offset_bytes}",
			f"\t\treturn self._msg.buffer[start:start + {count}]",
		]

		if any(attr.name == "nul_terminated" for attr in placement.attrs):
			lines.extend([
				"", "\t@property", f"\tdef {name}_len(self) -> int:",
				f'\t\t"""Content length: to the first zero byte, or {count}."""',
				f"\t\treturn nul_len(self.{name}, {count})",
			])
		return lines

	def _variable(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		start  = self._offset_expression(struct, placement)
		length = self._length_expression(struct, placement)

		if start is None or length is None:
			return ["", f"\t# {placement.path}: sized by"
			        f" `{placement.sized_by}`, which this backend cannot",
			        "\t# resolve yet."]

		nested = self.resolved.structs.get(placement.type_name or "")
		lines  = ["", "\t@property", f"\tdef {name}_offset(self) -> int:",
		          f'\t\t"""{placement.path}: offset and extent both from the data."""',
		          f"\t\treturn {start}"]

		if nested is None:
			lines.extend([
				"", "\t@property", f"\tdef {name}(self) -> memoryview:",
				"\t\tself._check()",
				f"\t\tstart = self._at + self.{name}_offset",
				f"\t\treturn self._msg.buffer[start:start + ({length})]",
			])
			return lines

		count = self._count_expression(struct, placement)
		inner = c_name(placement.type_name or "")
		lines.extend([
			"", "\t@property", f"\tdef {name}_count(self) -> int:",
			f"\t\treturn {count}",
			"", f"\tdef {name}(self, index: int) -> {inner}:",
			f'\t\t"""Element `index`, bounded by the count as well as the extent."""',
			f"\t\tif not 0 <= index < self.{name}_count:",
			f"\t\t\traise IndexError(f\"{placement.path}[{{index}}]\")",
			f"\t\treturn {inner}(self._msg,",
			f"\t\t\tself._at + self.{name}_offset + index * {inner}.SIZE_BYTES,",
			f"\t\t\t{inner}.SIZE_BYTES)",
		])
		return lines

	# -- dynamic arithmetic --------------------------------------------

	def _offset_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		if placement.offset_bits is not None:
			return str(placement.offset_bits // BITS_PER_BYTE)

		constant = 0
		terms: list[str] = []

		for other in own_members(struct):
			if other.path == placement.path:
				break
			if other.is_fixed_size:
				constant += other.size_bits // BITS_PER_BYTE
				continue
			length = self._length_expression(struct, other)
			if length is None:
				return None
			terms.append(length)

		return " + ".join([str(constant), *terms])

	def _length_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		if placement.sized_by == "remaining":
			start = self._offset_expression(struct, placement)
			return None if start is None else f"(self._len - ({start}))"
		if placement.sized_by is None:
			return None

		count = self._count_expression(struct, placement)
		if count is None:
			return None

		element = self._element_bytes(placement)
		if element is None:
			return None
		return f"({count})" if element == 1 else f"({count}) * {element}"

	def _count_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		driver = self.resolved.find(f"{struct.name}.{placement.sized_by}")
		if driver is None or driver.placement.scalar is None:
			return None
		if driver.placement.offset_bits is None:
			return None
		return self._raw_load(driver.placement, driver.placement.scalar)

	def _element_bytes(self, placement: Placement) -> int | None:
		nested = self.resolved.structs.get(placement.type_name or "")
		if nested is not None:
			return (int(nested.layout.size_bytes)
			        if nested.layout.is_fixed_size else None)
		if placement.scalar is not None and placement.scalar.bits % BITS_PER_BYTE == 0:
			return max(placement.scalar.bits // BITS_PER_BYTE, 1)
		return None

	# -- validation ----------------------------------------------------

	def _validate(self, struct: ResolvedStruct) -> list[str]:
		checks: list[str] = []
		for entry in own_entries(struct):
			checks.extend(self._check(struct, entry))

		lines = [
			"", "\tdef validate(self) -> None:",
			'\t\t"""Every constraint the schema declares, on parse.',
			"",
			"\t\tRaises ConstraintError rather than returning a code: a Python",
			'\t\tcaller drops a return value far too easily."""',
		]
		if not checks:
			lines.append("\t\t# Nothing in this struct is constrained.")
			lines.append("\t\treturn")
		lines.extend(checks)
		return lines

	def _check(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		from situc.expr import evaluate

		placement = entry.placement
		scalar    = placement.scalar
		name      = c_name(local_name(struct, placement))

		check = classify_check(struct, placement, self.structs)

		if check is Check.NOTHING:
			return []
		if check is Check.REPEATED:
			return self._array_check(struct, placement, scalar, name)
		if check is Check.NESTED:
			return [f"\t\tself.{name}.validate()"]

		assert scalar is not None

		if check is Check.RESERVED:
			policy = _reserved_policy(placement.attrs)
			if policy not in ("must_be_zero", "must_be_one"):
				return []
			want = 0 if policy == "must_be_zero" else (1 << scalar.bits) - 1
			return [
				f"\t\tif {self._raw_load(placement, scalar)} != {want}:",
				f"\t\t\traise ConstraintError("
				f"\"{placement.path} is reserved [{policy}]\")",
			]

		lines: list[str] = []

		enum = self.enums.get(placement.type_name or "")
		if enum is not None and enum.effective_default is ast.EnumDefault.ERROR:
			lines.extend([
				f"\t\tif not known_enum({c_name(enum.name)}, int(self.{name})):",
				f"\t\t\traise ConstraintError("
				f"f\"{placement.path} is {{int(self.{name})}}, not a"
				f" {enum.name}\")",
			])

		for attr in placement.attrs:
			if attr.name not in ("must_eq", "max", "min") or attr.value is None:
				continue
			expected = evaluate(attr.value, self.resolved.layout.env)
			operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
			lines.extend([
				f"\t\tif int(self.{name}) {operator} {expected}:",
				f"\t\t\traise ConstraintError("
				f"f\"{placement.path} is {{self.{name}}},"
				f" {attr.name} {expected}\")",
			])
		return lines

	def _array_check(self, struct: ResolvedStruct, placement: Placement,
			scalar: ScalarType | None, name: str) -> list[str]:
		if scalar is None or scalar.bits != BITS_PER_BYTE:
			return []
		if placement.sized_by is not None:
			return []

		count = placement.array_count or 0
		lines: list[str] = []

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				want = 0 if policy == "must_be_zero" else 0xFF
				start = placement.offset_bytes
				lines.extend([
					f"\t\tself._check()",
					f"\t\tif any(b != {want} for b in self._msg.buffer["
					f"self._at + {start}:self._at + {start + count}]):",
					f"\t\t\traise ConstraintError("
					f"\"{placement.path} is reserved [{policy}]\")",
				])
			return lines

		for attr in placement.attrs:
			if attr.name == "encoding":
				named = getattr(attr.value, "name", None)
				if named in ("ascii", "utf8"):
					lines.extend([
						f"\t\tif not {named}_valid(self.{name}):",
						f"\t\t\traise ConstraintError("
						f"\"{placement.path} is not {named}\")",
					])
			if attr.name == "nul_terminated":
				lines.extend([
					f"\t\tif self.{name}_len >= {count}:",
					f"\t\t\traise ConstraintError("
					f"\"{placement.path} has no terminator\")",
				])
		return lines

	# -- gates ---------------------------------------------------------

	def _gates(self, struct: ResolvedStruct) -> list[str]:
		regions = [entry.placement for entry in struct.entries
		           if entry.placement.kind == "sealed"]
		lines: list[str] = []
		for region in regions:
			lines.extend(self._gate(struct, region))
		return lines

	def _gate(self, struct: ResolvedStruct, region: Placement) -> list[str]:
		name   = c_name(local_name(struct, region))
		holder = f"_{name}_gate"
		sealed = [entry.placement for entry in struct.entries
		          if entry.placement.sealed_by == region.name
		          and entry.placement.kind == "field"]
		inside = [entry for entry in struct.entries
		          if entry.placement.sealed_by == region.name
		          and entry.placement.kind == "field"
		          and entry.placement.scalar is not None
		          and entry.placement.offset_bits is not None
		          and entry.placement.array_count is None
		          and entry.placement.sized_by is None]
		secret = [placement.path for placement in sealed
		          if any(attr.name == "secret" for attr in placement.attrs)
		          and (placement.array_count is not None
		               or placement.sized_by is not None)]

		lines = [
			"",
			f"\tclass {holder}(Gate):",
			f'\t\t"""{region.path}: reachable only through a verified open.',
			"",
			"\t\tThe refusal is a run-time one. It is not the C++ guarantee,",
			"\t\twhere forging a gate does not compile -- Python has no access",
			"\t\tcontrol, and `object.__new__` will make one of these whatever",
			'\t\tthis class says. Section 14.3, as far as Python reaches."""',
		]

		for entry in inside:
			placement = entry.placement
			scalar    = placement.scalar
			assert scalar is not None
			field_name = c_name(placement.path.rsplit(".", 1)[-1])

			if any(attr.name == "secret" for attr in placement.attrs):
				lines.extend(["",
				              f"\t\t# {field_name} is [secret]: no accessor is",
				              "\t\t# generated for it at all (section 14.6)."])
				continue

			lines.extend([
				"", "\t\t@property",
				f"\t\tdef {field_name}(self) -> {self._hint(placement)}:",
				f"\t\t\treturn {self._load(placement, scalar).replace('self.', 'self._view.')}",
			])

		for path in secret:
			lines.extend(["",
			              f"\t\t# {path} is [secret]: no accessor is generated",
			              "\t\t# for it at all (section 14.6)."])

		if not inside and not secret:
			lines.append("\t\tpass")

		lines.extend([
			"",
			f"\tdef open_{name}(self, verified: bool) -> \"{c_name(struct.name)}"
			f".{holder}\":",
			f'\t\t"""Hand out the sealed interior, and only if `verified`."""',
			f"\t\treturn open_gate(type(self).{holder}, self, verified)"
			f"  # type: ignore[return-value]",
		])
		return lines


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str | None:
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one"):
			return str(attr.name)
		if attr.name in ("preserve", "unknown"):
			return None
	return "must_be_zero"
