"""The Python backend (section 26.17).

Python reaches people who would otherwise not describe their format at all,
and it enforces the least of the lattice of any target situ has. Both are
reasons to build it; section 20.1 asks only that the second be said rather than
left for a reader to discover.

The surface is properties, not `get_x()` methods, because a Python caller who
has to write `packet.version()` will write the parser by hand instead -- and a
backend nobody uses enforces nothing at all. The cost that syntax hides is
recorded where situ records every cost: the capability map, and a docstring on
each field that quotes it.

`validate()` raises rather than returning a code, for the same reason. Idiom is
not a capability, and a return code a Python caller silently drops is worse
than an exception they have to catch.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c.names import c_name
from situc.diagnostics import Diagnostic
from situc.layout import BITS_PER_BYTE, Placement
from situc.names import over_fields, render_delimiter
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.invariant import derived as derived_by
from situc.invariant import expression as invariant_expression
from situc.traverse import (
	Check, Member, arm_members, classify, classify_check, extent_parts,
	has_computable_extent, local_name, matched_values, obligation,
	own_entries, own_members,
)
from situc.unparse import expr_to_source as unparse_expr
from situc.types import ScalarType


def _pythonic(source: str) -> str:
	"""A schema expression as Python.

	The schema's operators are C's, which is a choice the language made once
	and every other backend is happy with. Python spells three of them in
	words, and emitting `||` produced a module that did not parse -- the same
	shape as `/` meaning float division here and integer division everywhere
	else (8.6.2).

	`!=` is left alone, which is why the negation is matched with a lookahead
	rather than replaced outright.
	"""
	source = source.replace("||", " or ").replace("&&", " and ")
	source = re.sub(r"!(?!=)", "not ", source)
	return re.sub(r"\s+", " ", source).strip()


@dataclass
class Generated:
	"""One module per schema."""

	module: str
	basename: str
	warnings: list[Diagnostic] = field(default_factory=list)

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.py": self.module}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> Generated:
	return Generated(module=Emitter(schema, resolved, basename).module(),
	                 basename=basename)


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str) -> None:
		self.schema   = schema
		self.resolved = resolved
		self.basename = basename
		self.enums    = {decl.name: decl for decl in schema.enums()}
		self.structs  = set(resolved.structs)

	def module(self) -> str:
		lines = [
			f'"""Generated by situc from {self.basename}.situ -- do not edit.',
			"",
			"The operations below are the ones this schema's capability vectors",
			"support. Two axes do not survive the trip into Python and say so",
			"here rather than in each docstring: `atomic` means nothing, because",
			"Python has no single-instruction access, and `repr` costs what the",
			"map says it costs even though a property makes it look free.",
			'"""',
			"",
			"from __future__ import annotations",
			"",
			"import enum",
			"",
			"from situ_runtime import (",
			"\tConstraintError, Gate, Message, VersionError, View, acquire,",
			"\tas_enum,",
			"\tascii_valid, bcd_decode, bcd_encode, bcd_valid, known_enum,",
			"\tcompose, nul_len, open_gate, utf8_valid,",
			*self._delimited_imports(),
			")",
			"",
			"__all__ = [",
		]
		exported = [c_name(decl.name) for decl in self.schema.enums()]
		exported += [c_name(name) for name in sorted(self.structs)]
		lines.extend(f'\t"{name}",' for name in exported)
		lines.extend(["]", ""])

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		for name in self._order():
			lines.extend(self._struct(self.resolved.structs[name]))

		return "\n".join(lines) + "\n"

	def _delimited_imports(self) -> list[str]:
		"""The section 8.6 helpers, imported only where something uses one.

		A generated module that imports what it does not use is noise a reader
		learns to skim, and `digits_minimal` in particular would have said the
		schema asked for a canonicity check when it had not (invariant 23).
		"""
		placements = [entry.placement
		              for struct in self.resolved.structs.values()
		              for entry in struct.entries]

		needed = []
		if any(p.delimiter is not None for p in placements):
			needed.append("scan")
		if any(p.radix is not None for p in placements):
			needed.append("parse_uint")
		if any(p.radix_minimal for p in placements):
			needed.append("digits_minimal")
		if any(p.trimmed for p in placements):
			needed.append("trim")
		if any(p.case_insensitive for p in placements):
			needed.append("ascii_ci_eq")

		return [f"\t{', '.join(sorted(needed))},"] if needed else []

	def _order(self) -> list[str]:
		"""Contained structs first: a class body names them at definition time."""
		order: list[str] = []
		seen: set[str]   = set()

		def visit(name: str) -> None:
			if name in seen:
				return
			seen.add(name)
			for entry in own_entries(self.resolved.structs[name]):
				nested = entry.placement.type_name
				if nested in self.structs and nested != name:
					visit(nested)
			order.append(name)

		for name in sorted(self.structs):
			visit(name)
		return order

	# -- enums ---------------------------------------------------------

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		values = self.resolved.layout.env.enums[decl.name]
		lines  = [
			"",
			f"class {c_name(decl.name)}(enum.IntEnum):",
			f'\t"""enum {decl.name} : {decl.backing.name} --'
			f' unknown values are {decl.effective_default.value}."""',
			"",
		]
		lines.extend(f"\t{c_name(member.name)} = {values[member.name]}"
		             for member in decl.members)
		lines.append("")
		return lines

	# -- structs -------------------------------------------------------

	def _struct(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		name   = c_name(struct.name)

		if layout.register is not None:
			return self._register(struct)

		lines = ["", f"class {name}(View):", *self._class_doc(struct)]
		lines.extend(self._acquire(struct))

		for entry in own_entries(struct):
			lines.extend(self._member(struct, entry))

		lines.extend(self._extent_property(struct))
		lines.extend(self._invariants(struct))
		lines.extend(self._validate(struct))
		lines.extend(self._gates(struct))
		lines.append("")
		return lines

	# -- invariants (section 16.1) --------------------------------------

	def _invariants(self, struct: ResolvedStruct) -> list[str]:
		"""A derived field, and the one thing allowed to write it.

		The property has no setter -- `mutate` is Immutable and the docstring
		says which invariant decided that -- so without this the schema could
		state a relationship and never satisfy it.

		`recompute_x` rather than a `x.setter` on purpose. Assignment syntax
		for something that also clears a dirty bit reads as though it were
		free, and the C backend makes the same refusal for the same reason: a
		schema that means one thing in C must not mean another here.
		"""
		lines: list[str] = []

		for decl in derived_by(self.schema, struct):
			field = decl.derived.partition(".")[2]
			entry = next((e for e in struct.entries
			              if e.placement.path == f"{struct.name}.{field}"), None)
			if entry is None or entry.placement.scalar is None:
				continue

			name  = c_name(field)
			value = invariant_expression(struct, decl.expr, self)
			if value is None:
				lines.extend([
					"",
					f"\t# No recompute_{name}: this backend cannot evaluate",
					f"\t# `{unparse_expr(decl.expr)}` at run time. The refusal to",
					"\t# write the field directly still stands, so the invariant",
					"\t# cannot be broken -- only left unsatisfiable here.",
				])
				continue

			held = obligation(self.schema, struct, f"invariant {field}")
			assert held is not None, "the layout solver recorded this"
			bit = 1 << held.bit

			lines.extend([
				"",
				f"\tdef recompute_{name}(self) -> None:",
				f'\t\t"""{decl.derived} == {unparse_expr(decl.expr)}.',
				"",
				"\t\tWriting anything the right side reads marks this stale, and",
				"\t\t`Message.transmittable` refuses until this has run.",
				'\t\t"""',
				"\t\tself._check()",
				f"\t\tvalue = {value}",
				f"\t\t{self._store(entry.placement, entry.placement.scalar)}",
				f"\t\tself._msg.clear_dirty({bit})",
				"",
				f"\tdef {name}_is_stale(self) -> bool:",
				f"\t\treturn bool(self._msg.dirty & {bit})",
			])

		return lines

	# -- invariant.Terms, in Python -------------------------------------

	def literal(self, value: int) -> str:
		return str(value)

	def binary(self, op: str, left: str, right: str) -> str:
		# `/` is float division in Python and integer division everywhere else
		# situ emits. A size is a whole number of bytes in every backend, so
		# this is the one place the same expression needs different spelling
		# rather than a different meaning.
		return f"({left} {'//' if op == '/' else op} {right})"

	def offset(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		return (str(placement.offset_bytes) if placement.offset_bits is not None
		        else None)

	def size(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		if placement.is_fixed_size:
			return str(placement.size_bits // BITS_PER_BYTE)
		return self._length_expression(struct, placement)

	def count(self, struct: ResolvedStruct, placement: Placement) -> str | None:
		return self._count_expression(struct, placement)

	def _register(self, struct: ResolvedStruct) -> list[str]:
		"""A register's word composition, without pretending to be a driver.

		Python cannot promise `volatile` -- there is no way to tell the
		interpreter that a read has a side effect. What it can do exactly is the
		arithmetic: compose a whole word from its fields and hand it back for
		the caller to write however they reach the bus. That is the shape
		section 15's headline asks for anyway, since a partial-width field in a
		`no_rmw` register cannot be written alone.
		"""
		info = struct.layout.register
		assert info is not None

		name  = c_name(struct.name)
		lines = [
			"",
			f"class {name}:",
			f'\t"""register {struct.name}'
			+ (f" at {info.address:#x}" if info.address is not None else "")
			+ f': {info.width} bits.',
			"",
			"\tPython cannot promise `volatile`, so this composes words and does",
			"\tnot drive a bus. Read and write through whatever addresses the",
			"\tdevice -- an mmap of /dev/mem, a probe, a simulator -- and use",
			'\t`word` to build what you send."""',
			"",
			f"\tWIDTH = {info.width}",
		]
		if info.address is not None:
			lines.append(f"\tADDRESS = {info.address:#x}")

		lines.extend([
			"",
			"\tclass word:",
			'\t\t"""A copy of the bits. Composing costs no transaction."""',
			"",
			"\t\t__slots__ = (\"raw\",)",
			"",
			"\t\tdef __init__(self, raw: int = 0) -> None:",
			"\t\t\tself.raw = raw",
		])

		for entry in own_entries(struct):
			lines.extend(self._register_field(entry))

		lines.append("")
		return lines

	def _register_field(self, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar

		if placement.kind == "reserved":
			return ["",
			        f"\t\t# {placement.path} is reserved: no accessor, and its",
			        "\t\t# bits are carried through a compose untouched."]
		if scalar is None:
			return []

		name  = c_name(placement.path.rsplit(".", 1)[-1])
		mode  = placement.access_mode or ast.AccessMode.RW
		shift = placement.offset_bits or 0
		mask  = (1 << scalar.bits) - 1
		lines = ["", f"\t\t# {placement.path}: {mode.value},"
		         f" bits {shift}..{shift + scalar.bits - 1}"]

		if mode.readable:
			lines.extend([
				"\t\t@property",
				f"\t\tdef {name}(self) -> int:",
				f"\t\t\treturn (self.raw >> {shift}) & {mask:#x}",
			])
		else:
			lines.append(f"\t\t# No {name}: the mode is {mode.value}, so a read"
			             f" returns nothing the field holds.")

		if mode.writable and mode.is_assignment:
			lines.extend([
				f"\t\tdef with_{name}(self, value: int) -> \"{{}}\":".format(
					c_name(entry.placement.path.split(".")[0]) + ".word"),
				f'\t\t\t"""A new word with {name} set; the rest untouched."""',
				f"\t\t\treturn type(self)(compose(self.raw, int(value),"
				f" {shift}, {mask:#x}))",
			])
		elif mode.writable:
			lines.append(f"\t\t# No with_{name}: `{mode.value}` is not an"
			             f" assignment.")
		else:
			lines.append(f"\t\t# No with_{name}: the mode is {mode.value}.")
		return lines

	def _class_doc(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout
		extent = (f"{layout.size_bytes} bytes, fixed" if layout.is_fixed_size
		          else f"{layout.size_bytes} bytes and up")
		return [f'\t"""struct {struct.name}: {extent}."""', ""]

	def _acquire(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout

		if layout.is_fixed_size:
			return [
				f"\tSIZE_BYTES = {layout.size_bytes}",
				"",
				"\t@classmethod",
				f"\tdef at(cls, msg: Message, offset: int = 0) -> \"{c_name(struct.name)}\":",
				'\t\t"""The one bounds check. Everything after it trusts the extent."""',
				"\t\treturn acquire(cls, msg, offset, cls.SIZE_BYTES)"
				f"  # type: ignore[return-value]",
			]

		return [
			f"\tSIZE_MIN = {layout.size_bytes}",
			"",
			"\t@classmethod",
			f"\tdef at(cls, msg: Message, offset: int, length: int)"
			f" -> \"{c_name(struct.name)}\":",
			'\t\t"""Nothing in the bytes says where the frame ends, so the',
			'\t\tcaller supplies it. That is the one bounds check."""',
			"\t\treturn acquire(cls, msg, offset, length)"
			f"  # type: ignore[return-value]",
		]

	# -- members -------------------------------------------------------

	def _member(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement

		kind = classify(struct, placement, self.structs)

		if kind is Member.RESERVED:
			return ["", f"\t# {placement.path} is reserved: no accessor, and",
			        "\t# validate() holds it to the pattern the schema declares."]
		if kind is Member.REPEAT_WHILE:
			return self._repeat_while(struct, placement)
		if kind is Member.DELIMITED:
			return self._delimited(struct, placement)
		if kind is Member.RECORD_RUN:
			return self._record_run(struct, placement)
		if kind is Member.VARIABLE:
			return self._variable(struct, placement)
		if kind is Member.NESTED:
			return self._nested(struct, placement)
		if kind is Member.ARRAY:
			return self._array(struct, placement)
		if kind is Member.SCALAR:
			return self._scalar(struct, entry)
		if kind is Member.NOTHING:
			return []

		return ["", f"\t# {placement.path}: not emitted by this backend yet."]

	def _scalar(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar
		assert scalar is not None

		name   = c_name(local_name(struct, placement))
		hint   = self._hint(placement)
		offset = (None if placement.offset_bits is not None
		          else self._offset_expression(struct, placement))

		# The layout solver refuses a bit-packed field at a dynamic offset, so
		# this asserts that rule rather than declaring a gap this backend has.
		assert not (placement.offset_bits is None and scalar.is_bit_packed), \
			f"{placement.path}: bit-packed at a dynamic offset"

		if placement.offset_bits is None and offset is None:
			return ["", f"\t# {placement.path}: its offset cannot be resolved."]

		if placement.since is not None and placement.version_field is not None:
			lines = self._versioned(placement, entry, name, hint, scalar, offset)
		else:
			lines = ["", "\t@property", f"\tdef {name}(self) -> {hint}:",
			         *self._field_doc(entry),
			         f"\t\treturn {self._load(placement, scalar, offset)}"]

		if entry.vector.get(Axis.MUTATE).base != "InPlaceFixed":
			lines.extend([
				"",
				f"\t# No {name} setter: mutate is"
				f" {entry.vector.get(Axis.MUTATE).render()}.",
			])
			return lines

		# A covered write leaves a tag stale, so it is not an assignment and is
		# not spelled as one. The C backend makes the same refusal, and the two
		# have to agree: a schema that means one thing in C must not mean
		# another here.
		if placement.covered_by:
			tags = ", ".join(placement.covered_by)
			lines.extend([
				"",
				f"\t# No {name} setter: writing it leaves {tags} stale.",
				f"\t# Use set_{name}(msg, value), which marks the bit.",
				"",
				f"\tdef set_{name}(self, msg: Message, value: {hint}) -> None:",
				f'\t\t"""Write {placement.path} and mark {tags} stale."""',
				f"\t\t{self._store(placement, scalar, offset)}",
				f"\t\tmsg.mark_dirty({self._tag_bit(struct, placement)})",
			])
			return lines

		gate = []
		if placement.since is not None and placement.version_field is not None:
			# Writing it to an earlier message puts these bytes past that
			# message's end. The getter refused this from the start and the
			# setter did not, in every backend, until one of them was checked.
			version = c_name(placement.version_field)
			gate = [
				f"\t\tif self.{version} < {placement.since}:",
				"\t\t\traise VersionError(",
				f'\t\t\t\tf"{placement.path} is not in a version '
				f'{{self.{version}}} message")',
			]

		lines.extend([
			"",
			f"\t@{name}.setter",
			f"\tdef {name}(self, value: {hint}) -> None:",
			*gate,
			f"\t\t{self._store(placement, scalar, offset)}",
		])
		return lines

	def _versioned(self, placement: Placement, entry: Resolved, name: str,
			hint: str, scalar: ScalarType, offset: str | None) -> list[str]:
		"""A member present only from a given version (section 19.4).

		A property that raises, not one that returns a sentinel. There is no
		value to hand back when the field is not there, and returning the
		bytes that follow would give another member's -- which is the bug the
		construct exists to prevent, so it is not available to write.
		"""
		version = c_name(placement.version_field or "")
		return [
			"",
			"\t@property",
			f"\tdef {name}(self) -> {hint}:",
			*self._field_doc(entry),
			f"\t\tif self.{version} < {placement.since}:",
			"\t\t\traise VersionError(",
			f'\t\t\t\tf"{placement.path} arrives in version '
			f'{placement.since}; this message is version "',
			f"\t\t\t\tf\"{{self.{version}}}\")",
			f"\t\treturn {self._load(placement, scalar, offset)}",
		]

	def _tag_bit(self, struct: ResolvedStruct, placement: Placement) -> str:
		"""The bits every obligation over this field stands for, ORed.

		Every one of them, not the first. A field under a tag *and* an
		invariant leaves both stale when it is written, and marking one of the
		two is a message that reports itself ready to send while a covered byte
		no longer matches what authenticates it.

		The numbering is `traverse.obligations`, which is also where C gets it.
		This used to index a list of tags alone and fall back to bit 0 for
		anything it did not find -- and bit 0 is the first tag's, so an
		invariant marked the tag dirty and nothing else.
		"""
		bits = 0
		for label in placement.covered_by:
			held = obligation(self.schema, struct, label)
			if held is not None:
				bits |= 1 << held.bit
		return str(bits or 1)

	def _field_doc(self, entry: Resolved) -> list[str]:
		"""What the property syntax hides, said where a reader will find it."""
		vector = entry.vector
		axes   = " ".join(f"{axis.value}={vector.get(axis).render()}"
		                  for axis in (Axis.OFFSET, Axis.SIZE, Axis.REPR,
		                               Axis.MUTATE))
		return [f'\t\t"""{entry.placement.path}: {axes}."""']

	def _load(self, placement: Placement, scalar: ScalarType,
			offset: str | None = None) -> str:
		raw = self._raw_load(placement, scalar, offset)

		if scalar.is_bcd:
			raw = f"bcd_decode({raw}, {scalar.digits})"
		if placement.type_name in self.enums:
			return f"as_enum({c_name(placement.type_name)}, {raw})"
		return raw

	def _raw_load(self, placement: Placement, scalar: ScalarType,
			offset: str | None = None) -> str:
		big = placement.endian is not ast.Endian.LITTLE

		if scalar.is_bit_packed:
			if placement.offset_bits is None:
				return "0  # dynamic bit offset: not resolved by this backend"
			msb = placement.bit_order is not ast.BitOrder.LSB_FIRST
			return (f"self._bits({placement.offset_bits}, {scalar.bits},"
			        f" msb={msb}, signed={scalar.signed})")

		at = offset if offset is not None else str(placement.offset_bytes)
		return (f"self._read({at}, {scalar.bits // BITS_PER_BYTE},"
		        f" signed={scalar.signed}, big={big})")

	def _store(self, placement: Placement, scalar: ScalarType,
			offset: str | None = None) -> str:
		big   = placement.endian is not ast.Endian.LITTLE
		value = "int(value)"

		if scalar.is_bcd:
			value = f"bcd_encode({value}, {scalar.digits})"

		if scalar.is_bit_packed:
			msb = placement.bit_order is not ast.BitOrder.LSB_FIRST
			return (f"self._set_bits({placement.offset_bits}, {scalar.bits},"
			        f" {value}, msb={msb})")

		at = offset if offset is not None else str(placement.offset_bytes)
		return (f"self._write({at}, {scalar.bits // BITS_PER_BYTE}, {value},"
		        f" signed={scalar.signed}, big={big})")

	def _hint(self, placement: Placement) -> str:
		"""An enum field may hold a value that is not a member.

		Section 8.7's `default = error` says such a value is rejected on parse,
		not that a getter cannot return it -- and a `default = pass` schema
		admits it outright. So the hint is honest about both.
		"""
		if placement.type_name in self.enums:
			return f"{c_name(placement.type_name)} | int"
		return "int"

	def _nested(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		nested = c_name(placement.type_name or "")
		inner  = self.resolved.structs.get(placement.type_name or "")
		start  = self._offset_expression(struct, placement)

		if inner is not None and not inner.layout.is_fixed_size and start is not None:
			# `SIZE_BYTES` is a class attribute only where a struct has one
			# size, so this raised `AttributeError` on the first access -- a
			# crash at the point of use rather than at generation, which is
			# the worst place for it to arrive. `_extent` is the same trap one
			# round further on: emitted only where the struct can be measured
			# from its own bytes, and read here whether it was or not.
			if not has_computable_extent(self.resolved.structs, inner):
				return [
					"",
					f"\t# No accessor for {placement.path}: one "
					f"`{placement.type_name}` has no",
					"\t# extent this backend can compute, so nothing can say"
					" where it ends.",
				]
			return [
				"", "\t@property",
				f"\tdef {name}_extent(self) -> int:",
				f'\t\t"""How many bytes {placement.path} occupies here.',
				"",
				"\t\tRead from the bytes: the member has no one size, and",
				'\t\tneither does the offset of whatever follows it."""',
				f"\t\tstart = self._at + ({start})",
				f"\t\treturn {nested}(self._msg, start,",
				f"\t\t\tself._len - ({start}))._extent",
				"",
				"\t@property",
				f"\tdef {name}(self) -> {nested}:",
				f'\t\t"""{placement.path}, sized from its own contents."""',
				f"\t\treturn {nested}(self._msg, self._at + ({start}),",
				f"\t\t\tself.{name}_extent)",
			]

		return [
			"", "\t@property", f"\tdef {name}(self) -> {nested}:",
			f'\t\t"""{placement.path} at {placement.offset_bytes}."""',
			f"\t\treturn {nested}(self._msg, self._at + {placement.offset_bytes},",
			f"\t\t\t{nested}.SIZE_BYTES)",
		]

	def _array(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		scalar = placement.scalar
		count  = placement.array_count or 0

		if scalar is None or scalar.bits != BITS_PER_BYTE:
			nested = c_name(placement.type_name or "")
			if placement.type_name not in self.structs:
				return ["", f"\t# {placement.path}: element type"
				        f" {placement.type_name} is not emitted yet."]
			return [
				"", f"\tdef {name}(self, index: int) -> {nested}:",
				f'\t\t"""Element `index` of {count}. Bounded by the count as',
				'\t\twell as the extent: bytes after the array are inside the',
				'\t\tview and are not elements."""',
				f"\t\tif not 0 <= index < {count}:",
				f"\t\t\traise IndexError(f\"{placement.path}[{{index}}] of {count}\")",
				f"\t\treturn {nested}(self._msg,",
				f"\t\t\tself._at + {placement.offset_bytes}"
				f" + index * {nested}.SIZE_BYTES, {nested}.SIZE_BYTES)",
			]

		lines = [
			"", "\t@property", f"\tdef {name}(self) -> memoryview:",
			f'\t\t"""{placement.path}: {count} bytes, zero copy and writable."""',
			"\t\tself._check()",
			f"\t\tstart = self._at + {placement.offset_bytes}",
			f"\t\treturn self._msg.buffer[start:start + {count}]",
		]

		if any(attr.name == "nul_terminated" for attr in placement.attrs):
			lines.extend([
				"", "\t@property", f"\tdef {name}_len(self) -> int:",
				f'\t\t"""Content length: to the first zero byte, or {count}."""',
				f"\t\treturn nul_len(self.{name}, {count})",
			])
		return lines

	def _variable(self, struct: ResolvedStruct, placement: Placement) -> list[str]:
		name   = c_name(local_name(struct, placement))
		start  = self._offset_expression(struct, placement)
		length = self._length_expression(struct, placement)

		if start is None or length is None:
			return ["", f"\t# {placement.path}: sized by"
			        f" `{placement.sized_by}`, which this backend cannot",
			        "\t# resolve yet."]

		nested = self.resolved.structs.get(placement.type_name or "")
		lines  = ["", "\t@property", f"\tdef {name}_offset(self) -> int:",
		          f'\t\t"""{placement.path}: offset and extent both from the data."""',
		          f"\t\treturn {start}"]

		if nested is None:
			lines.extend([
				"", "\t@property", f"\tdef {name}(self) -> memoryview:",
				"\t\tself._check()",
				f"\t\tstart = self._at + self.{name}_offset",
				f"\t\treturn self._msg.buffer[start:start + ({length})]",
			])
			return lines

		count = self._count_expression(struct, placement)
		inner = c_name(placement.type_name or "")
		lines.extend([
			"", "\t@property", f"\tdef {name}_count(self) -> int:",
			f"\t\treturn {count}",
			"", f"\tdef {name}(self, index: int) -> {inner}:",
			f'\t\t"""Element `index`, bounded by the count as well as the extent."""',
			f"\t\tif not 0 <= index < self.{name}_count:",
			f"\t\t\traise IndexError(f\"{placement.path}[{{index}}]\")",
			f"\t\treturn {inner}(self._msg,",
			f"\t\t\tself._at + self.{name}_offset + index * {inner}.SIZE_BYTES,",
			f"\t\t\t{inner}.SIZE_BYTES)",
		])
		return lines

	# -- dynamic arithmetic --------------------------------------------

	# -- delimited members (section 8.6) --------------------------------

	def _scan_call(self, placement: Placement, data: str, limit: str) -> str:
		delim = placement.delimiter
		assert delim is not None
		args = [data, limit, repr(delim)]

		if placement.delimiter_quote is not None:
			args.append(f"quote={placement.delimiter_quote}")
		if placement.delimiter_escape is not None:
			args.append(f"escape={placement.delimiter_escape}")
		return f"scan({', '.join(args)})"

	def _delimited(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""The same three numbers every backend gives, as properties.

		`_len` is the content, `_span` is content plus delimiter -- what the
		next member's offset is computed from -- and `_terminated` is neither.
		Properties rather than methods for the reason the rest of this backend
		gives: a caller who has to write `packet.line_len()` writes the parser
		by hand instead, and a backend nobody uses enforces nothing.
		"""
		assert placement.delimiter is not None
		name  = c_name(local_name(struct, placement))
		delim = placement.delimiter
		start = self._offset_expression(struct, placement)
		if start is None:
			return ["", f"\t# {placement.path}: this backend cannot resolve"
			        " where the scan starts."]

		limit = (f"self._len - ({start})" if placement.delimiter_cap is None
		         else f"min({placement.delimiter_cap}, self._len - ({start}))")
		data  = f"self._msg.buffer[self._at + ({start}):]"

		# With `[trim]` the framing and the value are different numbers: the
		# scan says where the next member starts, and the value is what is
		# left after the whitespace at either end.
		scan = f"{name}_raw_len" if placement.trimmed else f"{name}_len"

		lines = [
			"",
			f"\t@property",
			f"\tdef {name}_offset(self) -> int:",
			f'\t\t"""{placement.path}: where the scan starts."""',
			f"\t\treturn {start}",
			"",
			"\t@property",
			f"\tdef {scan}(self) -> int:",
			f'\t\t"""To the first {render_delimiter(delim)}, or the whole run."""',
			f"\t\treturn {self._scan_call(placement, data, limit)}",
			"",
			"\t@property",
			f"\tdef {name}_terminated(self) -> bool:",
			f'\t\t"""Whether the delimiter is there at all. It is not when the'
			' frame was cut short."""',
			f"\t\treturn self.{scan} < ({limit})",
			"",
			"\t@property",
			f"\tdef {name}_span(self) -> int:",
			f'\t\t"""Content plus delimiter: where the next member starts."""',
			f"\t\treturn self.{scan} + ({len(delim)} if self.{name}_terminated"
			" else 0)",
			"",
			"\t@property",
			f"\tdef {name}_raw(self) -> memoryview:",
			f'\t\t"""The member\'s bytes, before anything is trimmed."""',
			"\t\tself._check()",
			f"\t\tstart = self._at + self.{name}_offset",
			f"\t\treturn self._msg.buffer[start:start + self.{scan}]",
		]

		if placement.trimmed:
			lines.extend([
				"",
				"\t@property",
				f"\tdef {name}_len(self) -> int:",
				f'\t\t"""The value\'s length: `[trim]` makes the whitespace at',
				'\t\teither end framing rather than value."""',
				f"\t\treturn len(trim(self.{name}_raw))",
			])

		value = f"trim(self.{name}_raw)" if placement.trimmed else f"self.{name}_raw"

		if placement.radix is None:
			lines.extend([
				"",
				"\t@property",
				f"\tdef {name}(self) -> memoryview | bytes:",
				f"\t\treturn {value}",
				"",
				f"\tdef {name}_eq(self, other: bytes) -> bool:",
				f'\t\t"""Whether {placement.path} is a given token, compared '
				+ ("folding" if placement.case_insensitive else "byte for"),
				("\t\tASCII case." if placement.case_insensitive
				 else "\t\tbyte."),
				"",
				"\t\tThe length is part of the comparison, so a prefix is not",
				'\t\ta match."""',
				(f"\t\treturn ascii_ci_eq({value}, other)"
				 if placement.case_insensitive
				 else f"\t\treturn bytes({value}) == other"),
			])
			return lines

		return lines + self._text_number(struct, placement, value)

	def _text_number(self, struct: ResolvedStruct, placement: Placement,
			value: str) -> list[str]:
		"""Digits, read through something that can say they are not digits.

		Raising rather than returning None, for the reason `validate` raises:
		idiom is not a capability, and a None a caller silently drops is worse
		than an exception they have to catch. `_value` is the same digits
		where nothing can be raised -- the offset arithmetic after this field
		is not fallible.
		"""
		assert placement.radix is not None
		scalar = placement.scalar
		assert scalar is not None

		name  = c_name(local_name(struct, placement))
		limit = (1 << scalar.bits) - 1
		raw   = value

		return [
			"",
			"\t@property",
			f"\tdef {name}(self) -> int:",
			f'\t\t"""{placement.path}: digits, in the range of {scalar.name}.',
			"",
			"\t\tThe only property here that can raise. Every other conversion",
			"\t\tis total; a decimal parse is not, and returning 0 for `12x4`",
			'\t\twould hand back a number nobody wrote."""',
			"\t\tself._check()",
			f"\t\tvalue = parse_uint({raw}, {placement.radix}, {limit})",
			"\t\tif value is None:",
			f"\t\t\traise ConstraintError(",
			f'\t\t\t\tf"{placement.path} is not a {scalar.name} written in '
			f'base {placement.radix}")',
			"\t\treturn value",
			"",
			"\t@property",
			f"\tdef {name}_value(self) -> int:",
			f'\t\t"""The same digits where nothing may raise.',
			"",
			"\t\tThe offset arithmetic after this field is not fallible, and",
			"\t\tmaking it so would put a try/except in every accessor after",
			"\t\tit. `validate` refuses a frame whose digits are not digits,",
			'\t\tso a validated one always parses here."""',
			f"\t\tvalue = parse_uint({raw}, {placement.radix}, {limit})",
			"\t\treturn 0 if value is None else value",
		]

	def _over_fields(self, struct: ResolvedStruct, source: str,
			held: str) -> str:
		names = [entry.placement.name for entry in struct.entries
		         if entry.placement.scalar is not None
		         and "." not in entry.placement.path[len(struct.name) + 1:]]
		return _pythonic(over_fields(names, source,
		                             lambda name: f"{held}.{c_name(name)}"))

	def _repeat_while(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""A run ending after the element that fails a condition (8.6.6)."""
		element = self.resolved.structs.get(placement.type_name or "")
		if element is None or self._extent_expression(element) is None:
			return ["", f"\t# No accessors for {placement.path}: one"
			        f" `{placement.type_name}` has no extent",
			        "\t# this backend can compute."]

		name  = c_name(local_name(struct, placement))
		inner = c_name(placement.type_name or "")
		start = self._offset_expression(struct, placement)
		if start is None:
			return ["", f"\t# {placement.path}: this backend cannot resolve"
			        " where the run starts."]

		cond = self._over_fields(element, placement.repeat_while or "", "element")
		cap  = ("" if placement.repeat_cap is None
		        else f" and len(starts) <= {placement.repeat_cap}")

		return [
			"",
			f"\tdef _{name}_walk(self) -> list[int]:",
			f'\t\t"""Where each `{placement.type_name}` starts, and where the'
			" run ends.",
			"",
			f"\t\tThe run ends after the element for which",
			f"\t\t`{placement.repeat_while}` is false -- that element is part",
			"\t\tof it, because the condition is asked once it has been read.",
			"",
			"\t\tBounded twice, by the buffer and by refusing to advance on a",
			'\t\tzero-extent element."""',
			"\t\tself._check()",
			f"\t\tat     = {start}",
			"\t\tstarts = []",
			"",
			f"\t\twhile at < self._len{cap}:",
			f"\t\t\telement = {inner}(self._msg, self._at + at, self._len - at)",
			"\t\t\tsize    = element._extent",
			"\t\t\tif size == 0 or at + size > self._len:",
			"\t\t\t\tbreak",
			"\t\t\tstarts.append(at)",
			"\t\t\tat += size",
			f"\t\t\tif not ({cond}):",
			"\t\t\t\tbreak",
			"",
			"\t\tstarts.append(at)",
			"\t\treturn starts",
			"",
			"\t@property",
			f"\tdef {name}_count(self) -> int:",
			f"\t\treturn len(self._{name}_walk()) - 1",
			"",
			"\t@property",
			f"\tdef {name}_span(self) -> int:",
			f"\t\treturn self._{name}_walk()[-1] - ({start})",
			"",
			f"\tdef {name}(self, index: int) -> {inner}:",
			f"\t\tstarts = self._{name}_walk()",
			"\t\tif not 0 <= index < len(starts) - 1:",
			f'\t\t\traise IndexError(f"{placement.path}[{{index}}]")',
			f"\t\treturn {inner}(self._msg, self._at + starts[index],",
			"\t\t\tstarts[index + 1] - starts[index])",
		]

	def _record_run(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""A run of records, ending where the terminator would be an element."""
		assert placement.delimiter is not None
		element = self.resolved.structs.get(placement.type_name or "")
		if element is None or self._extent_expression(element) is None:
			return ["", f"\t# No accessors for {placement.path}: one"
			        f" `{placement.type_name}` has no extent",
			        "\t# this backend can compute, so the run cannot be walked."]

		name  = c_name(local_name(struct, placement))
		delim = placement.delimiter
		inner = c_name(placement.type_name or "")
		start = self._offset_expression(struct, placement)
		if start is None:
			return ["", f"\t# {placement.path}: this backend cannot resolve"
			        " where the run starts."]

		return [
			"",
			f"\tdef _{name}_walk(self) -> list[int]:",
			f'\t\t"""Where each `{placement.type_name}` starts, and where the run'
			" ends.",
			"",
			f"\t\tThe terminator only terminates where an element would start;",
			"\t\tinside one it is that element's own byte. Bounded twice over,",
			"\t\tby the buffer and by refusing to advance on a zero-extent",
			"\t\telement -- a record whose members are all delimited and all",
			'\t\tempty occupies no bytes, and this would not return."""',
			"\t\tself._check()",
			f"\t\tat     = {start}",
			"\t\tstarts = []",
			"",
			f"\t\twhile at + {len(delim)} <= self._len:",
			f"\t\t\tif bytes(self._msg.buffer[self._at + at:"
			f"self._at + at + {len(delim)}]) == {delim!r}:",
			"\t\t\t\tbreak",
			f"\t\t\telement = {inner}(self._msg, self._at + at, self._len - at)",
			"\t\t\tsize    = element._extent",
			"\t\t\tif size == 0 or at + size > self._len:",
			"\t\t\t\tbreak",
			"\t\t\tstarts.append(at)",
			"\t\t\tat += size",
			"",
			f"\t\tstarts.append(at + ({len(delim)} if at + {len(delim)}"
			" <= self._len else 0))",
			"\t\treturn starts",
			"",
			"\t@property",
			f"\tdef {name}_count(self) -> int:",
			f"\t\treturn len(self._{name}_walk()) - 1",
			"",
			"\t@property",
			f"\tdef {name}_span(self) -> int:",
			f'\t\t"""Every element plus the terminator: where the next member'
			' starts."""',
			f"\t\treturn self._{name}_walk()[-1] - ({start})",
			"",
			f"\tdef {name}(self, index: int) -> {inner}:",
			f'\t\t"""Element `index`. Walked, not indexed: a view is a value and',
			"\t\tnothing here keeps a table of offsets, which is what",
			'\t\t`access = Sequential` in the map is telling you."""',
			f"\t\tstarts = self._{name}_walk()",
			"\t\tif not 0 <= index < len(starts) - 1:",
			f'\t\t\traise IndexError(f"{placement.path}[{{index}}]")',
			f"\t\treturn {inner}(self._msg, self._at + starts[index],",
			"\t\t\tstarts[index + 1] - starts[index])",
		]

	def _extent_expression(self, struct: ResolvedStruct) -> str | None:
		"""How many bytes one instance of a variable struct occupies."""
		# The arithmetic and the refusals are shared
		# (traverse.extent_parts); rendering one length is Python's business.
		parts = extent_parts(self.resolved.structs, struct)
		if parts is None:
			return None
		constant, variable = parts

		terms = [str(constant)]
		for placement in variable:
			length = self._length_expression(struct, placement)
			if length is None:
				return None
			terms.append(length)
		return " + ".join(terms)

	def _extent_property(self, struct: ResolvedStruct) -> list[str]:
		"""Emitted only for a type something walks a run of."""
		# A run walks them and a nested member sizes itself from one.
		if not any(classify(other, entry.placement, self.structs)
		           in (Member.RECORD_RUN, Member.REPEAT_WHILE, Member.NESTED)
		           and entry.placement.type_name == struct.name
		           for other in self.resolved.structs.values()
		           for entry in other.entries):
			return []

		extent = self._extent_expression(struct)
		if extent is None:
			return []

		return [
			"",
			"\t@property",
			"\tdef _extent(self) -> int:",
			f'\t\t"""How many bytes one `{struct.name}` occupies.',
			"",
			"\t\tA run of these is walked, and the walk needs to know where",
			'\t\teach one ends."""',
			f"\t\treturn {extent}",
		]

	def _offset_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		if placement.offset_bits is not None:
			return str(placement.offset_bits // BITS_PER_BYTE)

		constant = 0
		terms: list[str] = []

		for other in own_members(struct):
			if other.path == placement.path:
				break
			if other.is_fixed_size:
				constant += other.size_bits // BITS_PER_BYTE
				continue
			length = self._length_expression(struct, other)
			if length is None:
				return None
			terms.append(length)

		return " + ".join([str(constant), *terms])

	def _discriminant_check(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""`default: error` -- the discriminant must select an arm.

		Section 14.5 says an unrecognised discriminant is rejected on parse,
		and no backend rejected it. It stayed invisible while a variant had no
		computable extent, because nothing walked one.
		"""
		values = matched_values(placement)
		if not values or placement.discriminant is None:
			return []

		held = self._over_fields(struct, placement.discriminant, "self")
		test = " and ".join(f"{held} != {arm.value}" for arm in values)
		named = ", ".join(arm.source or str(arm.value) for arm in values)
		return [
			f"\t\t# {placement.path}: an arm for {named}, and"
			f" `default: error` for the rest.",
			f"\t\tif {test}:",
			f'\t\t\traise ConstraintError("{placement.path}: no arm for'
			f' this {placement.discriminant}")',
		]

	def _variant_length(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		"""How many bytes the selected arm occupies, as one expression.

		A conditional chain rather than a statement `switch`, because callers
		want this inside a sum -- the extent of the struct around it, or the
		offset of whatever follows.

		An unmatched discriminant yields zero, which is not a claim that such
		a message is empty: `default: error` says there is no such message,
		and `validate` is where that is said. Zero is the value the run walk
		already refuses to advance by.
		"""
		if not placement.arm_cases or placement.discriminant is None:
			return None

		held  = self._over_fields(struct, placement.discriminant, "self")
		chain = "0"
		for arm, member in reversed(arm_members(struct, placement)):
			if member is None:
				continue		# `default: error`; falls to the zero above
			if member.is_fixed_size:
				length = str(member.size_bits // BITS_PER_BYTE)
			else:
				rendered = self._length_expression(struct, member)
				if rendered is None:
					return None
				length = f"({rendered})"

			chain = (length if arm.value is None
			         else f"({length} if {held} == {arm.value} else {chain})")
		return chain

	def _length_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		if placement.kind == "variant":
			return self._variant_length(struct, placement)

		# A delimited member's extent is wherever the delimiter turns out to
		# be, and `_span` is the member's own answer. One name for "how far
		# this member reaches", whether it is a byte run or a run of records.
		if placement.delimiter is not None or placement.repeat_while is not None:
			return f"self.{c_name(local_name(struct, placement))}_span"

		# Arithmetic over a field rather than a reference to one. Without this
		# the member fell through to the scalar case and this backend read one
		# byte and called it the field.
		if placement.size_expr is not None:
			return self._over_fields(struct, placement.size_expr, "self")

		# A nested struct with no single size, which the sum treated as zero
		# bytes wide -- so whatever followed it was placed on top of it.
		inner = self.resolved.structs.get(placement.type_name or "")
		if (inner is not None and not inner.layout.is_fixed_size
				and placement.kind == "field"
				and placement.array_count is None
				and placement.sized_by is None):
			if not has_computable_extent(self.resolved.structs, inner):
				return None		# and so nothing after it can be placed
			return f"self.{c_name(local_name(struct, placement))}_extent"

		if placement.sized_by == "remaining":
			start = self._offset_expression(struct, placement)
			return None if start is None else f"(self._len - ({start}))"
		if placement.sized_by is None:
			return None

		count = self._count_expression(struct, placement)
		if count is None:
			return None

		element = self._element_bytes(placement)
		if element is None:
			return None
		return f"({count})" if element == 1 else f"({count}) * {element}"

	def _count_expression(self, struct: ResolvedStruct,
			placement: Placement) -> str | None:
		driver = self.resolved.find(f"{struct.name}.{placement.sized_by}")
		if driver is None or driver.placement.scalar is None:
			return None

		# A text driver holds digits, not bits, and sits behind the scans of
		# everything before it -- so neither the offset check below nor the
		# raw load after it applies.
		if driver.placement.radix is not None:
			return f"self.{c_name(local_name(struct, driver.placement))}_value"

		if driver.placement.offset_bits is None:
			return None
		return self._raw_load(driver.placement, driver.placement.scalar)

	def _element_bytes(self, placement: Placement) -> int | None:
		nested = self.resolved.structs.get(placement.type_name or "")
		if nested is not None:
			return (int(nested.layout.size_bytes)
			        if nested.layout.is_fixed_size else None)
		if placement.scalar is not None and placement.scalar.bits % BITS_PER_BYTE == 0:
			return max(placement.scalar.bits // BITS_PER_BYTE, 1)
		return None

	# -- validation ----------------------------------------------------

	def _validate(self, struct: ResolvedStruct) -> list[str]:
		checks: list[str] = []
		for entry in own_entries(struct):
			checks.extend(self._check(struct, entry))

		lines = [
			"", "\tdef validate(self) -> None:",
			'\t\t"""Every constraint the schema declares, on parse.',
			"",
			"\t\tRaises ConstraintError rather than returning a code: a Python",
			'\t\tcaller drops a return value far too easily."""',
		]
		if not checks:
			lines.append("\t\t# Nothing in this struct is constrained.")
			lines.append("\t\treturn")
		lines.extend(checks)
		return lines

	def _delimiter_check(self, struct: ResolvedStruct,
			placement: Placement) -> list[str]:
		"""The delimiter is there, and a text number's digits are digits.

		Terminated first, and deliberately: for a frame cut short before the
		digits both are wrong, and "this frame stops early" is the more useful
		of the two answers. C reports it in that order and so does this.
		"""
		if "." in placement.path[len(struct.name) + 1:]:
			return []		# checked under the element's own struct

		name  = c_name(local_name(struct, placement))
		delim = placement.delimiter
		assert delim is not None

		lines = [
			f"\t\tif not self.{name}_terminated:",
			f"\t\t\traise ConstraintError(",
			# `bytes` repr rather than `render_delimiter`, which is the one
			# place the two differ: the readable form holds both backslashes
			# and double quotes, and this goes inside a double-quoted Python
			# literal in generated source. `b'\r\n'` says the same thing and
			# survives the trip.
			f'\t\t\t\t"{placement.path} has no '
			f'{repr(delim).replace(chr(92), chr(92) * 2)}: '
			'the frame stops first")',
		]
		if placement.radix_minimal:
			lines.extend([
				f"\t\tif not digits_minimal(self.{name}, {placement.radix}):",
				"\t\t\traise ConstraintError(",
				f'\t\t\t\t"{placement.path} is not the minimal spelling of '
				'its value")',
			])
		if placement.radix is not None:
			# Reading it is the check: the property raises for digits that are
			# not digits, which is the whole of what it is for.
			lines.append(f"\t\t_ = self.{name}")
		return lines

	def _check(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		from situc.expr import evaluate

		placement = entry.placement
		scalar    = placement.scalar
		name      = c_name(local_name(struct, placement))

		check = classify_check(struct, placement, self.structs)

		if check is Check.DISCRIMINANT:
			return self._discriminant_check(struct, placement)
		if check is Check.DELIMITED:
			return self._delimiter_check(struct, placement)
		if check is Check.NOTHING:
			return []
		if check is Check.REPEATED:
			return self._array_check(struct, placement, scalar, name)
		if check is Check.NESTED:
			# Only where the accessor exists. Validation reaching for a
			# member the emitter declined to expose is the same crash as any
			# other, arriving on the path people are least likely to test.
			inner = self.resolved.structs.get(placement.type_name or "")
			if inner is not None and not inner.layout.is_fixed_size \
					and not has_computable_extent(self.resolved.structs, inner):
				return [f"\t\t# {placement.path}: no accessor to validate through."]
			return [f"\t\tself.{name}.validate()"]

		assert scalar is not None

		if check is Check.RESERVED:
			policy = _reserved_policy(placement.attrs)
			if policy not in ("must_be_zero", "must_be_one"):
				return []
			want = 0 if policy == "must_be_zero" else (1 << scalar.bits) - 1
			return [
				f"\t\tif {self._raw_load(placement, scalar)} != {want}:",
				f"\t\t\traise ConstraintError("
				f"\"{placement.path} is reserved [{policy}]\")",
			]

		lines: list[str] = []

		enum = self.enums.get(placement.type_name or "")
		if enum is not None and enum.effective_default is ast.EnumDefault.ERROR:
			lines.extend([
				f"\t\tif not known_enum({c_name(enum.name)}, int(self.{name})):",
				f"\t\t\traise ConstraintError("
				f"f\"{placement.path} is {{int(self.{name})}}, not a"
				f" {enum.name}\")",
			])

		for attr in placement.attrs:
			if attr.name not in ("must_eq", "max", "min") or attr.value is None:
				continue
			expected = evaluate(attr.value, self.resolved.layout.env)
			operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
			lines.extend([
				f"\t\tif int(self.{name}) {operator} {expected}:",
				f"\t\t\traise ConstraintError("
				f"f\"{placement.path} is {{self.{name}}},"
				f" {attr.name} {expected}\")",
			])
		return lines

	def _array_check(self, struct: ResolvedStruct, placement: Placement,
			scalar: ScalarType | None, name: str) -> list[str]:
		if scalar is None or scalar.bits != BITS_PER_BYTE:
			return []
		if placement.sized_by is not None:
			return []

		count = placement.array_count or 0
		lines: list[str] = []

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				want = 0 if policy == "must_be_zero" else 0xFF
				start = placement.offset_bytes
				lines.extend([
					f"\t\tself._check()",
					f"\t\tif any(b != {want} for b in self._msg.buffer["
					f"self._at + {start}:self._at + {start + count}]):",
					f"\t\t\traise ConstraintError("
					f"\"{placement.path} is reserved [{policy}]\")",
				])
			return lines

		for attr in placement.attrs:
			if attr.name == "encoding":
				named = getattr(attr.value, "name", None)
				if named in ("ascii", "utf8"):
					lines.extend([
						f"\t\tif not {named}_valid(self.{name}):",
						f"\t\t\traise ConstraintError("
						f"\"{placement.path} is not {named}\")",
					])
			if attr.name == "nul_terminated":
				lines.extend([
					f"\t\tif self.{name}_len >= {count}:",
					f"\t\t\traise ConstraintError("
					f"\"{placement.path} has no terminator\")",
				])
		return lines

	# -- gates ---------------------------------------------------------

	def _gates(self, struct: ResolvedStruct) -> list[str]:
		regions = [entry.placement for entry in struct.entries
		           if entry.placement.kind == "sealed"]
		lines: list[str] = []
		for region in regions:
			lines.extend(self._gate(struct, region))
		return lines

	def _gate(self, struct: ResolvedStruct, region: Placement) -> list[str]:
		name   = c_name(local_name(struct, region))
		holder = f"_{name}_gate"
		sealed = [entry.placement for entry in struct.entries
		          if entry.placement.sealed_by == region.name
		          and entry.placement.kind == "field"]
		inside = [entry for entry in struct.entries
		          if entry.placement.sealed_by == region.name
		          and entry.placement.kind == "field"
		          and entry.placement.scalar is not None
		          and entry.placement.offset_bits is not None
		          and entry.placement.array_count is None
		          and entry.placement.sized_by is None]
		secret = [placement.path for placement in sealed
		          if any(attr.name == "secret" for attr in placement.attrs)
		          and (placement.array_count is not None
		               or placement.sized_by is not None)]

		lines = [
			"",
			f"\tclass {holder}(Gate):",
			f'\t\t"""{region.path}: reachable only through a verified open.',
			"",
			"\t\tThe refusal is a run-time one. It is not the C++ guarantee,",
			"\t\twhere forging a gate does not compile -- Python has no access",
			"\t\tcontrol, and `object.__new__` will make one of these whatever",
			'\t\tthis class says. Section 14.3, as far as Python reaches."""',
		]

		for entry in inside:
			placement = entry.placement
			scalar    = placement.scalar
			assert scalar is not None
			field_name = c_name(placement.path.rsplit(".", 1)[-1])

			if any(attr.name == "secret" for attr in placement.attrs):
				lines.extend(["",
				              f"\t\t# {field_name} is [secret]: no accessor is",
				              "\t\t# generated for it at all (section 14.6)."])
				continue

			lines.extend([
				"", "\t\t@property",
				f"\t\tdef {field_name}(self) -> {self._hint(placement)}:",
				f"\t\t\treturn {self._load(placement, scalar).replace('self.', 'self._view.')}",
			])

		for path in secret:
			lines.extend(["",
			              f"\t\t# {path} is [secret]: no accessor is generated",
			              "\t\t# for it at all (section 14.6)."])

		if not inside and not secret:
			lines.append("\t\tpass")

		lines.extend([
			"",
			f"\tdef open_{name}(self, verified: bool) -> \"{c_name(struct.name)}"
			f".{holder}\":",
			f'\t\t"""Hand out the sealed interior, and only if `verified`."""',
			f"\t\treturn open_gate(type(self).{holder}, self, verified)"
			f"  # type: ignore[return-value]",
		])
		return lines


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str | None:
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one"):
			return str(attr.name)
		if attr.name in ("preserve", "unknown"):
			return None
	return "must_be_zero"
