"""Cross-message relations in Python (26.95).

The walk is `situc.relation`'s; this decides only how Python spells one.

Two differences from the other three, and the second is the interesting one.
A sub-view is a property rather than a call with an error return, and Python
raises where C returns -- `ConstraintError` rather than
`SITU_ERR_CONSTRAINT`, which is the convention `validate` already follows.

And **no widening happens here, while the refusal that goes with it still
does.** Python's integers are arbitrary precision, so a `u64` against an `i8`
would compare perfectly well. It is refused anyway, because `situc.relation`
decides what is expressible for every backend at once: a schema that a
Python consumer could use and a C one could not is a schema that means two
things, which is what the four-way agreement tests exist to catch.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.python.emit import py_name
from situc.relation import (PYTHON, Constraint, Read, ReadBytes, SubView,
                            plans, refusals,
                            render)
from situc.resolve import ResolvedSchema
from situc import __version__

__all__ = ["generate", "refusals", "signature"]


def _local(name: str) -> str:
	return f"v{name}"


def _source(name: str) -> str:
	return _local(name) if name.startswith("_") else name


def signature(relation: ast.Relation) -> str:
	params = ", ".join(f"{param.name}: {py_name(param.type_name)}"
	                   for param in relation.params)
	return f"def rel_{py_name(relation.name)}({params}) -> None:"


def _binding(bind: SubView | Read | ReadBytes) -> list[str]:
	source = _source(bind.source)
	target = _local(bind.target)
	kind   = ("sub-view" if isinstance(bind, SubView)
	          else "bytes" if isinstance(bind, ReadBytes) else "value")
	return [f"\t{target} = {source}.{py_name(bind.member)}"
	        f"\t# {bind.path} ({kind})"]


def _body(constraints: list[Constraint]) -> list[str]:
	lines: list[str] = []

	for constraint in constraints:
		for bind in constraint.bindings:
			lines += _binding(bind)

		if constraint.bytes_equal is not None:
			same = constraint.bytes_equal
			test = "!=" if not same.negated else "=="
			lines += [
				f"\tif bytes({_local(same.left)}) {test} "
				f"bytes({_local(same.right)}):",
				"\t\traise ConstraintError(",
				f"\t\t\t{_reason(constraint)!r})",
				"",
			]
			continue

		assert constraint.expr is not None
		locals_for = {path: _local(name)
		              for path, name in constraint.locals_for.items()}
		lines += [
			f"\tif not {render(constraint.expr, locals_for, PYTHON)}:",
			"\t\traise ConstraintError(",
			f"\t\t\t{_reason(constraint)!r})",
			"",
		]

	return lines


def _reason(constraint: Constraint) -> str:
	"""What the exception says, which is the constraint in the schema's own
	words rather than the generated locals nobody wrote."""
	back = {name: path for path, name in constraint.locals_for.items()}
	assert constraint.expr is not None
	return render(constraint.expr, {path: path for path in back.values()},
	              PYTHON)


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	"""The relation module, or nothing if no relation is expressible."""
	ready = plans(schema, resolved)
	if not ready:
		return {}

	lines = [
		f'"""Generated by situc {__version__} from {basename}.situ -- do not edit.',
		"",
		"Cross-message relations: a pure predicate per relation, over two",
		"views the caller already holds. A separate module on purpose -- a",
		"rung adds files rather than changing them (decision 0032).",
		'"""',
		"",
		"from __future__ import annotations",
		"",
		"from situ_runtime import ConstraintError",
		"",
		f"from {basename} import *  # noqa: F403",
		"",
	]

	for relation, constraints in ready:
		first, second = relation.params
		lines += [
			"",
			signature(relation),
			f'\t"""Whether `{second.name}` is a well-formed counterpart to '
			f'`{first.name}`.',
			"",
			"\tPure: reads two views, holds nothing. The caller owns the",
			"\tpairing; this answers only whether one is well formed, and",
			f"\tparameter order is temporal -- `{first.name}` is the message",
			"\tseen first.",
			"",
			"\tRaises ConstraintError where a constraint does not hold, which",
			"\tis what this runtime does instead of returning a code.",
			'\t"""',
			*_body(constraints),
		]

	return {f"{basename}_relate.py": "\n".join(lines).rstrip("\n") + "\n"}
