/* probe.c -- behavioural check of generated accessors on a cross target.
 *
 * cmocka is not available for aarch64 here, so this is a self-checking program
 * with no test framework: it returns non-zero and prints the first mismatch.
 * That is enough to answer the question decision 0004 deferred to phase 4 --
 * whether the generated byte-order conversion and unaligned loads behave the
 * same on another architecture as they do on the host.
 *
 * It is built for the host as well, so a failure here is a real difference
 * rather than a bug in the probe.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "header.h"
#include "tiff.h"
#include "edges.h"

static int failures;

static void check(const char *what, uint64_t got, uint64_t want)
{
	if (got != want) {
		printf("FAIL %-28s got %llu, want %llu\n", what,
		       (unsigned long long)got, (unsigned long long)want);
		failures++;
	}
}

static void check_bytes(const char *what, const uint8_t *got, const uint8_t *w, size_t n)
{
	if (memcmp(got, w, n) != 0) {
		size_t i;

		printf("FAIL %-28s bytes differ:\n  got ", what);
		for (i = 0; i < n; i++) {
			printf("%02X", got[i]);
		}
		printf("\n  want ");
		for (i = 0; i < n; i++) {
			printf("%02X", w[i]);
		}
		printf("\n");
		failures++;
	}
}

/* Big-endian on the wire whatever the host is. */
static const uint8_t HEADER_VECTOR[SITU_HEADER_SIZE_FIXED] = {
	0x01, 0x02, 0xE8, 0x05, 0xDC, 0xDE, 0xAD, 0xBE, 0xEF,
};

static void test_header(void)
{
	uint8_t buf[SITU_HEADER_SIZE_FIXED];
	situ_msg_t msg;
	situ_view_t view;
	situ_view_t flags;

	memcpy(buf, HEADER_VECTOR, sizeof(buf));
	situ_msg_init(&msg, buf, sizeof(buf));

	check("header view", situ_header_view(&msg, 0, &view), SITU_OK);
	check("header validate", situ_header_validate(view), SITU_OK);

	/* The values must be identical on every architecture: that is what
	 * declaring a byte order buys. */
	check("version", situ_header_version_get(view), 1);
	check("type", situ_header_type_get(view), SITU_MSG_TYPE_DATA);
	check("length", situ_header_length_get(view), 1500);

	/* seq sits at offset 5 and length at 3, both odd, so these are unaligned
	 * multi-byte loads relative to the view base. That is the case most likely
	 * to differ between architectures, and the reason this probe exists. */
	check("seq", situ_header_seq_get(view), 0xDEADBEEFu);

	check("flags view", situ_header_flags_view(view, &flags), SITU_OK);
	check("urgent", situ_flags_urgent_get(flags), 1);
	check("ack", situ_flags_ack_get(flags), 1);
	check("priority", situ_flags_priority_get(flags), 5);

	situ_header_seq_set(view, 0x01020304u);
	check("seq after set", situ_header_seq_get(view), 0x01020304u);
	check("seq byte 0", buf[5], 0x01);
	check("seq byte 3", buf[8], 0x04);

	situ_flags_priority_set(flags, 2);
	check("priority after set", situ_flags_priority_get(flags), 2);
	check("neighbouring bits kept", buf[2], 0xD0);
}

static const uint8_t TIFF_LITTLE[SITU_TIFF_HEADER_SIZE_FIXED] = {
	0x49, 0x49, 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00,
};

static const uint8_t TIFF_BIG[SITU_TIFF_HEADER_SIZE_FIXED] = {
	0x4D, 0x4D, 0x00, 0x2A, 0x00, 0x00, 0x00, 0x08,
};

static void test_tiff(void)
{
	uint8_t buf[SITU_TIFF_HEADER_SIZE_FIXED];
	situ_msg_t msg;
	situ_view_t view;
	unsigned i;
	const uint8_t *vectors[2];

	vectors[0] = TIFF_LITTLE;
	vectors[1] = TIFF_BIG;

	for (i = 0; i < 2u; i++) {
		memcpy(buf, vectors[i], sizeof(buf));
		situ_msg_init(&msg, buf, sizeof(buf));
		check("Tiff view", situ_tiff_header_view(&msg, 0, &view), SITU_OK);

		/* Both orders decode to the same values on every host: the branch is
		 * on the marker in the buffer, never on the build. */
		check("tiff magic", situ_tiff_header_magic_get(view), 42);
		check("tiff ifd", situ_tiff_header_ifd_offset_get(view), 8);

		situ_tiff_header_magic_set(view, 42);
		situ_tiff_header_ifd_offset_set(view, 8);
		check_bytes("tiff round-trip", buf, vectors[i], sizeof(buf));
	}

	/* And the host constant follows the build, not the data. */
	memset(buf, 0, sizeof(buf));
	situ_msg_init(&msg, buf, sizeof(buf));
	check("Tiff view", situ_tiff_header_view(&msg, 0, &view), SITU_OK);
	situ_tiff_header_byte_order_set_host(view);
	situ_tiff_header_magic_set(view, 42);
	situ_tiff_header_ifd_offset_set(view, 8);

	if (situ_tiff_header_byte_order_is_little(view)) {
		check_bytes("host writer little", buf, TIFF_LITTLE, sizeof(buf));
	} else {
		check_bytes("host writer big", buf, TIFF_BIG, sizeof(buf));
	}
}

/* Section 8.6 and 19.4, on a second architecture.
 *
 * The scan is byte-oriented and the digits are ASCII, so none of this should
 * depend on the host's byte order -- and "should not" is the claim this
 * directory exists to stop anyone making without checking. What could
 * genuinely differ is the offset arithmetic, which is uint32_t throughout and
 * feeds a pointer.
 */
static void test_framed(void)
{
	/* "SITU" | "1.0" CRLF | "abc" NUL | count */
	static const uint8_t FRAME[] = {
		'S', 'I', 'T', 'U',
		'1', '.', '0', 0x0D, 0x0A,
		'a', 'b', 'c', 0x00,
		0x12, 0x34,
	};
	uint8_t     buf[sizeof(FRAME)];
	situ_msg_t  msg;
	situ_view_t view;

	memcpy(buf, FRAME, sizeof(buf));
	situ_msg_init(&msg, buf, (uint32_t)sizeof(buf));
	check("framed view",
	      situ_framed_view(&msg, 0, (uint32_t)sizeof(buf), &view), SITU_OK);

	check("version len", situ_framed_version_len(view), 3);
	check("version terminated",
	      (uint64_t)situ_framed_version_terminated(view), 1);
	check("version span", situ_framed_version_span(view), 5);
	check("label len", situ_framed_label_len(view), 3);

	/* The one that is not obviously portable: a member found by two scans,
	 * read as a big-endian word. */
	check("count offset", situ_framed_count_offset(view), 13);
	check("count", situ_framed_count_get(view), 0x1234);
	check("framed validate", situ_framed_validate(view), SITU_OK);
}

static void test_text_number(void)
{
	static const uint8_t DIGITS[] = { '4', '2', 0x0D, 0x0A, 'x', 'y' };
	uint8_t     buf[sizeof(DIGITS)];
	situ_msg_t  msg;
	situ_view_t view;
	uint16_t    parsed = 0;

	memcpy(buf, DIGITS, sizeof(buf));
	situ_msg_init(&msg, buf, (uint32_t)sizeof(buf));
	check("texty view",
	      situ_texty_view(&msg, 0, (uint32_t)sizeof(buf), &view), SITU_OK);

	check("digits parse", situ_texty_count_get(view, &parsed), SITU_OK);
	check("digits value", parsed, 42);

	/* The message says 42 and carries 2. This asserted 42 -- the number the
	 * message claims -- beside a pointer at the frame base, which is the
	 * out-of-bounds read a fuzzer found on the same shape elsewhere. The
	 * accessor now reports what is there, and `validate` reports that the
	 * message is malformed rather than short. */
	check("body length", situ_texty_body_len(view), 2);
	check("texty validate", situ_texty_validate(view), SITU_ERR_BOUNDS);
}

static void test_versioned(void)
{
	static const uint8_t V1[] = { 1, 0x00, 0x05 };
	uint8_t     buf[16];
	situ_msg_t  msg;
	situ_view_t view;
	uint32_t    flags = 0;

	memset(buf, 0, sizeof(buf));
	memcpy(buf, V1, sizeof(V1));
	situ_msg_init(&msg, buf, (uint32_t)sizeof(V1));
	check("versioned view",
	      situ_versioned_view(&msg, 0, (uint32_t)sizeof(V1), &view), SITU_OK);

	check("v1 length", situ_versioned_length_get(view), 5);
	check("v1 refuses flags",
	      situ_versioned_flags_get(view, &flags), SITU_ERR_VERSION);
}

/* Section 8.6.6, on a second architecture.
 *
 * The walk itself is byte arithmetic and should not care about byte order.
 * What could differ is the element extent -- `(units + 1) * 4 - 2` over a u8
 * field, which is correct in C only because integer promotion widens the read
 * to `int` before the arithmetic. That is a rule, not an accident, but it is
 * a rule worth checking on a target with different register widths.
 */
static void test_linked(void)
{
	static const uint8_t CHAIN[] = {
		0x11, 0,  1, 2,           /* kind 0x11, (0+1)*4-2 = 2 body bytes  */
		0x22, 1,  3, 4, 5, 6, 7, 8,   /* kind 0x22, 6 body bytes          */
		0x33, 0,  9, 10,          /* kind 0x33 ends the run, and is in it */
		'T', 'A', 'I', 'L',
	};
	uint8_t     buf[sizeof(CHAIN)];
	situ_msg_t  msg;
	situ_view_t view;
	situ_view_t element;

	memcpy(buf, CHAIN, sizeof(buf));
	situ_msg_init(&msg, buf, (uint32_t)sizeof(buf));
	check("linked view",
	      situ_linked_view(&msg, 0, (uint32_t)sizeof(buf), &view), SITU_OK);

	/* Three, and the third is the one that ended it. */
	check("chain count", situ_linked_chain_count(view), 3);
	check("chain span", situ_linked_chain_span(view), 16);

	check("element 0", situ_linked_chain_at(view, 0u, &element), SITU_OK);
	check("element 0 extent", situ_link_extent(element), 4);
	check("element 1", situ_linked_chain_at(view, 1u, &element), SITU_OK);
	check("element 1 extent", situ_link_extent(element), 8);

	check("past the end", situ_linked_chain_at(view, 3u, &element),
	      SITU_ERR_BOUNDS);
	check("tail length", situ_linked_tail_len(view), 4);
}

int main(void)
{
	test_header();
	test_tiff();
	test_linked();
	test_framed();
	test_text_number();
	test_versioned();

	if (failures != 0) {
		printf("%d check(s) failed\n", failures);
		return 1;
	}

	printf("all checks passed\n");
	return 0;
}
