/* probe.c -- behavioural check of generated accessors on a cross target.
 *
 * cmocka is not available for aarch64 here, so this is a self-checking program
 * with no test framework: it returns non-zero and prints the first mismatch.
 * That is enough to answer the question decision 0004 deferred to phase 4 --
 * whether the generated byte-order conversion and unaligned loads behave the
 * same on another architecture as they do on the host.
 *
 * It is built for the host as well, so a failure here is a real difference
 * rather than a bug in the probe.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "header.h"
#include "tiff.h"

static int failures;

static void check(const char *what, uint64_t got, uint64_t want)
{
	if (got != want) {
		printf("FAIL %-28s got %llu, want %llu\n", what,
		       (unsigned long long)got, (unsigned long long)want);
		failures++;
	}
}

static void check_bytes(const char *what, const uint8_t *got, const uint8_t *w, size_t n)
{
	if (memcmp(got, w, n) != 0) {
		size_t i;

		printf("FAIL %-28s bytes differ:\n  got ", what);
		for (i = 0; i < n; i++) {
			printf("%02X", got[i]);
		}
		printf("\n  want ");
		for (i = 0; i < n; i++) {
			printf("%02X", w[i]);
		}
		printf("\n");
		failures++;
	}
}

/* Big-endian on the wire whatever the host is. */
static const uint8_t HEADER_VECTOR[SITU_HEADER_SIZE_FIXED] = {
	0x01, 0x02, 0xE8, 0x05, 0xDC, 0xDE, 0xAD, 0xBE, 0xEF,
};

static void test_header(void)
{
	uint8_t buf[SITU_HEADER_SIZE_FIXED];
	situ_msg_t msg;
	situ_view_t view;
	situ_view_t flags;

	memcpy(buf, HEADER_VECTOR, sizeof(buf));
	situ_msg_init(&msg, buf, sizeof(buf));

	check("Header view", situ_Header_view(&msg, 0, &view), SITU_OK);
	check("Header validate", situ_Header_validate(view), SITU_OK);

	/* The values must be identical on every architecture: that is what
	 * declaring a byte order buys. */
	check("version", situ_Header_version_get(view), 1);
	check("type", situ_Header_type_get(view), SITU_MSGTYPE_DATA);
	check("length", situ_Header_length_get(view), 1500);

	/* seq sits at offset 5 and length at 3, both odd, so these are unaligned
	 * multi-byte loads relative to the view base. That is the case most likely
	 * to differ between architectures, and the reason this probe exists. */
	check("seq", situ_Header_seq_get(view), 0xDEADBEEFu);

	check("flags view", situ_Header_flags_view(view, &flags), SITU_OK);
	check("urgent", situ_Flags_urgent_get(flags), 1);
	check("ack", situ_Flags_ack_get(flags), 1);
	check("priority", situ_Flags_priority_get(flags), 5);

	situ_Header_seq_set(view, 0x01020304u);
	check("seq after set", situ_Header_seq_get(view), 0x01020304u);
	check("seq byte 0", buf[5], 0x01);
	check("seq byte 3", buf[8], 0x04);

	situ_Flags_priority_set(flags, 2);
	check("priority after set", situ_Flags_priority_get(flags), 2);
	check("neighbouring bits kept", buf[2], 0xD0);
}

static const uint8_t TIFF_LITTLE[SITU_TIFFHEADER_SIZE_FIXED] = {
	0x49, 0x49, 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00,
};

static const uint8_t TIFF_BIG[SITU_TIFFHEADER_SIZE_FIXED] = {
	0x4D, 0x4D, 0x00, 0x2A, 0x00, 0x00, 0x00, 0x08,
};

static void test_tiff(void)
{
	uint8_t buf[SITU_TIFFHEADER_SIZE_FIXED];
	situ_msg_t msg;
	situ_view_t view;
	unsigned i;
	const uint8_t *vectors[2];

	vectors[0] = TIFF_LITTLE;
	vectors[1] = TIFF_BIG;

	for (i = 0; i < 2u; i++) {
		memcpy(buf, vectors[i], sizeof(buf));
		situ_msg_init(&msg, buf, sizeof(buf));
		check("Tiff view", situ_TiffHeader_view(&msg, 0, &view), SITU_OK);

		/* Both orders decode to the same values on every host: the branch is
		 * on the marker in the buffer, never on the build. */
		check("tiff magic", situ_TiffHeader_magic_get(view), 42);
		check("tiff ifd", situ_TiffHeader_ifd_offset_get(view), 8);

		situ_TiffHeader_magic_set(view, 42);
		situ_TiffHeader_ifd_offset_set(view, 8);
		check_bytes("tiff round-trip", buf, vectors[i], sizeof(buf));
	}

	/* And the host constant follows the build, not the data. */
	memset(buf, 0, sizeof(buf));
	situ_msg_init(&msg, buf, sizeof(buf));
	check("Tiff view", situ_TiffHeader_view(&msg, 0, &view), SITU_OK);
	situ_TiffHeader_byte_order_set_host(view);
	situ_TiffHeader_magic_set(view, 42);
	situ_TiffHeader_ifd_offset_set(view, 8);

	if (situ_TiffHeader_byte_order_is_little(view)) {
		check_bytes("host writer little", buf, TIFF_LITTLE, sizeof(buf));
	} else {
		check_bytes("host writer big", buf, TIFF_BIG, sizeof(buf));
	}
}

int main(void)
{
	test_header();
	test_tiff();

	if (failures != 0) {
		printf("%d check(s) failed\n", failures);
		return 1;
	}

	printf("all checks passed\n");
	return 0;
}
