"""The arithmetic a derived kernel implies, with no language in it.

Every backend that generates a codec needs the same numbers: the CRC table
a polynomial defines, the accumulator a width needs, the bit-reversal a
reflected variant starts from. Those are facts about the kernel, not about
C or Rust or Python, and the first two backends to want them would
otherwise have carried a copy each.

That is invariant 13's rule and it has already been paid for here: four
copies of one struct walk became `traverse`, and the four bugs of 26.225
to 26.228 were what a fifth copy cost. A CRC table computed twice is the
same shape with a worse failure -- two backends whose digests differ for a
reason no test would name.
"""

from __future__ import annotations

from situc import ast

#: The machine words a generated accumulator may use. A width narrower than
#: its word is masked back after every shift.
WORD_WIDTHS = (8, 16, 32, 64)


def crc_width(decl: ast.CodecDecl) -> int | None:
	"""A CRC width a backend can generate: 1 through 64.

	`None` where the width is not a literal or not in range, which is a
	kernel described correctly and not generated -- the caller emits a note
	rather than wrong code.

	Whole bytes only until 0046, which is the gate that decided whether an
	implementation was emitted AT ALL, for every backend at once. USB's
	five-bit CRC, MMC's seven and CAN's fifteen were all described correctly
	and generated by nobody.
	"""
	kernel = decl.kernel
	assert kernel is not None
	value = kernel.argument("width")
	width = value.value if isinstance(value, ast.IntLiteral) else None
	if width is None or not 1 <= width <= 64:
		return None
	# A NON-reflected code narrower than the byte it consumes runs
	# left-aligned: the register sits at the top of a byte, the table is
	# built from a shifted polynomial, and the result is shifted back at the
	# end. `crc_shift` is that offset and the three places that need it ask
	# for it -- the table, the register's start, and the final value.
	#
	# The reflected form needs none of it at any width: it consumes the byte
	# with right shifts and masks to the width. So `crc5_usb` always worked
	# and `crc7_mmc` is what this arithmetic was written for (0046, 26.369).
	return width


def accumulator(width: int) -> int:
	"""The word that holds a `width`-bit CRC: the next one up, or its own.

	A 24-bit CRC accumulates in a 32-bit word and every shift is masked back
	to 24 bits. No language here has a 24-bit integer, and inventing one
	would buy nothing a mask does not.
	"""
	return next(word for word in WORD_WIDTHS if word >= width)


def number(decl: ast.CodecDecl, name: str, default: int = 0) -> int:
	"""One of the kernel's integer arguments, or a default."""
	kernel = decl.kernel
	assert kernel is not None
	value = kernel.argument(name)
	return value.value if isinstance(value, ast.IntLiteral) else default


def reverse(value: int, width: int) -> int:
	"""`value` with its low `width` bits in the opposite order."""
	result = 0
	for _ in range(width):
		result = (result << 1) | (value & 1)
		value >>= 1
	return result


def crc_table(width: int, poly: int, reflect: bool) -> list[int]:
	"""One byte's worth of the polynomial division, for each possible byte.

	Reflected variants run the division the other way round, which is the
	same arithmetic over the bit-reversed polynomial. Doing it here rather
	than reversing bits at run time is what keeps the generated loop one
	table lookup wide.
	"""
	mask  = (1 << width) - 1
	table = []

	if reflect:
		reversed_poly = reverse(poly, width)
		for byte in range(256):
			crc = byte
			for _ in range(8):
				crc = (crc >> 1) ^ (reversed_poly if crc & 1 else 0)
			table.append(crc & mask)
		return table

	# Narrower than the byte it consumes: the register is left-aligned at the
	# top of a byte and so is the polynomial, which makes the loop the same
	# one the width-8 case runs. `byte << (width - 8)` cannot express it --
	# the shift is negative -- which is the arithmetic `crc_width` used to
	# decline rather than write (26.369).
	shift = crc_shift(width, reflect)
	if shift:
		aligned = (poly << shift) & 0xFF
		for byte in range(256):
			crc = byte
			for _ in range(8):
				crc = (((crc << 1) ^ aligned) & 0xFF if crc & 0x80
				       else (crc << 1) & 0xFF)
			table.append(crc)
		return table

	top = 1 << (width - 1)
	for byte in range(256):
		crc = (byte << (width - 8)) & mask
		for _ in range(8):
			crc = ((crc << 1) ^ poly) & mask if crc & top else (crc << 1) & mask
		table.append(crc)
	return table


def crc_start(init: int, width: int, reflect: bool) -> int:
	"""The register's initial value, in the direction the loop runs it.

	A reflected CRC runs the register the other way round, so it *starts*
	the other way round. Emitting the catalogue's value as written was right
	for every reflected CRC in the library -- CRC-32 and CRC-16/MODBUS both
	start all-ones, which is its own reverse -- and wrong for the first one
	that does not. CRC-24/BLE starts at 0x555555 and came out as 0xD39857
	where the catalogue says 0xC25A56.
	"""
	if reflect:
		return reverse(init, width)
	# And a left-aligned register starts left-aligned, for the same reason:
	# the loop runs in the register's units, not the catalogue's (26.369).
	return (init << crc_shift(width, reflect)) & 0xFF if width < 8 else init


def crc_shift(width: int, reflect: bool) -> int:
	"""How far left a register sits inside its word, in bits.

	Zero everywhere except a non-reflected code narrower than a byte, which
	runs at the top of one: the polynomial, the table and the initial value
	are all shifted up by this, and the result is shifted back down before
	the final xor. A reflected code runs the other way and needs none of it
	at any width.
	"""
	return 8 - width if width < 8 and not reflect else 0


def crc_register(width: int, reflect: bool) -> int:
	"""The word the loop runs the register in, in bits.

	The same as `accumulator` except where the register is left-aligned in a
	byte: there it is 8 whatever the code's width, which is what a backend
	formatting a table entry or an initial value has to write.
	"""
	return 8 if crc_shift(width, reflect) else accumulator(width)


# ---------------------------------------------------------------------------
# Reed-Solomon: the part that is not a spelling
# ---------------------------------------------------------------------------
#
# Here for the reason the CRC table is: a table computed twice is the same
# shape with a worse failure. These two are the whole of Reed-Solomon that
# does not depend on a target language -- 39 lines against the 250 of C
# that `c/derived.py` spells, which is the measurement 26.457 rests on.
#
# Moved out of `c/derived.py` unchanged (26.461). It buys nothing today,
# C being the only backend that generates the family; it is the half of
# the port that 0017's "a second backend re-spells; it does not re-derive"
# already covers, done first so that what remains is stated exactly: the
# decoder, whose Berlekamp-Massey, Chien search and Forney's formula exist
# nowhere in this repository except as C text inside string literals.


def gf_tables(field: int, primitive: int) -> tuple[list[int], list[int]]:
	"""Antilog and log for GF(2^m), generated from the primitive polynomial.

	The antilog table is doubled so a product of two logs can be looked up
	without a modulo, which is the usual trick and the reason the generated
	multiply is two loads and an add.
	"""
	size   = field - 1
	exp    = [0] * (2 * field)
	log    = [0] * field
	value  = 1

	for power in range(size):
		exp[power] = value
		log[value] = power
		value <<= 1
		if value & field:
			value ^= primitive

	for power in range(size, 2 * size):
		exp[power] = exp[power - size]

	return exp, log


def rs_generator_coefficients(nroots: int, first_root: int, exp: list[int],
		log: list[int], size: int) -> list[int]:
	"""Multiply out (x - alpha^(first_root + i)) for each root."""
	poly = [1]

	for root in range(nroots):
		alpha = exp[(first_root + root) % size]
		shifted = poly + [0]

		for at in range(len(poly)):
			if poly[at] and alpha:
				shifted[at + 1] ^= exp[(log[poly[at]] + log[alpha]) % size]

		poly = shifted

	return poly
