"""Matching a reply to its request in Rust (26.97).

Two things Rust decides differently, and neither is spelling.

`match` is a keyword, so the taking half is `take` -- which is the better
name anyway and the one `Option::take` already establishes: it returns what
was pending and leaves nothing behind, which is exactly why a duplicate reply
is refused.

The table holds a `u64` key and a `u32` handle and borrows nothing, so
ownership has no opinion about it. That is worth stating because it is the
first rung where it could have: had the table kept the request's *bytes*, the
borrow checker would have made a caller-supplied slice outlive every call
into it, and the design would have had to change rather than be translated.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.rust.emit import _ident, _pascal
from situc.relation import Read, Refused, Side, key_sides
from situc.resolve import ResolvedSchema

__all__ = ["generate", "refusals"]


def refusals(schema: ast.Schema,
		resolved: ResolvedSchema) -> list[tuple[str, str]]:
	found = []
	for relation in schema.relations():
		try:
			key_sides(relation, resolved)
		except Refused as why:
			found.append((relation.name, str(why)))
	return found


def _key(sides: Side, view: str) -> list[str]:
	lines = ["\t\tlet mut key: u64 = 0;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, Read):
				lines.append(f"\t\tkey = (key << {width}) | "
				             f"u64::from({source}.{_ident(step.member)}());"
				             f"\t// {step.path}")
			else:
				lines.append(f"\t\tlet {_ident(step.member)} = "
				             f"{source}.{_ident(step.member)}()?;")
				source = _ident(step.member)
	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	ready = []
	for relation in schema.relations():
		try:
			ready.append((relation, key_sides(relation, resolved)))
		except Refused:
			continue
	if not ready:
		return {}

	lines = [
		f"// Generated by situc from {basename}.situ -- do not edit.",
		"//",
		"// Conversations: a pending table per relation, matching a reply to",
		"// the request it answers. The schema states the pairing and this",
		"// holds the set. A separate module -- a rung adds files rather than",
		"// changing them (decision 0032).",
		"",
		f"use crate::{basename}::*;",
		"use crate::situ_rt::{Error, Result};",
		"",
	]

	for relation, (request, response) in ready:
		held  = _pascal(relation.name)
		first, second = relation.params
		lines += [
			f"/// Pending requests for `{relation.name}`.",
			"///",
			"/// The slots are yours and so is their number: a full table",
			"/// answers `Error::Bounds` rather than evicting an exchange you",
			"/// still wanted. Nothing is allocated.",
			"#[derive(Clone, Copy, Default)]",
			f"pub struct {held}Slot {{",
			"\tkey: u64,",
			"\tid: u32,",
			"\tlive: bool,",
			"}",
			"",
			f"pub struct {held}Table<'a> {{",
			f"\tslots: &'a mut [{held}Slot],",
			"}",
			"",
			f"impl<'a> {held}Table<'a> {{",
			f"\tpub fn new(slots: &'a mut [{held}Slot]) -> Self {{",
			"\t\tfor slot in slots.iter_mut() {",
			"\t\t\tslot.live = false;",
			"\t\t}",
			"\t\tSelf { slots }",
			"\t}",
			"",
			f"\t/// Remember `{first.name}` under its key.",
			f"\tpub fn record(&mut self, {first.name}: &"
			f"{_pascal(first.type_name)}, id: u32) -> Result<()> {{",
			*_key(request, first.name),
			"",
			"\t\tfor slot in self.slots.iter_mut() {",
			"\t\t\tif !slot.live {",
			"\t\t\t\t*slot = Self::held(key, id);",
			"\t\t\t\treturn Ok(());",
			"\t\t\t}",
			"\t\t}",
			"\t\tErr(Error::Bounds)",
			"\t}",
			"",
			f"\t/// Take the request `{second.name}` answers, and forget it.",
			"\t///",
			"\t/// `take` rather than `match`, which is a keyword -- and the",
			"\t/// better name: it leaves nothing behind, which is why a",
			"\t/// duplicate reply answers `Error::Constraint`.",
			f"\tpub fn take(&mut self, {second.name}: &"
			f"{_pascal(second.type_name)}) -> Result<u32> {{",
			*_key(response, second.name),
			"",
			"\t\tfor slot in self.slots.iter_mut() {",
			"\t\t\tif slot.live && slot.key == key {",
			"\t\t\t\tslot.live = false;",
			"\t\t\t\treturn Ok(slot.id);",
			"\t\t\t}",
			"\t\t}",
			"\t\tErr(Error::Constraint)",
			"\t}",
			"",
			f"\tfn held(key: u64, id: u32) -> {held}Slot {{",
			f"\t\t{held}Slot {{ key, id, live: true }}",
			"\t}",
			"}",
			"",
		]

	return {f"{basename}_converse.rs": "\n".join(lines).rstrip("\n") + "\n"}
