"""Matching a reply to its request in Rust (26.97).

Two things Rust decides differently, and neither is spelling.

`match` is a keyword, so the taking half is `take` -- which is the better
name anyway and the one `Option::take` already establishes: it returns what
was pending and leaves nothing behind, which is exactly why a duplicate reply
is refused.

The table holds a `u64` key and a `u32` handle and borrows nothing, so
ownership has no opinion about it. That is worth stating because it is the
first rung where it could have: had the table kept the request's *bytes*, the
borrow checker would have made a caller-supplied slice outlive every call
into it, and the design would have had to change rather than be translated.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.rust.emit import _ident, _pascal, numeric_accessor
from situc.relation import Read, KeyLayout, ReadBytes, Refused, Side, SubView, key_layout
from situc.resolve import ResolvedSchema
from situc import __version__

__all__ = ["generate", "refusals"]


def refusals(schema: ast.Schema,
		resolved: ResolvedSchema) -> list[tuple[str, str]]:
	found = []
	for relation in schema.relations():
		try:
			key_layout(relation, resolved)
		except Refused as why:
			found.append((relation.name, str(why)))
	return found


def _key(sides: Side, view: str, resolved: ResolvedSchema) -> list[str]:
	lines = ["\t\tlet mut key: u64 = 0;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, Read):
				# `_bits` where the member is an enum: its getter answers
				# `Option<T>` and `u64::from` has no such impl, so a relation
				# keyed on one did not compile at all.
				read = numeric_accessor(resolved, step.struct, step.member)
				lines.append(f"\t\tkey = (key << {width}) | "
				             f"u64::from({source}.{read}());"
				             f"\t// {step.path}")
			elif isinstance(step, SubView):
				lines.append(f"\t\tlet {_ident(step.member)} = "
				             f"{source}.{_ident(step.member)}()?;")
				source = _ident(step.member)
	return lines


def _key_bytes(sides: Side, view: str, total: int,
		resolved: ResolvedSchema) -> list[str]:
	"""The exact-bytes key (0042), Rust's spelling. `[u8; N]` copies and
	compares by value, so the slot needs no other change."""
	lines = [f"\t\tlet mut key = [0u8; {total}];",
	         "\t\tlet mut at = 0usize;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, ReadBytes):
				count = width // 8
				lines += [
					f"\t\tkey[at..at + {count}].copy_from_slice("
					f"{source}.{_ident(step.member)}());\t// {step.path}",
					f"\t\tat += {count};",
				]
			elif isinstance(step, Read):
				count = (width + 7) // 8
				read = numeric_accessor(resolved, step.struct, step.member)
				lines += [
					f"\t\tlet v = u64::from({source}."
					f"{read}());\t// {step.path}",
					f"\t\tfor b in 0..{count} {{",
					f"\t\t\tkey[at + b] = (v >> (8 * ({count} - 1 - b))) as u8;",
					"\t\t}",
					f"\t\tat += {count};",
				]
			elif isinstance(step, SubView):
				lines.append(f"\t\tlet {_ident(step.member)} = "
				             f"{source}.{_ident(step.member)}()?;")
				source = _ident(step.member)
	lines.append("\t\tlet _ = at;")
	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	ready = []
	for relation in schema.relations():
		try:
			ready.append((relation, key_layout(relation, resolved)))
		except Refused:
			continue
	if not ready:
		return {}

	lines = [
		f"// Generated by situc {__version__} from {basename}.situ -- do not edit.",
		"//",
		"// Conversations: a pending table per relation, matching a reply to",
		"// the request it answers. The schema states the pairing and this",
		"// holds the set. A separate module -- a rung adds files rather than",
		"// changing them (decision 0032).",
		"",
		f"use crate::{basename}::*;",
		"use crate::situ_rt::{Error, Result};",
		"",
	]

	for relation, layout in ready:
		request, response = layout.request, layout.response
		held  = _pascal(relation.name)
		first, second = relation.params
		lines += [
			f"/// Pending requests for `{relation.name}`.",
			"///",
			"/// The slots are yours and so is their number: a full table",
			"/// answers `Error::Bounds` rather than evicting an exchange you",
			"/// still wanted. Nothing is allocated.",
			"#[derive(Clone, Copy, Default)]",
			f"pub struct {held}Slot {{",
			("\tkey: u64," if layout.packed
			 else f"\tkey: [u8; {layout.total_bytes}],"),
			"\tid: u32,",
			"\tlive: bool,",
			"}",
			"",
			f"pub struct {held}Table<'a> {{",
			f"\tslots: &'a mut [{held}Slot],",
			"}",
			"",
			f"impl<'a> {held}Table<'a> {{",
			f"\tpub fn new(slots: &'a mut [{held}Slot]) -> Self {{",
			"\t\tfor slot in slots.iter_mut() {",
			"\t\t\tslot.live = false;",
			"\t\t}",
			"\t\tSelf { slots }",
			"\t}",
			"",
			f"\t/// Remember `{first.name}` under its key.",
			f"\tpub fn record(&mut self, {first.name}: &"
			f"{_pascal(first.type_name)}, id: u32) -> Result<()> {{",
			*(_key(request, first.name, resolved) if layout.packed
			  else _key_bytes(request, first.name, layout.total_bytes,
			                  resolved)),
			"",
			"\t\tfor slot in self.slots.iter_mut() {",
			"\t\t\tif !slot.live {",
			"\t\t\t\t*slot = Self::held(key, id);",
			"\t\t\t\treturn Ok(());",
			"\t\t\t}",
			"\t\t}",
			"\t\tErr(Error::Bounds)",
			"\t}",
			"",
			f"\t/// Take the request `{second.name}` answers, and forget it.",
			"\t///",
			"\t/// `take` rather than `match`, which is a keyword -- and the",
			"\t/// better name: it leaves nothing behind, which is why a",
			"\t/// duplicate reply answers `Error::Constraint`.",
			f"\tpub fn take(&mut self, {second.name}: &"
			f"{_pascal(second.type_name)}) -> Result<u32> {{",
			*(_key(response, second.name, resolved) if layout.packed
			  else _key_bytes(response, second.name, layout.total_bytes,
			                  resolved)),
			"",
			"\t\tfor slot in self.slots.iter_mut() {",
			"\t\t\tif slot.live && slot.key == key {",
			"\t\t\t\tslot.live = false;",
			"\t\t\t\treturn Ok(slot.id);",
			"\t\t\t}",
			"\t\t}",
			"\t\tErr(Error::Constraint)",
			"\t}",
			"",
			(f"\tfn held(key: u64, id: u32) -> {held}Slot {{"
			 if layout.packed else
			 f"\tfn held(key: [u8; {layout.total_bytes}], id: u32) -> {held}Slot {{"),
			f"\t\t{held}Slot {{ key, id, live: true }}",
			"\t}",
			"}",
			"",
		]

	return {f"{basename}_converse.rs": "\n".join(lines).rstrip("\n") + "\n"}
