"""Retransmission in Rust (26.98).

Two structural differences from C, both forced rather than chosen.

**The slot is lifetime-parameterised**, because it holds the bytes to
retransmit and Rust will not let that be a raw pointer the caller merely
promises not to move. `Slot<'a>` borrows them, so the compiler enforces what
the C header can only write in capitals -- and the driver takes two
lifetimes, `&'s mut [Slot<'a>]`, rather than one: a single `&'a mut [Slot<'a>]`
is invariant in `'a` and would make the table unusable at almost every call
site.

**The driver keeps its own key rather than borrowing rung 5's table.** The C
version composes with `converse` because both are plain structs; here that
would be a second mutable borrow threaded through every method for no gain,
so the slot carries the key itself. Same information, one borrow.

I/O is a trait, not a struct of function pointers. A vtable is C's way of
saying "the caller supplies this", and emitting one into Rust would be C
leaking through.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.rust.emit import _ident, _pascal
from situc.relation import Read, KeyLayout, ReadBytes, Refused, Side, SubView, key_layout
from situc.resolve import ResolvedSchema
from situc import __version__

__all__ = ["generate"]


def _policy(relation: ast.Relation) -> tuple[int, int] | None:
	found = {}
	for attr in relation.attrs:
		value = getattr(attr.value, "value", None)
		if attr.name in ("timeout_ms", "retries") and isinstance(value, int):
			found[attr.name] = value
	return (found["timeout_ms"], found["retries"]) if len(found) == 2 else None


def _key_bytes(sides: Side, view: str, indent: str,
		total: int) -> list[str]:
	"""The exact-bytes key (0042); see the converse twin for the layout."""
	lines = [f"{indent}let mut key = [0u8; {total}];",
	         f"{indent}let mut at = 0usize;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, ReadBytes):
				count = width // 8
				lines += [
					f"{indent}key[at..at + {count}].copy_from_slice("
					f"{source}.{_ident(step.member)}());\t// {step.path}",
					f"{indent}at += {count};",
				]
			elif isinstance(step, Read):
				count = (width + 7) // 8
				lines += [
					f"{indent}let v = u64::from({source}."
					f"{_ident(step.member)}());\t// {step.path}",
					f"{indent}for b in 0..{count} {{",
					f"{indent}\tkey[at + b] = (v >> (8 * ({count} - 1 - b))) as u8;",
					f"{indent}}}",
					f"{indent}at += {count};",
				]
			elif isinstance(step, SubView):
				lines.append(f"{indent}let {_ident(step.member)} = "
				             f"{source}.{_ident(step.member)}()?;")
				source = _ident(step.member)
	lines.append(f"{indent}let _ = at;")
	return lines


def _key(sides: Side, view: str, indent: str) -> list[str]:
	lines = [f"{indent}let mut key: u64 = 0;"]
	for chain, width in sides:
		source = view
		for step in chain:
			if isinstance(step, Read):
				lines.append(f"{indent}key = (key << {width}) | "
				             f"u64::from({source}.{_ident(step.member)}());")
			elif isinstance(step, SubView):
				lines.append(f"{indent}let {_ident(step.member)} = "
				             f"{source}.{_ident(step.member)}()?;")
				source = _ident(step.member)
	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	ready = []
	for relation in schema.relations():
		policy = _policy(relation)
		if policy is None:
			continue
		try:
			ready.append((relation, policy, key_layout(relation, resolved)))
		except Refused:
			continue
	if not ready:
		return {}

	lines = [
		f"// Generated by situc {__version__} from {basename}.situ -- do not edit.",
		"//",
		"// Retransmission and timeout. Owns I/O through a trait you",
		"// implement and never owns the clock: every entry point takes",
		"// `now_ms` and `step` says when to come back. Nothing allocates.",
		"",
		f"use crate::{basename}::*;",
		"use crate::situ_rt::{Error, Result};",
		"",
		"/// Where the bytes go. Yours, so a test substitutes a transcript and",
		"/// never opens a socket -- which is also how loss, reorder and",
		"/// duplication are injected without a network.",
		"pub trait Io {",
		"\tfn submit(&mut self, data: &[u8]) -> Result<()>;",
		"}",
		"",
	]

	for relation, (timeout, retries), layout in ready:
		request, response = layout.request, layout.response
		held = _pascal(relation.name)
		first, second = relation.params
		req  = _pascal(first.type_name)
		resp = _pascal(second.type_name)
		lines += [
			f"pub const {held.upper()}_TIMEOUT_MS: u32 = {timeout};",
			f"pub const {held.upper()}_RETRIES: u32 = {retries};",
			"",
			f"/// One outstanding `{relation.name}`.",
			"///",
			"/// `'a` is the retransmission's bytes. They are borrowed rather",
			"/// than pointed at, so the compiler enforces what the C header",
			"/// can only warn about.",
			"#[derive(Clone, Copy)]",
			f"pub struct {held}Slot<'a> {{",
			"\tbytes: &'a [u8],",
			("\tkey: u64," if layout.packed
			 else f"\tkey: [u8; {layout.total_bytes}],"),
			"\tid: u32,",
			"\tdeadline_ms: u32,",
			"\tleft: u32,",
			"\tlive: bool,",
			"}",
			"",
			f"impl Default for {held}Slot<'_> {{",
			"\tfn default() -> Self {",
			("\t\tSelf { bytes: &[], key: 0, id: 0, deadline_ms: 0,"
			 if layout.packed else
			 f"\t\tSelf {{ bytes: &[], key: [0u8; {layout.total_bytes}], "
			 "id: 0, deadline_ms: 0,"),
			"\t\t       left: 0, live: false }",
			"\t}",
			"}",
			"",
			f"/// Retransmission for `{relation.name}`.",
			"///",
			"/// Two lifetimes on purpose: `'s` is the slot array and `'a` the",
			"/// bytes it holds. One would be invariant and unusable.",
			f"pub struct {held}Driver<'s, 'a, I: Io> {{",
			f"\tslots: &'s mut [{held}Slot<'a>],",
			"\tio: I,",
			"\ttimeout_ms: u32,",
			"\tretries: u32,",
			"}",
			"",
			f"impl<'s, 'a, I: Io> {held}Driver<'s, 'a, I> {{",
			f"\tpub fn new(slots: &'s mut [{held}Slot<'a>], io: I,",
			"\t           timeout_ms: u32, retries: u32) -> Self {",
			"\t\tfor slot in slots.iter_mut() {",
			"\t\t\tslot.live = false;",
			"\t\t}",
			"\t\tSelf { slots, io, timeout_ms, retries }",
			"\t}",
			"",
			f"\t/// Send `{first.name}` and remember it until it is answered.",
			f"\tpub fn send(&mut self, {first.name}: &{req}, bytes: &'a [u8],",
			"\t            id: u32, now_ms: u32) -> Result<()> {",
			*(_key(request, first.name, "\t\t") if layout.packed
			  else _key_bytes(request, first.name, "\t\t", layout.total_bytes)),
			"",
			"\t\tfor slot in self.slots.iter_mut() {",
			"\t\t\tif !slot.live {",
			f"\t\t\t\t*slot = {held}Slot {{",
			"\t\t\t\t\tbytes, key, id,",
			"\t\t\t\t\tdeadline_ms: now_ms + self.timeout_ms,",
			"\t\t\t\t\tleft: self.retries, live: true,",
			"\t\t\t\t};",
			"\t\t\t\treturn self.io.submit(bytes);",
			"\t\t\t}",
			"\t\t}",
			"\t\tErr(Error::Bounds)",
			"\t}",
			"",
			f"\t/// A `{second.name}` arrived. `Ok(id)` where it answers",
			"\t/// something outstanding.",
			f"\tpub fn on_message(&mut self, {second.name}: &{resp})"
			" -> Result<u32> {",
			*(_key(response, second.name, "\t\t") if layout.packed
			  else _key_bytes(response, second.name, "\t\t", layout.total_bytes)),
			"",
			"\t\tfor slot in self.slots.iter_mut() {",
			"\t\t\tif slot.live && slot.key == key {",
			"\t\t\t\tslot.live = false;",
			"\t\t\t\treturn Ok(slot.id);",
			"\t\t\t}",
			"\t\t}",
			"\t\tErr(Error::Constraint)",
			"\t}",
			"",
			"\t/// Retransmit whatever is due; answer the next deadline and",
			"\t/// how many exchanges gave up. `None` is an empty in-flight",
			"\t/// set -- no deadline to wait on, which is completion rather",
			"\t/// than an error.",
			"\t///",
			"\t/// The count is reported on *both* paths, including the call",
			"\t/// that gives up on the last exchange. A caller that is never",
			"\t/// told has an exchange it waits on for ever, which is why C",
			"\t/// writes it alongside SITU_ERR_TRUNCATED and Python returns",
			"\t/// it beside a None deadline.",
			"\tpub fn step(&mut self, now_ms: u32) -> (Option<u32>, u32) {",
			"\t\tlet mut soonest: Option<u32> = None;",
			"\t\tlet mut expired = 0u32;",
			"\t\tlet mut due: [Option<&'a [u8]>; 32] = [None; 32];",
			"\t\tlet mut n = 0usize;",
			"",
			"\t\tfor slot in self.slots.iter_mut() {",
			"\t\t\tif !slot.live {",
			"\t\t\t\tcontinue;",
			"\t\t\t}",
			"\t\t\tif now_ms >= slot.deadline_ms {",
			"\t\t\t\tif slot.left == 0 {",
			"\t\t\t\t\tslot.live = false;",
			"\t\t\t\t\texpired += 1;",
			"\t\t\t\t\tcontinue;",
			"\t\t\t\t}",
			"\t\t\t\tslot.left -= 1;",
			"\t\t\t\tslot.deadline_ms = now_ms + self.timeout_ms;",
			"\t\t\t\tif n < due.len() {",
			"\t\t\t\t\tdue[n] = Some(slot.bytes);",
			"\t\t\t\t\tn += 1;",
			"\t\t\t\t}",
			"\t\t\t}",
			"\t\t\tsoonest = Some(match soonest {",
			"\t\t\t\tNone => slot.deadline_ms,",
			"\t\t\t\tSome(at) if slot.deadline_ms < at => slot.deadline_ms,",
			"\t\t\t\tSome(at) => at,",
			"\t\t\t});",
			"\t\t}",
			"",
			"\t\t// The submits happen after the walk: `self.io` and",
			"\t\t// `self.slots` cannot both be borrowed mutably at once, which",
			"\t\t// is the borrow checker noticing that C reentered its own",
			"\t\t// table through a callback and got away with it.",
			"\t\tfor bytes in due.iter().take(n).flatten() {",
			"\t\t\tlet _ = self.io.submit(bytes);",
			"\t\t}",
			"",
			"\t\t(soonest, expired)",
			"\t}",
			"}",
			"",
		]

	return {f"{basename}_drive.rs": "\n".join(lines).rstrip("\n") + "\n"}
