"""Owned decode against caller backing, in Rust (26.99).

**The backing is a lifetime, not a pointer**, which is the whole difference.
C hands back a struct holding `const uint8_t *` and asks the caller not to
free the storage; Rust holds `&'a [u8]` and the compiler will not let them.
`decode` takes the backing by mutable reference and returns a value borrowing
it, so the storage cannot go while the decoded message is alive.

`Vec` would be the ordinary Rust answer and is not available: `situ_rt` is
`no_std`, which is the point of a caller-supplied buffer rather than an
accident of translation.
"""

from __future__ import annotations

from situc import ast
from situc.codegen import arguments
from situc.codegen.c.edit import editable
from situc.codegen.rust.emit import Emitter, _ident, _pascal
from situc.layout import Placement
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import is_own_member, local_name
from situc import __version__

__all__ = ["generate"]


def _runs(struct: ResolvedStruct) -> list[Placement]:
	from situc.codegen.c.edit import _runs as runs_of
	return runs_of(struct)


def _scalar(placement: Placement) -> str:
	assert placement.scalar is not None
	bits  = max(8, placement.scalar.bits)
	width = 8 if bits <= 8 else 16 if bits <= 16 else 32 if bits <= 32 else 64
	return f"i{width}" if placement.scalar.signed else f"u{width}"


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	structs = editable(resolved)
	if not structs:
		return {}

	lines = [
		f"// Generated by situc {__version__} from {basename}.situ -- do not edit.",
		"//",
		"// Owned decode against backing you supply: rung 2. The backing is a",
		"// lifetime rather than a pointer, so the storage cannot go while a",
		"// decoded message is alive -- the compiler enforces what the C",
		"// header asks for. Nothing allocates; `situ_rt` is no_std.",
		"",
		f"use crate::{basename}::*;",
		"use crate::situ_rt::{Error, Result};",
		"",
	]

	# `new`'s signature is the backend's; asked of it rather than answered
	# again, so this file and the constructor it calls cannot drift apart.
	emitter = Emitter(schema, resolved, basename)

	for struct in structs:
		held  = _pascal(struct.name)
		owned = f"{held}Owned"
		runs  = _runs(struct)
		args  = arguments(struct)
		# The same order and spelling `new` takes them in, so a caller
		# holding both hands them on rather than remembering two shapes.
		taken = emitter._argument_signature(struct)
		given = emitter._argument_fields(struct)
		note  = (["\t///",
		          "\t/// Both take the argument(s) this struct's layout follows."]
		         if args else [])
		members = [entry.placement for entry in struct.entries
		           if is_own_member(struct, entry.placement)]

		fields = []
		for placement in members:
			local = _ident(local_name(struct, placement))
			if placement in runs:
				fields.append(f"\tpub {local}: &'a [u8],")
			elif placement.scalar is not None and placement.array_count is None:
				fields.append(f"\tpub {local}: {_scalar(placement)},")

		lines += [
			f"/// `{struct.name}`, decoded into storage you own.",
			"///",
			"/// `'a` is the backing. The message may go afterwards; the",
			"/// backing outlives it, and the borrow checker holds you to it.",
			f"pub struct {owned}<'a> {{",
			*fields,
			"}",
			"",
			f"impl<'a> {owned}<'a> {{",
			"\t/// How many bytes the variable members need.",
			*note,
			f"\tpub fn backing(data: &[u8]{taken}) -> Result<usize> {{",
			f"\t\tlet view = {held}::new(data{given})?;",
			"\t\tlet mut need = 0usize;",
		]
		for placement in runs:
			local = _ident(local_name(struct, placement))
			lines.append(f"\t\tneed += view.{local}().len();")
		lines += [
			"\t\tOk(need)",
			"\t}",
			"",
			"\t/// Copy into `store`. `Error::Bounds` where it does not fit.",
			"\t///",
			"\t/// The backing goes in by mutable reference and comes back",
			"\t/// borrowed, which is what stops it being freed underneath.",
			f"\tpub fn decode(data: &[u8], store: &'a mut [u8]{taken})"
			f" -> Result<Self> {{",
			f"\t\tlet view = {held}::new(data{given})?;",
			f"\t\tlet need = Self::backing(data{given})?;",
			"\t\tif need > store.len() {",
			"\t\t\treturn Err(Error::Bounds);",
			"\t\t}",
			"",
			"\t\tlet mut at = 0usize;",
		]
		for placement in runs:
			local = _ident(local_name(struct, placement))
			lines += [
				f"\t\tlet {local}_n = view.{local}().len();",
				f"\t\tstore[at..at + {local}_n].copy_from_slice(view.{local}());",
				f"\t\tlet {local}_at = at;",
				f"\t\tat += {local}_n;",
			]
		lines += [
			"\t\tlet _ = at;",
			"",
			"\t\t// One reborrow of the whole store, split into the pieces",
			"\t\t// each run was copied into. Taking them one at a time would",
			"\t\t// be several live mutable borrows of the same slice.",
			"\t\tlet frozen: &'a [u8] = store;",
			f"\t\tOk({owned} {{",
		]
		for placement in members:
			local = _ident(local_name(struct, placement))
			if placement in runs:
				lines.append(f"\t\t\t{local}: &frozen[{local}_at..{local}_at "
				             f"+ {local}_n],")
			elif placement.parameter:
				# THE FIELD IS THE VALUE (26.398), and this is the fault that
				# entry records live in this backend: `view.n()` was emitted
				# beside `pub n: u8` and read the payload's first byte, which
				# is where the member the argument sizes begins. The view
				# carries the caller's argument as a public field and there
				# is no getter, deliberately. Carried into the owned copy
				# rather than dropped, for the map's reason (26.390): a copy
				# decoded under an assumption should say so.
				lines.append(f"\t\t\t{local}: view.{local},")
			elif placement.scalar is not None and placement.array_count is None:
				lines.append(f"\t\t\t{local}: view.{local}(),")
		lines += ["\t\t})", "\t}", "}", ""]

	return {f"{basename}_edit.rs": "\n".join(lines).rstrip("\n") + "\n"}
