"""The Rust backend (section 26.18).

Ordered last of the four because adoption is furthest out, not because it
matters least: Rust expresses the capability system more naturally than any
other target situ has, and most of that costs nothing to emit because the
language already does it.

  * **Invalidation (12.3) is the borrow checker.** A view holds a slice. A
    write through `&mut` while a read view is outstanding does not compile, so
    the generation counter the C runtime carries is not needed here -- the
    check happens before the program runs.
  * **An error cannot be dropped**, because `Result` is `#[must_use]`.
  * **A gate cannot be constructed.** Its field is private to the module, so
    nothing outside can make one and the only thing that does is the open that
    checks the tag.

Two types per struct rather than one generic over mutability: `Foo` reads and
`FooMut` reads and writes. That is what the ecosystem does, it keeps the
generated code obvious, and a reader who wants only to parse never has to hold
a `&mut` they do not need.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from situc import ast
from situc.capability import Axis
from situc.codegen.c.names import c_name
from situc.diagnostics import Diagnostic
from situc.layout import BITS_PER_BYTE, Placement
from situc.propagate import Resolved
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import local_name, own_entries
from situc.types import ScalarType

WORD_WIDTHS = (8, 16, 32, 64)


@dataclass
class Generated:
	"""One module per schema."""

	module: str
	basename: str
	warnings: list[Diagnostic] = field(default_factory=list)

	def files(self) -> dict[str, str]:
		return {f"{self.basename}.rs": self.module}


def generate(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		prefix: str = "situ") -> Generated:
	return Generated(module=Emitter(schema, resolved, basename).module(),
	                 basename=basename)


#: Rust's reserved words. A schema is free to name a field `type` or `match`;
#: Rust is not. Raw identifiers take all of these except the four below, which
#: cannot be raw and have to be renamed instead.
KEYWORDS = frozenset({
	"as", "break", "const", "continue", "dyn", "else", "enum", "extern",
	"false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
	"move", "mut", "pub", "ref", "return", "static", "struct", "trait", "true",
	"type", "unsafe", "use", "where", "while", "async", "await", "abstract",
	"become", "box", "do", "final", "macro", "override", "priv", "try",
	"typeof", "unsized", "virtual", "yield",
})

#: The ones `r#` cannot rescue.
UNESCAPABLE = frozenset({"crate", "self", "Self", "super"})


def _ident(name: str) -> str:
	"""A schema name as a Rust identifier.

	Raw identifiers carry the keywords, which is the whole reason they exist:
	`r#type` is a field called `type`, and decision 0013 says the casing and
	the naming are the author's rather than the backend's to negotiate.
	"""
	safe = c_name(name)
	if safe in UNESCAPABLE:
		return f"{safe}_"
	return f"r#{safe}" if safe in KEYWORDS else safe


def _pascal(name: str) -> str:
	"""Rust type names are PascalCase, and a schema's are the author's.

	Decision 0013 says casing is the author's and collisions are the
	compiler's; this converts rather than demanding, so a snake_case schema
	does not produce a module full of warnings nobody asked for.
	"""
	return "".join(part.capitalize() or "_" for part in c_name(name).split("_"))


class Emitter:
	def __init__(self, schema: ast.Schema, resolved: ResolvedSchema,
			basename: str) -> None:
		self.schema   = schema
		self.resolved = resolved
		self.basename = basename
		self.enums    = {decl.name: decl for decl in schema.enums()}
		self.structs  = set(resolved.structs)

	def module(self) -> str:
		lines = [
			f"//! Generated by situc from {self.basename}.situ -- do not edit.",
			"//!",
			"//! The operations below are the ones this schema's capability",
			"//! vectors support. Where one is missing, a comment says why.",
			"",
			"#![allow(dead_code)]",
			"",
			"use crate::situ_rt::{self, Error, Result};",
			"",
		]

		for decl in self.schema.enums():
			lines.extend(self._enum(decl))

		for name in sorted(self.structs):
			lines.extend(self._struct(self.resolved.structs[name]))

		return "\n".join(lines) + "\n"

	# -- enums ---------------------------------------------------------

	def _enum(self, decl: ast.EnumDecl) -> list[str]:
		values  = self.resolved.layout.env.enums[decl.name]
		backing = decl.backing.scalar
		assert backing is not None

		name = _pascal(decl.name)
		lines = [
			f"/// enum {decl.name} : {decl.backing.name} --"
			f" unknown values are {decl.effective_default.value}.",
			"#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
			f"#[repr({self._rust_type(backing)})]",
			f"pub enum {name} {{",
		]
		lines.extend(f"\t{_pascal(member.name)} = {values[member.name]},"
		             for member in decl.members)
		lines.extend([
			"}",
			"",
			f"impl {name} {{",
			"\t/// Whether a value names a member (section 8.7).",
			f"\tpub fn is_known(raw: {self._rust_type(backing)}) -> bool {{",
			"\t\tmatches!(raw, "
			+ " | ".join(str(values[member.name]) for member in decl.members)
			+ ")",
			"\t}",
			"}",
			"",
		])
		return lines

	# -- structs -------------------------------------------------------

	def _struct(self, struct: ResolvedStruct) -> list[str]:
		layout = struct.layout

		if layout.register is not None:
			return [f"// register {struct.name} (section 15) is not emitted by",
			        "// the Rust backend yet; use the C header.", ""]
		if not layout.is_fixed_size:
			return [f"// {struct.name} is not fixed size. The Rust backend",
			        "// covers the static subset so far; use the C header.", ""]

		name  = _pascal(struct.name)
		lines = [
			f"/// struct {struct.name}: {layout.size_bytes} bytes, fixed.",
			"///",
			"/// The lifetime is the buffer's. Section 12.3's invalidation rule",
			"/// is the borrow checker here: a write through `{name}Mut` while",
			"/// this is outstanding does not compile.",
			"pub struct " + name + "<'a> {",
			"\tbytes: &'a [u8],",
			"}",
			"",
			f"pub struct {name}Mut<'a> {{",
			"\tbytes: &'a mut [u8],",
			"}",
			"",
			f"impl<'a> {name}<'a> {{",
			f"\tpub const SIZE: usize = {layout.size_bytes};",
			"",
			"\t/// The one bounds check. Everything below trusts it.",
			f"\tpub fn new(bytes: &'a [u8]) -> Result<Self> {{",
			"\t\tif bytes.len() < Self::SIZE {",
			"\t\t\treturn Err(Error::Bounds);",
			"\t\t}",
			"\t\tOk(Self { bytes })",
			"\t}",
		]

		for entry in own_entries(struct):
			lines.extend(self._getter(struct, entry))

		lines.extend(self._validate(struct))
		lines.extend(["}", ""])

		lines.extend([
			f"impl<'a> {name}Mut<'a> {{",
			f"\tpub const SIZE: usize = {layout.size_bytes};",
			"",
			f"\tpub fn new(bytes: &'a mut [u8]) -> Result<Self> {{",
			"\t\tif bytes.len() < Self::SIZE {",
			"\t\t\treturn Err(Error::Bounds);",
			"\t\t}",
			"\t\tOk(Self { bytes })",
			"\t}",
			"",
			"\t/// A read-only view of the same bytes.",
			f"\tpub fn as_ref(&self) -> {name}<'_> {{",
			f"\t\t{name} {{ bytes: self.bytes }}",
			"\t}",
		])

		for entry in own_entries(struct):
			lines.extend(self._setter(struct, entry))

		lines.extend(["}", ""])
		return lines

	# -- reads ---------------------------------------------------------

	def _getter(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar

		if placement.kind == "reserved":
			return ["",
			        f"\t// {placement.path} is reserved: no accessor, and",
			        "\t// validate() holds it to the declared pattern."]
		if placement.kind != "field" or placement.offset_bits is None:
			return ["", f"\t// {placement.path}: not in the static subset yet."]

		name = _ident(local_name(struct, placement))

		if placement.type_name in self.structs and placement.array_count is None:
			nested = _pascal(placement.type_name or "")
			return [
				"",
				f"\t/// {placement.path} at {placement.offset_bytes}.",
				f"\tpub fn {name}(&self) -> {nested}<'_> {{",
				f"\t\t{nested} {{ bytes: &self.bytes[{placement.offset_bytes}..]"
				f" }}",
				"\t}",
			]

		if placement.array_count is not None or placement.sized_by is not None:
			if scalar is None or scalar.bits != BITS_PER_BYTE:
				return ["", f"\t// {placement.path}: element type"
				        f" {placement.type_name} is not in the subset yet."]
			count = placement.array_count
			if count is None:
				return ["", f"\t// {placement.path}: a data-driven length is not",
				        "\t// in the static subset yet."]

			start = placement.offset_bytes
			lines = [
				"",
				f"\t/// {placement.path}: {count} bytes. A slice, so the length",
				"\t/// travels with the pointer and cannot be lost.",
				f"\tpub fn {name}(&self) -> &[u8] {{",
				f"\t\t&self.bytes[{start}..{start + count}]",
				"\t}",
			]
			if any(attr.name == "nul_terminated" for attr in placement.attrs):
				lines.extend([
					"",
					f"\t/// Content length: to the first zero byte, or {count}.",
					f"\tpub fn {name}_len(&self) -> usize {{",
					f"\t\tsitu_rt::nul_len(self.{name}())",
					"\t}",
				])
			return lines

		if scalar is None:
			return []

		return [
			"",
			*self._axes_doc(entry),
			f"\tpub fn {name}(&self) -> {self._field_type(placement)} {{",
			f"\t\t{self._load(placement, scalar)}",
			"\t}",
		]

	def _axes_doc(self, entry: Resolved) -> list[str]:
		vector = entry.vector
		axes   = " ".join(f"{axis.value}={vector.get(axis).render()}"
		                  for axis in (Axis.OFFSET, Axis.SIZE, Axis.REPR,
		                               Axis.ATOMIC, Axis.MUTATE))
		return [f"\t/// {entry.placement.path}: {axes}"]

	def _load(self, placement: Placement, scalar: ScalarType) -> str:
		raw   = self._raw_load(placement, scalar)
		rtype = self._rust_type(scalar)

		if scalar.is_bcd:
			raw = f"situ_rt::bcd_decode({raw}, {scalar.digits})"

		if placement.type_name in self.enums:
			enum = _pascal(placement.type_name or "")
			return (f"// SAFETY-FREE: the raw value is handed back where it is\n"
			        f"\t\t// not a member; section 8.7 rejects those on parse.\n"
			        f"\t\tmatch {raw} as {self._rust_type(scalar)} {{\n"
			        + "\n".join(
			            f"\t\t\t{value} => Some({enum}::{_pascal(member)}),"
			            for member, value in
			            self.resolved.layout.env.enums[placement.type_name or ""].items())
			        + "\n\t\t\t_ => None,\n\t\t}")

		return f"{raw} as {rtype}"

	def _raw_load(self, placement: Placement, scalar: ScalarType) -> str:
		big = placement.endian is not ast.Endian.LITTLE

		if scalar.is_bit_packed:
			msb  = placement.bit_order is not ast.BitOrder.LSB_FIRST
			raw  = (f"situ_rt::read_bits(self.bytes, {placement.offset_bits},"
			        f" {scalar.bits}, {str(msb).lower()})")
			if scalar.signed:
				return f"situ_rt::sign_extend({raw}, {scalar.bits})"
			return raw

		reader = "read_be" if big else "read_le"
		raw    = (f"situ_rt::{reader}(self.bytes, {placement.offset_bytes},"
		          f" {scalar.bits // BITS_PER_BYTE})")
		if scalar.signed:
			return f"situ_rt::sign_extend({raw}, {scalar.bits})"
		return raw

	# -- writes --------------------------------------------------------

	def _setter(self, struct: ResolvedStruct, entry: Resolved) -> list[str]:
		placement = entry.placement
		scalar    = placement.scalar

		if placement.kind != "field" or placement.offset_bits is None:
			return []
		if scalar is None or placement.array_count is not None \
				or placement.sized_by is not None:
			return []
		if placement.type_name in self.structs:
			return []

		# `set_` plus a raw identifier is not one: `r#` has to prefix the whole
		# name. `set_type` is not a keyword, so the escape is only needed on
		# the getter.
		base = c_name(local_name(struct, placement))
		name = _ident(local_name(struct, placement))
		setter = _ident(f"set_{base}")

		if entry.vector.get(Axis.MUTATE).base != "InPlaceFixed":
			return ["",
			        f"\t// No {setter}(): mutate is"
			        f" {entry.vector.get(Axis.MUTATE).render()}."]
		if placement.covered_by:
			tags = ", ".join(placement.covered_by)
			return ["",
			        f"\t// No {setter}(): writing it leaves {tags} stale, so",
			        "\t// it is not an assignment. Recompute the tag after."]

		rtype = self._field_type(placement, writing=True)
		return [
			"",
			f"\tpub fn {setter}(&mut self, value: {rtype}) {{",
			f"\t\t{self._store(placement, scalar)}",
			"\t}",
		]

	def _store(self, placement: Placement, scalar: ScalarType) -> str:
		big   = placement.endian is not ast.Endian.LITTLE
		value = "value as u64"

		if placement.type_name in self.enums:
			value = "value as u64"
		if scalar.is_bcd:
			value = f"situ_rt::bcd_encode({value}, {scalar.digits})"

		if scalar.is_bit_packed:
			msb = placement.bit_order is not ast.BitOrder.LSB_FIRST
			return (f"situ_rt::write_bits(self.bytes, {placement.offset_bits},"
			        f" {scalar.bits}, {str(msb).lower()}, {value})")

		writer = "write_be" if big else "write_le"
		return (f"situ_rt::{writer}(self.bytes, {placement.offset_bytes},"
		        f" {scalar.bits // BITS_PER_BYTE}, {value})")

	# -- validation ----------------------------------------------------

	def _validate(self, struct: ResolvedStruct) -> list[str]:
		from situc.expr import evaluate

		checks: list[str] = []

		for entry in own_entries(struct):
			placement = entry.placement
			scalar    = placement.scalar
			name      = _ident(local_name(struct, placement))

			if placement.type_name in self.structs and scalar is None \
					and placement.array_count is None:
				checks.append(f"\t\tself.{name}().validate()?;")
				continue
			if scalar is None or placement.offset_bits is None:
				continue

			if placement.kind == "reserved" and placement.array_count is None:
				policy = _reserved_policy(placement.attrs)
				if policy in ("must_be_zero", "must_be_one"):
					want = 0 if policy == "must_be_zero" else (1 << scalar.bits) - 1
					checks.extend([
						f"\t\tif {self._raw_load(placement, scalar)} != {want} {{",
						"\t\t\treturn Err(Error::Constraint);",
						"\t\t}",
					])
				continue

			if placement.array_count is not None or placement.sized_by is not None:
				checks.extend(self._array_checks(placement, name))
				continue

			enum = self.enums.get(placement.type_name or "")
			if enum is not None \
					and enum.effective_default is ast.EnumDefault.ERROR:
				checks.extend([
					f"\t\tif !{_pascal(enum.name)}::is_known("
					f"{self._raw_load(placement, scalar)} as"
					f" {self._rust_type(scalar)}) {{",
					"\t\t\treturn Err(Error::Constraint);",
					"\t\t}",
				])

			for attr in placement.attrs:
				if attr.name not in ("must_eq", "max", "min") or attr.value is None:
					continue
				expected = evaluate(attr.value, self.resolved.layout.env)
				operator = {"must_eq": "!=", "max": ">", "min": "<"}[attr.name]
				checks.extend([
					f"\t\tif {self._raw_load(placement, scalar)}"
					f" {operator} {expected} {{",
					"\t\t\treturn Err(Error::Constraint);",
					"\t\t}",
				])

		return [
			"",
			"\t/// Every constraint the schema declares, on parse.",
			"\tpub fn validate(&self) -> Result<()> {",
			*(checks or ["\t\t// Nothing in this struct is constrained."]),
			"\t\tOk(())",
			"\t}",
		]

	def _array_checks(self, placement: Placement, name: str) -> list[str]:
		checks: list[str] = []
		count = placement.array_count
		if count is None or placement.scalar is None:
			return checks
		if placement.scalar.bits != BITS_PER_BYTE:
			return checks

		if placement.kind == "reserved":
			policy = _reserved_policy(placement.attrs)
			if policy in ("must_be_zero", "must_be_one"):
				want  = 0 if policy == "must_be_zero" else 0xFF
				start = placement.offset_bytes
				checks.extend([
					f"\t\tif self.bytes[{start}..{start + count}]"
					f".iter().any(|&b| b != {want}) {{",
					"\t\t\treturn Err(Error::Constraint);",
					"\t\t}",
				])
			return checks

		for attr in placement.attrs:
			if attr.name == "encoding":
				named = getattr(attr.value, "name", None)
				if named in ("ascii", "utf8"):
					checks.extend([
						f"\t\tif !situ_rt::{named}_valid(self.{name}()) {{",
						"\t\t\treturn Err(Error::Constraint);",
						"\t\t}",
					])
			if attr.name == "nul_terminated":
				checks.extend([
					f"\t\tif self.{name}_len() >= {count} {{",
					"\t\t\treturn Err(Error::Constraint);",
					"\t\t}",
				])
		return checks

	# -- types ---------------------------------------------------------

	def _field_type(self, placement: Placement, writing: bool = False) -> str:
		if placement.type_name in self.enums:
			enum = _pascal(placement.type_name or "")
			# A field may hold a value no member names; section 8.7 rejects
			# those on parse, not on read, so the getter says so in its type.
			return enum if writing else f"Option<{enum}>"
		scalar = placement.scalar
		assert scalar is not None
		return self._rust_type(scalar)

	def _rust_type(self, scalar: ScalarType) -> str:
		width = _storage_width(scalar.bits)
		return f"i{width}" if scalar.signed else f"u{width}"


def _storage_width(bits: int) -> int:
	for width in WORD_WIDTHS:
		if bits <= width:
			return width
	return 64


def _reserved_policy(attrs: tuple[ast.Attr, ...]) -> str | None:
	for attr in attrs:
		if attr.name in ("must_be_zero", "must_be_one"):
			return str(attr.name)
		if attr.name in ("preserve", "unknown"):
			return None
	return "must_be_zero"
