"""Cross-message relations in Rust (26.95).

The walk is `situc.relation`'s; this decides only how Rust spells one.

Two things differ from C. A sub-view is `Result<Head>` rather than an
out-parameter, so `?` carries the failure and there is no error local to
thread. And Rust will not compare an `i8` against a `u16` at all -- it is a
type error rather than a warning -- so the widening the C backend does to
satisfy `-Wsign-conversion` is here to satisfy the compiler outright. Same
decision, made in `situc.relation`, arriving for a different reason.
"""

from __future__ import annotations

from situc import ast
from situc.codegen.rust.emit import _ident, _pascal
from situc.relation import Constraint, Read, SubView, plans, refusals, render
from situc.resolve import ResolvedSchema

__all__ = ["generate", "refusals", "signature"]


def _local(name: str) -> str:
	return f"v{name}"


def _source(name: str) -> str:
	return _local(name) if name.startswith("_") else name


def _member(name: str) -> str:
	"""A member's accessor. Rust keeps snake_case, which the schema already is."""
	return _ident(name)


def signature(relation: ast.Relation) -> str:
	params = ", ".join(f"{param.name}: &{_pascal(param.type_name)}"
	                   for param in relation.params)
	return f"pub fn rel_{_ident(relation.name)}({params}) -> Result<()>"


def _binding(bind: SubView | Read, cast: str) -> list[str]:
	source = _source(bind.source)
	target = _local(bind.target)

	if isinstance(bind, SubView):
		return [f"\t\tlet {target} = {source}.{_member(bind.member)}()?;"
		        f"\t// {bind.path}"]

	return [f"\t\tlet {target} = {source}.{_member(bind.member)}() as {cast};"
	        f"\t// {bind.path}"]


def _body(constraints: list[Constraint]) -> list[str]:
	lines: list[str] = []

	for constraint in constraints:
		cast  = "i64" if constraint.signed else "u64"
		block: list[str] = []

		for bind in constraint.bindings:
			block += _binding(bind, cast)

		assert constraint.expr is not None
		locals_for = {path: _local(name)
		              for path, name in constraint.locals_for.items()}
		block += [
			f"\t\tif !{render(constraint.expr, locals_for)} {{",
			"\t\t\treturn Err(Error::Constraint);",
			"\t\t}",
		]

		lines += ["\t{", *block, "\t}", ""]

	return lines


def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> dict[str, str]:
	"""The relation module, or nothing if no relation is expressible."""
	ready = plans(schema, resolved)
	if not ready:
		return {}

	lines = [
		f"// Generated by situc from {basename}.situ -- do not edit.",
		"//",
		"// Cross-message relations: a pure predicate per relation, over two",
		"// views the caller already holds. A separate module on purpose -- a",
		"// rung adds files rather than changing them (decision 0032).",
		"",
		"#![allow(clippy::needless_range_loop)]",
		"",
		f"use crate::{basename}::*;",
		"use crate::situ_rt::{Error, Result};",
		"",
	]

	for relation, constraints in ready:
		first, second = relation.params
		lines += [
			f"/// Whether `{second.name}` is a well-formed counterpart to "
			f"`{first.name}`.",
			"///",
			"/// Pure: reads two views, holds nothing, allocates nothing. The",
			"/// caller owns the pairing; this answers only whether one is",
			f"/// well formed. Parameter order is temporal -- `{first.name}`",
			"/// is the message seen first.",
			signature(relation),
			"{",
			*_body(constraints),
			"\tOk(())",
			"}",
			"",
		]

	return {f"{basename}_relate.rs": "\n".join(lines).rstrip("\n") + "\n"}
