"""`situc gen-dissector` -- a Wireshark dissector, in Lua.

Section 20.3 puts it plainly: debugging an encrypted protocol without a
dissector is painful, and the payoff is large. The argument for generating one
is the argument for generating anything else here -- a hand-written dissector
is a third description of the layout, after the schema and the accessors, and
the one nobody updates. This one is rendered from the same placements the
accessors come from.

Lua rather than C, because a Lua dissector is a file a user drops in a plugins
directory. A C one has to be compiled against the Wireshark headers of whatever
version they happen to be running, which is a build problem in exchange for
speed nobody debugging a protocol needs.

What it emits, per struct:

  * a `ProtoField` for every member, with the bitmask where the member is
    bit-packed and the value string where its type is an enum
  * a dissector function that walks the members in order and adds each to the
    tree, in a subtree of its own where the member is a nested struct
  * for a variable-length member, an offset computed at run time from the field
    that sizes it -- the same arithmetic the C offset functions do

Byte order is per field, which Lua supports directly: `add` reads big endian
and `add_le` little. A `native` field has no fixed answer here, because the
capture and the machine reading it are different machines; those are added as
bytes with a note rather than guessed at.
"""

from __future__ import annotations

from situc import ast
from situc.layout import BITS_PER_BYTE, Placement
from situc.names import render_delimiter
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import byte_span, container_bits, local_name, own_members

#: Widths Wireshark has a `ProtoField.uintN` for. Unlike C it has a 24-bit one,
#: so a three-byte scalar is read whole here and bit-assembled there.
FIELD_WIDTHS = (8, 16, 24, 32, 64)

def generate(schema: ast.Schema, resolved: ResolvedSchema,
		basename: str) -> str:
	"""The whole schema as a dissector.

	There is no `prefix` here, unlike the C backends: Lua names come from the
	struct names, and Wireshark abbrevs are already namespaced by the protocol
	they hang off.
	"""
	lines = _preamble(basename)

	# Only where something scans. A helper nobody calls is dead Lua in a file
	# a user is expected to read before trusting it.
	if any(entry.placement.delimiter is not None
	       for struct in resolved.structs.values()
	       for entry in struct.entries):
		lines.extend(SCAN_HELPER)

	values = _value_strings(schema, resolved)
	if values:
		lines.extend(values)

	roots = [name for name in sorted(resolved.structs)
	         if resolved.structs[name].layout.register is None]

	for name in roots:
		lines.extend(_proto(resolved, resolved.structs[name], basename))

	skipped = [name for name in sorted(resolved.structs)
	           if resolved.structs[name].layout.register is not None]
	if skipped:
		lines.extend(["",
		              "-- Not dissected: " + ", ".join(skipped) + ".",
		              "-- A register is a bus transaction, not something that "
		              "appears on a wire."])

	lines.extend(_registration(resolved, roots))
	return "\n".join(lines).rstrip() + "\n"


SCAN_HELPER = [
	"-- Where a delimited member stops (situ section 8.6.1).",
	"--",
	"-- Returns the content length, or the distance to `limit` when the",
	"-- delimiter is not there -- the same two answers the generated",
	"-- accessors give, so a capture and a parser disagree about nothing.",
	"local function situ_scan(tvb, at, delim, limit)",
	"\tlocal n = #delim",
	"\tif n == 0 or at + n > limit then",
	"\t\treturn limit - at",
	"\tend",
	"\tfor i = at, limit - n do",
	"\t\tlocal match = true",
	"\t\tfor j = 0, n - 1 do",
	"\t\t\tif tvb(i + j, 1):uint() ~= delim[j + 1] then",
	"\t\t\t\tmatch = false",
	"\t\t\t\tbreak",
	"\t\t\tend",
	"\t\tend",
	"\t\tif match then",
	"\t\t\treturn i - at",
	"\t\tend",
	"\tend",
	"\treturn limit - at",
	"end",
	"",
]


def _preamble(basename: str) -> list[str]:
	return [
		f"-- Generated by situc from {basename}.situ -- do not edit.",
		"--",
		"-- A Wireshark dissector. Drop this in your plugins directory",
		"-- (Help > About > Folders > Personal Lua Plugins) and reload with",
		"-- Ctrl-Shift-L.",
		"--",
		"-- Every offset here comes from the same layout the accessors are",
		"-- generated from, so the dissector cannot drift from the parser.",
		"",
	]


# ---------------------------------------------------------------------------
# Enums become value strings
# ---------------------------------------------------------------------------


def _value_strings(schema: ast.Schema, resolved: ResolvedSchema) -> list[str]:
	"""An enum is a Wireshark value string: Wireshark shows the name, not the number."""
	lines: list[str] = []

	for decl in schema.enums():
		values = resolved.layout.env.enums.get(decl.name)
		if not values:
			continue
		pairs = ", ".join(f"[{values[member.name]}] = \"{member.name}\""
		                  for member in decl.members)
		lines.append(f"local {_lua(decl.name)}_values = {{ {pairs} }}")

	if lines:
		lines.append("")
	return lines


# ---------------------------------------------------------------------------
# One struct becomes one Proto
# ---------------------------------------------------------------------------


def _proto(resolved: ResolvedSchema, struct: ResolvedStruct,
		basename: str) -> list[str]:
	proto = _lua(struct.name)
	lines = [
		f"-- struct {struct.name}",
		f"local {proto} = Proto(\"{struct.name}\", \"{struct.name} (situ)\")",
		"",
	]

	members = own_members(struct)
	fields  = [_field(resolved, struct, placement) for placement in members]
	fields  = [line for line in fields if line]

	if fields:
		lines.append(f"{proto}.fields = {{}}")
		lines.append(f"local {proto}_f = {proto}.fields")
		lines.extend(fields)
		lines.append("")

	lines.extend(_dissector(resolved, struct, members))
	lines.append("")
	return lines


def _field(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> str:
	"""One `ProtoField`, or "" for a member that gets a subtree instead."""
	name  = _local(struct, placement)
	abbrev = f"{struct.name}.{name}"

	if placement.type_name in resolved.structs:
		return ""			# a nested struct: its own Proto dissects it
	if placement.sized_by is not None or placement.array_count is not None:
		return (f"{_lua(struct.name)}_f.{_lua(name)} = "
		        f"ProtoField.bytes(\"{abbrev}\", \"{name}\")")

	scalar = placement.scalar
	if scalar is None:
		return ""

	width = container_bits(placement, FIELD_WIDTHS)
	if width is None:
		return (f"{_lua(struct.name)}_f.{_lua(name)} = "
		        f"ProtoField.bytes(\"{abbrev}\", \"{name}\")")

	kind = ("int" if scalar.signed else "uint") + str(width)

	# Wireshark has no BCD display, but hex is the right one anyway: the
	# nibbles of a packed decimal field read as the digits they spell, so
	# 0x12345678 is the number a reader wants to see. Decimal would show the
	# integer the bytes happen to be, which is not a number anybody wrote.
	base = "base.HEX" if scalar.is_bcd else "base.DEC"
	args = [f"\"{abbrev}\"", f"\"{name}\"", base]

	enum = placement.type_name if placement.type_name in _enum_names(resolved) else None
	mask = _bitmask(placement, width)

	if enum is not None:
		args.append(f"{_lua(enum)}_values")
	elif mask is not None:
		args.append("nil")

	if mask is not None:
		args.append(f"{mask:#x}")

	return (f"{_lua(struct.name)}_f.{_lua(name)} = "
	        f"ProtoField.{kind}({', '.join(args)})")


def _enum_names(resolved: ResolvedSchema) -> frozenset[str]:
	return frozenset(resolved.layout.env.enums)


def _bitmask(placement: Placement, width: int) -> int | None:
	"""Which bits of the container the field owns, or None if it owns all of them.

	Derived here from the offset and the declared bit order rather than taken
	from the emitter, for the same reason the conformance checks derive theirs:
	two descriptions that share a derivation agree even when both are wrong.
	"""
	if placement.size_bits == width and placement.offset_bits is not None \
			and placement.offset_bits % BITS_PER_BYTE == 0:
		return None

	assert placement.offset_bits is not None
	first = placement.offset_bits // BITS_PER_BYTE
	skip  = placement.offset_bits - first * BITS_PER_BYTE
	span  = width

	if placement.bit_order is ast.BitOrder.LSB_FIRST:
		shift = skip
	else:
		shift = span - skip - placement.size_bits

	return ((1 << placement.size_bits) - 1) << shift


# ---------------------------------------------------------------------------
# The dissector function
# ---------------------------------------------------------------------------


def _dissector(resolved: ResolvedSchema, struct: ResolvedStruct,
		members: list[Placement]) -> list[str]:
	proto  = _lua(struct.name)
	layout = struct.layout

	lines = [
		f"function {proto}.dissector(tvb, pinfo, tree)",
		f"\tif tvb:len() < {layout.size_bytes} then",
		"\t\treturn 0",
		"\tend",
		"",
		f"\tpinfo.cols.protocol = \"{struct.name}\"",
		f"\tlocal subtree = tree:add({proto}, tvb())",
		"\tlocal at = 0",
		"",
	]

	for placement in members:
		lines.extend(_member(resolved, struct, placement))

	lines.extend(["", "\treturn at", "end"])
	return lines


def _member(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> list[str]:
	"""Add one member to the tree, and advance `at` past it.

	A versioned member is wrapped in the guard its accessors have. Without it
	the dissector read `tvb(3, 4)` on a three-byte v1 message and Wireshark
	showed the packet as malformed -- blaming the capture for the schema.
	"""
	lines = _member_body(resolved, struct, placement)
	guard = _version_guard(struct, placement)
	if guard is None:
		return lines

	return [f"\t-- present from version {placement.since}", f"\t{guard}",
	        *[f"\t{line}" for line in lines], "\tend"]


def _version_guard(struct: ResolvedStruct, placement: Placement) -> str | None:
	"""`if <version> >= N then`, reading the version where the accessors do."""
	if placement.since is None or placement.version_field is None:
		return None

	field = next((entry.placement for entry in struct.entries
	              if entry.placement.name == placement.version_field), None)
	if field is None or field.offset_bits is None or field.scalar is None:
		return None

	span = byte_span(field)
	if span is None:
		return None

	first, count = span
	read = "le_uint" if field.endian is ast.Endian.LITTLE else "uint"
	return f"if tvb({first}, {count}):{read}() >= {placement.since} then"


def _member_body(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> list[str]:
	name  = _local(struct, placement)
	field = f"{_lua(struct.name)}_f.{_lua(name)}"

	# A static offset is assigned; a dynamic one is already in `at` from the
	# member before it, and `at = at` is noise.
	start = placement.offset_bits
	at    = "at" if start is None else str(start // BITS_PER_BYTE)
	seek  = [] if start is None else [f"\tat = {at}"]

	# Before the nested-struct case. A run of records names a struct type and
	# is not one, and this used to reach the delimiter branch only because a
	# delimited member carried `array_count = 1` -- so the check below failed
	# for the wrong reason and the right thing happened by accident. Removing
	# that lie from the solver is what exposed it.
	if placement.delimiter is not None:
		return _delimited(resolved, struct, placement, field, seek)

	# A nested struct gets its own dissector and its own subtree.
	if placement.type_name in resolved.structs and placement.array_count is None \
			and placement.sized_by is None:
		nested = resolved.structs[placement.type_name]
		return [
			f"\t-- {placement.path}",
			*seek,
			f"\tif tvb:len() >= at + {nested.layout.size_bytes} then",
			f"\t\tDissector.get(\"{placement.type_name}\"):call("
			f"tvb(at, {nested.layout.size_bytes}):tvb(), pinfo, subtree)",
			f"\tend",
			f"\tat = at + {nested.layout.size_bytes}",
		]

	if placement.sized_by is not None or placement.array_count is not None:
		return _repeated(resolved, struct, placement, field, seek)

	span = byte_span(placement)
	if span is None:
		return [f"\t-- {placement.path}: no bytes of its own"]

	first, count = span
	add = "add_le" if placement.endian is ast.Endian.LITTLE else "add"

	return [
		f"\tsubtree:{add}({field}, tvb({first}, {count}))",
		f"\tat = {first + count}",
	]


def _delimited(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement, field: str, seek: list[str]) -> list[str]:
	"""A member that ends at a delimiter (section 8.6.1).

	The scan is emitted rather than the length, because there is no length:
	Wireshark has the same bytes situ does and has to look for the same thing
	in them. A run of records is not unrolled here -- the terminator ends the
	run and each element is dissected by its own dissector -- so this handles
	the byte case and says so for the other.
	"""
	name  = _lua(_local(struct, placement))
	delim = placement.delimiter
	assert delim is not None

	if placement.type_name in resolved.structs:
		return [
			f"\t-- {placement.path}: a run of {placement.type_name} to "
			f"{render_delimiter(delim)}.",
			"\t-- Not unrolled: the terminator ends the run rather than each",
			"\t-- element, so where it stops is a walk this does not do.",
		]

	bytes_ = ", ".join(str(byte) for byte in delim)
	cap    = ("tvb:len()" if placement.delimiter_cap is None
	          else f"math.min(at + {placement.delimiter_cap}, tvb:len())")

	return [
		f"\t-- {placement.path}, to the first {render_delimiter(delim)}",
		*seek,
		f"\tlocal {name}_len = situ_scan(tvb, at, {{{bytes_}}}, {cap})",
		f"\tif {name}_len > 0 then",
		f"\t\tsubtree:add({field}, tvb(at, {name}_len))",
		"\tend",
		f"\tat = at + {name}_len",
		f"\tif at + {len(delim)} <= tvb:len() then",
		f"\t\tat = at + {len(delim)}",
		"\tend",
	]


def _repeated(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement, field: str, seek: list[str]) -> list[str]:
	"""An array, or a member whose length the data decides.

	Where the elements are a struct this loops and calls their dissector, which
	is the whole reason to have one: a repeated record shown as a run of bytes
	tells a reader nothing they could not get from the hex pane.
	"""
	name    = _lua(_local(struct, placement))
	element = resolved.structs.get(placement.type_name or "")

	count = _count_expression(resolved, struct, placement)
	if count is None:
		return [
			f"\t-- {placement.path}: sized by `{placement.sized_by}`, which this",
			"\t-- dissector cannot locate; the rest of the frame is shown raw",
			*seek,
			"\tif tvb:len() > at then",
			f"\t\tsubtree:add({field}, tvb(at))",
			"\tend",
			"\tat = tvb:len()",
		]

	if placement.sized_by == "remaining":
		return [
			f"\t-- {placement.path}: to the end of the frame",
			*seek,
			"\tif tvb:len() > at then",
			f"\t\tsubtree:add({field}, tvb(at))",
			"\tend",
			"\tat = tvb:len()",
		]

	each = _element_bytes(resolved, placement)
	if each is None:
		return [f"\t-- {placement.path}: elements of no fixed size"]

	lines = [f"\t-- {placement.path}", *seek, f"\tlocal {name}_n = {count}"]

	if element is None:
		# Scalar elements: one range, shown as bytes.
		scale = "" if each == 1 else f" * {each}"
		lines.extend([
			f"\tlocal {name}_len = {name}_n{scale}",
			f"\tif tvb:len() >= at + {name}_len then",
			f"\t\tsubtree:add({field}, tvb(at, {name}_len))",
			"\tend",
			f"\tat = at + {name}_len",
		])
		return lines

	lines.extend([
		f"\tfor i = 0, {name}_n - 1 do",
		f"\t\tif tvb:len() < at + {each} then break end",
		f"\t\tDissector.get(\"{placement.type_name}\"):call("
		f"tvb(at, {each}):tvb(), pinfo, subtree)",
		f"\t\tat = at + {each}",
		"\tend",
	])
	return lines


def _count_expression(resolved: ResolvedSchema, struct: ResolvedStruct,
		placement: Placement) -> str | None:
	"""How many elements there are, as Lua.

	A static count is a literal. A dynamic one is read back out of the buffer
	the same way the generated C reads it -- from a field parsed earlier, which
	is therefore at a static offset.
	"""
	if placement.array_count is not None:
		return str(placement.array_count)
	if placement.sized_by == "remaining":
		return "remaining"

	driver = resolved.find(f"{struct.name}.{placement.sized_by}")
	if driver is None or driver.placement.offset_bits is None:
		return None
	if driver.placement.offset_bits % BITS_PER_BYTE:
		return None

	byte  = driver.placement.offset_bits // BITS_PER_BYTE
	width = driver.placement.size_bits // BITS_PER_BYTE
	read  = "le_uint" if driver.placement.endian is ast.Endian.LITTLE else "uint"
	return f"tvb({byte}, {width}):{read}()"


def _element_bytes(resolved: ResolvedSchema, placement: Placement) -> int | None:
	element = resolved.structs.get(placement.type_name or "")
	if element is not None:
		return int(element.layout.size_bytes) if element.layout.is_fixed_size else None
	if placement.scalar is not None and placement.scalar.bits % BITS_PER_BYTE == 0:
		return max(placement.scalar.bits // BITS_PER_BYTE, 1)
	return None


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------


def _outermost(resolved: ResolvedSchema, names: list[str]) -> str | None:
	"""The struct nothing else contains, which is the one on the wire.

	`record` is not the protocol; `message` is. Suggesting the wrong one in the
	registration example sends a reader to bind a dissector for a struct that
	only ever appears inside another.
	"""
	contained = {
		entry.placement.type_name
		for name in names
		for entry in resolved.structs[name].entries
		if entry.placement.type_name in resolved.structs
	}
	free = [name for name in names if name not in contained]
	if not free:
		return names[-1] if names else None

	# Among the free ones, the largest: a schema can describe several
	# independent messages, and the biggest is the likeliest to be the point.
	return max(free, key=lambda name: resolved.structs[name].layout.size_bytes)


def _registration(resolved: ResolvedSchema, names: list[str]) -> list[str]:
	"""How a user reaches the dissector.

	Nothing here knows which UDP port or EtherType the protocol lives on --
	that is not in the schema and guessing it would be wrong. So the dissectors
	register by name, which makes them available to "Decode As" and to any
	other dissector that calls them, and the file says how to bind one.
	"""
	outermost = _outermost(resolved, names)
	if outermost is None:
		return []

	return [
		"",
		"-- The schema does not say which port or EtherType this protocol runs",
		"-- on, so nothing is bound automatically. Either use Decode As..., or",
		"-- bind it here, for example:",
		"--",
		f"--     DissectorTable.get(\"udp.port\"):add(9999, {_lua(outermost)})",
	]


# ---------------------------------------------------------------------------


def _local(struct: ResolvedStruct, placement: Placement) -> str:
	"""The member's name, with the synthetic brackets a reserved field carries
	stripped: `<reserved0>` is not a name Wireshark accepts in an abbrev."""
	return local_name(struct, placement).strip("<>")


def _lua(name: str) -> str:
	"""A Lua identifier. `::` from a namespace is the only thing that appears
	in a situ name and not in a Lua one."""
	return "".join(char if char.isalnum() or char == "_" else "_" for char in name)
