"""`situc doc` -- the schema as documentation.

Section 20.3 asks for "RFC-style packet diagrams straight from the schema; what
protocol documentation always needs". The reason it belongs in the compiler
rather than in a wiki is that a hand-drawn diagram is a second description of
the layout, and second descriptions drift. This one cannot: it is rendered from
the same placements the accessors are generated from, so a field that moved has
moved in the picture too.

The diagram is the RFC 791 convention -- 32 bits to a row, two characters to a
bit -- because that is what protocol documentation has looked like for forty
years and what a reader will already know how to read.

What it draws is the struct's own members, not their interiors. A nested struct
appears as one box under its own name, the way `Source Address` does in RFC 791
rather than as four separate octets; the nested struct gets its own diagram
further down. Bit-packed fields are drawn at bit granularity, which is the
whole point of the format.
"""

from __future__ import annotations

from collections.abc import Callable

from situc import ast
from situc.layout import BITS_PER_BYTE, Placement
from situc.names import render_delimiter
from situc.resolve import ResolvedSchema, ResolvedStruct
from situc.traverse import (
	element_bytes, indexed_elements, local_name, own_members,
)
from situc.unparse import expr_to_source

#: The RFC convention. Everything below assumes two characters to a bit; the
#: cell borders line up with the ruler only at that scale.
BITS_PER_ROW = 32


def _row_width(struct: ResolvedStruct) -> int:
	"""How wide a row should be for this struct.

	32 bits is the convention and the right answer for a packet header. It is
	the wrong answer for a one-byte register or flags word: three empty bytes
	of row read as three bytes of struct. Narrow structs get a narrow diagram.
	"""
	bits = struct.layout.size_bytes * BITS_PER_BYTE
	if 0 < bits <= 8:
		return 8
	if bits <= 16:
		return 16
	return BITS_PER_ROW


def render(schema: ast.Schema, resolved: ResolvedSchema, basename: str,
		fmt: str = "ascii") -> str:
	"""The whole schema as a document."""
	lines = _preamble(basename, fmt)

	for name in sorted(resolved.structs):
		struct = resolved.structs[name]
		lines.extend(_struct(struct, fmt))

	return "\n".join(lines).rstrip() + "\n"


def _preamble(basename: str, fmt: str) -> list[str]:
	title = f"{basename}.situ"
	if fmt == "markdown":
		return [f"# {title}", "",
		        "Generated by `situc doc`. Every offset here comes from the same",
		        "layout the accessors are generated from, so the diagrams cannot",
		        "drift from the code.", ""]
	return [title, "=" * len(title), "",
	        "Generated by situc doc. Every offset here comes from the same layout",
	        "the accessors are generated from, so the diagrams cannot drift from",
	        "the code.", ""]


def _struct(struct: ResolvedStruct, fmt: str) -> list[str]:
	heading = f"struct {struct.name}"
	lines   = [f"## {heading}", ""] if fmt == "markdown" else [heading,
	                                                           "-" * len(heading), ""]

	lines.extend(_size_note(struct))
	lines.append("")

	if struct.layout.register is not None:
		lines.extend(_register_note(struct))
		lines.append("")

	diagram = _diagram(struct)
	if diagram:
		lines.extend(["```"] if fmt == "markdown" else [])
		lines.extend(diagram)
		lines.extend(["```"] if fmt == "markdown" else [])
		lines.append("")

	lines.extend(_table(struct, fmt))
	lines.append("")
	return lines


def _bytes(count: int) -> str:
	return f"{count} byte" if count == 1 else f"{count} bytes"


def _size_note(struct: ResolvedStruct) -> list[str]:
	layout = struct.layout
	if layout.is_fixed_size:
		return [f"Size: {_bytes(layout.size_bytes)}, fixed."]

	most = getattr(layout, "size_max_bytes", None)
	if most is not None:
		return [f"Size: {layout.size_bytes} to {_bytes(most)}."]
	return [f"Size: {_bytes(layout.size_bytes)} and up; no upper bound."]


def _register_note(struct: ResolvedStruct) -> list[str]:
	register = struct.layout.register
	assert register is not None

	where = "at no fixed address" if register.address is None \
		else f"at {register.address:#x}"
	notes = [f"{register.width} bits",
	         f"{register.access_width}-bit bus access"]
	if register.volatile:
		notes.append("volatile")
	if register.no_rmw:
		notes.append("no read-modify-write")

	return [f"Memory-mapped register {where} ({', '.join(notes)})."]


# ---------------------------------------------------------------------------
# The diagram
# ---------------------------------------------------------------------------


def _label(struct: ResolvedStruct, placement: Placement) -> str:
	local = local_name(struct, placement)
	if placement.kind == "reserved":
		return "reserved"
	# `name...`, because there is no count to show and no length either: where
	# it stops is in the data. It read `name[1]` while the solver claimed a
	# count of one, and somebody implementing from that diagram writes a
	# fixed-width parser.
	if placement.delimiter is not None:
		return f"{local}..."
	# A text number's bracket is a width in bytes, not a count of elements
	# (8.6.2), so `magic[6]` reads as six magics where there is one number in
	# six digits. The Size column already says six bytes; the name saying it
	# again, in the notation an array uses, is the `name[1]` mistake in its
	# other form.
	if placement.radix is not None:
		return local
	if placement.array_count is not None:
		return f"{local}[{placement.array_count}]"
	if placement.sized_by is not None:
		return f"{local}[{placement.sized_by}]"
	# ...and the same array with its count written as arithmetic, which came
	# out bare: `a[n]` beside `b`, for two members of the same kind, in the
	# column a reader identifies fields by. The Size column has said
	# `[n + 1]` for it all along, so the diagram named a scalar and the table
	# beside it named an array (invariant 69).
	if placement.size_expr is not None:
		return f"{local}[{placement.size_expr}]"
	return local


def _diagram(struct: ResolvedStruct) -> list[str]:
	"""Rows of `_row_width` bits, in the RFC 791 convention.

	Cells accumulate into the row they belong to and the row is emitted once it
	is full, because a row is one line however many fields share it -- which is
	the entire point of drawing bit-packed fields this way.
	"""
	members = [placement for placement in own_members(struct)
	           if placement.offset_bits is not None]
	if not members:
		return []

	width = _row_width(struct)
	lines: list[str] = [*_ruler(width), _rule(width)]
	row: list[tuple[int, str]] = []		# (bits, label), left to right

	def flush() -> None:
		"""Emit the row under construction, padding a partial one."""
		if not row:
			return
		filled = sum(bits for bits, _ in row)
		if filled < width:
			row.append((width - filled, ""))
		lines.append("|" + "|".join(_cell(text, bits) for bits, text in row) + "|")
		lines.append(_rule(width))
		row.clear()

	at = 0
	for placement in members:
		start = placement.offset_bits
		assert start is not None

		if start > at:
			_place(row, flush, width, at, start - at, "unused")
			at = start

		# One question, asked once: does this member have a single size? It
		# used to enumerate three ways of not having one -- sized by a field,
		# zero bits, delimited -- which missed two more. A `while` run was
		# drawn as a one-byte box, and a variant reached the right branch only
		# because its smallest arm happens to be empty; one whose smallest arm
		# were two bytes would have been drawn as a two-byte field.
		if not placement.is_fixed_size:
			# A variable member starting mid-row takes the rest of that row.
			# Flushing first would pad it with blanks, which reads as unused
			# space exactly where the member actually begins.
			name   = _label(struct, placement)
			filled = sum(bits for bits, _ in row)
			if row and filled < width:
				row.append((width - filled, name))
			flush()
			lines.extend(_slanted(name, width))
			continue

		bits = placement.size_bits
		name = _label(struct, placement)

		# Whole rows and more than one of them: a box with the name in the
		# middle, rather than the same name repeated on every line.
		if start % width == 0 and bits % width == 0 and bits > width:
			flush()
			lines.extend(_tall(name, bits // width, width))
		else:
			_place(row, flush, width, start, bits, name)

		at = start + bits

	flush()
	return lines


def _place(row: list[tuple[int, str]], flush: Callable[[], None], width: int,
		start: int, bits: int, name: str) -> None:
	"""Add a member to the row being built, splitting it at row boundaries."""
	remaining = bits
	at        = start
	first     = True

	while remaining > 0:
		take = min(width - at % width, remaining)

		# A continuation says so before it says which member it continues:
		# where the box is too narrow for both, the marker is the half a
		# reader needs, and the member above it is right there.
		if first:
			label = name
		else:
			label = f"{name} (cont.)"
			if len(label) > 2 * take - 1:
				label = "(cont.)"
		row.append((take, label))
		at        += take
		remaining -= take
		first      = False

		if at % width == 0:
			flush()


def _ruler(width: int) -> list[str]:
	tens = " ".join(str(bit // 10) if bit % 10 == 0 else " " for bit in range(width))
	ones = " ".join(str(bit % 10) for bit in range(width))
	return [" " + tens.rstrip(), " " + ones]


def _rule(width: int) -> str:
	return "+" + "-+" * width


def _cell(text: str, bits: int) -> str:
	"""A member's own space between two borders: two characters to a bit, less one.

	A label that does not fit is cut, and the cut is *marked*. It was silent,
	so `cell_count (cont.)` in a fifteen-character box came out as
	`cell_count (con` -- a field name that is not any field's name, in the one
	artifact whose whole purpose is that somebody implements from it. The
	table below the diagram carries the full name; the diagram says when it is
	not showing it.
	"""
	room = 2 * bits - 1
	if len(text) > room:
		# A narrow box gets a prefix and no marker, which is the convention
		# RFC 791 uses for its own one-bit flags: `R`, `D`, `M`, and the
		# reader looks below. There is no room for a marker there and a
		# lone `~` says less than a letter does.
		#
		# A box with room gets the marker, because a name that is *nearly*
		# right is the one a reader retypes. `cell_count (cont.)` came out as
		# `cell_count (con`, which is not any field's name.
		text = text[:room - 1] + "~" if room >= 4 else text[:room]
	return text.center(room)


def _tall(name: str, rows: int, width: int) -> list[str]:
	"""A member occupying whole rows: one box, named in the middle."""
	blank  = "|" + " " * (2 * width - 1) + "|"
	titled = "|" + _cell(name, width) + "|"
	middle = rows // 2

	return [titled if row == middle else blank for row in range(rows)] + [_rule(width)]


def _slanted(name: str, width: int) -> list[str]:
	"""A member with no fixed extent, in the convention RFCs use for one."""
	return ["/" + _cell(name, width) + "/",
	        "/" + _cell("(variable)", width) + "/",
	        _rule(width)]


# ---------------------------------------------------------------------------
# The table
# ---------------------------------------------------------------------------


def _table(struct: ResolvedStruct, fmt: str) -> list[str]:
	"""What the diagram cannot say: types, constraints and byte order."""
	rows = [_row(struct, entry.placement) for entry in struct.entries
	        if entry.placement.kind != "element"
	        and "." not in entry.placement.path[len(struct.name) + 1:]]
	if not rows:
		return []

	headers = ("Field", "Offset", "Size", "Type", "Notes")
	if fmt == "markdown":
		lines = ["| " + " | ".join(headers) + " |",
		         "|" + "|".join(["---"] * len(headers)) + "|"]
		lines.extend("| " + " | ".join(row) + " |" for row in rows)
		return lines

	widths = [max(len(headers[i]), max(len(row[i]) for row in rows))
	          for i in range(len(headers))]
	lines  = ["  ".join(headers[i].ljust(widths[i]) for i in range(len(headers))),
	          "  ".join("-" * widths[i] for i in range(len(headers)))]
	lines.extend("  ".join(row[i].ljust(widths[i]) for i in range(len(headers))).rstrip()
	             for row in rows)
	return [line.rstrip() for line in lines]


def _row(struct: ResolvedStruct, placement: Placement) -> tuple[str, ...]:
	return (
		_label(struct, placement),
		_offset(placement),
		_size(placement),
		placement.type_name or "-",
		"; ".join(_notes(placement)) or "",
	)


def _offset(placement: Placement) -> str:
	if placement.offset_bits is None:
		return "dynamic"
	if placement.offset_bits % BITS_PER_BYTE == 0:
		return str(placement.offset_bits // BITS_PER_BYTE)
	return f"{placement.offset_bits // BITS_PER_BYTE}.{placement.offset_bits % BITS_PER_BYTE}"


def _stride(placement: Placement) -> str:
	"""How wide one element is, where a count alone would not say.

	Nothing for a byte element, where the count *is* the byte count, and for
	an element of a struct type, whose name the Type column carries.
	"""
	if not indexed_elements(placement):
		return ""
	return f" x {element_bytes(placement)} bytes"


def _size(placement: Placement) -> str:
	if placement.delimiter is not None:
		# What a reader needs is where it stops, not how many bytes the
		# delimiter takes -- which is what the fixed-size branch below
		# reported, and it is the one number nobody wants.
		shown = render_delimiter(placement.delimiter).strip("`")
		if placement.delimiter_cap is not None:
			return f"to {shown}, max {placement.delimiter_cap}"
		return f"to {shown}"
	# The count is in elements, and this column is otherwise in bytes: a
	# constant array two rows down says "8 bytes" for four `u16`s. So `[n]`
	# beside a `u16` read as n bytes, and half the array was invisible to
	# somebody sizing a buffer from the table. The two coincide for a byte
	# element, which is every data-sized array anybody had written.
	if placement.sized_by is not None:
		return f"[{placement.sized_by}]{_stride(placement)}"
	if placement.size_expr is not None and placement.array_count is None:
		# The same question `sized_by` answers, for a length written as
		# arithmetic rather than as a bare field reference. Without it this
		# fell to the fixed-size branch below and printed the *minimum* --
		# "0 bytes" for a payload that is `nla_len - 4`, beside a diagram
		# saying "(variable)". Three constructs above have their own comment
		# recording this same mistake; the fourth is here because the
		# predicate was `sized_by` rather than `traverse.data_sized`.
		return f"[{placement.size_expr}]{_stride(placement)}"
	if placement.kind == "variant" and placement.discriminant is not None:
		# The fixed-size branch below reported `size_bits`, which for a
		# variant is the *smallest* arm -- printed as "0 bytes" beside a
		# diagram saying "(variable)", in a column where every other variable
		# member says how its length is decided. A true number answering a
		# question nobody asked, which is the `array_count` lesson again.
		return f"by {placement.discriminant}"
	if placement.repeat_while is not None:
		return f"while {placement.repeat_while}"
	if placement.size_bits % BITS_PER_BYTE:
		bits = placement.size_bits
		return f"{bits} bit" if bits == 1 else f"{bits} bits"
	return _bytes(placement.size_bits // BITS_PER_BYTE)


#: Attributes this module says in words rather than passing through.
RENDERED_IN_PROSE = ("since",)


def _notes(placement: Placement) -> list[str]:
	notes = []
	scalar = placement.scalar
	if scalar is not None and scalar.is_fixed_point:
		notes.append(f"fixed point, /{scalar.scale}")
	if scalar is not None and scalar.is_bcd:
		notes.append(f"{scalar.digits} packed digits, 0 to {scalar.decimal_max}")
	# Byte order is a property of a multi-byte *number*, and the test was the
	# member's total width -- so a two-byte marker, a four-byte address and a
	# 110-byte nested struct all carried it. `bmp.signature` is the sharpest
	# case: its own comment says it is bytes rather than a `u16` so that its
	# value does not depend on byte order, and the document said it did.
	#
	# The element's width is the question, which also keeps the note where it
	# belongs on `u16 samples[4]`. A number written as digits has no byte
	# order at all: the bytes are characters, and `repr = TextConverted` is
	# the axis saying so.
	if placement.marker is not None and placement.kind != "marker" \
			and scalar is not None and scalar.bits > BITS_PER_BYTE:
		# A field whose byte order the *message* decides. The column said
		# nothing, which reads as host order beside every neighbour that names
		# one -- and the fact a reader most needs about such a field is which
		# other field to read first.
		notes.append(f"byte order from {placement.marker}")
	elif placement.endian is not None and placement.radix is None \
			and scalar is not None and not scalar.is_bit_packed \
			and scalar.bits > BITS_PER_BYTE:
		notes.append(f"{placement.endian.value} endian")
	for attr in placement.attrs:
		# Skip the ones rendered in prose above. `since = 2` and "from version
		# 2" in one row is the same fact twice, and a reader who sees a
		# document repeat itself starts skimming it.
		if attr.name in RENDERED_IN_PROSE:
			continue
		notes.append(attr.name if attr.value is None
		             else f"{attr.name} = {_attr_value(attr)}")
	if placement.covered_by:
		notes.append("covered by " + ", ".join(placement.covered_by))
	if placement.radix is not None:
		base = {10: "decimal", 16: "hexadecimal"}.get(placement.radix,
		                                             f"base {placement.radix}")
		notes.append(f"{base} digits")
	if placement.since is not None:
		notes.append(f"from version {placement.since}")
	if placement.derived_by is not None:
		# The half of section 16.1 a reader of this table most needs. The
		# fields an invariant *reads* already showed up here, through
		# `covered_by`, so the dependency was documented from one end only --
		# and the end that was missing is the one somebody writing an encoder
		# from this table has to know about, because it says the value is not
		# theirs to choose.
		notes.append(f"derived: {placement.derived_by} computes it")
	if placement.sealed_by is not None:
		notes.append(f"sealed by {placement.sealed_by}")
	return notes


def _attr_value(attr: ast.Attr) -> str:
	"""The attribute's value as a user wrote it.

	Through the unparser rather than `str()`: an expression node is a dataclass
	holding its own span, and its span holds the whole source file, so the
	default repr renders the entire schema into one table cell.
	"""
	if attr.raw is not None:
		return str(attr.raw)
	return "" if attr.value is None else expr_to_source(attr.value)
